### ISSUE TITLE
Confusing behavior/documentation of `Bind Scope`

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10064]
The documentation of `Bind Scope` says: 

> When a scope scope is bound to a type type, any new function defined later on gets its arguments of type type interpreted by default in scope scope

However, `Bind Scope` seems to also apply to previously defined constants:

```coq
Definition T := nat.

Definition id (x : T) (y : bool) := x.

Declare Scope T_scope.
Bind Scope T_scope with T.

About id.
(*
Argument scopes are [T_scope bool_scope]
*)
```

Is this a `Bind Scope` bug or a documentation bug? Naively, I find it strange that the metadata associated to an existing constant (its argument scopes) is impacted by a command that does not mention the constant. I thought changing the scopes after the fact was the role of `Arguments`.

Cc @herbelin

**Comment by herbelin** [comment]
This seems to have been changed in 8.5 (3d09e39dd) but the reference manual and `CHANGES` not updated.

I don't have a strong opinion on what is best. If the 8.5 semantics is fine (and apparently it is, based on the fact that it was argumented and that noone complained), it is the documentation which should be updated.

**Comment by maximedenes** [comment]
Thanks for the pointer! I wasn't aware of the complications related to functor applications, but it seems a bit strange that it implies to go for such dynamic semantics. The fact that nobody complained may not be so significant, given that the discrepancy w.r.t. documentation wasn't reported.

Moreover, the dynamic semantics seems counterintuitive:

```coq
Declare Scope foo_scope.
Section foo.
Section bar.
Variable x : bool.
Variable y : nat.
Definition def1 := x.
Definition def2 := y.
End bar.
Bind Scope foo with nat.
End foo.
Bind Scope foo with bool.
About def1.
(* Argument scope is [foo] *)
About def2.
(* Argument scope is [nat_scope] *)
```

**Comment by maximedenes** [comment]
Forget about this example, I guess it is just `Bind Scope` being local to sections.

**Comment by maximedenes** [comment]
Sorry again for the bogus example. What I find a bit strange is that specifying a scope for one argument makes the dynamic binding no longer apply to the other arguments:

```coq
Declare Scope foo_scope.
Definition def (x : bool) (y : nat) := x.
Arguments def _ y%nat_scope.
Bind Scope foo_scope with bool.
About def.
(* Argument scopes are [_ nat_scope] *)
```

the same example in a section works differently, though:

```coq
Section foo.
Variable (x : bool).
Definition def (y : nat) := x.
Global Arguments def y%nat_scope.
End foo.
Bind Scope foo_scope with bool.
About def.
(* Argument scopes are [foo_scope nat_scope] *)
```

is this the intended behavior?

Also, I imagine that dynamic binding of scopes opens some questions, like `Require foo` being able to change the scope of definitions in library `bar`.

But I can imagine that addressing functor application issues while keeping the static binding semantics may be tricky.

**Comment by jashug** [comment]
I have used this feature, but never really thought about the semantics. The way I usually depend on this is to declare a type and some functions, then declare a module containing the scope declaration and a bunch of notations in that scope for working on things of this type. When the module is imported I want to be able to use the notations, but I also want to work without it imported (to reduce notation conflicts).

How I was thinking about it probably comes down to: the default scoping behavior for functions is to choose based on the type of their arguments. This can be overridden with Arguments, but usually doesn't need to be. Then I want to use whatever scope is currently bound to bool to interpret an argument of type bool.

If we move to a more static binding semantics, the same approach will probably need to declare a scope for each type immediately after definition (and setting the scopes of constructors using Arguments). Because scopes are not qualified by modules, I worry about getting conflicts in scope names in that approach though.

(To be clear though, I'm generally in favor of more explicit semantics)

---

The difference with being in a section and without is understandable as seeing `Arguments def _ y%nat_scope` declaring that the first argument has no scope, while in the section `Arguments def y%nat_scope` leaves the first argument as the default (dynamic). If this is liked, you could have a syntax for specifying to use this dynamic default in arguments. (Not sure if this is actually what is wanted however).

I don't think `Bind Scope` takes effect on `Require` however, at least using modules in a single file it requires `Import` to take effect:
```coq
Definition def (y : nat) := true.
About def. (* Argument scope is [nat_scope] *)

Module A.
Declare Scope foo_scope. (* Same if declared outside A *)
Bind Scope foo_scope with nat.
About def. (* Argument scope is [foo_scope] *)
End A.

About def. (* Argument scope is [nat_scope] *)
Import A.
About def. (* Argument scope is [foo_scope] *)
```

**Comment by maximedenes** [comment]
@jashug Sorry, my example was bogus again. I hadn't realized `Arguments def _ y%foo` was unsetting the scope for the first argument.

Here's what I meant (hopefully):

```coq
Declare Scope foo_scope.
Section foo.
Variable (x : bool).
Section bar.
Variable (y : bool)
Definition def (z : nat) := (x,y).
Global Arguments def z%nat_scope.
End bar.
End foo.
Bind Scope foo_scope with bool.
About def.
(* Argument scopes are [foo_scope bool_scope nat_scope] *)
```

isn't this one strange?

**Comment by jashug** [comment]
@maximedenes 
Yes, that looks weird to me and I can't come up with a reasonable semantics for `Bind Scope` that gives that behavior. I agree that this should be redesigned.
(To be clear, the semantics I suggested in my previous comment was also speculation to match my use of Bind Scope and the previous examples, and not founded in the documentation or the source code.)

**Comment by herbelin** [comment]
That both scopes are different depending on the section level also looks like a bug to me!

**Comment by maximedenes** [comment]
The more I look at it, the more I think this dynamic binding is not well defined. For example, what's the expected output of `coqc A.v && coqc B.v` on:

`A.v`
```coq
Declare Scope foo_scope.
Declare Scope bar_scope.

Axiom T : Type.
Bind Scope foo_scope with T.
Definition def (x : T) := x.
Bind Scope bar_scope with T.
About def.
```

`B.v`
```coq
Require A.
About A.def.
```

I'll experiment switching back to a declarative semantics (i.e. more or less what is described in the manual).

**Comment by ggonthier** [comment]
It is likely no one noticed the dynamic behaviour because `Bind Scope` is usually only used once, just after the bound type has has been defined.
The dynamic behaviour does solve a nagging problem that I've run into several times: It is common to want to define a parametrised type inside a `Section`, alongside its operations and their properties. However this makes it difficult to `Bind` a scope to that type, because if one puts the `Bind Scope` command inside the section, then it and its effects will be forgotten at the end of the section, so it will have to be repeated after that _and_ `Arguments` will have to be used to respecify the scopes for _every_ constant and lemma in the section.
    I've actually done this a few times, but most of the time I just move the type declaration ahead of the section, and put the `Bind Scope` immediately after. Then `Arguments` is only needed for the constructors and projectors that are defined alongside the type. Unfortunately this often drags other material out of the section, namely everything needed to define coercions from the type (the dreaded uniform inheritance condition bars declaring coercions from a type constructor applied to section variables).
  The dynamic interpretation solves almost all these issues, since every constant defined in the main declaration section will be affected by a `Bind Scope` placed after the section. The only remaining issue is that one may need to repeat the `Bind Scope` in and out of the section. I might have used that feature if i'd realised it had been implemented (was it documented?).
  However I can think of better ways of resolving those issues than dynamic binding:
(a) Align the scope of `Bind Scope` on `Coercion` rather than `Notation`, making it survive the end-of-section unless the type definition itself goes out of scope.
(b) Provide a `#[bind_scope(my_scope)]` attribute that can be attached to a type definition, and affects all constants defined thereafter (in the `Module` scope).

**Comment by maximedenes** [comment]
Thanks for the feedback! IIUC, this dynamic behavior was introduced to circumvent a limitation of functor-based structures. Essentially, in the standard library, one would like to do something like:

```coq
Declare Scope foo_scope.

Module Type S.
Parameter T : Type.
End S.

Module F (X : S).
Import X.
Definition def (x : X.T) := x.
End F.

Module M.
Axiom T : Type.
Bind Scope foo_scope with T.
End M.

Module N := F M.

About N.def.
(* Here we'd like N.def to have argument scopes foo_scope, but it is not the case *)
```

and have `N.def` inherit the argument scopes from `M`.  This happens for example in `Numbers`, where a part of the library is abstracted as functors over a type later instantiated to `Z`. Lemmas and definitions would like to have their arguments in type `Z` (once concretized) automatically bound to `Z_scope`.

However, the example above does not work because extra logical objects are taken from the signature, not the implementation (IIUC), so we'd have to add the `Bind Scope` directive to the signature `S`, which defeats the whole purpose since the type `T` is not concrete yet.

I'm not sure if the dynamic behavior is the right fix for this problem, though.

**Comment by maximedenes** [comment]
Since the standard library relies heavily on this dynamic behavior, I guess the only reasonable short term option is to update the documentation. I'll give it a try.

**Comment by JasonGross** [comment]
> It is likely no one noticed the dynamic behaviour

For the record, I noticed, and made use of it, and quite possibly rely on it.
