### ISSUE TITLE
How to give a name to a term binder?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#10102]
Playing with Ltac2, I succeeded to build a term with a given binder name as follows:
```coq
Ltac2 myintro x := Std.intros true [Std.IntroNaming (Std.IntroIdentifier x)].
Ltac2 myapply x := Std.apply true true [fun () => (x,Std.NoBindings)] None.
Ltac2 myid y := myintro y; myapply (Control.hyp y).
Definition idnat : nat -> nat := ltac2:(myid @u). (* fun u : nat => u *)
```
Is there a simpler way?

Typical questions are: What are the advantage of `&y` being `Control.hyp ident:(y)` and not `Control.hyp y` since there is already `@y` for `ident:(y)`? Is there a way to give a name to a term-level `fun` without using `Std.intros` (e.g. virtually something like `constr:(fun $y => $(Control.hyp y))` for `y:ident`)?.

**Comment by ppedrot** [comment]
@herbelin You can write this:

```
Ltac2 myid n :=
  intros $n; let n := Control.hyp n in exact $n.
```

The reason for `&x` referring to a literal rather than a variable is based on a scrutiny of the number of uses of the corresponding Ltac1 feature in the wild. Most of the time, they're performed in interactive proofs where you actually want a specific named variable, not referring to some Ltac bound variable.

(I think this issue can be closed, if you don't feel happy with the answer please reopen.)
