### ISSUE TITLE
coqdep should fail when it cannot find a .v file

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#10156]
#### Description of the problem

Currently it emits a warning (which gets lost in Makefile output flood) and an incomplete list of dependencies (which results in the .vo not getting rebuilt).

#### Coq Version

8.9.0

**Comment by ejgallego** [comment]
Indeed I guess that's a problem inherited from OCaml, see https://github.com/ocaml/ocaml/issues/8625

I have a much stripped down version of `coqdep` [aimed to be used by Dune] which avoids this problem.

**Comment by samuelgruetter** [comment]
@ejgallego is this new `coqdep` version available somewhere?

**Comment by JasonGross** [comment]
Note that this would break the fiat-crypto build, because some of the coqprime files depend on having coq-bignums installed, but we only build and depend on the ones that don't depend on bignums.  (It's very plausible that the right answer is one of (a) make bignums a proper dependency of fiat-crypto, (b) don't reuse coqprime's makefile to build the subset of coqprime, or (c) remove the uses of coqprime from fiat-crypto (c.f. https://github.com/mit-plv/fiat-crypto/issues/482).  But I want to note that we are currently relying on this behavior, so that it is not a surprise if/when things break)

**Comment by hendriktews** [comment]
How abou a `-lax` option that changes the proposed error in #14023 in a warning?

**Comment by ejgallego** [comment]
See also discussion in #12108 and #13992

**Comment by hendriktews** [comment]
> Indeed I guess that's a problem inherited from OCaml, see [ocaml/ocaml#8625](https://github.com/ocaml/ocaml/issues/8625)

I don't think so. ocaml/ocaml#8625 is about command line arguments that don't exist. This issue speaks about a warning, therefore it must be the problem that `coqdep` prints `library x is required and has not been found in the loadpath!` on stderr, if it parses a file containing, for instance, `Require x` and it cannot find `x.v`. Note that `ocamldep` silently drops dependencies that it cannot find, without printing a warning.

**Comment by hendriktews** [comment]
> How abou a `-lax` option that changes the proposed error in #14023 in a warning?

I suggested this under the assumption that #14023 describes the same problem as this issue, which I don't think is the case. Here I would suggest a `-picky` option, that turns the warning into a proper error. This would retain backward compatibility but would also give tools such as Proof General a chance to reliably detect the error without needing to pattern match on the output.
