### ISSUE TITLE
Coqide wont run

### ISSUE THREAD

**Issue by R-Her-E** [coq/coq#10243]
Everytime I run coqide in a terminal I get the following error message:

Connection with coqtop failed!
Command was: '/home/rher/.opam/system/bin/coqtop' -batch -ideslave 
Answer was: Don't know what to do with -ideslave
  See -help for the list of supported options
Exception was: Coq.WrongExitStatus("WEXITED 1")

#### Coq Version

Coq version 8.8.1

**Comment by Zimmi48** [comment]
Your version of CoqIDE is 8.8.1 but it would seem that your version of `coqtop` is more recent. What does `/home/rher/.opam/system/bin/coqtop --version` says?

How did you install CoqIDE?

**Comment by R-Her-E** [comment]
It says:
The Coq Proof Assistant, version 8.9.0 (May 2019)

I installed CoqIDE via opam: opam install coqide

Thanks

**Comment by Zimmi48** [comment]
What does `which coqide` and `coqide --version` say?

**Comment by R-Her-E** [comment]
which coqide: 
/home/rher/opam-coq.8.9.1/4.02.3/bin/coqide

When I run coqide --version I get the following message:
Coqtop exited
Command was: '/home/rher/.opam/system/bin/coqtop' -nois -filteropts '--version'
Answer was: The Coq Proof Assistant, version 8.9.0 (May 2019)
  compiled on May 24 2019 21:14:04 with OCaml 4.05.0

**Comment by Zimmi48** [comment]
It appears that you have Coq installed in two different opam roots: one of them at `/home/rher/.opam` and the other at `/home/rher/opam-coq.8.9.1`. This seems to be the reason for having inconsistent installations of coqtop and coqide.

Could you run ` /home/rher/opam-coq.8.9.1/4.02.3/bin/coqtop --version`?

**Comment by R-Her-E** [comment]
It says: 
The Coq Proof Assistant, version 8.8.1 (May 2019)
compiled on May 25 2019 0:12:59 with OCaml 4.02.3

**Comment by Zimmi48** [comment]
Bingo!
So you have indeed two roots: one of them contains Coq 8.9.0 and the other one contains Coq and CoqIDE 8.8.1. Your PATH contains the two roots, the first before the second. So when you open CoqIDE, it will find it in the second root because it is not installed in the first. But then CoqIDE calls coqtop and because it is installed in the first root it uses this one, and boom: version mismatch.

I'd recommend you remove the additional root `/home/rher/opam-coq.8.9.1` (`rm -rf /home/rher/opam-coq.8.9.1` but this is an optional step), then:

```
export OPAMROOT=/home/rher/.opam
eval `opam config env`
opam install coqide
```

This should give you a fresh install of CoqIDE 8.9.1 in the main opam root.

You might also want to clean up your `.bashrc` or `.profile` file from some of the clutter.

**Comment by R-Her-E** [comment]
Thanks! Now CoqIDE starts running but I get an error message: Coqtop died badly.

I follow this process
```

export OPAMROOT=/home/rher/.opam
eval `opam config env`
opam install coqide
```
But I got 

`[NOTE] Package coqide is already installed (current version is 8.9.0).
`

**Comment by R-Her-E** [comment]
So, it seems that now is working perfectly fine.  I did the following:
```
opam remove coq
opam remove coqide
export OPAMROOT=/home/rher/.opam
eval `opam config env`
opam pin add coq 8.9.0
opam install coq.8.9.0
opam install coqide
```
I don't know exactly why this worked, but it did.

Thanks for your useful help!
