### ISSUE TITLE
Coq 8.10 has new ambiguous path warnings

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#10247]
#### Description of the problem

According to @SkySkimmer, we should be seeing *fewer* "ambiguous paths" warnings with Coq 8.10. Instead, we are seeing more.

No warnings with 8.9.1: https://gitlab.mpi-sws.org/iris/iris/-/jobs/32395
A whole bunch of warnings with 8.10.dev: https://gitlab.mpi-sws.org/iris/iris/-/jobs/32394

#### Coq Version

8.10 branch (commit acea42fc)

**Comment by RalfJung** [comment]
Cc @vbgl should this be fixed before the Coq 8.10 release?

The PR that changed the ambiguous path condition is likely https://github.com/coq/coq/pull/9743 -- but the part where it says "relaxed" does not seem universally true.

**Comment by pi8027** [comment]
In Coq 8.9, ambiguous paths messages were implemented by `Feedback.msg_info` and only shown when we interact with `coqtop` through Emacs or CoqIDE. I turned them to warnings by using `CWarnings.create` in order to test them systematically, and think that this is a better way to implement them. (But I forgot to write about it in `CHANGES.md`.)

One could suppress them by giving `-arg -w -arg -ambiguous-paths` to `coq_makefile` as a part of its input file in the `_CoqProject` format.

**Comment by Zimmi48** [comment]
So this is not an actual regression. @pi8027 It seems like it would indeed be a good idea to add a note to the changelog entry of this change of status and people building with fatal warnings might discover this new warning being emitted. Classifying as a documentation issue.

**Comment by RalfJung** [comment]
I see, so we had ambiguous paths all along but did not notice.

However, also see https://github.com/coq/coq/issues/5412: the message is not very helpful at figuring out what the ambiguity is.

**Comment by pi8027** [comment]
OK. I will work on this next week. I can discuss this with someone in CUDW2019 if needed but I will be there from Tuesday.
