### ISSUE TITLE
Fail does not print "The command indeed failed with error...." unless we pass -test-mode to coqc

### ISSUE THREAD

**Issue by gares** [coq/coq#10288]

**Comment by SkySkimmer** [comment]
Otherwise why would we have the -test-mode flag?

**Comment by gares** [comment]
-test-mode alters caching for example in the STM.
As long as I recall, Fail always prints the reason of failure...

Do you know which commit changed the behavior?

**Comment by SkySkimmer** [comment]
>-test-mode alters caching for example in the STM.

No, it's only accessed for Fail's printing.
~~~
git grep test_mode
toplevel/coqargs.ml:    |"-test-mode" -> Vernacentries.test_mode := true; oval
vernac/vernacentries.ml:let test_mode = ref false
vernac/vernacentries.ml:      if not !Flags.quiet || !test_mode then Feedback.msg_info
vernac/vernacentries.mli:val test_mode : bool ref
~~~
It's been this way since you added it in e47c30bf431f3c8160b41384eedb538ba16578d0 AFAICT

**Comment by gares** [comment]
I'm very bad at booleans, I summon @maximedenes (my personal tutor)

**Comment by maximedenes** [comment]
I believe @SkySkimmer is correct, not printing anything is the intended behavior for `coqc`. We can debate whether we want to change that. @gares, when you told me about this you didn't mention it was for `coqc`, rather than interactive use.

**Comment by maximedenes** [comment]
> not printing anything is the intended behavior for `coqc`

I meant for `Fail`.

**Comment by SkySkimmer** [comment]
Seems like there was some misunderstanding of the intended behaviour.
