### ISSUE TITLE
Mtac2 installation failure on Windows

### ISSUE THREAD

**Issue by vbgl** [coq/coq#10440]
Coq-8.10+β2 installers for Windows do not include any add-on because Mtac2 build failed (during its `make install` step):

> src/machine.cmi does not exist
src/cClosure_copy.cmi does not exist
src/machine.cmi does not exist
src/machine.cmx does not exist
src/cClosure_copy.cmx does not exist
make: *** [Makefile:472: install] Error 1

cc/ @Janno

**Comment by Zimmi48** [comment]
Next time, it will be a good idea to test the compilation before tagging. I don't remember if it is in the release checklist, but if it isn't, it should be added.

**Comment by gares** [comment]
This sounds a bell: the files up there are in the _CoqProject file but don't exists.
At some point we had a similar problem with MathComp.
CC #9906

**Comment by MSoegtropIMC** [comment]
For the file `src/cClosure_copy.cmi` it is true that it is in _CoqProject but does not exist, so it should be removed.

For the `src/machine.cmx` file I am less sure what is going on. The CoqMakefile generated makefile does not even try to build the .cmx file even with make all, but it tries to install it. To me this almost looks like a bug in CoqMakefile. I don't see how one could create such an effect by a wrong _CoqProject file.

If one tries to build the file explicitly, one gets errors.

In mtac2 for 8.9.1 this file is not installed.

So in order to get forward I will remove this file from _CoqProject as well - a hack!

**Comment by MSoegtropIMC** [comment]
P.S.: this leads to exactly the same set of files installed as in mtac2 for 8.9.1, but still this needs further investigation.

**Comment by SkySkimmer** [comment]
machine.ml is dead code AFAICT
cc @Janno

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : thanks - I guess then it is ok to remove it from _CoqProject. I will check some of the test files with the finished installer.

Still I find the behavior of CoqMakefile weird. If it thinks that machine.ml should be installed, then it should also build it. Let's switch to dune ...

**Comment by SkySkimmer** [comment]
You might notice that the current dune file for mtac2 specifically excludes machine.ml ;)

**Comment by MSoegtropIMC** [comment]
Should I switch to dune? I looked at the latest mtac2 opam file, which is for 8.9 and it still uses classic make, so that is what I did as well. See <https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-mtac2/coq-mtac2.1.1%2B8.9/opam>

**Comment by gares** [comment]
As a rule of thumb,I think we should use what the upstream do use daily, since it is what is actually tested. Cc @Janno what do you actually use? Why do you keep 2 build systems?

Wrt coq_makefile, I guess machine.ml is not listed in the mlpack file. There is a stupid duplication of data between mlpack and _coqproject...

**Comment by vbgl** [comment]
Fixed upstream: https://github.com/Mtac2/Mtac2/pull/220 and https://github.com/Mtac2/Mtac2/pull/221
