### ISSUE TITLE
Is `cutrewrite` deprecated?

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#10572]
The manual says that `cutrewrite` is deprecated, but I couldn't find the corresponding deprecation warning in the codebase.

We should either remove the deprecation from the manual, or add it in the code.

Cc @herbelin

**Comment by herbelin** [comment]
I would personally suggest to deprecate `cutrewrite`. First because I find the name a bit abstruse, and, as approximatively said in the corresponding comment of `extratactics.mlg`, it has simple equivalents based on more general concepts:
- `cutrewrite <- (t=u)` = `enough (t=u) as <-`
- `cutrewrite -> (t=u)` = `replace u with t` = `enough (t=u) as ->`
