### ISSUE TITLE
`caml_signals_are_pending` has been removed from OCaml upstream.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#10603]
OCaml's PR https://github.com/ocaml/ocaml/pull/8691 has removed that variable from the list of exported variables; this is used in the main VM interpreter loop.

I am not sure what strategy we should follow here.

**Comment by ejgallego** [comment]
@jhjourdan does comment on the proper solution to this here [here](https://github.com/ocaml/ocaml/pull/8691#issuecomment-521181762):

> As far as I understand, the current version of the Coq VM interpreter needs to "reset the VM" when an interruption occurs. Why is this needed?
> 
> In the current version, the way this is done is by manually intercepting signals by checking `caml_something_to_do/caml_signals_are_pending` periodically, and checking for the `SIGINT` signal just before manually calling the internal function `caml_process_pending_signals`. Not only this is very fragile because this interacts with internal mechanisms of the OCaml runtime, I think this is wrong, for several reasons:
> 
> - If the computation is interrupted by some other signals (say, `SIGALRM` from a timeout, for example), then the resetting will not happen. The same thing will happen if, e.g., the runtime decides to trigger an out of memory exception.
> - I don't think `caml_check_urgent_gc` is called anywhere. This a several unfortunate consequences, such as disabling GC's own mechanisms for defending against e.g., too many pointers from the major to the minor heap, or deactivating finalizers.
> - If a Ctrl-C happens between the check of `caml_pending_signals[SIGINT]` and the call to `caml_process_pending_signals`, then this resetting will not happen.
> What I think the Coq interpreter should do is:
>
> 1. Stop using a custom mechanism for handling signals in the VM. Just use the same piece of code as in the OCaml runtime:
> 
>  ```c
>  Instruct(CHECK_SIGNALS):    /* accu not preserved */
>       if (caml_something_to_do) goto process_signal;
>       Next;
> 
>     process_signal:
>       Setup_for_event;
>       caml_process_event();
>       Restore_after_event;
>       Next;
> ```
> 2. If resetting is needed (I guess for freeing the roots in the Coq VM stack ?), then perform the resetting of the Coq VM in a try/finally block wrapping any call to the Coq VM. This is way more robust, since this will make it possible to reset the VM even if it is interrupted by an unexpected exception.
> 
> 3. Use `Alloc_small_origin` to tell the allocator that this is fine to call callbacks (via `caml_check_urgent_gc`) when calling allocation functions in the Coq VM interpreter. This can be done with something in the lines of
> 
> ```c
> #undef Alloc_small_origin
> #define Alloc_small_origin CAML_FROM_CAML
> ```
> as in the OCaml bytecode interpreter.

**Comment by gadmm** [comment]
### Issues with try/finally

Regarding 2.: implementing a dedicated try/finally safe for asynchronous exceptions is possible but tricky. Acquisition and release functions must not poll (for instance they could be written in C). In addition, you would need to be careful to write the try/finally by hand to avoid any polling during the critical sections of acquisition and release. I don't say it is impossible in the present case (assuming native compilation). I have some experience with it so do not hesitate to send me a message if you try that path.

### Alternate strategy

I discussed with @ppedrot of a different strategy than redefining Alloc_small_origin. (Disclaimer: I am not familiar with the Coq VM code.)
1. Call regularly a variant `caml_check_urgent_gc_exn` of `caml_check_urgent_gc`/`caml_process_events` that returns the exception instead of jumping to Caml. Do your cleanup, then reraise the exception.

Please tell me as soon as possible if you think this strategy can work. We can try having this function (and corresponding `caml_enter/leave_blocking_section_exn` functions) on time for 4.10.

**Comment by gadmm** [comment]
It appeared that Coq's `Alloc_small` functions are different from OCaml's, and upon inspection they have never polled signals. So step 3. from @jhjourdan is not needed, nor is it needed to add new polling points to compensate.

So, the solution is to replace in `coq_interp.c`:
```c
      if (caml_signals_are_pending) {
	/* If there's a Ctrl-C, we reset the vm */
	if (caml_pending_signals[SIGINT]) { coq_sp = coq_stack_high; }
	caml_process_pending_signals();
      }
```
with:
```c
      {
        value exn = caml_process_pending_events_exn();
        if (Is_exception_result(exn)) {
          coq_sp = coq_stack_high;
          caml_raise(Extract_exception(exn));
        }
      }
```
where `caml_process_pending_events_exn` is a new public function proposed for inclusion at https://github.com/ocaml/ocaml/pull/8993.

**Comment by jhjourdan** [comment]
> It appeared that Coq's Alloc_small functions are different from OCaml's, and upon inspection they have never polled signals.

Oh yes, you are right, well spotted! But then this is yet another interaction with OCaml internal API, and that one will break both because of https://github.com/ocaml/ocaml/pull/8713 and of memprof...

Really, Coq VM's uses of OCaml internal API is a disaster waiting to happen and should be limited at all costs. In terms of performane, how much would it cost to use `caml_alloc_small` instead of `Alloc_small`? The only difference is the function call.

**Comment by gadmm** [comment]
What I remember from @ppedrot's explanations is that Coq uses its own heap.

I think that it is good for OCaml maintainers to look at how the language is used in practice when evolving the language, but seriously, anyone who feels the need to hijack caml internals for serious work is well inspired to open a bug report to explain what the use-case and the limitations are.

**Comment by silene** [comment]
> In terms of performance, how much would it cost to use `caml_alloc_small` instead of `Alloc_small`? The only difference is the function call.

That is not the only difference. As the OCaml source code says, "`caml_alloc_small` does the same work as the macro `Alloc_small` in the case where `Setup_for_gc` and `Restore_after_gc` are no-ops". Since `Setup_for_gc` and `Restore_after_gc` are effectful in Coq, this is no solution.

I guess that, starting with OCaml 4.06, we could force `CAML_INTERNALS` and call the `Alloc_small` macro from OCaml rather than defining our own version.
