### ISSUE TITLE
Documentation: Error in 2nd code block in `Uniform Inductive Parameters` 

### ISSUE THREAD

**Issue by Janno** [coq/coq#10610]
#### Description of the problem

The second code block in
https://coq.inria.fr/refman/language/gallina-specification-language.html#coq:flag.uniform-inductive-parameters
reports an error and, as far as I understand, it shouldn't. I don't understand enough of how the documentation works to figure out why. The code block is using `coqtop: all reset` which seems to solve this problem in earlier examples in the manual such as `list2` in the note just above `Uniform Inductive Parameters`.

**Comment by ejgallego** [comment]
That seems like a build error? I dunno, it seems fine on master 

https://coq.github.io/doc/master/refman/language/gallina-specification-language.html#parameterized-inductive-types

so whatever the problem was it has been fixed.

**Comment by Zimmi48** [comment]
Thanks for the report @Janno, but indeed the issue has already been fixed, even in 8.9.1 as can be seen at https://coq.github.io/doc/V8.9.1/refman/language/gallina-specification-language.html#coq:flag.uniform-inductive-parameters. Unfortunately, the documentation has not been updated since the release :cry: (@maximedenes I will continue to harass you until you do something about this, and honestly I don't think that what is needed is very hard, cf #10619, coq/www#118.)

**Comment by maximedenes** [comment]
> I will continue to harass you until you do something about this

I tend to consider that harassment is not a good practice. And also, it does not scale. I'd prefer to give you access to the server than being a blocking point each time we have to update the manual.

**Comment by Zimmi48** [comment]
Yeah, I know, I was joking. But:
1. I would have asked access to the server and solved this myself if I was not really busy writing my thesis right now.
2. I really think this is a problem that can be solved just once with the right redirection logic (as I think, I have explained in the linked issues).
