### ISSUE TITLE
How to disable output when importing in an rcfile?

### ISSUE THREAD

**Issue by tchajed** [coq/coq#10640]
#### Description of the problem

When I do an import in an rcfile, Coq always prints a message of the form `R15:20 Coq.Strings.String <> <> lib`. This is unhelpful line noise. Is there a way to disable it?

To reproduce:

```bash
echo "Require Import String." > string_rc.v
echo > empty.v
coqc -init-file string_rc.v empty.v
```

this outputs `R15:20 Coq.Strings.String <> <> lib`.

#### Coq Version

The Coq Proof Assistant, version 8.10+alpha (July 2019)
compiled on Jul 16 2019 14:45:28 with OCaml 4.07.1

**Comment by ejgallego** [comment]
This actually looks like a bug.

**Comment by tchajed** [comment]
If so, it's been present in Coq since at least v8.8.

**Comment by ejgallego** [comment]
> If so, it's been present in Coq since at least v8.8.

Yup, it would make sense even in that timeframe due to the changes that happened after 8.6.

**Comment by ejgallego** [comment]
@tchajed the problem is that in `ccompile.ml` `record_aux_file` is set to true, however, `start aux file` is called after `load_init_vernaculars`, so indeed that's a bug as the aux info is written to stdout.

I wonder what the right fix is?

Should we emit aux info for the rc files? IMHO we should not, I will cook a quick patch.
