### ISSUE TITLE
Valid statement cannot be Admitted or Qed

### ISSUE THREAD

**Issue by damien-pous** [coq/coq#10751]
The proof of rcomputation in the code below fails to pass Qed.
Actually, the statement itself, although accepted by Theorem, cannot be Admitted.

Preliminary debugging by Enrico suggests that this is due to implicit arguments : uncommenting the 'Unset Implicit Arguments' solves the problem.

You need the library at https://gitlab.inria.fr/amahboub/approx-models to compile that file.
(this public version on git does not move for now ; in case it would, commit e841ba45 from July 1st, 2019, is the one to select) 

Coq 8.9.1

Can't find how to attach a file to this report... I've put it there:
 http://perso.ens-lyon.fr/damien.pous/bug.v

**Comment by JasonGross** [comment]
What is the error message given by `Admitted`?

If you want to attach a file or development, you can either rename it to `.txt` or put it into a `.zip` file (or probably `.tar.gz` or `.tar.bz2`) and drag and drop the file onto the textbox on GitHub.

If you want to make a smaller version of this test case (which will make it easier to debug), you can use [my coq-bug-minimizer find-bug.py script](https://github.com/JasonGross/coq-tools/blob/master/find-bug.py) which will attempt to inline all of the dependencies, remove useless statements, etc.  (I expect you'll get a much smaller file if you feed it the `Admitted` version of the bug rather than the `Qed` version.)

**Comment by gares** [comment]
thanks, I've a branch that tries to use call by need instead of call by name in the computation of implicit arguments, that we identified being the cause of the divergence. I'm running a bench to see if it is a viable switch here https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/771/

I'll try it on you example asap.

**Comment by gares** [comment]
> What is the error message given by `Admitted`?

it never returns...

**Comment by SkySkimmer** [comment]
That doesn't seem to have anything to do with implicits, do you mean 772?

Gaëtan Gilbert

**Comment by ejgallego** [comment]
Can we get an up to date example on this bug?

**Comment by gares** [comment]
I don't recall anything about the bench results :-(
This is the commit that needs benchmarking https://github.com/gares/coq/commit/e759fff29800b3e0e5685a9ccba0d008e7c9480b
I don't think we really need to run it on the original problem, if a bench says there are no regressions then it's OK. There is no apparent reason for using call by name instead of call by need when computing the weak head normal form of a term.

**Comment by gares** [comment]
I'll open a PR and see
