### ISSUE TITLE
Bogus "Error: H is already used." on correct code

### ISSUE THREAD

**Issue by awson** [coq/coq#10778]
#### Description of the problem
When trying to build https://swirlds.com/downloads/hashgraph-coq.zip with 8.10b3 I've faced
```
coqc -q Decide.v
File ".\Tact.v", line 192, characters 23-26:
Error: H is already used.
```
which looks like a coq bug.

#### Coq Version
8.10b2 is already bad, 8.10b1 is ok.

After bisecting, I've found the bug have been introduced in https://github.com/coq/coq/commit/a4914ce3f0ca25d3579c1d1589adeb0c3551e086. HTH.

**Comment by Zimmi48** [comment]
Thanks for the bug report and the bisect.
This commit is part of #10239.
The `Tact.v` file already defines two tactic notations with `simple_intropattern`:

```
Tactic Notation "exploit" constr(t) "as" simple_intropattern(pat)
  :=
  exploit_main t ltac:(type of t) pat ltac:(fun _ => idtac).


Tactic Notation "exploit" constr(t)
  :=
  let H := fresh "H"
  in
    exploit_main t ltac:(type of t) H ltac:(fun _ => idtac).


Tactic Notation "so" constr(T) "as" simple_intropattern(pat)
  :=
  pose proof T as pat.
```

@herbelin I am surprised, because I thought that before your PR, simple_intropattern was not available in Tactic Notation, and here it seems that it was already in use, and that its semantics changed...

**Comment by herbelin** [comment]
This is due to `fresh` not anymore avoiding the variables occurring in patterns parsed by `simple_intropattern`. I'm preparing a fix.
