### ISSUE TITLE
Can't use same brackets for different (disjoint) custom entries

### ISSUE THREAD

**Issue by bcpierce00** [coq/coq#10813]
#### Description of the problem

The new custom entries stuff in 8.9 looks great, with one glaring downside: It does not seem possible to use the same brackets to access different custom grammars, even when there is no ambiguity.  If this is true, then it makes custom entries much less useful, as it leads to a confusing proliferation of brackets.  Moreover, I don't see why this restriction should be needed: after all, the default grammar is perfectly capable of parsing things of many different types.  So... what gives?

```coq
Inductive aexp : Type :=
  | ANum (n : nat).

Declare Custom Entry aexp.
Notation "[[ e ]]" := e (e custom aexp at level 0).

Inductive bexp : Type :=
  | Eq (a1 a2 : aexp).

Declare Custom Entry bexp.
(* Next line is not accepted: *)
Notation "[[ e ]]" := e (e custom bexp at level 0).

```

[MinimalCustomEntriesExample.txt](https://github.com/coq/coq/files/3682617/MinimalCustomEntriesExample.txt)

#### Coq Version

8.9.1

**Comment by maximedenes** [comment]
(I've inlined the example to make the report easier to read)

This restriction seems a bit arbitrary indeed, since the grammar can still be LL(1), from what I understand (if the nonterminals in `aexp` and `bexp` can be distinguished knowing the leftmost token.

@herbelin what is the rationale behind this limitation? Is it printing that would be problematic?

Even with this restriction, if one could define a grammar from vernac, we could do something like:
```coq
Notation "[[ e ]]" := e (e custom cexp at level 0).
Grammar Extend cexp := aexp + bexp.
```

**Comment by herbelin** [comment]
> @herbelin what is the rationale behind this limitation? Is it printing that would be problematic?

If `aexp` and `bexp` are disjoint, one can certainly build a `cexp` which combines them and write a `Notation "[[ e ]]" := e (e custom cexp at level 0).` together with rules in `cexp` which simulates the effect of having rules in `bexp` and `aexp`, taking care of factorizing the possible interferences in `aexp` and `bexp`. Maybe can a realistic case be given, e.g. starting the discussion from Konstantinos Kallas' example on coq-club, to see how to do it?

On the other side, I'm wondering: is there a implicit question about having the same brackets triggering calls to different parsers depending on scope?

**Comment by maximedenes** [comment]
Ah yes, I see: one can do what I wrote above with just notations.

I'll have a look at the real example, thanks for the suggestion.

**Comment by maximedenes** [comment]
> together with rules in `cexp` which simulates the effect of having rules in `bexp` and `aexp`, taking care of factorizing the possible interferences in `aexp` and `bexp`

@herbelin This is the part I'm not sure about. I defined a `[[ x ]]` notation with `x` in a new custom entry `imp`. Now I'd like to inject both `aexp` and `bexp` in `imp`. However, Coq still does not let mean define the two injections:

```coq
Notation "x" := x (in custom imp at level 0, x custom aexp at level 10).
Notation "x" := x (in custom imp at level 0, x custom bexp at level 10).
```

It still fails because of the same limitation @bcpierce00 reported here.

So I guess the question is simple: how do you define a custom entry that is the union of two other entries? Sorry, I imagine this is a beginner question, but I'm indeed just learning the basics of custom entries.

**Comment by bcpierce00** [comment]
> On the other side, I'm wondering: is there a implicit question about having the same brackets triggering calls to different parsers depending on scope?
> 
I hadn’t gotten as far as wondering about this, but I agree that it’s an excellent question!!  :-)

**Comment by herbelin** [comment]
> > On the other side, I'm wondering: is there a implicit question about having the same brackets triggering calls to different parsers depending on scope?
> > 
> I hadn’t gotten as far as wondering about this, but I agree that it’s an excellent question!!  :-)

Actually, I talked too fast as that may be quite tricky to implement, if ever possible. Indeed, the interpretation of scopes would now have to be interleaved with the parser which typically includes (among others) tweaking the rule for parsing application to update the current scope stack dynamically. Then,  we would typically have to reserve `[[` as special and, when seeing `[[` in the parser, based on current scope, calling the appropriate subparser, then, after returning from the subparser, checking that `]]` comes afterwards.

Similarly, making the inside of  `[[ ... ]]%foo` parsed differently depending on `foo` would require to parse the text `foo` before parsing the inside which is basically incompatible with a left-to-right parsing technology. 

By the way, this makes me realize an inconsistent design in the implementation. The following is allowed:
```
Declare Custom Entry aexp.
Declare Custom Entry bexp.
Notation "[[ e a]]" := e (e custom bexp at level 10).
Notation "[[ e b]]" := e (e custom aexp at level 10).
```
but it has the same defect as using twice `[[ ...]]` for different grammars: the grammars for `aexp` and `bexp` would not be automatically factorized, and, if overlapping, an error in the first one would not be able to be tracked at the right place to restart with `bexp`. [Continuing reasoning aloud, if one is ready to pay the price of backtracking, one could however install a backtracking point after `[[` so that if parsing using `bexp` fails, `aexp` is tried. That may be worth being investigated.]

**Comment by maximedenes** [comment]
@bcpierce00 were you satisfied with the answers you got above, or would like us to do more on this issue?

**Comment by maximedenes** [comment]
Closing for now, but feel free to reopen if needed.
