### ISSUE TITLE
Parallel build with 8.10 release results in error about missing gramlib/.pack/gramlib.cmi

### ISSUE THREAD

**Issue by tchajed** [coq/coq#10864]
#### Description of the problem

Compiling from the release tarball for 8.10.0 using `./configure` and `make -j8` reliably produces the following error about a missing interface for gramlib:

```
OCAMLC    interp/numTok.mli
OCAMLOPT  gramlib/.pack/gramlib.ml
OCAMLC    gramlib/.pack/gramlib.ml
OCAMLC    tactics/dnet.mli
OCAMLC    tactics/dn.mli
OCAMLC    vernac/attributes.mli
OCAMLC    vernac/locality.mli
OCAMLC    stm/spawned.mli
OCAMLC    stm/dag.mli
File "gramlib/.pack/gramlib.ml", line 1:
Error: Could not find the .cmi file for interface gramlib/.pack/gramlib.cmi.
make[1]: *** [gramlib/.pack/gramlib.cmx] Error 2
make[1]: *** Waiting for unfinished jobs....
OCAMLC    stm/tQueue.mli
make: *** [submake] Error 2
```

The build works fine for me without parallelism, but of course is much slower.

#### Coq Version

8.10 on macOS

**Comment by SkySkimmer** [comment]
Probably GENGRAMFILES should be added to GENMLFILES or some such thing.

**Comment by Blaisorblade** [comment]
Thanks @SkySkimmer, that helped for #10876 tho I added to GENFILES. I also tried your GENMLFILES suggestion, but it failed with a bunch of warnings (including circular deps being dropped).

The alternative which I tried and failed was:
```
-GENMLFILES:=$(LEXFILES:.mll=.ml) $(YACCFILES:.mly=.ml) $(GENMLGFILES)  ide/coqide_os_specific.ml kernel/copcodes.ml kernel/uint63.ml
+GENMLFILES:=$(LEXFILES:.mll=.ml) $(YACCFILES:.mly=.ml) $(GENMLGFILES)  ide/coqide_os_specific.ml kernel/copcodes.ml kernel/uint63.ml $(GENGRAMFILES)
```

Folks on ocaml/opam-repository#15017 would like a fix as well.

**Comment by gares** [comment]
The bug is that `gramlib/.pack/gramlib.ml` has not `.mli` file, and that we compile byte and opt in parallel, so at the same time `ocamlc` and `ocamlopt` generate `gramlib.cmi` at the same time.

I can't reproduce it on my machine, I guess my hard drive is too fast, but I'm convinced this is the root cause.

**Comment by gares** [comment]
The problem might be that `Makefile.build` computes the .ml files without a corresponding .mli too early
https://github.com/coq/coq/blob/ac862fb5ae8eb15c15f81817d78ba8db4430ea8b/Makefile.build#L731-L750
since `gramlib.ml` is generated by the following code (later, I'm afraid)
https://github.com/coq/coq/blob/ac862fb5ae8eb15c15f81817d78ba8db4430ea8b/Makefile.build#L623-L642
What do you think @SkySkimmer

**Comment by SkySkimmer** [comment]
I think the issue is that GENGRAMFILES has both the .ml and the .mli, then the MLWITHOUTMLI computation is incorrect.
We need to add GENGRAMFILES filtered for .ml (resp .mli) to GENMLFILES (resp GENMLIFILES, which doesn't exist currently but used to), or some such thing.

**Comment by gares** [comment]
You mean adding to
https://github.com/coq/coq/blob/53e8533b58a22584a642447123ae4aecfdf665a3/Makefile#L109
an explicit mention to `gramlib/.pack/gramlib.ml`?

**Comment by SkySkimmer** [comment]
Not just that one, all the .ml in GENGRAMFILES

**Comment by gares** [comment]
I've opened a PR, let's see
