### ISSUE TITLE
Dependency checker in configure

### ISSUE THREAD

**Issue by QinxiangCao** [coq/coq#10978]
## Description of the problem

I choose to build coq from source code. When "./configure", it tells me that my ocaml is good, my ocamlfind is good and the Num library is good.

However, my Num library is only compiled and installed under an old ocaml. That is not detected. I am not sure whether testing this is possible in "configure". 

At least, I did not find this problem until my compilation failed at a invalid "/usr/local/lib/ocaml/nums.cma" or "/usr/local/lib/ocaml/nums.cmxa" file.

#### Coq Version

8.10.1

**Comment by ejgallego** [comment]
Hi @QinxiangCao , configure does use `ocamlfind` to detect `num`, so I guess in this case the problem is that your OCaml is broken [quite a common occurrence, for example when upgrading a compiler]

It is likely that you compiled the `num` library with the older OCaml, then you need to remove it.

I am thus tempted to mark this bug as `not a Coq bug`. Personal recommendation: remove all traces of system-wide OCaml and only use OPAM switches with their own compiler.

**Comment by QinxiangCao** [comment]
I see. I install new Ocaml first, then install new ocamlfind. But old ocamlfind file still lies in my system thus ocamlfind can find my old Num. I agree that it is "not a coq bug" in this sense and hopefully ocamlfind can improve it in the future. Thank you very much.

By the way, I just dislike Opam personally. Thus I choose to install dependent softwares manually.

**Comment by ejgallego** [comment]
I'd say it is more like old `num` is still in the standard location, so `ocamlfind` does find it.

It is OK if you don't want to use opam, but then you'll have to track a fair amount of dependencies manually, and that gets hard very easily; keep in mind that that OCaml is not ABI compatible at all.
