### ISSUE TITLE
How to limit reserved notations to a scope?

### ISSUE THREAD

**Issue by KevOrr** [coq/coq#11008]
#### Description of the problem

Perhaps I'm just missing something in the docs, but I can't seem to find any way to limit a reserved notation to a scope, or any way to delete a reserved notation once it has been given an interpretation.

For example,

```coq
Reserved Notation "a ; b : c" (at level 40, b at level 59).

Inductive Foo : nat -> nat -> nat -> Prop :=
| Foo_I a b c : (a; b : c)
where "a ; b : c" := (Foo a b c) : Foo_scope.

Delimit Scope Foo_scope with foo.

Check (1; 2 : 3)%foo.
Fail Check (1; 2 : 3). (* Expected *)
Fail Record Bar :=
  bar {
      x : nat;
      y : nat
    }. (* Expected to pass, actually fails *)

Close Scope foo.
Fail Record Bar :=
  bar {
      x : nat;
      y : nat
    }. (* Expected to pass, actually fails *)
```

Even though the custom notation conflicts with the notation(s) for `Record`, I would expect some way of disabling the notation temporarily. I expected that by limiting the notation to a scope, and ensuring that this scope is closed before the `Record` command, it would parse correctly. But it seems that the _reserved_ notation is lonely\*, and according to [the docs](https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#coq:cmd.reserved-notation), I don't see any way to limit a reserved notation to a scope.

#### Coq Version

8.9.1 (opam)
Linux

Edit: side note: I can't seem to find the notation(s) which make `Record` work (e.g. `Print Scopes` or `Print Visibility`). Is there some ML-level parsing hook that it takes advantage of?

\*I'm really not sure what I mean here by _lonely_. Maybe a typo

**Comment by herbelin** [comment]
Hi @KevOrr, a notation globally modifies the parser, independently of the presence of scopes.

I know that this a strong constraint on the parser, but we don't know how to do better at the current time (except by using so-called [custom entries](https://coq.inria.fr/distrib/current/refman/user-extensions/syntax-extensions.html?highlight=custom#custom-entries)).

What you would like is that the grammar is modified only within the scope of a `( ... )%foo` expression. To start with, our parser is left-to-right, so, it is already difficult to know that the inner of the parenthesis should be parsed with a special grammar because the `%foo` arrives only afterwards...

**Comment by KevOrr** [comment]
Thanks for your comment @herbelin. I had forgotten about this issue actually, I think I got around it by just modifying my notation to `a ;; b : c` or something. And that's an interesting point about `( ... )%foo` that I hadn't considered before.

Thanks for directing me towards custom entries, I'll try them out.
