### ISSUE TITLE
CI runners from ci.inria.fr need maintenance

### ISSUE THREAD

**Issue by vbgl** [coq/coq#11073]
The VMs from ci.inria.fr that we use for CI need maintenance. This is an issue per se.

On linux machines, docker images pile up. Periodically running “docker system prune” may help. Otherwise, one can list the images by executing “docker images” and remove the ones that are no longer useful by executing “docker rmi XXXX”.

On Windows machines, build directories are not always removed (usually in case of failure). I don’t know how to manually remove these directories. Maybe Michael can help.

Ping @MSoegtropIMC

**Comment by MSoegtropIMC** [comment]
@vbgl: I once did a PR #9227 which contains some scripts and documentation on the runner maintenance. It was not integrated back then because it was expected that we switch to Azure soon, but this did not happen as yet.

See (https://github.com/coq/coq/pull/9227/files), especially the section "# Hints on Runner maintenance work" in the Readme file. There is a script which logs into all runners one by one from Windows - not sure if this works from a non Windows machine.

I moved to Apple this month and am still struggling a bit with OSX. I don't have a Windows machine here but can do the maintenance from home this evening.

**Comment by MSoegtropIMC** [comment]
P.S.: It wouldn't be hard to change the build scripts such that they clean up before they start. This is currently not done so that one can analyse what is going on. But I would say this is pretty well understood meanwhile.

**Comment by vbgl** [comment]
Thanks Michael. Reading carefully your hints for maintenance work, I could free a lot of disk space on all Windows runners.

**Comment by MSoegtropIMC** [comment]
@vbgl: thanks - I also installed the required stuff on my private Windows machine and had a look just now. It looks like you killed some of the running processes - there where a lot of dead cygwins from around 16:30 today. Please delete only cygwins / coqs which are older than the runner timeout (I think this is 6 hours).

I will do a PR do remove the folder name randomization and to delete the folders on start. This should substantially reduce the required maintenance work.
