### ISSUE TITLE
With native_compute, flambda slows Coq (a bit on Linux, a lot on Mac)

### ISSUE THREAD

**Issue by Blaisorblade** [coq/coq#11107]
#### Description of the problem

As discussed in #10975, on macOS, flambda appears to slow down Coq, unless `native_compute` is disabled at build-time. Confirmed by me and @llelf.

> `time make -j1` for stdpp master. Coq master, ocaml 4.09.0, macOS 10.13.

||  | ¬ native-compiler
-|-|-
vanilla | 1m48s | 1m23s
flambda | 2m21s | 1m23s (the same)

_Originally posted by @llelf in https://github.com/coq/coq/pull/10975#issuecomment-547122866_. More details in that PR and links.

#### Coq Version

macOS only: Coq 8.10, Coq master.

EDIT: related issues include #12564 (about fixing native-compute workflows) and #11178.

**Comment by ejgallego** [comment]
Thanks @Blaisorblade , I couldn't reproduce in linux so this issue could benefit from help from OSX developers.

**Comment by Blaisorblade** [comment]
I've created variants of the coq package in https://github.com/Blaisorblade/opam-overlay that enable flambda (and disable native-compute).

I'm also updating https://github.com/Blaisorblade/my-ocaml-coq-benchs to benchmark the various configurations reproducibly (without manual setup), so that I can test this on both Mac and Linux.

**Comment by ejgallego** [comment]
We got a worrying report in #11178 which seems very related to this; I'm setting the milestone as this may be release-critical.

Note @Blaisorblade that the `strace` output in that bug revealed very strange stuff related to native linking; which in the first place should not be attempted.

**Comment by Blaisorblade** [comment]
Thanks, I thought I was going mad or missing something really stupid.

I also have some evidence that native-compiler might *slow down* Coq even on Linux and without flambda, tho the effect is smaller — but I wasn't believing my eyes, so I never finalized and posted that. A highlight:

| user time | default | ¬ native-compiler
-|-|-
stdpp, Linux | 2m15s +/- 1.2s | 2m7s +/- 0.4s

Raw data:
```
run-3/coq-stdpp-dev.2019-09-19.1.9041e6d8-bench-ocaml-4.07.1-coq-8.10.1.log: Mean +/- stddev: 135.663 +/- 1.16863 s user time
run-3/coq-stdpp-dev.2019-09-19.1.9041e6d8-bench-ocaml-4.07.1-coq-8.10.1-no-native.log: Mean +/- stddev: 127.367 +/- 0.399283 s user time
```

**Comment by ejgallego** [comment]
Indeed that look consistent with the time it'd be spent on loading the native libs; if you could confirm with `strace` that native libs are being loaded we will make this a RC bug.

**Comment by Blaisorblade** [comment]
> if you could confirm with strace that native libs are being loaded we will make this a RC bug.

That's confirmed on mac https://github.com/coq/coq/issues/11178#issuecomment-567082853; I'm traveling so I won't have time for this soon, but by now the issue seems to be confirmed and reproducible (see also https://github.com/coq/coq/pull/11306#issuecomment-567109765).

**Comment by ppedrot** [comment]
Postponing for the same reasons as #11178.

**Comment by Zimmi48** [comment]
Removing the milestone for the same reason as #11178.

**Comment by Blaisorblade** [comment]
@silene mentions that this issue was finally fixed in 8.13, so that `ondemand` has no overhead. Closing.

**Comment by Zimmi48** [comment]
@proux01 specifically wrote "your problem is fixed in 8.13". This doesn't mean that the bad interaction with flambda has been investigated or resolved but rather (IIUC) that the new `-native-compiler ondemand` configure option, which doesn't build the stdlib with `native_compute` by default, shouldn't produce any slowdown for a user who is *not* attempting to use `native_compute`.

**Comment by Zimmi48** [comment]
Although, it should also have been the case when you were previously using the `-native-compiler yes` configure option with Coq < 8.13 if I read the [table in the related CEP](https://github.com/erikmd/ceps/blob/bd40b83806ac0eeb884260d8649c76bc40772e1f/text/048-packaging-coq-native.md#regarding-item-2) correctly. As far as I'm aware, this puzzling behavior was never investigated nor really confirmed, and thus not fixed either.
However, if this behavior doesn't really exist, then why do we need to turn native-compute completely off (with the `-native-compiler no` configure option) in the case the `coq-native` package isn't installed in an opam switch?

**Comment by silene** [comment]
> if this behavior doesn't really exist

Whenever a `.vo` file is loaded, the corresponding `.cmxs` is loaded too. In the old model (i.e., `ondemand`, but files could still be precompiled, e.g., the standard library), the code was thus loading the files from the standard library. Unfortunately, dynamically loading a file is exceedingly slow on macOS.

Now, that the standard library is no longer precompiled with `-native-compiler ondemand`, Coq should not have anything left to load, hence no slowdown. (There are still a few system calls, but it should not be noticeable.)

The bug still exists for `-native-compiler yes`, because the precompiled files are present (and thus will be loaded) even if `native_compute` is not used.

**Comment by Zimmi48** [comment]
Thanks for the clarification. Wouldn't it make sense then that the default configure option on opam (in the absence of the `coq-native` package) be `-native-compiler ondemand` rather than `-native-compiler no`? cc @erikmd 

Also, shouldn't there an issue still open about the bad interaction with flambda? (#11178 is specifically about macOS, not about flambda.)

**Comment by Zimmi48** [comment]
> Thanks for the clarification. Wouldn't it make sense then that the default configure option on opam (in the absence of the `coq-native` package) be `-native-compiler ondemand` rather than `-native-compiler no`?

Oh, I see that @Blaisorblade is already working on it.

**Comment by Blaisorblade** [comment]
1. I split out #13849 and #13850 from here.
2. I apologize for missing @proux01's message in https://github.com/coq/coq/pull/13352#issuecomment-726736049.
3. 
> Thanks for the clarification. Wouldn't it make sense then that the default configure option on opam (in the absence of the coq-native package) be -native-compiler ondemand rather than -native-compiler no? cc @erikmd

IIUC for Coq < 8.13, the CEP still did the right thing, because the precompiled stdlib caused a slowdown. But for Coq >= 8.13 you're right AFAIK. That suggests https://github.com/ocaml/opam-repository/compare/master...Blaisorblade:coq-813-native-compiler-ondemand, but I don't know if this has further knock-on effects (which is why I haven't pushed the "submit PR" button).

**Comment by Blaisorblade** [comment]
I hope the above covers what remains of this issue, but I could well be wrong again; I'm sorry for my mistake.
