### ISSUE TITLE
Simultaneous definition of term and notation in custom grammar 

### ISSUE THREAD

**Issue by angelhof** [coq/coq#11121]
#### Description of the problem

I am having trouble simultaneously defining a term and a notation in a custom grammar. Here is an indicative example:

```
Declare Custom Entry example.

Notation "'[' e ']'" := e (e custom example).
Notation "x" := x (in custom example at level 0, x constr at level 0).

Reserved Notation "'+a' x y" (in custom example at level 10).

Fixpoint add (x y :nat) :=
  match x with
  | 0 =>
    y
  | S x' =>
    S [+a x' y ]
  end

where "'+a' x y" := (add x y).
```

The parser returns the following error.

```
Error: Parsing rule for this notation has to be previously declared.
```

Am I doing something wrong?

#### Coq Version

8.9.0

**Comment by JasonGross** [comment]
I would expect you'd have to write `where "'+a' x y" := (add x y) (in custom example).`  Does this work?

**Comment by angelhof** [comment]
Unfortunately no, it returns:
```
Error: Syntax error: '.' expected after [vernac:gallina] (in [vernac_aux]).
```

**Comment by bcpierce00** [comment]
Coq devs (@herbelin ? @maximedenes ?): Could we raise the priority of this custom entry issue?  It's been pending for a while now...  Thank you!!

**Comment by bcpierce00** [comment]
P.S.  Here is a minimal example from Irene Yoon...
`Declare Custom Entry example.

Reserved Notation " x '==' 1 " (in custom example at level 0, x constr).

Fail Fixpoint stupid (x : nat) : nat := 1
where " x '==' 1" := (stupid x).
`

**Comment by maximedenes** [comment]
@bcpierce00 Sure, I'll have a look ASAP.

**Comment by maximedenes** [comment]
There seems to be several problems here.

First, I'm not sure why the following is rejected:
```coq
Declare Custom Entry example.
Fixpoint stupid (x : nat) : nat := 1.
Reserved Notation " x '==' 1 " (in custom example at level 0, x constr).
Notation " x '==' 1" := (stupid x) (in custom example).
```

while the following is accepted:
```coq
Declare Custom Entry example.
Fixpoint stupid (x : nat) : nat := 1.
Reserved Notation " x '==' 1 " (at level 0, x constr).
Notation " x '==' 1" := (stupid x).
```

Second, I guess as Jason wrote above, the `in custom` syntax should be accepted in `where` clauses.

**Comment by maximedenes** [comment]
And a third strange behavior:
```coq
Fixpoint stupid (x : nat) : nat := 1.
Notation " x '==' 1" := (stupid x) (at level 0).
Notation " x '==' 1" := (stupid x) (at level 1).
```
is rejected, while:
```coq
Declare Custom Entry example.
Fixpoint stupid (x : nat) : nat := 1.
Notation " x '==' 1" := (stupid x) (in custom example at level 0).
Notation " x '==' 1" := (stupid x) (in custom example at level 1).
```
is accepted

**Comment by maximedenes** [comment]
@herbelin I see that the original custom notations commit introduced the following ADT:

```ocaml
type notation_entry_level = InConstrEntrySomeLevel | InCustomEntryLevel of string * int
```

but I'm not sure why levels in custom entries are treated differently than the `constr` ones (which here can be omitted). Can you explain a bit how they differ?

**Comment by herbelin** [comment]
> I'm not sure why levels in custom entries are treated differently than the constr ones (which here can be omitted). Can you explain a bit how they differ?

This is because precedences for printing are managed at the level of the printer for constr (in `ppconstr.ml`, with the insertion of parentheses in the printing loop) but at the level of externalization (in `constrextern.ml` with an explicit grammar rule for `"( x )"`) for custom entries.

**Comment by maximedenes** [comment]
Yes, this is exactly what I was looking at. But why this difference?

**Comment by herbelin** [comment]
As far as I can judge, the following are bugs:
```
Declare Custom Entry example.
Fixpoint stupid (x : nat) : nat := 1.
Reserved Notation " x '==' 1 " (in custom example at level 0, x constr).
Notation " x '==' 1" := (stupid x) (in custom example).
(* Should find the reserved notation *)
```
```
Declare Custom Entry example.
Fixpoint stupid (x : nat) : nat := 1.
Notation " x '==' 1" := (stupid x) (in custom example at level 0).
Notation " x '==' 1" := (stupid x) (in custom example at level 1).
(* Should see that it is already defined *)
```
The two `where` examples are a priori correct failures. But one would need a way to tell that this is about a custom grammar (e.g. with a syntax `"'+a' x y" := (add x y)  (in custom example)`).

**Comment by herbelin** [comment]
> Yes, this is exactly what I was looking at. But why this difference?

Originally, the insertion of parentheses to go from level 0 to some higher level n>0 was not thought as a grammar rule, but as a special, say, disambiguation mechanism.

It is only with the introduction of custom grammars that the insertion of parentheses has been seen as a particular case of a grammar rule rather than as an ad hoc disambiguation mechanism. I could have changed `ppconstr.ml` so that parentheses become part of the abstract syntax tree, like it is for custom grammars. I.e. I could have forced the addition at extern-time of a `CNotation ("( _ )", ...)` node for parenthese in `constr_expr`, but I found this to be too disruptive/disturbing/heavy change, so I kept the management of parentheses at printing of `constr` in `ppconstr.ml` as it was.

If the developers are ready to make the step though, why not.

**Comment by maximedenes** [comment]
I see, thanks for the explanation.

This discrepancy in the data structures seem related to the bug(s): the map used for storing levels is indexed by a notation "key", which for `constr` is fine but for custom entries also contains the level, which makes no sense at that particular point.

I don't know if the right fix is to change notation keys, so that they don't contain a level, or to simply change this particular level map, so that it is indexed by entries without levels.

**Comment by herbelin** [comment]
Probably the second option (assuming this is compatible with the other uses of this map, if any).

**Comment by maximedenes** [comment]
There's something that I still understand: if a notation can be defined only at one level, in a given entry, why is the level part of the `notation` type (for custom entries)?

**Comment by maximedenes** [comment]
Related question: why are there two levels in `Metasyntax.syn_data` (i.e. `level` and the second component of `not_data`)?

**Comment by herbelin** [comment]
> if a notation can be defined only at one level, in a given entry, why is the level part of the notation type

That's probably correct that it should be retrievable by an access in a table. That may clarify things (up to a probably time-insignificant indirection), e.g. by avoiding a difference between `notation_entry` and `notation_entry_level` in `constrexpr.ml`. Might be tempted if you have the courage.

> Related question: why are there two levels in Metasyntax.syn_data (i.e. level and the second component of not_data)?

This is because of the `{ ... }` syntax hack. The first level is the intended one. The second, in `not_data` is an effective one taking into account that the grammar rule may have been split into several components (e.g `{ A } + { B }` is a combination of `A + B` and `{ A }`, so the effective sublevels for `+` are the ones of `+` (i.e. 50) and not the official ones of `{ A } + { B }` (which are 200).

**Comment by maximedenes** [comment]
https://github.com/coq/coq/pull/12523 is a first draft for this feature and the bug fixes.

**Comment by bcpierce00** [comment]
Do we know whether this fix is likely to be included in 8.12?

**Comment by ejgallego** [comment]
> Do we know whether this fix is likely to be included in 8.12?

Seems about borderline I'd say, but IMO it is still possible; once the fix is ready we'll prioritize review and merge.

**Comment by bcpierce00** [comment]
Maxime, whose help do you need to polish the fix?

**Comment by maximedenes** [comment]
@bcpierce00 I got some feedback from Hugo on https://github.com/coq/coq/pull/12523, so I should be able to complete the patch today unless something unexpected shows up.

**Comment by ejgallego** [comment]
@bcpierce00 I understand it is pretty important for you folks to get this in to 8.12.0, right?

We still have some time, but we cannot delay too far into July and it should be out before people go on holidays around here.

**Comment by maximedenes** [comment]
@ejgallego Do you have a pointer to the current 8.12 schedule?

**Comment by ejgallego** [comment]
It is in the standard place https://github.com/coq/coq/wiki/Release-Plan-for-Coq-8.12 , however see the discussion in the Zulip release thread; we aim to release a bit later than planned [and we can be flexible depending on issues such as this one]

**Comment by bcpierce00** [comment]
Yes, I would love to get it into the 8.12 release if possible.  We're in the middle of a huge round of notation tidying in SF, and I don't want to do it twice!

**Comment by maximedenes** [comment]
@bcpierce https://github.com/coq/coq/pull/12523 is now ready (modulo one last CI run). Sorry for the delay, something unexpected did show up (questions of semantics of levels w.r.t. `only printing` and `only parsing`). The code handling notation levels would probably need more polishing, but I did a first round to make this new feature possible.

**Comment by maximedenes** [comment]
@bcpierce00 https://github.com/coq/coq/pull/12523 is now ready (modulo one last CI run). Sorry for the delay, something unexpected did show up (questions of semantics of levels w.r.t. `only printing` and `only parsing`). The code handling notation levels would probably need more polishing, but I did a first round to make this new feature possible.
