### ISSUE TITLE
"make refman-pdf" issues/curiosities

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#11218]
Some issues/curiosities I've run into with `make refman-pdf` on master (version 8.10+):

- Running this make when `doc/sphinx/_build/latex` is empty and then a second time give different results.  (In my case, I get different failures.  I'm debugging a sphinx enhancement, https://github.com/coq/coq/pull/11183).  Seems to me the simplest fix is for the makefile to erase the directory before starting.  I can submit a PR to do this.  Please advise.

- We use different OCaml versions for the `doc:refman` (building pdf doc) and `doc:refman:dune` (building html doc), respectively 4.05 and 4.09.  I expected these would be consistent.  The 4.09 build has 8 `Alert deprecated:` messages.  Should anything change here?

- `doc/sphinx/_build/latex` contains several files that aren't in git that look like inputs to the build process rather than outputs.  Presumably these are downloaded as part of the make from some trusted location--but doesn't that leave us vulnerable to breakage if and when that trusted source is updated?  Also seems to make it rather difficult to tweak those options.  For example IIRC the latex output suggests setting a `-f` option that looks like it has to be in the downloaded `Makefile`.   The files include:

```
-rwxrwxrwx 1 jfehrle jfehrle 1765 Nov 29 18:21 Makefile
-rwxrwxrwx 1 jfehrle jfehrle  8888 Jul 30 15:58 footnotehyper-sphinx.sty
-rwxrwxrwx 1 jfehrle jfehrle 77197 Jul 30 15:58 sphinx.sty
-rwxrwxrwx 1 jfehrle jfehrle  2487 Jul 30 15:58 sphinxcyrillic.sty
-rwxrwxrwx 1 jfehrle jfehrle  8137 Nov 29 18:20 sphinxhighlight.sty
-rwxrwxrwx 1 jfehrle jfehrle   731 Nov 29 18:21 sphinxmessages.sty
-rwxrwxrwx 1 jfehrle jfehrle 14618 Jul 30 15:58 sphinxmulticell.sty
```

- The make generates the file `doc/unreleased.rst` in the source tree.  Perhaps it should go in the `_build` tree?

- I get this failure running under Windows/WSL.  I suspect it is between not easy and impossible to work around in WSL (memory mapping is not the same as in Linux).  The next version of Windows/WSL, due out next spring, will run Linux as a virtual machine, which will probably resolve the issue.

```
Latexmk: calling xindy( -L english -C utf8 -M sphinx.xdy -o CoqRefMan.ind CoqRefMan.idx )
Cannot map memory to address 0x800965be3000 .
```

**Comment by SkySkimmer** [comment]
>Running this make when doc/sphinx/_build/latex is empty and then a second time give different results. (In my case, I get different failures. I'm debugging a sphinx enhancement, #11183). Seems to me the simplest fix is for the makefile to erase the directory before starting. I can submit a PR to do this. Please advise.

Can you tell more about what's different?

> The 4.0.9 build has 8 Alert deprecated: messages. Should anything change here?

This is because it's recompiling coq for some reason (https://github.com/coq/coq/issues/10694), the alerts are known and nothing to do with the refman (not sure if there's an issue about them though, @ejgallego ?)

>doc/sphinx/_build/latex contains several files that aren't in git that look like inputs to the build process rather than outputs. Presumably these are downloaded as part of the make from some trusted location--but doesn't that leave us vulnerable to breakage if and when that trusted source is updated?

Pretty sure they're just generated by sphinx.

> For example IIRC the latex output suggests setting a -f option that looks like it has to be in the downloaded Makefile.

I don't know what you're talking about.

>The make generates the file doc/unreleased.rst in the source tree. Perhaps it should go in the _build tree?

I think _build is more for the stuff generated by sphinx than for our stuff. We also generate index.html (in the conf.py) without putting it in _build.

**Comment by SkySkimmer** [comment]
>I get this failure running under Windows/WSL. I suspect it is between not easy and impossible to work around in WSL (memory mapping is not the same as in Linux). The next version of Windows/WSL, due out next spring, will run Linux as a virtual machine, which will probably resolve the issue.

See also https://github.com/Microsoft/WSL/issues/3403

**Comment by Zimmi48** [comment]
>We use different OCaml versions for the `doc:refman` (building pdf doc) and `doc:refman:dune` (building html doc), respectively 4.05 and 4.09.

Yes, this has changed recently when updating Dune, which no longer supports OCaml 4.05.

>Presumably these are downloaded as part of the make from some trusted location

I'm pretty sure there is no download process during the build, otherwise we couldn't build offline! I think you're confusing "downloaded" and "copied from somewhere outside the source of Coq" (i.e. in the install path of the Sphinx dependencies).

>     * The make generates the file `doc/unreleased.rst` in the source tree.  Perhaps it should go in the `_build` tree?

Well, there are lots of files that running `make` adds to the source tree. With Dune, there is no such problem (but the refman-pdf target isn't provided yet...).

**Comment by jfehrle** [comment]
> Can you tell more about what's different?

Running with an empty directory generates CoqRefMan.pdf, which is not regenerated when the directory is populated.  Here's an `ls -t` excerpt immediately after I ran in a populated directory at 12:22. The files with the earlier timestamp look like output files that were not regenerated.  It would be interesting for someone to try doing 2 runs on their local Linux system to see if this is a general issue.  Probably worth tweaking the makefile in any case.

```
-rwxrwxrwx 1 jfehrle jfehrle   15829 Nov 30 12:22 CoqRefMan.fdb_latexmk
-rwxrwxrwx 1 jfehrle jfehrle     558 Nov 30 12:22 make.bat
-rwxrwxrwx 1 jfehrle jfehrle     644 Nov 30 12:22 latexmkrc
-rwxrwxrwx 1 jfehrle jfehrle    1765 Nov 30 12:22 Makefile
-rwxrwxrwx 1 jfehrle jfehrle     731 Nov 30 12:22 sphinxmessages.sty
-rwxrwxrwx 1 jfehrle jfehrle 4148636 Nov 30 12:22 CoqRefMan.tex
-rwxrwxrwx 1 jfehrle jfehrle    8137 Nov 30 12:22 sphinxhighlight.sty
-rwxrwxrwx 1 jfehrle jfehrle 1252483 Nov 29 22:52 CoqRefMan.log
-rwxrwxrwx 1 jfehrle jfehrle 2800354 Nov 29 22:52 CoqRefMan.pdf
-rwxrwxrwx 1 jfehrle jfehrle  104486 Nov 29 22:52 CoqRefMan.idx
-rwxrwxrwx 1 jfehrle jfehrle   10251 Nov 29 22:52 CoqRefMan.out
-rwxrwxrwx 1 jfehrle jfehrle   67556 Nov 29 22:52 CoqRefMan.toc
-rwxrwxrwx 1 jfehrle jfehrle   19810 Nov 29 22:52 CoqRefMan.fls
-rwxrwxrwx 1 jfehrle jfehrle  372537 Nov 29 22:52 CoqRefMan.aux
```

> > For example IIRC the latex output suggests setting a -f option that looks like it has to be in the downloaded Makefile.

> I don't know what you're talking about.

See the second to last line in the following annotated output.  Not sure I really want to try the `-f` option, but I was interested in running the conversion step from `CoqRefMan.tex` to `CoqRefMan.pdf` to try to figure out how to get fix the errors in the .tex file.

```
(* skip many messages *)

Runaway argument?
{\sphinxupquote {
! Paragraph ended before \sphinxbfcode was complete.
<to be read again>
                   \par
l.12313

? R                 (* I type "R" *)

(* more than 10000 lines of messages about missing references *)

Latexmk: Summary of warnings:
  Latex failed to resolve 914 reference(s)
  Latex failed to resolve 61 citation(s)
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,           (* the -f option *)
 unless error was exceeding maximum runs of latex/pdflatex.
```

>> doc/sphinx/_build/latex contains several files that aren't in git that look like inputs to the build process rather than outputs.

> Pretty sure they're just generated by sphinx.

Yeah, I verified that.

**Comment by jfehrle** [comment]
> I'm pretty sure there is no download process during the build, otherwise we couldn't build offline!

My system is always online, except a little bit when I'm travelling.

>> We use different OCaml versions for the `doc:refman` (building pdf doc) and `doc:refman:dune` (building html doc), respectively 4.05 and 4.09.

> Yes, this has changed recently when updating Dune, which no longer supports OCaml 4.05.

So 4.09 is now required for Coq?  Time to update my ocaml.

**Comment by Zimmi48** [comment]
> So 4.09 is now required for Coq? Time to update my ocaml.

No, because Dune is still not required for Coq. If you want to use Dune, then you need a version between 4.06 and 4.09.

**Comment by ejgallego** [comment]
Or you can use Dune 1.11 , in fact if you have a non trivial Opam setup you will be already stuck in Dune 1.11 as Dune 2.0 conflicts with many packages due the jbuilder conflict [this is going to be fixed soon tho]

Note that we haven't yet decided what the compat story for Coq + Dune will be, we will do so once the support is "stable", for example not a big worry in having Dune 2.0 work with 4.05

**Comment by jfbu** [comment]
We at Sphinx are interested into helping fixing PDF build issues users encounter. When the latex builder is exercised it creates from templates coming with Sphinx itself some files in the latex build repertory which are adapted to the user chosen configuration in conf.py. For example whether the latex_engine is default or is xelatex. This influences what are those files. There is also a file coming from a Sphinx call to Pygmentize library. Among those files there is a Makefile and a make.bat and a latexmkrc file which configures Latexmk execution.

It is possible to override some conf.py settings from the command line invocation of sphinx-build, thus influencing the actual configuration put by Sphinx into the latex build directory (from then on refered too as `<latexbuilddir>`).  For the specific case of the [`latex_use_xindy`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-latex_use_xindy) configuration variable, Sphinx 2.2.2 and prior suffers from an unfortunate bug which will be fixed in next release and setting it from the command line to override the conf.py is impossible. If your project does not need indexing terms starting with Unicode characters, then add `latex_use_xindy =  False` in the conf.py.

From the source directory where you execute sphinx-build if you want to clean the latex build and have a `make` executable available then (in Linux syntax) `make -C <latexbuilddir> clean` will clean up all auxiliary files (but not the actual foo.tex file created by the latex builder). You can then do `make -C <latexbuilddir> all-pdf` to trigger again the PDF build from an already produced foo.tex. It is recommended in case of problems to execute `make -C _build/latex LATEXOPTS=--halt-on-error` (convert this to the syntax of your shell), as the console output will abort with the first latex error encountered and then the problem can be analyzed further.
