### ISSUE TITLE
setoid_rewrite regression (times out on master)

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#11250]
Here's a case where `setoid_rewrite` [succeeds in Coq 8.9 and Coq 8.10](https://github.com/mit-plv/bedrock2/runs/336622456), but [times out](https://travis-ci.com/mit-plv/bedrock2/jobs/263820971#L2221) (> 5min) on Coq master.

We have an [easy workaround](https://github.com/mit-plv/bedrock2/commit/3fb395c17f4f1f464495007fedd051c8a74a5fcc), so it's not an immediate problem for us at the moment, but I'm still reporting it just in case it becomes a problem for anyone later.

I don't quite know how I could minimize this -- have you ever used your bug minimizer to isolate performance problems, @JasonGross ?

**Comment by JasonGross** [comment]
Yeah.  The procedure is a bit involved though, so I'd suggest doing a bit more snooping first.

In particular, my guess is that the timeout would be explained by different typeclass logs from `Set Typeclasses Debug`, and that the difference in logs could be explained by different states of the `typeclass_instances` database (you can check with `Print HintDb`, I think).  I expect `diff` to be quite useful here. This might give you a much smaller example to debug, like "why has the instance search changed?" (e.g., at some point there was a change between where it searched for `respectful` vs `pointwise_relation`) or "why is this instance no longer / now being found?"  I was thinking it might be a change in the behavior of `Import`, but that's actually in the 8.10 -> 8.11 transition.  It might be "Modes are now taken into account by typeclasses eauto for local hypotheses" from the change log, if you use `Hint Mode` anywhere.

Anyway, if more snooping does not reveal the issue, the first step is to get a file that will run with both versions of Coq, which means inlining all the dependencies.  You can do this with the [`inline-imports.py` script](https://github.com/JasonGross/coq-tools/blob/master/inline-imports.py).  Then you want to make the proof script be the last thing in the file (and stick an `Abort.` after the `setoid_rewrite` and close any sections you need to so that it passes on Coq 8.9), and add `Timeout n` before `setoid_rewrite` where *n* is the smallest number that makes the file still always pass on 8.9.  Now, finally, you can run `find-bug.py`.  You can pass it `--coqbin=path/to/coq-8.10/bin --passing-coqc=path/to/coq-8.9/bin/coqc` and it will minimize the file subject to the constraints that it fails with the given error message on 8.10 and succeeds on 8.9.  You probably want to give it the options `--no-remove-typeclasses --no-deps` and maybe also want to give it `--no-admit-transparent`.

**Comment by ppedrot** [comment]
Was this solved by #11343?

**Comment by samuelgruetter** [comment]
I re-triggered the build and now it [succeeds](https://github.com/mit-plv/bedrock2/runs/373909965) also on Coq master.
(For the record, it seems that the URL to the build log with the timeout that I posted above now points to the successful build log, so the original failing build log is lost).

This issue seems to be resolved.
