### ISSUE TITLE
Backtraces for parser exceptions

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11310]
When investigating exceptions raised by the parser, I realized they did not come with a useful backtrace.

As an example, in `entry_parse` in `parsing/pcoq.ml`, replace:

```ocaml
let c = Entry.parse e p in
state := CLexer.get_lexer_state ();
c
```

with

```ocaml
Ploc.raise Ploc.dummy Not_found
```

then build `coqc` and run `coqc -nois -debug theories/Init/Notations.v`

the backtrace that is displayed does not even mention `parsing/pcoq.ml`.

Are we doing something wrong with the exception catching logic in `entry_parse`?

Cc @ppedrot

**Comment by ejgallego** [comment]
As pointed out in the WG the current backtrace infrastructure is pretty broken, see #6446 and #8771 which IIRC fixed this issue.

**Comment by ppedrot** [comment]
@ejgallego While I agree with the first part of your message, I can't let you FUD around that replacing Coq backtrace mechanism by the OCaml one is going to make the situation better. Your PR was actually making the backtrace system more unsound, because you were replacing
```
try X with e -> let (e, info) = Exninfo.push e in Y; Exninfo.iraise (e, info)
```
with
```
try X with e -> Y; reraise e
```
The backtrace mechanism from Coq reuses the underlying OCaml feature to extract the relevant data and encapsulates it into a functional structure. By performing the above change, you completely destroyed the meaningfulness of the backtrace used by reraise if ever `Y` happens to raise exceptions itself, which does happen.

So, no, OCaml backtrace system is *inferior* to the Coq one. Please stop spreading lies. Also, you didn't touch gramlib in your PR, so it's unlikely to fix the problem if it is caused by a try-with that forgets to reraise in the parsing library.

@maximedenes I see various potential causes to the problem. The first one is simply that the call is inlined, so that you don't see it in the backtrace. The second one is that somewhere in gramlib we catch an exception without reraising it properly. I'll have a deeper look.

**Comment by maximedenes** [comment]
> The first one is simply that the call is inlined, so that you don't see it in the backtrace

I doubt it, because in the real example I was investigating, the exception happens deep inside the parsing, so I should at least see something from the parser.

Note that in my example, if I raise an exception directly (as opposed to using `Ploc.raise`, I see a better backtrace). Please double check, though, I've been doing a lot of debugging this morning so I may be remembering incorrectly.

**Comment by maximedenes** [comment]
(in particular, I don't know if the `with` clause in the same function is doing things correctly w.r.t. backtrace info)

**Comment by ppedrot** [comment]
@maximedenes With merely raising the exception I do get
```
...
frame @ file "vernac/vernacstate.ml", line 22, characters 10-35
raise @ unknown
raise @ file "parsing/pcoq.ml", line 86, characters 6-21
```
instead of
```
...
frame @ file "vernac/vernacstate.ml", line 22, characters 10-35
raise @ file "clib/exninfo.ml", line 65, characters 2-15
```
with `Ploc.raise`.

You are right that we are seemingly not properly enriching the exception in the with clause though.

**Comment by ppedrot** [comment]
@maximedenes Can you try with https://github.com/ppedrot/coq/tree/fix-parse-backtrace? It works for the trivial case where the entry always fail.

**Comment by maximedenes** [comment]
Will try, thanks!

**Comment by maximedenes** [comment]
The backtrace I was studying is only slightly better, with one more line pointing to `gramlib/grammar.ml, line 1546`. I wonder if these other lines in the same file are correct w.r.t. backtrace info:

https://github.com/coq/coq/blob/6621e7cf79d7d824461de14007b2a06cabe59aef/gramlib/grammar.ml#L1518

https://github.com/coq/coq/blob/6621e7cf79d7d824461de14007b2a06cabe59aef/gramlib/grammar.ml#L1520

https://github.com/coq/coq/blob/6621e7cf79d7d824461de14007b2a06cabe59aef/gramlib/grammar.ml#L1523

**Comment by ejgallego** [comment]
Wasn't this finally solved?

**Comment by ejgallego** [comment]
This should be largely solved by lots of refactoring that happened there.
