### ISSUE TITLE
8.11+beta1: please document -quick/-vio and interaction with -vos

### ISSUE THREAD

**Issue by hendriktews** [coq/coq#11471]
#### Description of the problem

I really appreciate the precise documentation of `-vos`/`-vok`, especially what files they read and produce! I would suggest to also document to following points:

- option `-quick` : What does it do? Can it still be used?
- interaction of `-quick` and `-vos`: Can one use `-vos` on a file of which some dependencies have been compiled with `-quick`?
- consistency guarantees with `-vok`: Section "Compiled interfaces (produced using -vos)" contains a warning about missing universe constraints when using `-vos`. I would suggest to change `Technically, when using -vos,` into `Technically, when using -vos and/or -vok`, to make it very clear that checking all proofs with `-vok` does not guarantee consistency.

#### Coq Version

This is about the documentation https://coq.github.io/doc/v8.11/refman/practical-tools/coq-commands.html in the version of January 28, 2020.

**Comment by Zimmi48** [comment]
In Coq 8.11.0, `-quick` is deprecated and replaced by `-vio`: https://coq.github.io/doc/v8.11/refman/changes.html#changes-in-8-11-0

For the rest of the questions, cc @charguer

**Comment by charguer** [comment]
Answering the questions: 

- `-quick` is now an alias for `-vio`. It produces a `.vio` file that contains compiled statements (like `.vos`) files, but also "suspended proofs", which can be resumed to complete the production of a `.vo` file using `-vio2vo`. One caveat is that the `.vio` files tend to be large in size.

- I think that one may be able to use `-vos` on a file of which some dependencies have been compiled with `-quick`. However, this kind of interaction is purposely undocumented. There is no good reason imo to mix the two features. The `-quick` flag (and `-vio`) might get deprecated in the future. 

Thanks for the feedback.

**Comment by palmskog** [comment]
Here is a natural scenario for combining `-vos` and `-vio` in incremental checking in CI, and why I think it's essential to test interaction of files compiled with each option.

Assume `A.v` depends on `B.v` which depends on `C.v`. Assume the lemmas `l10`-`l15` must be reproved in `A.v`, due to changes to some definition they depend on. Assume other lemmas in `A.v` take a lot of time to prove, and are unaffected since the last change.

Then, the least amount of work (and disk writing) to reprove these lemmas from scratch would be:
```shell
coqc -vos C.v && coqc -vos B.v && coqc -vio A.v && coqc -schedule-vio-tasks l10 l11 l12 l13 l15 A.vio
```

**Comment by charguer** [comment]
As far as I know, `-schedule-vio-tasks` is an undocumented feature. Thus, it does not seem necessary to provide documentation for supporting scenarios involving it. 

For details, read the code of the function `select_vo_file`  from file `vernac/loadpath.ml` in the sources of Coq, you'll see that only when the flag `load_vos_libraries` is set, then `coqc` attempds to load `vos` files. And in `toplevel/coqcargs.ml`, one can see that only `-vos` and -vok` currently set this flag. Thus, `-quick` would, I presume, refuse to load `vos` dependency files.

Fixing this would require modification to the code, and would lead us back to the hard question of which file to load when both a `.vos` file and a `.vio` file exist. Discriminating on the date cause trouble, and this is why `.vos` dos not follow this approach, which was (and is still) used to choose between loading a `.vos` file and a `.vo` file.

For a use case such as the one you describe, I believe you might want fine-grain control, providing on the command line the list of the dependency files to load. Yet this requires quite some code infrastructure to support. 

Alternatively, you could assume that you carefully remove deprecated files yourselves, and implement a rule of the form "`-schedule-vio-tasks` compilation attempts to first load the most recent of a `vo` or a `vio` file, and in case of failure attempt to load a `vos` file. But again, the issue is that it adds up more loading rules that are not necessarily in the spirit of the other ones, and may cause further unexpected issues for other users.

**Comment by palmskog** [comment]
The `-schedule-vio-checking` option is described [in the refman](https://coq.inria.fr/refman/addendum/parallel-proof-processing.html#batch-mode), so I don't see how it can be considered undocumented. Recall that our use case is starting from an empty filesystem state in CI, with only the current version control revision available (i.e., only source files) - hence the problem with deciding to load `.vos` or `.vio` doesn't occur.

Can we then expose the `load_vos_libraries` flag via the command line in some way for 8.12? In this way, I don't think ordinary users will be affected at all, while permitting the advanced regression proving we are interested in.

cc: @ejgallego

**Comment by SkySkimmer** [comment]
-check-vio-tasks (which is what you need to pick individual lemmas afaict) is undocumented (also afaict)

**Comment by charguer** [comment]
> Can we then expose the load_vos_libraries flag via the command line in some way?

I suppose we could add an undocumented flag to achieve this. You can schedule this question for the next Coq-dev discussion (tomorrow, I suppose). 

An alternative, perhaps simpler, solution is to make `load_vos_libraries` set by default when the command is `-schedule-vio-tasks` or `-schedule-vio-checking`. I'm not sure what the implications are.

**Comment by SkySkimmer** [comment]
>I suppose we could add an undocumented flag to achieve this. 

We seek to avoid adding any new undocumented stuff. Document it as unstable if you want users to avoid it.

**Comment by palmskog** [comment]
@SkySkimmer how about the following then for 8.12:

- document `coqc -check-vio-tasks` properly (along with related options) but mark as experimental
- document any CLI flag or similar setting related to enabling `load_vos_libraries`, but again mark as experimental

I can do this as a PR in the planned sequence of PRs that properly exposes metadata about  `.vio` files (via `votour`) through the CLI.

(I also added a short note about this for the Coq-dev discussion Jan 29.)

**Comment by hendriktews** [comment]
Thanks for all the answers. I started this issue, because I was unable to find all the vio related options in the reference manual. I assumed that the Section "The Coq commands" would contain all options. I just noticed yesterday, that most of the vio options are described in the Addendum Section "Asynchronous and Parallel Proof Processing". In particular, this section says quite clearly that `-vio` and `-vos` should not be mixed.

Taking this Addendum section into account, I would suggest the following minor documentation improvements:

- list the options `-schedule-vio2vo`, `-schedule-vio-checking`, `-vio` and `-vio2vo` in Section "The Coq commands" and refer the reader to Section "Asynchronous and Parallel Proof Processing".

- mention `-vio2vo` in the Addendum section, for instance by adding "(using option `-vio2vo`)" to the sentence "Alternatively one can turn each .vio into the corresponding .vo."

- For `-check-vio-tasks`, `coqc -help` says "see manual". If this option is indeed unsupported, I would suggest to omit it from `coqc -help` or to change the output there, for instance into "purposely undocumented, please do not use".

**Comment by charguer** [comment]
cc @gares for the documentation on vio.

**Comment by gares** [comment]
>     * For `-check-vio-tasks`, `coqc -help` says "see manual". If this option is indeed unsupported, I would suggest to omit it from `coqc -help` or to change the output there, for instance into "purposely undocumented, please do not use".

This option, IIRC, is part of the implementation of `-schedule-vio-checking`. Indeed the scheduler invokes coqc with the other option. Dear @coq/doc-maintainers is there a customary way to document "internal" flags?

**Comment by Zimmi48** [comment]
> Dear @coq/doc-maintainers is there a customary way to document "internal" flags?

Yes, we do document them and say: internal flag, do not use directly, or anything like this. Note however, that with respect to what should be the reference documentation for flags, it is still unsettled: cf. #5388, #10598, etc.
