### ISSUE TITLE
Binding arguments to an interpretation scope works bad

### ISSUE THREAD

**Issue by roglo** [coq/coq#11486]
#### Description of the problem

```coq
Declare Scope sc.
Delimit Scope sc with S.
Definition f (_ _ : bool) : bool := false.
Definition g (x : bool) := false.
Notation "1" := false : sc.
Notation "a + b" := (f a b) : sc.

Check (g (1 + 1)%S).
```
The answer is

```coq
g (1 + 1)%S
```

That's ok. But I want to make this `%S` disappear using **Arguments**

```coq
Arguments g x%S.
```
I test again

```coq
Check (g (1 + 1)%S).
```

But the answer is now

```coq
g (1%S + 1%S)
```

#### Coq Version

The Coq Proof Assistant, version 8.12+alpha (January 2020)
compiled on Jan 30 2020 17:11:38 with OCaml 4.07.2+dev0-2018-10-04

**Comment by Blaisorblade** [comment]
@roglo That behavior is intended and documented; `Arguments g x%S.` uses scope `S` for argument `x`, but not for its subterms. You need to associate scope S with `f`'s arguments. If you want all booleans to use that scope, you can just write `Bind Scope sc with bool.`

> The effect of the scope is limited to the argument itself. It does not propagate to subterms but the subterms that, after interpretation of the notation, turn to be themselves arguments of a reference are interpreted accordingly to the argument scopes bound to this reference.

https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#binding-arguments-of-a-constant-to-an-interpretation-scope

**Comment by Blaisorblade** [comment]
I'd propose to resolve as invalid and close, but I'm not in a rush.

**Comment by roglo** [comment]
Does not work either when adding
```coq
Bind Scope sc with bool.
```

**Comment by Blaisorblade** [comment]
Found out why: I should have tried again and been more specific.

Turns out that `Bind Scope sc with bool.` must happen *before* notations that need to get this scope, tho it can happen after function declarations.

At least on 8.10.1, the code below works and produces:
```
g (1 + 1)
	 : bool
```
as IIUC expected. If *that* breaks on 

```
Declare Scope sc.
Delimit Scope sc with S.
Definition f (_ _ : bool) : bool := false.
Definition g (x : bool) := false.
Notation "1" := false : sc.
Bind Scope sc with bool. (* NOTE THIS COMES BEFORE THE NOTATION *)
Notation "a + b" := (f a b) : sc.

Check (g (1 + 1)%S).
```

**Comment by roglo** [comment]
Not sure to understand how all these things work, but ok.

**Comment by Zimmi48** [comment]
> Turns out that `Bind Scope sc with bool.` must happen _before_ notations that need to get this scope, tho it can happen after function declarations.

Is this documented? It seems to me that it isn't, and this note would even tend to suggest that it is not required:

>When active, a bound scope has effect on all defined functions (even if they are defined after the Bind Scope directive), except if argument scopes were assigned explicitly using the Arguments command.

(cf. https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#coq:cmd.bind-scope)

Note that an alternative solution to Daniel's problem only using arguments rather than `Bind Scope` would be:

```coq
Declare Scope sc.
Delimit Scope sc with S.
Definition f (_ _ : bool) : bool := false.
Definition g (x : bool) := false.

Arguments g x%S.
Arguments f _%S _%S.
(* Note that this Arguments declaration must come before the corresponding Notation *)

Notation "1" := false : sc.
Notation "a + b" := (f a b) : sc.

Check (g (1 + 1)).
```

**Comment by Blaisorblade** [comment]
@Zimmi48 I don’t know of any docs; I asked on Gitter but forgot about it.

And yes, that documentation is very confusing and should be improved. *In practice* you must use Bind Scope *IMMEDIATELY* after defining a datatype *if you can at all*. That’s what the docs should say. Instead, that documentation says the opposite. I’m 200% sure this wasn’t intentional (writing is hard), but it felt very confusing — “unintentional gaslighting” comes to mind.

BTW, from this I *infer* notations have scope information themselves, but I don’t know if *that* is documented, and it’s not even clear if it’s necessary, so that might be a design bug. But I guess Coq needs to document this anyway before considering changes.
