### ISSUE TITLE
`Compile -> Compile Buffer` in CoqIDE fails silently when file paths contain whitespaces or symlinks

### ISSUE THREAD

**Issue by Pieter12345** [coq/coq#11595]
#### Description of the problem
`Compile -> Compile Buffer` in CoqIDE fails silently when file paths contain whitespaces or symlinks.
IDE feedback: `Running: coqc -topfile \Users\CENSORED\Lab assignments\library.v -Q C:\Users\CENSORED\Lab assignments sv -w -notation-overridden,-parsing "\Users\CENCORED\Lab assignments\library.v" 2>&1`.
Issues:
 - The drive letter (`C:`) is missing in two of the three paths in the command. This seems to be only the case when the path contains a symlink (created on Windows 10 using the `mklink` command).
 - Two of the three paths are not quoted, causing whitespaces in the path to make `coqc` interpret each file path as multiple arguments.

Note that the mentioned file path is the path to the file that is opened with the CoqIDE, and not the CoqIDE itself.

When not going through symlinks and quoting the file paths, the command functions properly from Windows 10 command prompt.

#### Coq Version
Release 8.11.0.

**Comment by ppedrot** [comment]
See also #3991.

**Comment by robbertkrebbers** [comment]
I obtained a similar problem under Linux: "Compile > Compiler buffer" in CoqIDE fails when the path contains whitespaces. However, contrary to Windows, an error is reported:

```
Compilation output:

Error: Can't find file ./bar/library.v
```

The folder in question is called "foo bar".

I noticed that a number of my students are running into this. Especially those that are using WIndows because a.) it's much more common to put whitespaces in folder names in WIndows b.) using `_CoqProjecft` and `make` is a hassle, so they resort to "Compile buffer" in CoqIDE.
