### ISSUE TITLE
Ltac2: how to use a match pattern variable in a constr term?

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#11603]
#### Description of the problem

It is unclear how to use a match pattern variable in a constr term in Ltac2. In case this is possible, it should be better documented. Among the things I tried is this:

```
Require Import Ltac2.Ltac2.

Record bla := mkbla { bla1 : nat; bla2 : bool }.

Ltac2 bla_or_what (val : constr) :=
  lazy_match! val with
  | {| bla1:=?n; bla2:=?b |} => constr:(@pair nat bool ltac2:(n) ltac2:(b))
  end.

Fail Ltac2 Eval bla_or_what constr:(mkbla 2 true).
(* Fails with: Cannot infer an existential variable of type "nat". *)
```

#### Coq Version

8.11.0

**Comment by MSoegtropIMC** [comment]
@ppedrot : could you please have a quick look at this - it really stops me from making progress.

**Comment by ppedrot** [comment]
The quotations are ill-typed, but for some reason the warning is not printed. An `ltac2:(...)` quotation should contain a tactic of type `unit`, not a term. For your code to work, you should write
```
Ltac2 bla_or_what (val : constr) :=
  lazy_match! val with
  | {| bla1:=?n; bla2:=?b |} => constr:(@pair nat bool ltac2:(exact $n) ltac2:(exact $b))
  end.
```

**Comment by ppedrot** [comment]
The reason why there is no warning displayed is due to the order of type-checking. Essentially, `ltac2:(expr)` prints a warning if `expr` has a *rigid* type different than `unit`. In particular, if its type is a unification variable, then the warning is not displayed, which is the expected behaviour.

Unfortunately, due to the way the match macro is expanded, at the time `ltac2:(n)` is type-checked, `n` has no fixed type yet, because it's essentially a bound variable in a function. I guess I could tweak the macro to add type annotations where possible, but there is little less I can do.

**Comment by ppedrot** [comment]
@MSoegtropIMC Also, I just realized that for this simple of very simple term antiquotations, you can directly use the `$x` syntax for something that is similar to `ltac2:(exact $x)` one, barring efficiency and subtle unification details.

**Comment by ppedrot** [comment]
Both syntaxes are discussed in [the term antiquotation section of the Ltac2 documentation](https://coq.inria.fr/refman/proof-engine/ltac2.html?highlight=ltac2#term-antiquotations). Except if you have a more precise need, I'd favour closing this issue.

**Comment by MSoegtropIMC** [comment]
Thanks for the quick help - it is indeed documented. I somehow didn't see the section "Trivial Term Antiquotations". I guess what is missing are a few more practical examples. I will provide a few later.
