### ISSUE TITLE
"Global" locality for hints

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#11792]
When defining hints in stdlib2, we'd like to give them a "global" locality behavior (as opposed to "superglobal"). I believe there's no way to do that today. The related `Loose Hint Behavior` controls the behavior when using hints, not when defining then, as discussed in https://github.com/coq/stdlib2/issues/6.

Cc @ppedrot

**Comment by Zimmi48** [comment]
To clarify for people who don't read the related issue, currently hints defined in a module are made available at `Require` time instead of being made available at `Import` time. The [documentation of hint locality](https://coq.github.io/doc/master/refman/proof-engine/tactics.html#hint-locality) is currently very confused and partially incorrect, but basically the `Hint` commands support the `local` attribute that makes a hint local to a module, but nothing between this and the default "superglobal" behavior.

Before even considering changing the defaults, we should provide finer-grained attributes / options allowing to emulate the various possible behaviors.

**Comment by charguer** [comment]
Related question. How do I bind hints to a module, so that the hints can be imported when importing the module? I couldn't manage to get it work at the moment (in coq-master).

```
Set Loose Hint Behavior Strict.

Parameter P : Prop.

Module M.
  Axiom myhint : P.
  Hint Resolve myhint : mybase.
End M.

Lemma P_proof : P.
Proof. auto with mybase. Qed. 
(* I would like this proof to succeed only after a [Import M]. *)
```
Is there a way to achieve that currently?

The behavior that I would find natural (with `Set Loose Hint Behavior XXX`) is that:
- `Local Hint` defines a hint used inside the current module only
- `Hint` defines a hint that that is exported together with the module (available upon "import" of that module), unless defined inside a section, in which case it remains local to the section.

An alternative design choice might be:
- `Hint` defines a hint local to the module
- `Global Hint` defines a hint that is exported by the module.

**Comment by ppedrot** [comment]
> Is there a way to achieve that currently?

This is precisely the issue described here: currently it is not possible.

**Comment by Blaisorblade** [comment]
(Maybe obviously) the same applies to typeclass instances.

**Comment by ppedrot** [comment]
@Zimmi48 should I creat an `attr` entry in the Attributes section of `gallina-specification-language.rst`, alongside with the local / global / whatnot?
