### ISSUE TITLE
test misc/quotation_token fails on bytecode architecures

### ISSUE THREAD

**Issue by treinen** [coq/coq#11808]
#### Description of the problem

The test misc/quotation_token fails on byecode architectures. The list of archs where I have observed this failure:

armel mips64el mipsel hppa ia64 powerpc riscv64 x32

Here is how this looks like on armel:

````
(sid_armel-dchroot)treinen@abel:~/coq-8.11.0/test-suite$ make misc/quotation_token.log 
TEST      misc/quotation_token.sh
FAILED    misc/quotation_token.log
(sid_armel-dchroot)treinen@abel:~/coq-8.11.0/test-suite$ cat misc/quotation_token.log 
==========> TESTING misc/quotation_token.sh <==========
make[1]: Entering directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
CLEAN
make[1]: Leaving directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
make[1]: Entering directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
COQDEP VFILES
COQPP src/quotation.mlg
COQDEP src/quotation_plugin.mlpack
CAMLDEP src/quotation.ml
Fatal error: cannot load shared library dllcoqrun
Reason: dllcoqrun.so: cannot open shared object file: No such file or directory
CAMLC -c src/quotation.ml
CAMLC -pack -o src/quotation_plugin.cmo
CAMLC -a -o src/quotation_plugin.cma
make[1]: Leaving directory '/home/treinen/coq-8.11.0/test-suite/misc/quotation_token'
wong loc: 
0m0.000000s 0m0.000000s
0m1.840000s 0m0.490000s
==========> FAILURE <==========
    misc/quotation_token.sh...Error!
````
It seems that the first Fatal Errors are already produced by the invokation of make clean.

#### Coq Version

8.11.0

**Comment by herbelin** [comment]
If the file `kernel/byterun/dllcoqrun.so` has not been built, it is probably because the architecture does not support dynamic linking of libraries.

I suspect that adding option `-custom` to `./configure` would do the trick, but I'm not very knowledgeable in this kind of subtleties, so maybe the problem is elsewhere. In particular, if ever the trick works, I don't know if it is should be considered a bug of our Makefiles that the detection is not done automatically.

**Comment by herbelin** [comment]
`dllcoqrun.so` actually exists but is not found. This is related to the `misc` test calling a `coq_makefile`-generated makefile in a context where `dllcoqrun.so` is not known.

I can reproduce a more general `test-suite` bug using the following call to configure:
```
./configure -byte-only -no-custom -prefix /usr/local
```
(Note: the `-no-custom` is needed for me only because I'm using MacOS and MacOS X/Windows otherwise default to `-custom`.)

What to do? When compiling the stdlib, `coqc` (in `byte`) apparently finds `dllcoqrun.so` thanks to `CAML_LD_LIBRARY_PATH` being set (in `Makefile.build`).

Doesn't it just mean that the line `CAML_LD_LIBRARY_PATH := $(COQLIB)/kernel/byterun:$(CAML_LD_LIBRARY_PATH)` of `Makefile.build` should be put in `Makefile.common` instead, so that the `Makefile` of the `test-suite` inherits it?

Note: what is strange is that @treinen seem to have the bug only on the `misc` file which calls the `Makefile` generated by `coq_makefile`, while, with the above `configure` command, this fails for all the test-suite.

Cc @coq/test-suite-maintainers.

**Comment by treinen** [comment]
About the last observation by @herbelin: this is certainly due to the fact that I first observed the test failures by looking at the reports that are part of the package builds, that is they are generated by a "make test" (or something similar) from the toplevel directory. Only when trying to reproduce that particular failure I called make from the test-suite directory, as indicated in test-suite/README.md. That is the top-level Makefile seems OK, but the Makefile in test-suite/ seems to be missing some variable settings.

This also means the the observed test faikure is independent from that issue of dynamic loading.
