### ISSUE TITLE
Why is the declaration of arbitrary terms as hints deprecated?

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#11970]
#### Description of the problem

I'm trying to remove all non-silly warnings from fiat-crypto, and I ran across the deprecation warning of #7791.  I think it is a mistake, though, and a moderate hindrance in usability, requiring a change of about 100 loc in fiat-crypto alone for what I see as no particularly good reason.

From what I can glean from #7791, the issue is that the implementation is complicated by having hints that are not globals.  This is fine, I don't really care about the shape of the resulting term, and if I need to not indirect through a constant, I can use `Hint Extern`.  However, it's very convenient to be able to give terms without needing to make my own names for them.  (Often I am projecting a single component out of a conjunction.)

I propose the following: add a flag `Set Automatic Hint Indirection Through Globals` or something like that which (a) emits a global constant for each term a la `Hint Resolve ->` and `Hint Resolve <-` (which already declare constants), and (b) removes the deprecation warning.  Then we can update the deprecation warning to mention this setting, and maybe in 8.12 or 8.13 we can turn the setting on by default, and if it does not cause too much disruption, we can remove it (and the deprecation warning and associated codepaths) in 8.14 or so.

#### Coq Version

master (8.12+alpha)

**Comment by JasonGross** [comment]
cc @ppedrot , the author of #7791

**Comment by Zimmi48** [comment]
@JasonGross Such automatic declaration of constant is not a bad idea but I don't see why it couldn't be activated by default from the beginning, i.e. 8.12. It should anyway not create more disruption than removing the support for declaring arbitrary terms as hints.

**Comment by Zimmi48** [comment]
*Note in passing.* The suggestion you make looks similar in spirit to the `Instance : foo := bar` feature (unnamed instance declaration), except in this case you must provide the type (at the very least the head constant applied to holes).
Since `#[ canonical ] Definition foo := bar` is now supported to declare a new constant as a canonical instance, and making `Instance` a variant of `Definition` with the right combination of attributes has been mentioned recently (https://github.com/coq/ceps/pull/42#discussion_r384727546), it would be natural to add a new feature to declare a global constant without choosing its name nor specifying its type (`Definition := foo`) and adding attributes to declare a newly defined constant as a hint.
This would completely fulfill the use case that you describe and work in the same way.

**Comment by Zimmi48** [comment]
The conclusion from the discussion in #12493 is that on-the-fly declaration of constants will be done only in 8.13. In the meantime, the warning should be kept but adjusted. But given that this is only a user message change and that no PR has been opened yet to do this adjustment, it is reasonable if nothing is done for the beta.

**Comment by Zimmi48** [comment]
Given that PR #12493 shows that this is far from easily solved, our view as RMs is that we'll have to revert the deprecation in 8.12. @ppedrot If you want this deprecation warning replaced by some other warning about the fragility of this stuff, please open a PR. Otherwise, we'll just remove the warning entirely.

**Comment by ppedrot** [comment]
Just *en passant*, the issues encountered in #12493 are *also* present without declaring a proxy hint definition. The difference is that in one case it is statically obvious in the semantics (definitions are checked to exist in functor interfaces) while it is hidden in the current state of the code that delegates this to libobject (hints in functors are known to be buggy). I personally believe that hiding dust under the rug is not a viable software practice, but it seems our users disagree, so for the time being I'll tweak the warning. But this is pushing back **for the n-th time** a proper fix for the underlying issues.

**Comment by ejgallego** [comment]
Pity the last two calls were postponed, I really wanted to discuss a bit more about this.
