### ISSUE TITLE
Evaluating a term works but binding the result fails

### ISSUE THREAD

**Issue by tschiatf** [coq/coq#12166]
#### Description of the problem

Given the following contrived example of a function `bar` with an implicit parameter `n`
(NB: branch `true` does not depend on the implicit parameter):

```Coq
Inductive foo : nat -> Type := Foo n : foo n.

Definition bar_type b n : Type :=
  match b with
  | true => nat -> nat
  | false => foo n -> nat
  end.

Definition bar b {n} : bar_type b n :=
  match b return bar_type b n with
  | true => fun _ => 38
  | false => fun _ => 42
  end.

(* Set Debug Cbv. *)
Eval cbv in bar true 17. (* = 38 : nat *)
Fail Definition foobar_1 := Eval cbv in bar true 17.
```
`Eval cbv in bar true 17.` works in Coq 8.11.0 without having to provide the implicit
parameter and results in

> = 38
> : nat

Trying to bind the result of the evaluation to `foobar_1` as follows

`Definition foobar_1 := Eval cbv in bar true 17.`
  
fails with

> Cannot infer the implicit parameter n of bar whose type is "nat".

Executing `Set Debug Cbv.` before trying the above code snippets shows that
`Eval` unfolds `bar` successfully. In case of `Definition` the evaluation fails at
the unfolding step.

Is this behavior intended?

#### Coq Version

The Coq Proof Assistant, version 8.11.0 (February 2020)
compiled on Feb 14 2020 11:30:44 with OCaml 4.09.0

**Comment by JasonGross** [comment]
Yes, this is intended.  Here's a simpler example:
```coq
Definition const : unit -> unit := fun _ => tt.
Eval cbv in const _. (* gives `tt` *)
Definition foo := Eval cbv in const _. (* fails *)
```
The issue is that in `Eval cbv in ...`, unresolved evars will be dropped, whereas in definitions, all evars must be instantiated.  While dropping unmentioned unresolved evars may seem innocuous (and usually is), I believe it might be incompatible with Private Inductive types, which are used to implement higher inductive types in HoTT.  (I'm not certain about this, though.)

**Comment by tschiatf** [comment]
Thanks for clarifying this. As it is expected behavior I will close this issue.
