### ISSUE TITLE
Search-Command semantics changes by having transitiv dependency on SSReflect

### ISSUE THREAD

**Issue by fakusb** [coq/coq#12253]
#### Description of the problem

The Search-command changes from the standard- to the the SSReflect-semantics (Treating the first term after as the head I want to have in the conclusion of found lemmas) by just having a transitive dependency on a file that `Require`s ssreflect.

No matter what the intended behaviour on Require and loading ocaml-parts of plugins is, it seems very strange that external dependencies on libraries using ssreflect change my workflow concerning how I have to use "Search". 

#### Coq Version

8.11.0

**Comment by Zimmi48** [comment]
There are two issues here:
- transitively requiring a module that declares an ML plugin loads the commands and more generally the syntax that this plugin defines;
- SSReflect's `Search` hides the standard `Search`.

The first problem can be reproduced with any plugin (e.g. Ltac2). The issue is that `Require` is transitive and that the syntax defined in an ML plugin is loaded whenever a module declaring the plugin is `Require`-d. I don't know if there is hope to change this (make the loading of the syntax `Import`-bound) and I'll let other developers answer to this.

The second problem is something that we are quite aware and that we intend to resolve in the short term (cf. https://github.com/coq/coq/pull/8855#issuecomment-612420723).
