### ISSUE TITLE
Flocq not correctly imported on Mac

### ISSUE THREAD

**Issue by QinxiangCao** [coq/coq#12275]
#### Description of the problem

This line works on windows CoqIDE, but not on Mac's CoqIDE's dmg:

From Flocq Require Import Binary Bits.

#### Coq Version

8.11.0 CoqIDE on mac.

**Comment by herbelin** [comment]
Hi @QinxiangCao. Since file systems on Mac are by default case-insensitive that may be a capitalization problem? Which of `From Flocq Require Import Binary.` or is From Flocq Require Import Bits.` is not working? What is the error message? Did you contact the authors of Flocq (http://flocq.gforge.inria.fr)?

**Comment by QinxiangCao** [comment]
This is the error message. I did not contact Flocq yet since it works well on my windows machine and I believe it seems a problem when packaging the Coq executive for Mac.

<img width="798" alt="Screen Shot 2020-05-08 at 9 12 07 AM" src="https://user-images.githubusercontent.com/6250812/81359597-2daa6c00-910c-11ea-8aac-7a62bff46de8.png">

**Comment by herbelin** [comment]
The error you see is normal: @Zimmi48 or @MSoegtropIMC will confirm but the windows package comes with Flocq preinstalled while the Mac package doesn't. So, you'll have to first install Flocq. 

I'm afraid the basic way to do so is with the Terminal. Are you familiar with it? In any case, you need to download [Flocq 3.2.1](https://gforge.inria.fr/frs/download.php/file/38301/flocq-3.2.1.tar.gz) then do the following from a window of the Terminal:

  ```
  # download
  mv ~/Download/flocq-3.2.1.tar.gz .
  # uncompress
  tar xzvf flocq-3.2.1.tar.gz
  # compile and install
  cd flocq-3.2.1
  export COQBIN=/Applications/CoqIDE_8.11.0.app/Contents/Resources/bin/
  autoconf && ./configure && ./remake -j4 && ./remake install
  ```

In particular, this requires the `autoconf` tool. If it failed because of `autoconf: Command not found`, this means you have to install it first. This is typically done with a package manager such as brew (see [http://macappstore.org/autoconf/](http://macappstore.org/autoconf/)) or following instructions at [Install Autoconf and Automake on OS X](https://gist.github.com/justinbellamy/2672db1c78f024f2d4fe).

Hopefully, it should work. There are otherwise alternative ways to do depending on your familiarity with various tools (such as using `opam`).

Note also the existence of the work on a "Coq Platform" which will eventually provide Coq bundled with Flocq also on MacOS. Maybe, we will even have one day a tool which automatically downloads and installs any package which we require!

**Comment by Zimmi48** [comment]
I do confirm. The macOS installer for now only installs Coq + CoqIDE (no packages) and it is the goal of the Coq platform to provide an experience similar to the current Windows installer on all operating systems.

**Comment by MSoegtropIMC** [comment]
For the time beine (until we are further down the road with the platform project) I would suggest to install Coq and Coq libraries like Flocq via opam on OSX. Opam in turn can be installed e.g. via MacPorts and I guess also via homebrew. So the sequence of commands should be:

## Install MacPorts

Download .pkg file from (https://www.macports.org/install.php)

Double click on the pkg file in download folder

(close and reopen shells in case they were open before)

Homebrew should work in a similar way, but I don't use it currently, so I don't know the details.

## Install opam via MacPorts

```
sudo port install opam
```

## Initialise opam

```
opam init
opam switch create coq 4.07.1
eval "$(opam env)"
opam repo add coq-released https://coq.inria.fr/opam/released
```

## Install Coq via opam

```
opam install coq
opam install lablgtk3-sourceview3
opam install coqide
opam install coq-flocq
```

**Comment by QinxiangCao** [comment]
I see. Thank you very much for your explanation and solutions @herbelin @Zimmi48 @MSoegtropIMC .

Actually, I am quite surprised when finding out it is a design choice that the windows package comes with Flocq preinstalled while the Mac package doesn't. I am wondering whether it is possible for the next Coq release to have a Flocq-preinstalled Mac as well, since the platform project seems to have a long way to go still. Or is there a foundational difficulty for that?

**Comment by Zimmi48** [comment]
It's not a design choice. It's just more work. Windows was a priority because opam isn't well supported there. The current effort is focusing on the platform now. The first experimental versions for macOS should not be so far down the road that you seem to think.

**Comment by QinxiangCao** [comment]
Aha. Now I understand. Thank you very much for this explanation. Looking forward to seeing the platform!
