### ISSUE TITLE
Clarifying the semantics of Ltac's ; [ ... ] and ; [> ... ].

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#12283]
The documentation of `[> ... ]` says:

>`ltac_expr ; [ ... ]` is equivalent to `[> ltac_expr ; [> ... ] .. ]`.

This surprised me a lot, as I rather thought that it was equivalent to `ltac_expr ; [> ... ]`.

Turns out both are wrong!

```coq
Goal True /\ False.
split.
all: let n := numgoals in idtac n; [ .. ].
(*
2
2
*)
all: let n := numgoals in idtac n; [> .. ].
(*
2
*)
all: [> let n := numgoals in idtac n; [> .. ] .. ].
(*
1
1
*)
```

I understand the second and the third, but not the first. This behavior seems insane. Can someone explain it to me?

**Comment by ppedrot** [comment]
Ltac has a very peculiar semantics when it comes to arguments. Due to the fact that some arguments need to be focussed, an Ltac expression can sometimes trigger a focus dynamically and dispatch the continuation on the focussed goals. I wouldn't be surprised if `idtac` was causing this here.

**Comment by Zimmi48** [comment]
But how come the first and the second behave differently?

Another example of the difference:

```coq
Goal True /\ False.
split.
all: cycle 1; [ .. ]. (* does not do anything *)
all: cycle 1; [> .. ]. (* swaps the goals *)
```

**Comment by Zimmi48** [comment]
Or are you saying that most of the time, `; [ ]`, should be understood as presented in the doc (`[> ... ; [> ... ] .. ]`) and there is an exception here due to how `idtac` focuses, but after the goals have been counted?

How do we justify this design choice for `; [ ]`?

**Comment by herbelin** [comment]
I'm not an expert at all in multigoal semantics but my own guess would be that there are two issues:
- the `[>` is inserted after the surrounding `let` in the equivalence between `t ; [ ... ]` and `[> t ; [> ... ] .. ]`
- there are non-focussing `let` arguments and `numgoals` (as well as `idtac`) are ones of them
```
Goal True /\ False.
split.
all: let n := numgoals in (idtac n; [ .. ]). (* 2 2 *)
all: (let n := numgoals in idtac n); [ .. ]. (* 1 1 *)
all: let _ := match goal with |- _ => idtac 0 end in let n := numgoals in idtac n; [ .. ].
(* 0 0 1 1 *)
all: match goal with |- _ => idtac 0 end; let n := numgoals in idtac n; [ .. ].
(* 0 0 2 2 *)
```

**Comment by JasonGross** [comment]
> Ltac has a very peculiar semantics when it comes to arguments. Due to the fact that some arguments need to be focussed, an Ltac expression can sometimes trigger a focus dynamically and dispatch the continuation on the focussed goals. I wouldn't be surprised if `idtac` was causing this here.

No, this is not the difference, and the difference you're observing is just a side-effect of the actual important difference:
- `[ > @multi_goal_tactics ]` will run `@multi_goal_tactics` on the list all goals currently under focus.  So, e.g., `[ > | ]` ensures that there are two goals under focus.
- `a; [ @multi_goal_tactics ]` will run `@multi_goal_tactics` on the list of all goals produced by the application of `a` to a single goal, and will do this for all goals under focus before running `a`.  So `a; [ | ]` will ensure that `a` produces leaves behind two goals, for each goal it is run on.

So the semantics of `a; [ @multi_goal_tactics ]` cannot be implemented without first focussing `a` to run on a single goal, and this is the effect you are seeing above with `idtac`.  The real use of this tactic is doing something like `all: split; [ left | right ]`, where you don't know how many goals there are, but you know all of them are conjunctions of disjunctions and you want to split them all and then do `left` on each left conjunct and `right` on each right conjunct.

I believe `@ltac_expr; [ @multi_goal_tactics ]` is always equivalent to `[ > @ltac_expr; [ > @multi_goal_tactics ] .. ]` (note the `..` at the end; it's important).

**Comment by JasonGross** [comment]
The historical perspective might also be useful here: in Coq 8.4 and earlier, there weren't really any multi-goal tactics, and you could think of each tactic as operating independently on each goal under focus.  Hence a tactic was a thing that got applied to each goal in a list, and there was a special construct, `; [ ... ]` for dispatching across multiple goals created by an individual tactic.  In Coq 8.5 (I think) and later, after the proof engine was rewritten and exposed, tactics were things that got a list of goals and transformed them into a new list of goals, and it was only the primitive tactics that were defined as applying their action to each goal in the list of goals.  In this world, goal dispatch is a primitive thing, hence `[ > ... ]`.

However, from the point of view of users, it's still very convenient to model most tactic execution as applying to each goal under focus separately.  This is a much simpler model, most of the time, though it breaks down in the following cases:
1. When you are explicitly using multigoal tactics (such as `numgoals`)
2. When you are depending on unification of evars in one goal to (not) influence your tactic's behavior on another goal (i.e., you are doing `tac1; tac2`, on two or more goals, and even though these tactics are single-goal tactics, the ordering of goals matter (i.e., you care about the difference between `1: tac1. 2: tac1. 1: tac2. 2: tac2.` vs `1: tac1. 1: tac2. 2: tac1. 2: tac2.`))
3. You are dispatching on the goals produced by a single tactic.

When (1) happens, you are necessarily using a multi-goal model, so it doesn't really matter that the single-goal-at-a-time model breaks down.  When (2) happens, you scratch your head confusedly and consult the reference manual (or, as I did, report a bug in Ltac and have a back-and-forth with the coqdev team) and learn that Ltac was not nearly as simple as you thought.  When (3) happens, you use `; [ ... ]` rather than `; [ > ... ]`.  Of these, I think beginners are most likely to run into (3), and so we might see the benefit of `; [ ... ]` as allowing the users to hold the abstraction of their simpler model of Ltac for longer.  (It's also fewer characters to type for a relatively simple operation, and I'd really rather not have to track all the time whether or not I successfully focussed a single goal before writing `split; [ > left | right ]` in order to know whether or not I need to wrap it in `[ > <tactic> .. ]`.)

**Comment by jfehrle** [comment]
The commit message in 2925c97c852efd66656edebedba543c7c8335b73 agrees with you.  It says:

> New tactical [> t1…tn] to apply tactics t1…tn to the corresponding goal.

> Differs from the usual t;[t1…tn] in two ways: * It can be used without a preceding tactic * It counts every focused subgoal, rather than considering independently the goals generated by the application of the preceding tactic on individual goals.

> In other words t;[t1…tn] is [> t;[>t1…tn].. ].

However, this equivalence doesn't cover the case where `; [ ... ]` contains `..`.  Maybe that's not useful.

> It's also fewer characters to type for a relatively simple operation

Ah, only one character shorter!

**Comment by JasonGross** [comment]
> Ah, only one character shorter!

No, it's six characters (+ six spaces).  The difference between `split; [ left | right ]` and `[ > split; [ > left | right ] .. ]`

> However, this equivalence doesn't cover the case where `; [ ... ]` contains `..`. Maybe that's not useful.

I'm not sure what you mean.  Do you have an example where it's not equivalent?

**Comment by jfehrle** [comment]
Never mind, I confused some details.

**Comment by Zimmi48** [comment]
Thanks all, and in particular @JasonGross, for the explanations!
