### ISSUE TITLE
Coq's CI fails on at least some developments using native_compute due to incompatible OCaml versions (fiat-crypto)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12400]
#### Description of the problem

```
File "/tmp/Coq_native97170a/Coq_native2ba814.native", line 1:
 Error: /builds/coq/coq/_install_ci/lib/coq/kernel/nativevalues.cmi
 is not a compiled interface for this version of OCaml.
 It seems to be for a newer version of OCaml.
 Finished failing transaction in 1.16 secs (0.017u,0.007s) (failure)
 File "./src/UnsaturatedSolinasHeuristics/Tests.v", line 138, characters 0-459:
 Error: Native compiler exited with status 2
 Command exited with non-zero status 1
```
https://gitlab.com/coq/coq/-/jobs/565436568

cc @coq/ci-maintainers 

#### Coq Version

16e0877c6e3ec6228875e10afb1ec17d640eb1e9

**Comment by SkySkimmer** [comment]
Indeed we have 
~~~yaml
# We cannot use flambda due to
# https://github.com/ocaml/ocaml/issues/7842, see
# https://github.com/coq/coq/pull/11916#issuecomment-609977375
library:ci-fiat_crypto:
  extends: .ci-template
  stage: stage-4
  needs:
  - build:edge+flambda
  - library:ci-coqprime
  - plugin:ci-bignums
  - plugin:ci-rewriter
  dependencies:
  - build:edge+flambda
  - library:ci-coqprime
  - plugin:ci-rewriter
~~~
ie we switch to non-flambda 4.05 but use dependencies compiled with flambda 4.10

Since succeeding job https://gitlab.com/coq/coq/-/jobs/564129619 only #12379 and #12392 have been merged to Coq, neither have a plausible impact.
On the fiat crypto side the failing file was added https://github.com/mit-plv/fiat-crypto/commit/b5d9ba0385443fa9b3d7d6ca7ca63600f2b01efa
So I guess we only succeeded because fiat-crypto didn't use native compute? (we stopped using flambda because extracted code failed to compile, not native_compute code, so that's plausible)
