### ISSUE TITLE
Creating a new Extraction "language"?

### ISSUE THREAD

**Issue by VizorKit** [coq/coq#12416]
I am trying to create my own extractor to a different output than Scheme, OCaml, C, and Haskell. I am sorry to even bother anyone with this question. But there doesn't seem to be a lot of documentation on how the original creators did so. Any direction at all would be helpful, as far as where to look at someones previous work. Any documentation that might be helpful with contributing to Coq. Etc.

Thanks.

**Comment by JasonGross** [comment]
The code implementing extraction lives in https://github.com/coq/coq/tree/master/plugins/extraction .  Each language has it's own .ml and .mli file.

**Comment by ppedrot** [comment]
No more interactions in a while, so we can close.

**Comment by ppedrot** [comment]
Indeed, plugins can depend on one another. Actually this is a rather standard situation since most plugins depend on the Ltac one. Depending on the build system used by your plugin, the exact invocation to add dependencies is different. You should probably ask on the Coq zulip for more interactive questions about this, though.
