### ISSUE TITLE
Universe with Prop <= i not minimized to i := Set, resulting in costly, unconstrained universes

### ISSUE THREAD

**Issue by Janno** [coq/coq#12414]
#### Description of the problem
The following snippet fails at the last `Check` invocation.
```coq
Set Universe Polymorphism.
Set Printing Universes.
Inductive list {T} : Type := | cons (t : T) : list -> list. (* who needs nil anyway? *)
Arguments list : clear implicits.

Fixpoint map {A B} (f: A -> B) (l : list A) : list B :=
  let '(cons t l) := l in cons (f t) (map f l).
Check map@{_ _}.
(* Two universes, as expected. *)

Definition map_Set {A B : Set} := @map A B.
Check map_Set@{}.
(* Universes minimized away, as expected. *)

Definition map_Prop {A B : Prop} := @map A B.
Check map_Prop@{}.              (* Fails! *)
(* Universes *not* minimized away! Confusion abound! *)
```
While this is not *wrong*, it essentially means that users pay a very heavy and unnecessary price for using universe polymorphism and later instantiating the definitions with propositions. It is very easy to amass thousands and sometimes tens of thousands of universes in a single definition and in my Mtac2 use cases most of them would disappear since they correspond to types instantiated with propositions.

I am reporting this issue to make sure that the feature request—or should it be called a bug fix?—is not forgotten. (My initial "bug report" happened verbally during POPL.) 

There have been two attempts at fixing this (#9343, #10331) but they have both been closed.

#### Coq Version
master, but to my knowledge this behaviour was never different in earlier Coq version.

**Comment by ppedrot** [comment]
FTR, I believe that the kernel should not even accept these constraints. Unfortunately we use the same code for universe unification and universe type-checking, so we have to tolerate these transient constraints during unification...

**Comment by SkySkimmer** [comment]
@ppedrot what constraints are you talking about?

**Comment by ppedrot** [comment]
AFAIK nothing in the kernel enforces that `Prop <= i <= Set` implies `i = Prop ∨ i = Set`. I believe that none of the specific universes `Prop`, `Set` and `SProp` should even be contained in the `UGraph`, i.e. the latter should only contain either global or local universes.

**Comment by SkySkimmer** [comment]
So what should the kernel see if I have `Polymorphic Definition foo@{u} : Type@{u} := Set.` (ie a `Set < u`)?

**Comment by ppedrot** [comment]
Every universe should also remember that it's greater than `Set` (and `Prop` for that matter). Essentially, I want to keep the dynamic graph structure from the static one.

**Comment by maximedenes** [comment]
@Janno we (@SkySkimmer and I) made a bit of progress in https://github.com/coq/coq/pull/12449, but changing the minimization strategy breaks a lot of exisiting code :(

**Comment by Janno** [comment]
Thanks for picking this up again! I appreciate every bit of progress on this!

I see some of the failures are because definitions need fewer/(more?) universes now. I consider those technical debt in the sense that the current way of instantiating universe-polymorphic code is not very user friendly. It's not just that I don't *want* to write out 25 universes in braces, it's that I need to *change* that to 21 or 47 or depending on how exactly I write the preceding definitions, how I annotate types, whether I use template-polymorphic or properly polymorphic datatypes, etc. Universe polymorphic code is extremely hard to maintain!

What happens when there's an actual bug in the minimization procedure that needs fixing? Every development that manually instantiates universes will need fixing. I really feel like Coq manoeuvred itself into a bit of a corner here. Am I wrong? 

I see that other failures in the CI are failing universe constraints and those I am intrigued by. Why would a strategy that minimizes away the redundant universes for `Prop`s make constraints unsatisfiable? From my naïve perspective, removing those universes should have zero impact on satisfiability because they are are unconstrained. There must be a piece of this puzzle that I am missing.

**Comment by SkySkimmer** [comment]
Because replacing `i <= Prop` by `i := Set` is not the same as "removing redundant universes".
Indeed removing redundant universes would be nice, but I don't know how to define redundancy.

**Comment by Janno** [comment]
Ah, I suppose I don't understand the terminology well enough. There isn't anything lower than `Prop`, is there? If so, then we have no choice when instantiating the `i` in `i <= Prop`. That's what I meant by redundant. There's probably a better term for that.

**Comment by ppedrot** [comment]
> I really feel like Coq manoeuvred itself into a bit of a corner here. Am I wrong?

That's also my impression. Universe unification is extremely fragile. I think that *at the very least* one should be forced to write the bound universe variables in polymorphic mode, i.e. the strict mode should be the default. Not sure whether this scales much though.

**Comment by SkySkimmer** [comment]
>Ah, I suppose I don't understand the terminology well enough. There isn't anything lower than Prop, is there? If so, then we have no choice when instantiating the i in i <= Prop. That's what I meant by redundant. There's probably a better term for that.

Woops I should have written `Prop <= i`

**Comment by Janno** [comment]
> Woops I should have written `Prop <= i`

Well, that explains why my reply made sense to me locally but why, at the same time, I just couldn't figure out why I was talking about universes with upper bounds. I really should have re-read the preceding discussion.

In what kind of situation will `i := Set` cause problems (if `Prop <= i` is the only constraint on it)?

**Comment by SkySkimmer** [comment]
>That's also my impression. Universe unification is extremely fragile. I think that at the very least one should be forced to write the bound universe variables in polymorphic mode, i.e. the strict mode should be the default. Not sure whether this scales much though.

There's some kind of conflict between universe polymorphism and cumulativity: cumulativity means the fully general form of lemmas can involve huge numbers of universes related by `<=`, and unverse polymorphism means having many universes is very slow and impractical (also if you care about the universes when trying to understand the meaning of a lemma having thousands of them makes it impossible).
This leads to using heuristics to try to reduce the number of universes by replacing some of the `<=` by `=` (minimization). Since they're heuristics they can be either too strict (so you can't use the resulting lemma how you need it) or not strict enough (so you still get too many universes) or even both at the same time (so you get a universe error involving thousands of universes).

Systems with universe polymorphism and no cumulativity (Agda, Lean) do not seem to have this issue (I don't have that much experience with them though), so we may consider disabling implicit cumulativity in universe polymorphic mode (so if you want a `<=` you have to somehow make it explicit). https://github.com/coq/coq/pull/11512 for instance experiments in that direction.
However I think this still has issues dealing with algebraic universes:
- without cumulativity, `forall A : Type@{i}, (B : Type@{j})` lives exactly in `Type@{max(i,j)}`, not any `k >= i,j`. This means we cannot refresh universes to remove algebraics from inside terms, and we need to be able to instantiate polymorphic universes by algebraics (ie in `@id@{_} (forall A, B)` the `_` must be `max(i,j)`). (also if universe variables range over impredicative universes we also need `imax`)
- in cumulative mode, having algebraics in arbitrary positions leads to constraints we can't (efficiently) solve (this is why Coq has the current restriction on algebraics and why we refresh).

So making universe polymorphism with explicit cumulativity work is not trivial.

**Comment by SkySkimmer** [comment]
>In what kind of situation will i := Set cause problems (if Prop <= i is the only constraint on it)?

When you later want to instantiate `i` by non-Set. `Prop <= i` being the only constraint doesn't mean much wrt to the use of `i` in your term.

**Comment by Janno** [comment]
Okay, I am beginning to understand the difference in perspective. For me, when debugging universe issues, universes usually have some kind of semantic meaning attached to them. "This is the universe of that type former `M`" or something like that. In that scenario, if `M` is instantiated with a `Prop` then the universe that Coq generates for that instantiation certainly shouldn't ever be used for a non-Set later (or for anything else, for that matter).
