### ISSUE TITLE
Avoid defining tactic syntax twice (mlg plus Ltac2 Notation)

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12591]
Defining the syntax of tactics twice is problematic:
- some built-in tactics are probably missing in `Notations.v`
- some tactic variations are not supported, e.g. `intros until n` or `intros until 2`.  (Let us know if there's a workaround, which can be documented.)
- user confusion if the definitions get out of sync (e.g. `simpl` is not identical) and awkward to explain in the doc
- more work to ensure the 2 definitions remain in sync or to add a new tactic (which in some cases may mean adding more quotation nonterminals).

Getting this info from the mlg files would be an excellent step towards a solution.  (The better approach would be to get the info from the parser, suitably extended, so that it just works for tactics defined in 3rd party plugins.)

Similarly but separately, it would be helpful to automatically make Ltac1 definitions visible in Ltac2.  Probably this would be simple to do for no-argument definitions.  For definitions with arguments, perhaps there could be an Ltac2 command that defines the types of the arguments.  Note that using Ltac2 will be more seamless if that argument-defining command is available even when Ltac2 is not loaded--that would allow keeping Ltac1 and Ltac2 definitions together in the .v files.

Note that the Ltac1 definition may vary depending on what packages are loaded.  For example, `lia` is defined in `Psatz.v`, `Lia.v`, and `Ztac.v`.

**Comment by SkySkimmer** [comment]
Both mechanisms have their place, that's not going to change imo

**Comment by jfehrle** [comment]
@SkySkimmer Why don't you explain  your opinion?  There are some real drawbacks to having the syntax differ in ltac2 and I'm not aware of any benefit at all of having the syntax differ.

**Comment by SkySkimmer** [comment]
Perhaps I'm not understanding the issue but I don't see how we could stop using either mlg or Ltac2 Notation. Same way ltac has both mlg and Tactic Notation.

**Comment by Zimmi48** [comment]
A path forward (for the long-term) could be for every tactic to be defined using an Ltac2 Notation, couldn't it?

**Comment by jfehrle** [comment]
Ltac2 doesn't use the tactic syntax defined in mlgs.  Instead it uses its own syntax definitions using Ltac2 Notation.  The problems are a) the definitions already don't match exactly, which is confusing for users, b) very hard to document clearly and c) is a maintenance issue because it's likely that new inconsistencies will creep in over time.

I think we're better off if Ltac2 inherits the definitions from the mlgs. I'm not at all suggesting that the Ltac2 Notation command should go away.

**Comment by jfehrle** [comment]
> A path forward (for the long-term) could be for every tactic to be defined using an Ltac2 Notation, couldn't it?

IMO the path forward is to have a single definition for each tactics' syntax.  While there's some value in being able to define syntax for new tactics at runtime with a command, being able to redefine existing commands at runtime just seems confusing.  It's perhaps analogous to the Add Load path discussion--something that's technically possible but adds undesirable complexity in practice.  I think the existing mlg mechanism is fine and preferable.

**Comment by jfehrle** [comment]
Also IIRC built-in tactics are not available in Ltac2 unless there is an Ltac2 Notation command for it.

I also wonder how the current mechanism works with SSR syntax.

**Comment by Zimmi48** [comment]
Coq libraries are compiled, so `Ltac2 Notation` cannot be called definition "at runtime". They do affect the Coq parser when you load the corresponding libraries, but it is also the case for the tactics defined in mlg files when you load the Ltac plugin.

We should expect that more and more tactics will be defined directly in Ltac2 instead of OCaml over time, and for these we cannot expect to have their syntax defined in mlg files. The reason I said `Ltac2 Notation` could be a way to have a single mechanism to define tactics (in the long-term future where we retire Ltac) is that defining Ltac2 notations for tactics written in OCaml is already supported.

**Comment by jfehrle** [comment]
> We should expect that more and more tactics will be defined directly in Ltac2 instead of OCaml over time, and for these we cannot expect to have their syntax defined in mlg files.

Sure.  If and when tactics migrate from OCaml implementations to Ltac2 implementations, of course they won't appear in the mlgs.  But what tactics have already been reimplemented?  AFAIK stdlib only uses Ltac2 Notation commands when you load Ltac2, which most users are not doing.  In the meantime, we have syntax inconsistencies depending on whether Ltac2 is loaded.

> The reason I said `Ltac2 Notation` could be a way to have a single mechanism to define tactics (in the long-term future where we retire Ltac) is that defining Ltac2 notations for tactics written in OCaml is already supported.

I expect there's enough existing Ltac code that won't be ported to Ltac2 so that "retiring Ltac" is likely at least 10 years away.  If ever.  And reimplementing all tactics in Ltac2 will be a lot of work.  Do we actually know how much Ltac code is out there?

In the meantime, the inconsistency is not good.

I would like to understand why some of the Ltac2 tactic differs--were they intentional and well-considered or not?

(Also, of course, `doc_grammar` would need to be modified to somehow pick up syntax from Ltac2 Notations.)

**Comment by SkySkimmer** [comment]
>Ltac2 doesn't use the tactic syntax defined in mlgs.

Oh yes, ltac2 uses the "external" system

But this means there is no duplication since there is no tactic definition in the mlg so I still don't understand the issue.

**Comment by jfehrle** [comment]
One hokey example:

```
Goal True -> True.
intro.
destauto in H.  (* No destructable match found -- NOT a syntax error *)

From Ltac2 Require Import Ltac2.
Goal True.
destauto in H.   (* Syntax error: [ltac_use_default] expected after [ltac2_expr] (in [ltac2_command]).
```

Or try `shelve_unifiable` in Ltac2 (* Unbound value shelve_unifiable *)

Another: The Ltac2 syntax for intropatterns is a subset of standard syntax.  Note that the `% @term0` is missing in Ltac2.

standard syntax:
![image](https://user-images.githubusercontent.com/1253341/194775668-38fc5d40-6ee0-4d2b-b410-0cf3a128c801.png)

Ltac2 syntax:
![image](https://user-images.githubusercontent.com/1253341/194775737-541ef785-46f6-4500-91ed-e9588a20e600.png)

Also getting the Ltac2 syntax and comparing it to the standard syntax to find additions and deletions was and is a manual and error-prone process.

**Comment by ppedrot** [comment]
I have already explained why I find this kind of issues nonsensical in another place but I can't find it again, so just to quickly summarize here: Ltac and Ltac2 are not the same language, it doesn't make sense to try asking to share their syntax. Making the notations similar is just a convenience and should *never* be enforced in any way.

**Comment by jfehrle** [comment]
What's the big win from redefining numerous nonterminals in `g_ltac2.mlg` and redefining all the tactics with `Ltac2 Notation`?  I don't see any benefit.

Tactic syntax and nonterminals definitions such as for `simple_intropattern` are used by Ltac but aren't considered part of Ltac itself.   Being _almost_ the same is often the most confusing for users.  It makes it very hard to provide accurate documentation.  It will likely slow the adoption of Ltac2 and reduce users' satisfaction with it.

You add a few productions such  as `$ lident` (shown above in my previous message).  These could have been handled more simply by adding only the needed new productions when Ltac2 is loaded and using a common format (i.e. used both within and without Ltac2) for the AST for nonterminals such as `simple_intropattern`.

How will your scheme ever work for SSR without major enhancements?  (While I've never tried it, I expect that SSR tactics work in Ltac.  I have no idea how many users do that.)

**Comment by ppedrot** [comment]
> What's the big win from redefining numerous nonterminals in g_ltac2.mlg and redefining all the tactics with Ltac2 Notation? I don't see any benefit.

This is very important, and actually a conscious design. This allows any end-user to reimplement their own variant of the tactic without having to resort to ML code.

> aren't considered part of Ltac itself

I cannot find two persons in this universe who share the same idea of what is part of Ltac and what is not, so I'm not sure this is a valid argument.

> These could have been handled more simply by adding only the needed new productions when Ltac2 is loaded and using a common format

At the risk of repeating myself, *this doesn't make sense*. There is no such antiquotation in Ltac1 and you don't want to pollute the Ltac1 syntax with unrelated stuff. This does not even build the same datatype! Ltac2 intropatterns build actual Ltac2 terms.

> I expect that SSR tactics work in Ltac

This is another clear case of confusion I was mentioning above: technically, ssr tactics *are* Ltac tactics. It's not because some people twenty years ago were insisting on separating the "proof language" and the "tactic language" that it makes much sense. It's like saying that `fopen` is not a C function but a POSIX one. Ltac is full of such accidental mental overhead, e.g. the insistence on separating "tactics" and "tacticals". All of these are programs in an untyped language, so this is at best a rule of thumb.

Likewise, ssr is part of Ltac, although the superficial syntax is different, and the overall feeling is also distinct. I have on my todo list the port of ssr to Ltac2. Depending on the granularity this would require more or less work. I think that to follow the design principle exposed at the beginning of this answer, I also need to expose the ssr datastructures such as the views and the like.

**Comment by Zimmi48** [comment]
@ppedrot Pretending that standard or SSReflect tactics are Ltac tactics is rewriting history. Ltac was introduced after the tactics. Furthermore, they are not Ltac tactics in the sense that they are not written in Ltac. Only the syntax is part of the Ltac plugin (because *you* decided so, when you created this plugin).

When you launched the Ltac2 project, you said you were going to replace Ltac, the tactic language, you never said you wanted to redefine the syntax of tactics, and you were not given a mandate to do so.

> Likewise, ssr is part of Ltac, although the superficial syntax is different, and the overall feeling is also distinct. I have on my todo list the port of ssr to Ltac2. Depending on the granularity this would require more or less work. I think that to follow the design principle exposed at the beginning of this answer, I also need to expose the ssr datastructures such as the views and the like.

Somehow, I'm betting that the SSReflect maintainers will manage more successfully being heard so that the existing syntax is fully respected even if that means they will be served last.

@jfehrle 

> But what tactics have already been reimplemented?

You don't actually need to reimplement tactics to decide to make them available through Ltac2 notations instead of the current mlg mechanism. So deciding to actively make `Ltac2 Notation` the standard mechanism for exposing tactic syntax is a forward-compatible solution, that's all I'm saying.

> I expect there's enough existing Ltac code that won't be ported to Ltac2 so that "retiring Ltac" is likely at least 10 years away. If ever. And reimplementing all tactics in Ltac2 will be a lot of work. Do we actually know how much Ltac code is out there?

We don't actually need to retire Ltac to move forward on such a plan, as long as we are past the step where we can declare Ltac to be the legacy proof mode.

But actually, even before Ltac becomes the legacy proof mode, it could become the legacy tactic language. With the `Ltac2 Ltac1 Notation` command from #16394, we could start redefining many tactics and tactic notations using Ltac2 without needed to change the default proof mode.

**Comment by ppedrot** [comment]
> Pretending that standard or SSReflect tactics are Ltac tactics is rewriting history.

Obviously, I am being revisionist, I insisted that it was the case *technically*. Yet, unifying concepts is the goal of mathematics and science in general. We can keep claiming that epicycles are real, or maybe just accept this as historical complexity.

**Comment by jfehrle** [comment]
> > What's the big win from redefining numerous nonterminals in g_ltac2.mlg and redefining all the tactics with Ltac2 Notation?

> This allows any end-user to reimplement their own variant of the tactic without having to resort to ML code.

The general concept of `Ltac2 Notation` is fine--it lets you pass more complex syntax elements to user-defined tactics.  But I have trouble imagining that users will want to _**redefine**_ tactics using the same name rather than a new name.  What is a use case for that?  And it makes no sense for the mlg-defined tactics to have different syntax in Ltac2 or to simply be missing.

I recognize that Ltac2 is still under construction.  So I suggest:
1. In the short term, we should first document that some tactics are unimplemented, preferably with a list of those that are unimplemented.  `doc_grammar` already generates a useful alphabetized list of mlg tactics with their syntax.  (There are also some common tactics that are defined as Ltac tactics, such as `exfalso`--those need to be addressed, too.)
2. Make all of the missing tactics available in Ltac2.
3. For later on, ensure that the Ltac2 definitions are the same as the mlg definitions, either by inheriting the mlg syntax or a lint step that verifies that the `Ltac2 Notation` defined-syntax matches the mlg grammar syntax (not entirely trivial, might need some constraints to permit comparison).

Also, I wondered about these use cases:
- Where are the Ltac2 definitions for plugin-defined tactics such as in micromega?  Are they loaded with the existing `Require`, such as `Require Import Psatz` or will users need to `Require` both Ltac2 and another file containing `Ltac2 Notation "xlia" = ...`?
- How does the Ltac2 Notation handle potentially ambiguous definitions?  Can a user create an ambiguous definition?  Does it permit defining multiple variations of a tactic with the same name, such as for `assert` (syntax below)?  If so, is there any provision for explicit lookahead to choose between the alternatives?  (like `test_lpar_id_coloneq` for `assert`)
- How do you ensure that a method signature such as `Ltac2 @ external intros : evar_flag -> intro_pattern list -> unit := "ltac2" "tac_intros".` matches the signature of the underlying method?  If an entry is incorrect, can that produce a seg fault or some other gross failure?
- How do we ensure that the Ltac2 tactics behave the same as the mlg tactics?  For example, below is the Ltac2 code for `exists`, a little different from the mlg-called tactic.  Differences and bugs can creep in even for the most experienced, careful developers.  One convincing test (an acid test?) would be to temporarily modify Coq so that all the code in CI is parsed with the Ltac2 syntax definition and see if that causes any failures.  That would take some work.  (It would also be interesting to see if there's a notable performance difference since some of the implementation moves from a compiled language, OCaml, to interpreted Ltac2.)

I'll respond to @Zimmi48's comments later. 

```
Ltac2 exists0 ev bnds := match bnds with
| [] => split0 ev (fun () => Std.NoBindings)
| _ =>
  let rec aux bnds := match bnds with
  | [] => ()
  | bnd :: bnds => split0 ev bnd; aux bnds
  end in
  aux bnds
end.

Ltac2 Notation "exists" bnd(list0(thunk(bindings), ",")) := exists0 false bnd.
```

![image](https://user-images.githubusercontent.com/1253341/195423322-d413271e-aa7c-4db0-bc98-15e3775a6952.png)

**Comment by ppedrot** [comment]
> all the code in CI is parsed with the Ltac2 syntax definition and see if that causes any failures

What part of "Ltac2 is not the same language as Ltac1" don't you understand exactly? The syntax is not the same *by design*, the semantics is not the same *by design*, this is the whole point of writing a new language. Do you also expect that OCaml code should be valid Coq syntax, also?

**Comment by jfehrle** [comment]
with the Ltac2 syntax definition _for tactics_, of course
