### ISSUE TITLE
Make Ltac2 syntax more consistent with existing syntax for q_* nonterminals

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12590]
Some nonterminals defined by Ltac2 appear to differ from similar existing nonterminals more than they must.  This can be tricky to document and awkward for users.  Showing similar syntax twice in the doc is confusing and takes a lot of space (4 pages to cover the q_* nonterminals in the draft PR #12085 in the Ltac2/Notations/Syntactic classes section).  Manually editing the grammar to condense the differences so they can appear in a unified presentation with tags (e.g. "Ltac2") is tedious and error prone.  Inconsistency between the Ltac2 and non-Ltac2 behavior of tactics is not user-friendly.

In some cases, it may make sense to change the non-Ltac2 grammar to make it match the Ltac grammar.

Consider `delta_flag`, reachable from `q_strategy_flag`.  In Ltac2, this is:

```
G_LTAC2_delta_flag: [
| "-" "[" refglobals "]"      (* Ltac2 plugin *)
| "[" refglobals "]"      (* Ltac2 plugin *)
|      (* Ltac2 plugin *)
]

refglobals: [
| LIST1 refglobal      (* Ltac2 plugin *)
]

refglobal: [
| "&" Prim.ident      (* Ltac2 plugin *)
| Prim.qualid      (* Ltac2 plugin *)
| "$" Prim.ident      (* Ltac2 plugin *)
]
```

Otherwise it is:

```
delta_flag: [
| "-" "[" LIST1 smart_global "]"
| "[" LIST1 smart_global "]"
|
]

smart_global: [
| reference    (* qualid is an alias *)
| by_notation
]

reference: [
| ident fields
| ident
]

by_notation: [
| ne_string OPT [ "%" IDENT ]
]
```

Why is `by_notation` not included in refglobal?

It might make sense to merge `smart_global` and `refglobal`.  (Though I don't know what $ident or &ident signify.)
If the semantic actions differ, it would still help to have the syntax be absolutely identical so that there can be an automatic check somewhere, perhaps in `doc_grammar`, that this part of the grammar is the same.  If $ident isn't supported outside of Ltac2, the parse action could generate a specific user-friendly message "&ident is only available with Ltac2".

Also note that `simpl` takes only a `delta_flag`, whereas Notations.v defines it with `strategy` aka `q_strategy_flag`.  Which one should change to achieve consistency?  The tactic or Ltac2?

**Comment by jfehrle** [comment]
@ppedrot What are your thoughts on this?  If you think it may be workable, I'll create a PR for a few of the `q_*` nonterminals as a proof of concept.

**Comment by JasonGross** [comment]
> For example, consider `strategy_flag`, which is used in the `cbv`, `cbn` and `lazy` tactics. It includes

You have an incomplete sentence here.

> Though I don't know what $ident or &ident signify.

Both are Ltac2 anti-quotations, and are not valid outside of Ltac2.  See, e.g., https://coq.inria.fr/refman/proof-engine/ltac2.html#term-antiquotations

I'm not sure this is a reasonable goal, as much as we try to make the grammar match between Ltac1 and Ltac2.  In particular, the way that Ltac1 does dynamically-typed antiquotations without any syntactic signifiers seems strongly incompatible with the syntactically-delimited antiquotations of Ltac2.  Furthermore, places where Ltac1 tactics take an Ltac1 expression (things like `rewrite ... by tac` or `abstract tac`) are places where Ltac2 should take an Ltac2 expression.

----

Here's another thought:
Might it be possible to parameterize the grammar over the choice of Ltac1/Ltac2, so that you instantiate what a "tactic expression" is, what the various notions of antiquotations are, etc?

**Comment by jfehrle** [comment]
> You have an incomplete sentence here.

Removed it.  I was initially going to use `strategy_flag` as the example, changed my mind and left some debris behind.

> In particular, the way that Ltac1 does dynamically-typed antiquotations without any syntactic signifiers seems strongly incompatible with the syntactically-delimited antiquotations of Ltac2.    Furthermore, places where Ltac1 tactics take an Ltac1 expression (things like `rewrite ... by tac` or `abstract tac`) are places where Ltac2 should take an Ltac2 expression.

Explaining semantic differences is not a problem.  Having almost-the-same-but-not-quite grammars is a huge problem for doc.

> Might it be possible to parameterize the grammar over the choice of Ltac1/Ltac2, so that you instantiate what a "tactic expression" is, what the various notions of antiquotations are, etc?

How is that different from my suggestion, which is to unify the confusingly similar grammar elements while using semantic checks to exclude, for example, Ltac2-only constructs when Ltac2 is not loaded?  And, if necessary, have the Ltac2 parser actions be separate (in separate productions) while checking that the Ltac2 productions have the same syntax as the non-Ltac2?  Perhaps excluding a few things, such as the nonterminals used for `match!`.  Then the doc can identify the constructs that only apply to Ltac2 or non-Ltac2.

If we need to give separate grammars for things that are mostly shared and scattered across multiple chapters of the doc, it becomes very challenging to create accurate and easy to use documentation for Ltac2--you almost need separate documents.

There's a similar issue with Ltac2 tactic definitions that don't match the non-Ltac2 definitions.

**Comment by ppedrot** [comment]
@jfehrle my take on this is that it's a very bad idea to introduce strong coupling at the syntactic level between Ltac1 and Ltac2. There have been similar attempts at sharing data structures between the "glob" level of Ltac1 and the ML API, and it's horrible since you never know what is expected from the input.

The sanest way to achieve sharing seems to me what @JasonGross proposed, i.e. having parameterized entries. But even this is far from being trivial because the grammar engine does not provide this feature, and furthermore the output AST would not even live in the same target type.

**Comment by ppedrot** [comment]
Also, on the topic of duplication, let me mention that duplication of the syntactic kind is really not concerning me too much in the Coq codebase, compared to the semantic duplications, e.g.
- the three typing algorithms
- the two unification engines (+ explosive combinatorics of flags)
- the three auto-like tactics
- the three rewrite tactics, etc.

**Comment by jfehrle** [comment]
> my take on this is that it's a very bad idea to introduce strong coupling at the syntactic level between Ltac1 and Ltac2.

It seems a stretch to consider the syntax of `simple_tactic` as a part of Ltac1 or Ltac2.  That's what makes it hard to document.  Some of the syntax changes seem unnecessary, or omissions.

> Also, on the topic of duplication, let me mention that duplication of the syntactic kind is really not concerning me too much in the Coq codebase, compared to the semantic duplications, e.g.

These sound like good things to clean up but they are probably less of an issue to explain in documentation.

**Comment by ppedrot** [comment]
I am inclined to close this as INVALID or WONTFIX.
