### ISSUE TITLE
mangle names vs. decide equality: anomaly "variable diseq unbound."

### ISSUE THREAD

**Issue by jonleivent** [coq/coq#12676]
In Coq 8.12beta1.

Apparently, some built in tactics don't like having Mangle Names turned on:
```Coq
Set Mangle Names.
Definition nat_eq_dec(i j:nat) : {i=j}+{i<>j}.
Proof.
  decide equality. (*Error: Anomaly "variable diseq unbound." ...*)
Defined.
```

**Comment by jashug** [comment]
An argument that this is a bug with `decide equality` rather than `Mangle Names`: you can get (essentially) the same problem by having a hypothesis named `diseq` in scope.
```coq
Definition nat_eq_dec(i j:nat) : {i=j}+{i<>j}.
Proof.
  pose (diseq := false).
  decide equality.
(* In environment
i, j : nat
diseq := false : bool
n : nat
H : forall x : nat, {n = x} + {n <> x}
n0 : nat
diseq0 : n <> n0
absurd : S n = S n0
Unable to unify "bool" with "False". *)
Defined.
```

**Comment by jonleivent** [comment]
Another case, perhaps more problematic, is with lia;
```Coq
Require Import Coq.micromega.Lia.
Goal 1 > 0.
  lia.
  Undo.
  Set Mangle Names.
  Fail lia.
  (*The variable __ff was not found in the current environment.*)
Abort.
```
This is in 8.12.  I now suspect there are probably other tactics that will fail with `Set Mangle Names`.  If there was a way to turn this switch on at the command line, perhaps it would be worth running some portion of the test suite with it?  An alternative is to make the effect of `Set Mangle Names` local to the interactive scope, so that existing tactics with this "bug" are not compromised (note: adding `Local` to the above `Set Mangle Names` does not prevent the error)

**Comment by jashug** [comment]
I indeed agree that there are likely many tactics which fail with `Set Mangle Names`. That is the primary reason this option is still labeled experimental. It is not currently feasible to check a large development with mangled names even if the user-facing proof scripts are making an effort to avoid auto-generated names.

In most cases where a tactic fails under `Set Mangle Names`, my expectation is that the failure can be reproduced without `Set Mangle Names` by adding conflicting names to the context or in binders, like I showed with `decide equality` above. In these cases, `Set Mangle Names` is doing it's job well by pointing out proof scripts which are vulnerable to changes to the set of names in scope or changes to the auto-naming algorithm.

I am working on a project to compile the standard library with `Set Mangle Names` (tracked at coq/coq#6781), working to fix the bugs that crop up along the way (which is hopefully most of them). The current blocker is #12001, and after that the next blocker in the standard library will be #12763. I expect `decide equality` and `lia` will both show up eventually as well. This is very slow going, both because I do not have a lot of time to spend on this project, but also because some of the bugs are very difficult to fix.

I would oppose complicating the effect of `Set Mangle Names`. The way tactics are implemented, I don't see any difference in the code between the name generated by `intro` and the internal name `__ff` generated by `lia`.

(FYI: You can use `-mangle-names _` to `Set Mangle Names` on the command line.)

**Comment by jashug** [comment]
Here is how to break `lia` without `Set Mangle Names`:
```coq
Require Import Coq.micromega.Lia.
Axiom __ff : Set.
Goal 1 > 0.
lia. (* The variable __ff was not found in the current environment. *)
```

In this case, the error comes from https://github.com/coq/coq/blob/d5a8bdc8f67b691dd39a27a9fe07a026d998fda3/theories/micromega/Lia.v#L23-L24
where we introduce a fresh name, and then use the non-refreshed name in the exact tactic. Shouldn't be too hard of a fix, though there may be other problems waiting after that one.

**Comment by jonleivent** [comment]
It is likely the case that every error that `Set Mangle Names` uncovers in a tactic indicates an issue where the tactic can break without `Set Mangle Names`.  Which of course is the whole idea.

**Comment by RalfJung** [comment]
I also ran into this in std++, minimized example:
```coq
From Coq Require Export Utf8.

Global Generalizable All Variables.

Class Decision (P : Prop) := decide : {P} + {¬P}.
Hint Mode Decision ! : typeclass_instances.
Arguments decide _ {_} : simpl never, assert.

Class RelDecision {A B} (R : A → B → Prop) :=
  decide_rel x y :> Decision (R x y).
Hint Mode RelDecision ! ! ! : typeclass_instances.
Arguments decide_rel {_ _} _ {_} _ _ : simpl never, assert.
Notation EqDecision A := (RelDecision (@eq A)).

Instance prod_eq_dec `{EqDecision A, EqDecision B} : EqDecision (A * B).
Proof. unfold EqDecision. intros. unfold Decision. decide equality.
```

**Comment by SkySkimmer** [comment]
See https://github.com/coq/coq/pull/12881
In general `intro_using` mangles the name it's given without returning it to the caller so its usage is dubious.

**Comment by RalfJung** [comment]
Is there a meta-issue for name mangling problems? That might be useful so that people interested in the general issue can subscribe to one issue and do not have to figure out themselves that yet another one showed up...

@ppedrot thanks for the fix! We now get a few files further into std++. :)
Here's the next issue: https://github.com/coq/coq/issues/12907.

**Comment by jashug** [comment]
@RalfJung It's not fully general (It doesn't point to this issue, for example), but if you haven't seen #6781, you might want to look there. As I come across name mangling problems while working on checking the standard library with `-mangle-names`, I've been dropping a link there.
