### ISSUE TITLE
SF Notations Broken: Custom Grammar

### ISSUE THREAD

**Issue by euisuny** [coq/coq#12710]
Hello,

I'm working on improving the notations for SF, and the recent release of 8.12.dev broke some of our custom grammar. 

This commit (https://github.com/DeepSpec/sfdev/tree/ab4366b260b2302f0ec89fea4b2010d6a918241f) for our [release] branch was stable for the last 8.12.dev version, but it is broken for the latest release.

In particular, 
https://github.com/DeepSpec/sfdev/blob/ab4366b260b2302f0ec89fea4b2010d6a918241f/plf/Equiv.v#L2377

Gives the following error message:
```
Error: Notation "_ := _" in custom com is already defined in com at level 0
with arguments constr at level 0, custom com at level 85
while it is now required to be in com at level 0 with arguments constr at level 0,
custom com at level 3.
```

And for all re-definitions of such custom grammar syntax, it gives similar error messages.
Is this expected behavior? Thank you!

**Comment by herbelin** [comment]
Hi @euisuny, this is the expected behavior and it is not new to 8.12. It was already like that in 8.11 and the change is related to a (quite severe) bug of 8.10 (see #11331).

In `Equiv.v`, at the time of redefining `_ := _`, if you do `Print Custom Grammar com` just before, you'll see that the notation `_ := _` is already indeed defined as follows:
```
| "0" RIGHTA
  [ SELF;  ":="; constr:com LEVEL "85"
  ...
```
For the record, the interpretation of a notation is in two parts. The first part is to parse the notation, and this is what requires levels, precedences, etc. The second part is the interpretation, which disambiguates to which effective term a notation is interpreted.

The commands to know about the parser are `Print Grammar` and `Print Custom Grammar`. The commands to know about the interpretation are `Print Scope`, `Print Scopes`, `Locate` (as well as `Print Visibility`).

In the above case, the notation is already declared to the parser, so there is no need to declare again levels and precedences for it. In 8.12, you can simply do (in `Equiv.v`):
```
 Notation "x := y" := (CAss x y) (in custom com).
```
which will tells to inherit the existing parsing rule of "_ := _" but rebinding its intepretation to the new `CAss` (in 8.11, you need to copy-paste the levels exactly as they were before, though) .

If you really want a grammar different from the existing `com` grammar, you could alternatively define a grammar `com2` in which you could have a new organization of levels. But I suspect that what you really want here is to reuse the existing grammar with a different interpretation.

Hope it helps.

**Comment by euisuny** [comment]
That helps, thanks a bunch! :-)
