### ISSUE TITLE
Why Coq does not allow the containment relationship between types

### ISSUE THREAD

**Issue by hhiim** [coq/coq#12731]
#### English is not my native language
 I want to define "integer type".But encountered obstacles
Positive integers, negative integers, and zero are all integers.
But Coq does not seem to allow containment relationships between types.
How to define "integer"? Is there such a function?
 If not, please add this function!

**Comment by ejgallego** [comment]
Hi @hhiim , I think your question will be better addressed in https://coq.discourse.group/ , together with an example of what you are trying to do; Coq's bug tracker is more about issues in the Coq system itself rather than dependent types design issues.

There are several ways to implement "type containement" in Coq, for example math-comp does provide is a `subType` class that can be used to achieve what you want easily while avoiding some issues such as proof-relevance:

```coq
Definition pos_int := { x : int | 0 <= x }.
```

**Comment by hhiim** [comment]
> Hi @hhiim , I think your question will be better addressed in https://coq.discourse.group/ , together with an example of what you are trying to do; Coq's bug tracker is more about issues in the Coq system itself rather than dependent types design issues.
> 
> There are several ways to implement "type containement" in Coq, for example math-comp does provide is a `subType` class that can be used to achieve what you want easily while avoiding some issues such as proof-relevance:
> 
> ```coq
> Definition pos_int := { x : int | 0 <= x }.
> ```
> 
> I'd suggest to follow up in discouse / stackoverflow and close this issue.

Thanks, let me see, I'm going to bed now

**Comment by hhiim** [comment]
If the problem is solved tomorrow, I will delete the problem

**Comment by hhiim** [comment]
![image](https://user-images.githubusercontent.com/21029803/88262685-3bc75c00-ccfb-11ea-8f52-f1391caefe29.png)

**Comment by SkySkimmer** [comment]
Discourse is more appropriate for this kind of question.
