### ISSUE TITLE
Tactic error underlining is sometimes reported in the wrong place

### ISSUE THREAD

**Issue by Alizter** [coq/coq#12773]
#### Description of the problem

When coqide underlines an error it does so in the wrong place. The following code snippet demonstrates this problem:
```coq
Require Import Prelude.

Goal Type.
simpl; exact 0.
```

Obviously, this throws an error but `simpl` is underlined instead of `exact 0`.

#### Coq Version
I've tried this on 8.12 and 8.11.2 and they both have this issue. However I get the intended behaviour with 8.10.2 so this seems to be a regression.

**Comment by herbelin** [comment]
Hi, this is due to 01e465952e79f4e7fdef3417c6f1883ca2c5e328 and not related to CoqIDE (let me update the title). Sorry about it.

To developers: this happens in situations involving a `TacAlias` (such as `exact`, but probably also for `TacML`-based tactics). The misplacing is due to the `Tacinterp.update_loc` updating done in the wrong way combined with the use of `tclOR`. A combination `tac; tac' args` is interpreted as `(tclOR tac reraise-with-loc-of-tac); tac' args`. Then, if a located error goes out of `args`, it is caught back by `tclOR` which replaces the `loc` of `tac` (even if there is already one, unfortunately), causing a wrong location to be reported.

Tentative fix at #12774.
