### ISSUE TITLE
Parens not printing right in custom grammar

### ISSUE THREAD

**Issue by bcpierce00** [coq/coq#12775]
In 8.12, there is a printing bug involving parens that turns one of SF's associativity lemmas into nonsense:

     Theorem seq_assoc : forall c1 c2 c3,
       cequiv [[(c1;c2);c3]] [[c1;(c2;c3)]].

becomes

     1 subgoal (ID 47)
  
       c1, c2, c3 : com
       st, st' : state
       ============================
       st =[ c1; c2; c3 ]=> st' <-> st =[ c1; c2; c3 ]=> st’

I believe Hugo understands what the problem is already, but I can provide more details if needed.

**Comment by bcpierce00** [comment]
Just noticed another printing issue that may be related: in our lambda-calculus development (file MoreStlc.v (line 1337), on the 'release' branch)

    Check <{(x y) (x y)}>.
    Check <{x (y x) y x y}>.

prints as 

    <{ x y x y }>
         : tm
    <{ x y x y x y }>
         : tm

So apparently the problem is more serious and pervasive than we thought.

**Comment by herbelin** [comment]
Both examples are fixed by #13026 (for 8.2) and #13027 (for master).

Note: For the assoc example, of course, the right-hand side shows no parentheses since this is the default associativity. For pedagogical purpose though, you may want to add a `Set Printing Parentheses` which ignores priority rules and forces printing parentheses. Only in the master PR (hence 8.13) though.

**Comment by bcpierce00** [comment]
Great!
