### ISSUE TITLE
Injection raises “Anomaly "File "tactics/equality.ml", line 1316, characters 2-8: Assertion failed."”

### ISSUE THREAD

**Issue by yannl35133** [coq/coq#12787]
#### Description of the problem

```coq
Inductive sigT3 {A: Type} {P: A -> Type} (Q: forall a: A, P a -> Type) :=
  existT3: forall a: A, forall b: P a, Q a b -> sigT3 Q
.

Definition projT3_1 {A: Type} {P: A -> Type} {Q: forall a: A, P a -> Type} (a: sigT3 Q) :=
  let 'existT3 _ x0 _ _ := a in x0.

Definition projT3_2 {A: Type} {P: A -> Type} {Q: forall a: A, P a -> Type} (a: sigT3 Q) : P (projT3_1 a) :=
  let 'existT3 _ x0 x1 _ := a in x1.



Lemma projT3_3_eq' (A B: Type) (Q: B -> Type) (a b: sigT3 (fun (_: A) b => Q b)) (H: a = b) :
  unit.
  
  destruct a as [x0 x1 x2], b as [y0 y1 y2].
  assert (H' := f_equal projT3_1 H).
  cbn in H'.
  subst x0.
  assert (H' := f_equal (projT3_2 (P := fun _ => B)) H).
  cbn in H'.
  subst x1.

  inversion H. (* both raise the same anomaly *)
  injection H.
Admitted.
```

#### Coq Version

```
The Coq Proof Assistant, version 8.11.2 (June 2020)
compiled on Jun 15 2020 9:11:00 with OCaml 4.10.0
```

**Comment by herbelin** [comment]
Thanks for reporting. PR #12816 is providing a fix.

Note that we know nowadays how `injection` could produce nicer goals by transporting an equality rather than using an equality of dependent tuples. For instance, it could typically produce:
```coq
...
H0 : y1 = y1
H1 :  rew H0 in x2 = y2
============================
  unit
```
which is just obtained by postcomposition with `apply eq_sigT_uncurried_iff in H0 as (H0,H1); simpl in H0, H1` and 
where the `rew` notation is obtained by `Import EqNotations`. Then, if `H0` were not between two identical terms (as it is here), a `destruct H0` could be used to continue simplify the goal further.

It could even use an "equality over", which is a very nice heterogeneous equality having the advantage to be symmetric:
```coq
H0 : y1 = y1
H1 :  x2 =_{H0} y2
============================
  unit
```
where `x =_{ H } y` is defined by:
```
Reserved Notation "x =_{ H } y" (at level 70).
Inductive eq_over {A} (x:A) : forall {B} (y:B), A = B -> Prop :=
  eq_over_refl : x =_{eq_refl} x 
where "x =_{ H } y" := (eq_over x y H).
```

**Comment by SkySkimmer** [comment]
What does the eq_over version look like when you iterate? eg injection over `(a;(b;c)) = (a';(b';c'))` where `(_;_)` is dependent pairing.

**Comment by jashug** [comment]
You would probably get something like `H1 : a = a'`, `H2 : b =_{f_equal B H1} b'`, `H3 : c =_{f_equal C (sig_pair_eq H1 H2)} c'`
where `sig_pair_eq {A : Type} {B : A -> Type} {a a' : A} {b : B a} {b' : B a'} (H1 : a = a') (H2 : b =_{f_equal B H1} b') : (a;b) = (a';b')`.
Note that `sig_pair_eq (sig_pair_eq H1 H2) H3` is well-typed, so we don't need to generalize `sig_pair_eq` to more than two arguments either.

**Comment by ppedrot** [comment]
@herbelin I'd heartily support such a change in the injection tactic, because currently it's essentially useless on dependent goals. It's not even likely to create a lot of backwards incompatibility precisely because of that, since nobody sane uses it in this setting.

**Comment by yannl35133** [comment]
About that, I can't make `dependent rewrite` work. It might be that I don't get how it should work, but then the documentation would be misleading (me, at least): shouldn't it be able to change `x2` to type `Q y1` ?
```coq
Lemma projT3_3_eq' (A B: Type) (Q: B -> Type) (a b: sigT3 (fun (_: A) b => Q b)) (H: a = b) :
  unit.
  
  destruct a as [x0 x1 x2], b as [y0 y1 y2].
  dependent rewrite H in x2.
Admitted.
```

**Comment by herbelin** [comment]
> About that, I can't make `dependent rewrite` work. 

I'm not very accustomed to `dependent rewrite` but the fact is that it works only with sigma-types (`existT`) or subset types (`exist`). It could be extended in principle to work with more general forms of dependent equality but I would rather bounce on @ppedrot's remark and favor a version of `injection` which splits equality of dependent tuples into atomic rewritable  (dependent) equalities. In this case, the combination of `injection H` and `dependent rewrite` on a pair would mostly look like `injection H as -> ->`.

**Comment by herbelin** [comment]
A question to @ppedrot remains: how to organize ourselves? To start with, do we favor a `rew H in t = u` form or a `t =_{f_equal Q H} u` form, or do we make it configurable? Do we develop a library of properties of equality over, showing in particular that it strictly generalizes usual `eq` (which I could e.g. do)? Do we extend `rewrite` so that it is able to rewrite with `t =_{eq_refl} u`?
