### ISSUE TITLE
Check loops forever, but Print works

### ISSUE THREAD

**Issue by larsr** [coq/coq#12817]
#### Description of the problem

When I do `Check b.` then `coqtop` hangs forever. In collacoq it gives a stack overflow.

```
Require Import Coq.Classes.Equivalence.

Class a G equ `{@Equivalence G equ} := { b : G -> G -> G }.

Print b.  (* this works *)
Check b.  (* infinite loop *)
```
Try here: https://x80.org/collacoq/zivitagonu.coq

#### Coq Version

8.11.0 and 8.12.0

**Comment by SkySkimmer** [comment]
Because of pointwise_relation preserving equivalence it can generate an infinite stream of equivalences to search an instance of `a` for.
Maybe we should set a Hint Mode on `Equivalence`? Unlike `Reflexive` (https://github.com/coq/coq/issues/7916) it doesn't seem to break setoid rewrite (at least on the example in https://github.com/coq/coq/issues/7916)

**Comment by SkySkimmer** [comment]
Let's defer to more general typeclass loop issues.
