### ISSUE TITLE
`try` cannot find tactic notations above level 3

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#12824]
I would expect `try` to be able to receive any tactic notation, but it cannot find notations registered above level 3:
```
Tactic Notation (at level 5) "test0" := idtac.
Tactic Notation (at level 4) "test1" := idtac.
Tactic Notation (at level 3) "test2" := idtac.

Goal True.
Fail try test0.
Fail try test1.
try test2.
let t := test0 in try t.
```

#### Coq Version

The Coq Proof Assistant, version 8.12.0 (July 2020)
compiled on Jul 25 2020 10:17:03 with OCaml 4.10.0

**Comment by Zimmi48** [comment]
This is normal and documented as such: https://coq.inria.fr/refman/proof-engine/ltac.html#coq:tacn.try

If you need to pass a tactic notation at a different level, it is always possible to add parentheses:

```
Tactic Notation (at level 5) "test0" := idtac.
Tactic Notation (at level 4) "test1" := idtac.
Tactic Notation (at level 3) "test2" := idtac.

Goal True.
try (test0).
try (test1).
try (test2).
let t := test0 in try t.
```

The reason the error you get is "The reference ... was not found in the current environment." and not a parsing error is because according to the parsing rules, the code is then looking for a basic tactic (not a tactic notation) and no such tactic exists. I'm not sure if the error message could be improved in this case, but I'm tentatively labeling this issue as a request for error message improvement.

**Comment by LasseBlaauwbroek** [comment]
Ah, excuse my ignorance, I did not check the documentation. Improving the message might help, but if that's too hard I suggest closing this.

**Comment by Zimmi48** [comment]
No worries! I don't personally know if it's feasible to improve the error message or not in this case, so I'll leave it to others to decide whether to close this or not.

**Comment by ppedrot** [comment]
I don't think we can do anything about the error message, I'd recommend closing.

**Comment by SkySkimmer** [comment]
Declaring atoms with a nonzero level is kinda surprising.
In the general case I guess there may be optional arguments, then maybe we could auto declare the 0 argument instance at level 0?

**Comment by ppedrot** [comment]
@SkySkimmer the declaration of atoms at arbitrary level is useful here to exhibit a small test. You could get a similar error with arguments though, so at best instead of silently resetting the level, a warning might be useful.

**Comment by ppedrot** [comment]
As already argued for, let' close.
