### ISSUE TITLE
zify install directory

### ISSUE THREAD

**Issue by fajb** [coq/coq#12885]
#### Description of the problem
In the Coq source tree, the code of the `zify` plugin is located in `plugins/micromega` [*].
However, it is installed in the `plugins/zify` directory. 
I noticed this because `coq_makefile` forgets to list `plugins/zify` in the list `COQMF_COQ_SRC_SUBDIRS`.

[*] At the time, creating a new directory was responsible for a noticeable slowdown - AFAIK, the mystery has never been solved...

#### Coq Version
8.13+alpha

**Comment by ejgallego** [comment]
@fajb actually this is a discordance of the install layout of the make system vs the way the dune build system installs the libraries.

IMHO `coq_makefile` should not make any assumptions about the install scripts and instead use `ocamlfind` to locate plugins.

**Comment by fajb** [comment]
So you mean that the generated CoqMakefile should call `ocamlfind` over the `$(COQ_SRC_SUBDIRS` instead of the syntactic
`COQSRCLIBS?= $(foreach d,$(COQ_SRC_SUBDIRS), -I "$(COQLIB)/$(d)")`

**Comment by ejgallego** [comment]
It should be more like `ocamlfind` over `COQ_PLUGIN_LIST` , note that since a while the list of plugins doesn't correspond to the listing of directories under `plugins`.

Dune installs each OCaml plugin in a separate folder as otherwise there is not way to exclude it from the list of dependencies, for example, with current makefile install layout, if you pass `-I plugins/micromega` , `zify` will also be in scope for you OCaml dev.

Another fix would be to actually create separate directories [that would also need tauto]
