### ISSUE TITLE
Why does the Windows(?) installation include menhir documentation?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12902]
Why do we include the menhir documentation in the installed, official build of Coq?  How is it relevant?

It's definitely there for Windows; not easy for me to check for other platforms.

**Comment by Zimmi48** [comment]
Did you install Coq with or without the addons? Menhir is one of the dependencies of some addons (CompCert and VST IIRC).

cc @MSoegtropIMC

**Comment by MSoegtropIMC** [comment]
Menhir can generate Coq source code for formally verified parsers, so it is relevant for some Coq developers (me for one). For this reason the Windows installer does install menhir (if selected) and with it the menhir documentation.

So this is intended / expected / useful behavior.

**Comment by jfehrle** [comment]
That makes some sense, but how do users know to look in that directory?  Seems like this is one-off handling for menhir--after a full Windows install, no other package has doc there (there is an FAQ for CoqIDE).  (FWIW, I see installing menhir with opam includes the html version of menhir doc.  I wonder why we don't install the Coq doc in this directory.)

Also, shouldn't the Coq doc include at least a brief list of the installable packages (below) and pointers to information on them (when available)?  And mention Windows vs OPAM differences in what packages are installed (and how)?

![image](https://user-images.githubusercontent.com/1253341/91485319-8b9bc480-e85f-11ea-8365-8dafc34cc846.png)

**Comment by MSoegtropIMC** [comment]
Since the Windows installer is end of life in this form, I don't see much of a point in discussing this right now. It will be replaced with an opam based solution and it will install files where the corresponding opam package says they should go. If this is not appropriate, this is a an issue which should be reported against the respective package.

It would make more sense to look at the directory structure created by the Coq platform alpha3 build.

I don't think this should be documented in Coq documentation, because these packages will be removed from the plain Coq installer in the next version of Coq (8.13).

**Comment by jfehrle** [comment]
> Since the Windows installer is end of life in this form ... It will be replaced with an opam based solution

Ah, opam2 has been fixed for Windows?  I was not aware of that.  It was totally unusable when I last tried it a year plus ago.  If opam works, it's much better for Windows to be consistent with the other platform.

**Comment by MSoegtropIMC** [comment]
> Ah, opam2 has been fixed for Windows? I was not aware of that. It was totally unusable when I last tried it a year plus ago. If opam works, it's much better for Windows to be consistent with the other platform.

It is still quite tricky. There is a repo with a lot of patched packages which is reasonably well maintained. You have to use that. See the coq platform setup script for details.

For a reason I don't understand these patches are not merged into the main opam repo, but since we don't need that many OCaml packages and the Coq repo is anyway separate, I can live with this.

Btw.: any feedback, especially on the documentation, on the coq platform alpha3 release is most welcome!

(https://github.com/MSoegtropIMC/coq-platform/tree/v8.12.0.alpha3)
(https://github.com/MSoegtropIMC/coq-platform/tree/v8.11.2.alpha3)

**Comment by Zimmi48** [comment]
FWIW, Anil Madhavapeddy from OCaml Labs has announced that the next opam release (2.2) would be the "Windows release" and that those patches would be integrated. See: https://youtu.be/E8T_4zqWmq8?t=3397
