### ISSUE TITLE
Why does coq_makefile generate `CoqMakeFile` rather than just `Makefile`?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#12903]
It seems like it would be simpler just to generate `Makefile`.  Then you wouldn't need the extra arguments in "make **-f CoqMakefile**".  Does anyone know why it was done this way?

cc @herbelin

**Comment by Zimmi48** [comment]
People usually call `coq_makefile` with two arguments (`-f _CoqProject` and `-o Makefile.coq`) as part of small Makefile wrappers such as [this one](https://github.com/coq-community/aac-tactics/blob/master/Makefile). While the `-o` option is optional, the output of `coq_makefile --help` still says that it is "recommended". I personally would favor making this a mandatory option instead of changing the default...

**Comment by jashug** [comment]
Is the point of that wrapper just to not put the generated `Makefile.coq` in git? If so, I wonder if it would be possible to have `coq_makefile` either produce output that played nicely with git or to generate the wrapper as well.

Context: I've always used `coq_makefile -f _CoqProject -o Makefile`, and then just `make`, and so I am missing out on whatever value is added by that Makefile wrapper. At the very least, there might be some documentation around `coq_makefile` explaining this trick.

**Comment by Zimmi48** [comment]
Indeed, I think this is the main value. The auto-generated makefiles are both long and version-specific. Committing them in git is usually not a good idea because when re-running `make` they are overwritten and if you happen to be working on a different Coq version than your colleagues, then you might introduce spurious changes to that file. The wrapper `Makefile` avoids users having to remember to run `coq_makefile -f _CoqProject -o Makefile` before they can run `make`. Some projects use a `configure.sh` file instead for this purpose.

**Comment by herbelin** [comment]
Is there a recommended wrapper that we could put as example in the reference manual? For instance, the following seems pretty common:
```
all: CoqMakefile
        +make -f CoqMakefile all

clean: CoqMakefile
        +make -f CoqMakefile clean
        rm -f Makefile.coq

CoqMakefile: _CoqProject
        $(COQBIN)coq_makefile -f _CoqProject -o CoqMakefile

_CoqProject: ;

%: CoqMakefile
        +make -f CoqMakefile $@

.PHONY: all clean
```
Can it be safely documented?

Side question: culturally speaking, are there advantages of `CoqMakefile` vs `Makefile.coq` or would the difference be perceived as completely arbitrary?
