### ISSUE TITLE
Name mangling breaks using names in `abstract`

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#12928]
#### Description of the problem

The following proof script fails, but I would expect it to work:
```coq
Set Mangle Names.
Lemma test: forall x: nat, nat.
Proof. intros x. abstract (exact x). Qed.
```
It says:
```
Error: The reference x was not found in the current environment.
```

#### Coq Version

Latest Coq master

**Comment by SkySkimmer** [comment]
The issue is we do
~~~ocaml
  let concl = match goal_type with
              | None ->  Proofview.Goal.concl gl
              | Some ty -> ty in
  let concl = it_mkNamedProd_or_LetIn concl sign in
  let solve_tac = tclCOMPLETE (tclTHEN (tclDO (List.length sign) Tactics.intro) tac) in
~~~
ie we put the context in the goal as forall to start the subproof, then intro the variables back to the context. This refreshes the names.
I'll make a PR to fix.

**Comment by jashug** [comment]
Issue #3146 is highly related.
