### ISSUE TITLE
configure succeeds but make fails when libzarith-ocaml but not libzarith-ocaml-dev is installed on ubuntu

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#12951]
#### Description of the problem

#12939 is not sufficient, see https://github.com/HoTT/HoTT/pull/1392/checks?check_run_id=1048236906 where [`./configure` says](https://github.com/HoTT/HoTT/pull/1392/checks?check_run_id=1048236906#step:9:130) :
```
You have OCaml 4.05.0. Good!
You have OCamlfind 1.7.3. Good!
You have native-code compilation. Good!
You have the Zarith library installed. Good!
LablGtk3 or LablGtkSourceView3 not found:
=> no CoqIde will be built.

  Architecture                : Linux
  Sys.os_type                 : Unix
  Coq VM bytecode link flags  : -dllib -lcoqrun -dllpath /usr/local/lib/coq/kernel/byterun
  Other bytecode link flags   : 
  OCaml version               : 4.05.0
  OCaml binaries in           : /usr/bin/
  OCaml library in            : /usr/lib/ocaml
  OCaml flambda flags         : 
  Native dynamic link support : true
  CoqIde                      : no
  Documentation               : None
  Web browser                 : firefox -remote "OpenURL(%s,new-tab)" || firefox %s &
```
but [`make coqocaml` fails with](https://github.com/HoTT/HoTT/pull/1392/checks?check_run_id=1048236906#step:9:367)
```
OCAMLC    tools/coqdep.ml
OCAMLOPT  tools/coqdep.ml
OCAMLBEST -o bin/coqdep
File "_none_", line 1:
Error: Cannot find file /usr/lib/ocaml/zarith/zarith.cmxa
Makefile.build:501: recipe for target 'bin/coqdep' failed
```

cc @SkySkimmer 

#### Coq Version

94d9fe2b6cb06fe7f862683d8337433e18314001

**Comment by silene** [comment]
For what is worth, we had the same kind of issue with Why3. So, we solved it by checking not only that `ocamlfind query zarith` succeeds, but also that the resulting directory contains both `zarith.cma` and `z.cmi`. The latter file is provided by `libzarith-ocaml-dev`.

**Comment by treinen** [comment]
You might also use the debian package for coq 8.12.0 which is currently in debian experimental (I cannot upload it to unstable ATM since why3 depends on coq 8.11.0).  I suppose that you can just build the package on a recent ubuntu system, and it has all the dependencies on the necessary debian packages, including lablgtk3 stuff for building the IDE.

**Comment by Alizter** [comment]
@treinen The issue is that the configure script is not picking up that `libzarith-ocaml-dev` is not installed. We (the HoTT library) were able to build the library on coq master fine, but initially `./configure` was incorrectly reporting that zarith was found even though we had only installed `libzarith-ocaml` rather than `libzarith-ocaml-dev`.

In summary, the coq configure script isn't checking for `libzarith-ocaml-dev` like it should.
