### ISSUE TITLE
Doc for notations incorrectly claims that there are spaces when there are not

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13020]
https://github.com/coq/coq/blame/e0696ef1db06dbe32c95ac16b9c54d6b3624dff0/doc/sphinx/user-extensions/syntax-extensions.rst#L249
reads
```coq
Notation "{{ x : A | P }}" := (sig (fun x : A => P)) (at level 0, x at level 99).
```
and claims that there are extra spaces around `|`.  There are not.  Despite this, the display on the subsequent line is still
```
{{x : nat | x = x}}
     : Set
```
as can be seen at https://coq.inria.fr/refman/user-extensions/syntax-extensions.html#displaying-symbolic-notations

@herbelin can you explain why there are spaces around `|` even when the notation only uses one space?  And what example should we be using here?

For reference, the doc is:
> A first, simple control that a user can have on the printing of a notation is the insertion of spaces at some places of the notation. This is performed by adding extra spaces between the symbols and parameters: each extra space (other than the single space needed to separate the components) is interpreted as a space to be inserted by the printer. Here is an example showing how to add spaces around the bar of the notation.

We could use something like `"{{  x : A | P  }}"`.  But we should also say why `|` and `:` are special?

**Comment by herbelin** [comment]
> claims that there are extra spaces around `|`.

It seems that the spaces disappeared during the translation of the reference manual to sphinx. Maybe because the person who translated did not see a use of them, since, indeed, one space is inserted anyway on both sides of the bar.

> There are not. Despite this, the display on the subsequent line is still [with one space]

There is a heuristic starting at line 330 of [`metasyntax.ml`](https://github.com/coq/coq/blob/282bf5806ca861ca7649bdd8555cba2b2130a3d7/vernac/metasyntax.ml#L330) which would be tedious to document.

I'm making a fix for the refman (#13022).
