### ISSUE TITLE
coq_makefile -destination-of dir/F fails if dir exists but does not contain F

### ISSUE THREAD

**Issue by jadephilipoom** [coq/coq#13031]
#### Description of the problem

Ran into a bit of a bizarre bug where `coq_makefile -destination-of` prints the correct output *unless* the top-level directory exists, in which case it prints nothing. I tested it out by creating an empty directory, trying `coq_makefile -destination_of` with dummy arguments, and then running `mkdir src` and running it again. The second run produces no output. (I also tested it out with directory names other than `src` in case that one was special, and the issue is the same.)

```
$ ls -a
.  ..
$ coq_makefile -destination-of src/Y/Z/Test.v -Q src X
X//Y/Z
$ mkdir src
$ coq_makefile -destination-of src/Y/Z/Test.v -Q src X
```

This is causing `make install` to fail for me on a few different projects that rely on `-destination-of`.

#### Coq Version

```
$ coqtop -v
The Coq Proof Assistant, version 8.12.0 (September 2020)
compiled on Sep 15 2020 14:27:23 with OCaml 4.08.1
```

**Comment by gares** [comment]
Does Test.v exist?
```
gares@ollypat:/tmp$ mkdir -p src/Y/Z
gares@ollypat:/tmp$ touch src/Y/Z/Test.v
gares@ollypat:/tmp$ coq_makefile -destination-of src/Y/Z/Test.v -Q src X
X//Y/Z
```
There is clearly something wrong, but your setup seems not standard either.

**Comment by jadephilipoom** [comment]
Investigating a little further, it seems like it works if `Test.v` doesn't exist, but stops working if the `Z` directory doesn't exist:
```
$ mkdir -p src/Y
$ coq_makefile -destination-of src/Y/Z/Test.v -Q src X
$ mkdir src/Y/Z
$ coq_makefile -destination-of src/Y/Z/Test.v -Q src X
X//Y/Z
$ rmdir src/Y/Z
$ coq_makefile -destination-of src/Y/Z/Test.v -Q src X
```
So it seems to be about whether it can find the directory that the file should be in.

**Comment by gares** [comment]
Thanks for investigating.
Now I still don't get how this breaks your project.
Why are you installing a non existent file?

**Comment by jadephilipoom** [comment]
A fix for this wouldn't fix my problem, it turns out, so it's not blocking for me. Still, my debugging would have gone a lot faster if the behavior was more predictable.

**Comment by gares** [comment]
The code compares two *canonical* dir paths in order to tell if one is the prefix of the other. One if the file name's dirpath, the other the argument to -Q. Depending on the existence, they are made absolute or not by the code below, and a relative path is not the prefix of an absolute one.

The culprit is
https://github.com/coq/coq/blob/ff508baf8de691dfa94b9d65d7c77cf395127381/clib/cUnix.ml#L63-L72
We compute the canonical path name (which is absolute) of the directory but if it does not exist we don't prefix $cwd to it.
I'll try to fix that, but looks like a change that could break things.
I'll open a PR soon.
