### ISSUE TITLE
Windows CI is broken on both Azure and GitLab CI

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#13065]
As I previously mentioned on Zulip, something has changed (not on the Coq side) which has broken Windows CI both on Azure (opam-based) and on GitLab CI (manual build of OCaml). See https://dev.azure.com/coq/coq/_build/results?buildId=11965&view=logs&jobId=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=f33089cd-d3fe-578c-2c5e-4ee560e10a0d and https://coq.gitlab.io/-/coq/-/jobs/748531263/artifacts/artifacts/buildlogs/ocaml-4.08.1-make-world.opt_err.txt.

(I've verified that the first failure on master happened when merging a PR whose CI was successful.)

Given the error message, it looks like some C sources of OCaml, which previously build fine, do not anymore.

Diffing the packages installed by Cygwin between a successful and a subsequent failed build on `master` informs us that `mingw64-x86_64-winpthreads`, `mingw64-x86_64-runtime`, `mingw64-x86_64-headers`, `w32api-runtime` and `w32api-headers` have been upgraded from 7.0.0-1 to 8.0.0-1.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I fear the only way to fix this on the Cygwin side is using a local repo. See (https://stackoverflow.com/questions/25912335/cygwin-installing-a-specific-package-version-using-the-commandline-installer/26100113). Since we anyway wanted to do this, I think this is the way to go.

The other option is to patch the OCaml sources - it shouldn't be that difficult.

I think in any case we should report an issue upstream at OCaml.

I will hold pack the platform announcement until this is fixed.

Can you look into it or should I do it? I would look into fixing the OCaml sources.

**Comment by Zimmi48** [comment]
I confirm that we have the exact same issue with OCaml 4.07.1 (in `v8.12`), which means that this will delay the 8.12.1 release as well.

Patching the OCaml sources might indeed be the simplest way of fixing the problem for the packaging script, but it won't be as easy to apply to the Azure tests. Maybe we should explore the other option instead (and as you said we wanted to do this anyway). Let me know what I can do to help.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I will look into both options today. For the platform a patched cygwin repo is not terribly attractive, but we should do both.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : Coq platform on windows is not affected because (I forgot) it uses a binary pre compiled version of OCaml, but for testing I can change this.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I didn't manage to fix this yesterday - the main issue is that the opam source package I use on the platform doesn't even build with the old version of Cygwin. Since I usually use the binary delivery I didn't notice so far.

I guess to debug such issues more easily it would be best to create an opam package which builds OCaml as I build it in the Coq Windows installer (a non trivial process for 4.07). I won't have time for further investigations before today evening.

Btw.: Coqide didn't build either yesterday evening (with the binary OCaml 4.07.1) - I didn't look into why as yet.

**Comment by Zimmi48** [comment]
Is this pre compiled OCaml a possible option for building the Windows package for 8.12.1?

**Comment by MSoegtropIMC** [comment]
> Is this pre compiled OCaml a possible option for building the Windows package for 8.12.1?

It is tricky because it goes together with the Windows Opam. I wouldn't change to much here now - I will anyway switch to CoqPlatform soon. Chances are good that I can fix it today - if not we can still discuss.

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : I tested this fix only on 4.07.1 and just merged it over to 4.08.1, but both have the same issue / code, so this should work.

**Comment by MSoegtropIMC** [comment]
See also (https://github.com/fdopen/opam-repository-mingw/issues/77)

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : what I forgot to tell: my PR fixes only my build - I don't know much about teh Azure build and don't know how to apply the patch there.

**Comment by Zimmi48** [comment]
Yes, but if @fdopen adds your patch to the opam-repository-mingw, then it will fix Azure as well, because this build is opam-based.

**Comment by MSoegtropIMC** [comment]
In that case it might make sense to add a little patch repo as I do for Coq platform - i can look into that if you want.

Or use the Coq platform script with a reduced module list (a separate file) right away - it is quite flexible in not doing things already done (install cygwin, opam, ...), so it should whould work well and efficiently in any environment.

**Comment by Zimmi48** [comment]
This is now fixed both for GitLab CI and Azure pipelines in `master` and `v8.12`.
