### ISSUE TITLE
Simplify isLinearOrder

### ISSUE THREAD

**Issue by rpgcbaptista** [coq/coq#13211]
#### Coq 8.12.0

In theories/Reals/Abstract/ConstructiveReals.v the definition of isLinearOrder can be simplified. Asymmetry and cotransitivity imply transitivity, so transitivity is unnecessary.

Also, why is CRlt_trans transparent if it depends on opaque theorems?

**Comment by Zimmi48** [comment]
cc @coq/reals-library-maintainers 
@rpgcbaptista Note that when you see what to change, you should always feel free to open pull requests yourself.

**Comment by rpgcbaptista** [comment]
I'm working on it. Some of these axioms for constructive real numbers are unnecessary.

**Comment by silene** [comment]
I suppose the original reason is the same for both issues. These theorems are meant to be used as algorithms. So, they have to be transparent, and they might be more efficient if defined separately rather than one on top of the other. That said, this is seemingly misguided:

1. As you point out, `CRlt_trans` is defined using `CRlt_le_trans` instead of `CRltLinear`, thus useless as an algorithm.
2. CoRN, which the only provider of `isLinearOrder` instances (as far as I know), uses `Qed`. So, even if the above was fixed in the standard library, it would still be useless as an algorithm.

**Comment by herbelin** [comment]
I would suppose indeed that the motivation is computational. At best should there be an explanatory comment. Requesting help from @VincentSe.

**Comment by VincentSe** [comment]
Yes, the motivation is computational. A proof of `x < y` is a rational number `0 < q`, together with a proof that `q <= y-x`. This rational number `q` is the computational content, or witness, of the proof of `x < y`. It must be transparent. It is used for example in the division `1/x`, which takes a proof of `0 < x`, to get that number `q` so that it knows at what precision to compute `x`. The bigger `q` is, the faster the following computations. The proof of `q <= y-x` can be left opaque, because it has no computational content : it is a negation.

Imagine you derive `x < z` from `x < y`, `y < z`, co-transitivity and asymmetry. Denote `q` and `r` the witnesses of `x < y` and `y < z` respectively. The witness your proof produces for `x < z` is something close to `q/2`. But this will not come for free, it will already be a computation of co-transitivity, that takes a little bit of time. And worse, `q/2` is lower than a much better witness : `q+r`. And that latter witness is immediate to compute, you just need to destruct it from the proofs of `x < y` and `y < z`.

So `isLinearOrder` leaves transitivity as a separate field, so that implementations can fill it by the direct summation of the witnesses of `x < y` and `y < z`. Logically this is not the shortest proof, but computationally it is the fastest. You could comment that in your PR, or I can do it if you prefer.

**Comment by rpgcbaptista** [comment]
If performance is a concern, then there's not much that can be done. But I still think CRplus_lt_compat_l and CRplus_lt_reg_l can be derived from each other without a penalty in performance.

CRplus_lt_compat_l : forall r r1 r2 : CRcarrier,
        CRlt r1 r2 -> CRlt (CRplus r r1) (CRplus r r2);
CRplus_lt_reg_l : forall r r1 r2 : CRcarrier,
        CRlt (CRplus r r1) (CRplus r r2) -> CRlt r1 r2;

**Comment by VincentSe** [comment]
I spent some time trying to derive `CRplus_lt_compat_l` and `CRplus_lt_reg_l` from one another, but failed. I would gladly see a PR that does it.

Performance may or may not be a concern. If you are a constructive mathematician and don't want to compute, you will not code another implementation of record ConstructiveReals. So its redundant hypotheses do not matter to you, because they are given to you. Just use the stdlib Cauchy reals implementation in that case.

On the other hand, if you want to compute, you want to compute fast. Then you might want to code another implementation of ConstructiveReals specialized for your computation. And then you will want to optimize all proofs, not relying on the basic logical equivalences between them.

**Comment by VincentSe** [comment]
By the way, if you want to compute fast, have a look at 
https://github.com/coq-community/corn
It has a implementation of this record ConstructiveReals by dyadic rationals based on machine integers. That would be around 100 times faster than the stdlib's Cauchy reals.

**Comment by rpgcbaptista** [comment]
I take that back. I can't derive CRplus_lt_reg_l from CRplus_lt_compat_l without there being an impact on performance, because the proof depends on cotransitivity. My question now is: is the record ConstructiveReals meant to be fast or meant to be simple? Because I think I can simplify it a bit.

The proof of CRplus_lt_reg_l is probably the same as Rplus_lt_reg_l. You can find it at https://github.com/coq/coq/compare/master...rpgcbaptista:delete-axiom.

**Comment by VincentSe** [comment]
Ok, nice proof of `CRplus_lt_reg_l`. I guess co-transitivity is hidden in the `rewrite`s.

Record ConstructiveReals is meant to be fast, that is to allow fast implementations. The absolute value `CRabs` is redundant in it for example, it is only there so that the implementations can provide faster formulas for it.

**Comment by rpgcbaptista** [comment]
That being the case, no changes can be made.
