### ISSUE TITLE
Hardly predictable bytecode compilation of let-in constructs 

### ISSUE THREAD

**Issue by silene** [coq/coq#13234]
As explained in #12947, the bytecode compiler tends to reorder (or even ignore) let-in constructs. This is has no impact on the normal forms that are computed. But it can have an impact on the time complexity of normalization, especially when one takes into account semi-persistent data structures (e.g., primitive arrays) or lifetime of values (e.g., garbage collections).

For example, for the following function,

```coq
Axiom T : Set.
Axiom f g h : T -> T.

Definition v x :=
  let a := f x in
  let b := g x in
  let c := h a in
  (b, c).
```

function `f` is called first, then `h`, and finally `g`.

And if the returned value is instead `(c,  b)`, then `g` is called first, then `f`, and finally `h`.

But at no point are the functions called in the order specified by the user.

**Comment by herbelin** [comment]
Who was saying that the vm is call-by-value :smile:!

**Comment by ppedrot** [comment]
While this can be considered as a bug, I do believe there is something more fundamental at work there. The VM uses a call-by-value semantics at the meta-level for an object theory that is call-by-name, so it must validate any equational CBN property. In particular, it could decide to reorder terms in any fancy way that is compatible with this calling convention. Throwing in subtly hidden effects in the mix shows that efficiency is obviously observable in the system, and that people do care about it.

Forcing let-bindings to be computed in a particular order is essentially a hack. If we want a reliable way to enforce the order of evaluation we should rely on the only way to force something in CBN, namely pattern-matching. I think that the persistent array API should be exposed either in CPS or with boxed types / unit types so that we know for sure that the term is evaluated by the reduction. For instance, reroot could have type `forall A, array A -> unit` so that it would have its effect when pattern-matched.

**Comment by silene** [comment]
To be clear, I do not consider it a bug (and I did not tag this issue as such). For me, this is no different than the fact that OCaml does not specify the evaluation order of function arguments. Here, it is a bit more extreme, since not only function arguments but also let-in values are evaluated in an order left unspecified by the bytecode compiler, which breaks a lot of user assumptions (at least mine). But this still fully complies with a call-by-value evaluation (by definition), so it is not a bug.

As for `reroot`, the very idea of this function was misguided and it no longer exists.

**Comment by herbelin** [comment]
@ppedrot: To clarify, it is clear that the vm implements a call-by-name equational theory. Without having precisely studying the vm myself, I was however in the belief that it would however implement a call-by-value evaluation strategy of the call-by-name semantics, precisely in the sense of seeing `let x:=t in u` as a proper (possibly effectful) construction (rather than as a mere substitution) and of first reducing `t` to cbn-head-normal form (as well as seeing `(fun x => u) t` as `let x := t in u`). I'm learning that this is not even the case. Nothing bad at it, but useful to know when explaining what the vm does regarding standard ways to describe evaluation semantics.

On the other side, @silene, you seem to see cbv as only characterized by the strategy used to evaluate `t u` (and see `let x:=t in u` as a mere substitution?).

To  continue with making plans on the comet, isn't there a lot of OCaml or C code around which de facto rely on the effectively implemented evaluation order and which would break if it came to be changed? Claiming that the evaluation order of argument does not matter w/o enforcing statically that this is well the case seems a bit like a theoretical position. Alternatively, maybe one day will we be able to type OCaml programs in a logic which traces side-effect and reject those programs which exposes side-effects in a position where they are not supposed to do so.

**Comment by silene** [comment]
> you seem to see cbv as only characterized by the strategy used to evaluate `t u` (and see `let x:=t in u` as a mere substitution?).

Not a mere substitution. Expression `t` is still turned into a value before it is bound to `x`. My definition of call-by-value is that any expression is evaluated before it is bound to a variable (be it a function argument or a let-in binder).

> isn't there a lot of OCaml or C code around which de facto rely on the effectively implemented evaluation order and which would break if it came to be changed?

There seems to be a misconception, at least regarding C. There is no two C compilers out there that have the same evaluation order. Moreover, just changing an optimization option might modify the evaluation order. Even changing the operating system might change the evaluation order (since argument order is dictated by the ABI, which indirectly influences the evaluation order). No sane C program relies on a specific evaluation order.

For OCaml, the situation is slightly more fuzzy, since there is only one compiler, it is not that optimizing, and it does not quite respect the system ABI. So, the evaluation order happens to be a lot more stable. Yet, just going from native code to bytecode might change the evaluation order. So, hopefully, no sane OCaml program relies on a specific order.

**Comment by silene** [comment]
By the way, when C compilers detect that some code depends on the evaluation order, they warn about it:
```
a.c: In function ‘f’:
a.c:1:28: warning: operation on ‘x’ may be undefined [-Wsequence-point]
    1 | int f(int x) { return x + x++; }
      |                           ~^~
```

**Comment by SkySkimmer** [comment]
We had an execution order bug on code looking like `!sigma, effectful_call sigma`.

**Comment by herbelin** [comment]
> We had an execution order bug on code looking like !sigma, effectful_call sigma.

... and not only once.

Talking about `map`, I'd bet that the following kind of code is quite common in the wild:
```
let rec map f = function [] -> [] | a :: l -> f a :: map f l
```

**Comment by herbelin** [comment]
> Who was saying that the vm is call-by-value

Comment for myself: the vm itself follows a call-by-value evaluation strategy (for call-by-name equational theory), it is only the compiler which pre-expands the explicit beta-redexes and let-ins whose associated variable syntactically occurs at most once.

In particular, there is no "reordering" if `a`, `b` and `c` would occur more than once in the initial code above.

Also, in #12947, what does the compiler is to compile as if it were:
```
Definition foo (n : positive) :=
  let a := make 2 0 in
  let a' := reroot a in
  Pos.iter (fun v => v + get a1 0) (get (Pos.iter (fun b => set b 1 1) a 100000) 0) n.
```
i.e. no reordering properly speaking, only an inlining of variables occuring once.

This is governed by the `optimize` flag of `lambda_of_constr`.

**Comment by silene** [comment]
> This is governed by the `optimize` flag of `lambda_of_constr`.

Note that `optimize` does a lot more than just that. For example, it turns beta redexes  (which are exceedingly slow to evaluate) into let-in constructs. It also eliminates let-ins that are binding expressions that are already values.

**Comment by SkySkimmer** [comment]
>for call-by-name equational theory

What makes it cbn?

**Comment by ppedrot** [comment]
@SkySkimmer Thankfully if `t ≡β u` then the VM will say that `t` and `u` are convertible.

**Comment by herbelin** [comment]
> Note that optimize does a lot more than just that.

Indeed, I should have made it clearer.

> What makes it cbn?

A state of the machine blocking on a variable, such as`< x | E · E' >` for `E` an applicative stack and `E'` the non applicative continuation of the stack, is reified into an expression `E[x]` which is then treated as a value to be given to `E'`, i.e. continuing with `< E[x] | E' >`. This is essentially a cbn reduction rule.

This is implemented by binding free variables to a piece of code which captures the applicative stack and build a "value" `E[x]` out of it.

Talking from memory (maybe the details are a bit different).

**Comment by SkySkimmer** [comment]
Isn't that about a specific implementation of the theory?

**Comment by ppedrot** [comment]
This is straying far from the original discussion. I just wanted to rehighlight my position: programming in call-by-name in a bad idea, and hoping the compiler is not introduce exponential blowups is even worse. The only way to do that is to be very defensive and rely on pattern-matching everywhere so that it introduces sequentialization in a systematic way.

**Comment by herbelin** [comment]
Should close this? Or providing a way to more fine-grainedly "optimize" the vm code?
