### ISSUE TITLE
Error: "test-suite/misc/deps/\316\261\316\262/\316\263\316\264.v": No such file or directory

### ISSUE THREAD

**Issue by silene** [coq/coq#13437]
I just tried to run `opam pin add coq .` into Coq's repository and it instantly fails with

    # command ... dune subst
    # exit-code   1
    # ...
    ### output ###
    # Error: "test-suite/misc/deps/\316\261\316\262/\316\263\316\264.v": No such
    # file or directory

Dune does not like the file names of Coq's testsuite. Have people been able to use it in practice?

**Comment by ejgallego** [comment]
Oh that's the combination of https://github.com/ocaml/dune/issues/3219 and https://github.com/coq/coq/pull/13374 :+1: 

`dune subst` is broken with unicode files (fixed in dune's master) , and after #13374 we generate opam files automatically so `dune subst` is added to the opam file [before we didn't which was a way to workaround the bug]

I'll add a workaround to our opam files until we bump the dune version.

**Comment by ejgallego** [comment]
So indeed the bug has been in place for a few days, yes we use it in practice even in the CI, but somehow this problem was not caught.

**Comment by Zimmi48** [comment]
AFAIK, the bug has been fixed by removing the `dune subst` invocation from the opam file.

**Comment by silene** [comment]
For reference, it is pull request #13572.
