### ISSUE TITLE
String notations and primitive arrays

### ISSUE THREAD

**Issue by f-fries** [coq/coq#13484]
#### Description of the problem

Currently, parsing a string notation will fail if the produced term is not "ground" (made up of inductive types, constructor applications or primitive integers):

`Unexpected term [|97;98;99 | 0 : int |] while parsing a string notation.`

 Would it be possible to extend that criterion to include primitive arrays?

#### Coq Version

Version 8.13+alpha (November 2020) compiled on Nov 11 2020 14:05:43 with OCaml 4.07.1

**Comment by herbelin** [comment]
> Would it be possible to extend that criterion to include primitive arrays?

No idea, probably @proux01 or @JasonGross would know more about it.

**Comment by proux01** [comment]
Probably, would you have a concrete example?

**Comment by f-fries** [comment]
The use case that I have in mind is a string type based on arrays:
```coq
Inductive nstring := mk_str (_ : array int).

Definition to_byte_list '(mk_str a) :=
    (fix go (n : nat) (i : int) (acc : list byte) :=
        match n with
        | 0 => acc
        | S n => go n (i - 1) (cons (i63_to_byte a.[i]) acc)
        end) (nat_length a) (length a - 1) nil

Definition from_byte_list (xs : list byte) := 
    let arr := make (list_length_i63 xs) 0 in
    mk_str ((fix go i xs acc := 
        match xs with
        | nil => acc
        | cons x xs => go (i + 1) xs (acc.[i <- i63_from_byte x])
        end) 0 xs arr)

String Notation nstring from_byte_list to_byte_list : nstring_scope.
```

**Comment by proux01** [comment]
Thanks, I'll have a look.

**Comment by f-fries** [comment]
Thank you!

**Comment by JasonGross** [comment]
I think you just need to update
https://github.com/coq/coq/blob/7f3c46acc937eb9257c29b5881e5a8b17b28cd48/interp/notation.ml#L694
and
https://github.com/coq/coq/blob/7f3c46acc937eb9257c29b5881e5a8b17b28cd48/interp/notation.ml#L714
to have similar support for primitive arrays and then update the documentation as mentioned in
https://github.com/coq/coq/blob/7f3c46acc937eb9257c29b5881e5a8b17b28cd48/interp/notation.ml#L626-L634

**Comment by fakusb** [comment]
Just to make sure it is written explicitly in this issue: It would be nice to both parse and print things that contain Primitive arrays.

**Comment by fakusb** [comment]
I created a test case for what I expect this feature would satisfy:
https://github.com/fakusb/coq/commit/6be44850ef25c5b149fd5680a861f9ffd9d35319

**Comment by fakusb** [comment]
I got the parsing to work, but not the printing 7e332761085a65bb9697d8fcd3f7b3c916adcecd .
I'm not sure why printing does not work to be honest.

I thought a bit more and I think that maybe one wants to support a third kind of string notation besides `list byte` and `byte`, namely `array byte`, as it seems rather silly that there now are somewhat efficient arrays in coq, but printing still must always build a list.

**Comment by JasonGross** [comment]
I don't have a good idea of how to debug printing not working; you'll probably have to either step through the code in a debugger, do printf-debugging, or else somehow get the error messages raised during printing of numeral and string notations to be displayed rather than silenced.  Perhaps @proux01 or @herbelin will have debugging suggestions.

As for handling `array byte` directly, you'll need to update
https://github.com/coq/coq/blob/7f1b4176d2606cc965adc09ce5e8346663980240/plugins/syntax/string_notation.ml#L64-L78
and
https://github.com/coq/coq/blob/7f1b4176d2606cc965adc09ce5e8346663980240/interp/notation.mli#L150-L152
(as well as all the pattern matches made incomplete by adding an `ArrayByte` type).  Note that you'll need to handle the case where the module declaring primitive arrays has not yet been loaded by guarding with `Coqlib.has_ref`, as in https://github.com/coq/coq/blob/7f1b4176d2606cc965adc09ce5e8346663980240/plugins/syntax/number.ml#L76
Finally, you'll have to register the primitive array type for coqlib around https://github.com/coq/coq/blob/7f1b4176d2606cc965adc09ce5e8346663980240/theories/Array/PArray.v#L5 as is done at https://github.com/coq/coq/blob/7f1b4176d2606cc965adc09ce5e8346663980240/theories/Numbers/Cyclic/Int63/Int63.v#L29
As you can see, there's a lot more work to be done here, so you might decide it's not worth the effort.

**Comment by fakusb** [comment]
Thanks @JasonGross for all the pointers. I think that with #13519, one could now define a string notation for `array int` or `array bite ` in ocaml to avoid translation to lists if one wants to.

**Comment by xavierleroy** [comment]
@fakusb : I'm interested in this reimplementation of strings as native arrays of native integers.  Did you continue your experiments?  Any code you'd be willing to make public?

**Comment by fakusb** [comment]
We did not really work on a re-implementation of the while string library, but just used native arrays of native integers as representation of strings in a development.
The experiment is here, and we are currently not working on it: https://github.com/f-fries/metacoq/blob/native_idents/template-coq/theories/utils/MCNativeString.v

**Comment by xavierleroy** [comment]
That's an interesting example of using arrays.  Thanks for putting it online!
