### ISSUE TITLE
Document pattern matching with ?x in `change` tactics

### ISSUE THREAD

**Issue by fakusb** [coq/coq#13561]
#### Description of the problem

The change tactic can find patterns and reuse them on the right hand side:

`change (f ?x ?y) with (g (x, y))` or `change (fun x => ?f x) with f`

It would be nice to mention or document this very useful feature in the doc. Are there more places in tactics where this is possible?

#### Coq Version
master

**Comment by herbelin** [comment]
@Zimmi48, @jfehrle: is this part of your plans or is it worth I do a PR?

**Comment by Zimmi48** [comment]
Since #13470 is already updating the doc of `change`, it could be done as part of this PR. However, it would be useful if you could answer to this question:

>Are there more places in tactics where this is possible?

I guess this is also the case of `replace`. Other ones?

**Comment by ppedrot** [comment]
The `replace` tactic doesn't let you that, for a good reason: it would break under binders.

**Comment by herbelin** [comment]
In my memory, the reason for `replace` not doing it is that `replace` is a `TACTIC EXTEND` and that there is no easy way to tell that the rhs depends on holes of the lhs at interpretation with `TACTIC EXTEND` infrastructure. I suspect that working under binder is acceptable (on the basis that the holes are considered under exactly the same spine of binders on both sides).

I think it would be natural that `replace` provides the pattern (with the appropriate care).

**Comment by jfehrle** [comment]
I can add a sentence like this in the last paragraph shown as part of #13444 

```:n:`@one_term` may contain pattern variables such as `?x` whose values which will substituted in :n:`@one_term__repl`, such as
in `change (f ?x ?y) with (g (x, y))` or `change (fun x => ?f x) with f` ```

This doesn't apply if there's just a single `one_term`, right?

![image](https://user-images.githubusercontent.com/1253341/101265687-42c89700-36fd-11eb-9427-5adc1263d474.png)

**Comment by herbelin** [comment]
> ```:n:`@one_term` may contain pattern variables such as `?x` whose values which will substituted in :n:`@one_term__repl`, such as in `change (f ?x ?y) with (g (x, y))` or `change (fun x => ?f x) with f` ```

I guess that there is the choice to say from the very beginning that this is a pattern, or to add in a second sentence that the term can also be a pattern. I don't know which is best.

If the second case, a possibility is: In the more general case, `@one_term` is a pattern that may contain pattern variables such as `?x` while `@one_term__repl` is a term that may refer to these variables (without a `?`) . All subterms of the goal that match the pattern `@one_term` are then replaced with the corresponding instantiation of `@one_term__repl`, as in `change (f ?x ?y) with (g (x, y))` or `change (fun x => ?f x) with f`.

> This doesn't apply if there's just a single `one_term`, right?

In this case, the term is not a pattern and, indeed, this does not apply.

**Comment by herbelin** [comment]
> I think it would be natural that replace provides the pattern (with the appropriate care).

@ppedrot:  I now see a way to implement it with `TACTIC EXTEND` and I'm a priori ready to spent a couple of hours on it, but is it really the direction we want to go? For instance, how easy or difficult would it be to implement such a `replace pattern with term` directly in `Ltac2`? In particular, do we already have all the needed components in Ltac2 available so that it could be done e.g. in one or two hours or would we first need to implement more Ltac2 components?

**Comment by jfehrle** [comment]
> I guess that there is the choice to say from the very beginning that this is a pattern

Perhaps.  Sometimes a description is more readable if it begins with the most common case rather than the most general case.  In academic writing it may be more common to give the fully general description first.  Théo and I are in the midst of revising the chapter (300+ lines changed so far).  How letting us work out the wording details in #13470?

> If the second case, a possibility is: In the more general case, `@one_term` is a pattern that may contain pattern variables such as `?x` while `@one_term__repl` is a term that may refer to these variables (without a `?`) . All subterms of the goal that match the pattern `@one_term` are then replaced with the corresponding instantiation of `@one_term__repl`, as in `change (f ?x ?y) with (g (x, y))` or `change (fun x => ?f x) with f`.

This has more words and is more specific but harder to read.  I think it doesn't add anything significant.  It's in an academic style rather than what's typical for a user manual.  The examples suggest the syntax in a way that's easier to grasp than a description in words.  At some point we'll have a good subsection that describes patterns in detail; this is a secondary repeat to remind the reader about pattern handling.

BTW, do these examples in the source tree introduce new existential variables?

- `change (0 = S ?x).`
- `change ((n, n0) = (S ?p, S ?p) /\ ?p = ?n).`
- `change (eq (A := ?C) ?x ?y) with (eq).`   (huh??)
- `change false with (1 <=? 0)%float.`  (What's the `?` by itself for?)

**Comment by herbelin** [comment]
> > If the second case, a possibility is: In the more general case, `@one_term` is a pattern that may contain pattern variables such as `?x` while `@one_term__repl` is a term that may refer to these variables (without a `?`) . All subterms of the goal that match the pattern `@one_term` are then replaced with the corresponding instantiation of `@one_term__repl`, as in `change (f ?x ?y) with (g (x, y))` or `change (fun x => ?f x) with f`.
> 
> This has more words and is more specific but harder to read. I think it doesn't add anything significant. It's in an academic style rather than what's typical for a user manual. The examples suggest the syntax in a way that's easier to grasp than a description in words. At some point we'll have a good subsection that describes patterns in detail; this is a secondary repeat to remind the reader about pattern handling.

OK, I let you judge. It might remain be important to say that rhs refers to the pattern variables w/o a `?` though.

> BTW, do these examples in the source tree introduce new existential variables?
> 
>     * `change (0 = S ?x).`

No. The `?x` is supposed here to refer to an existing existential variables, as in:
```
Goal exists x, 0 = S (0 + x).
eexists ?[x].
change (0 = S ?x).
```

>     * `change ((n, n0) = (S ?p, S ?p) /\ ?p = ?n).`

Idem.

>     * `change (eq (A := ?C) ?x ?y) with (eq).`   (huh??)

In the pattern (the lhs), there is no way to refer to an existing existential variables (unless it has an instance in which case we can say e.g. `?x@{y:=y}`. [This can probably be considered a design bug... At least, we should accept `?x@{}`...]

>     * `change false with (1 <=? 0)%float.`  (What's the `?` by itself for?)

Here, the `?` is part of the `<=?` notation, with the convention that the equality returns a `bool` (rather than to `Prop`).

**Comment by retzger77** [comment]
Spot on friend well done 🙏😎🙏
