### ISSUE TITLE
PR #13436 should be backported to Coq 8.12

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#13599]
#### Description of the problem

PR #13436 seems to fix an issue that breaks some notations displays in mathcomp for Coq 8.12 cf https://github.com/math-comp/math-comp/pull/674#issuecomment-733657891
Could you please backport it to Coq 8.12 ASAP?
_Originally posted by @CohenCyril in https://github.com/coq/coq/issues/13436#issuecomment-733653527_

FTR, PR #13473 ships an output test for this issue, and could be backported as well, for the sake of safety and completeness.

CC @ejgallego @Zimmi48 @gares 

#### Coq Version
8.12

**Comment by herbelin** [comment]
@CohenCyril: I believe that the reason you did not get answers to your initial comment is, as far as I could understand it in these days of fast release cycles, that the recommendation is to move to new versions (8.13 is coming soon) rather than spending (too much time) in maintaining older versions, and 8.12 is already considered old (at least, I've not heard about projects to release a 8.12.2 version, and, as can be observed, the milestone does not exist).

I don't know all the details of the pros and cons of the reasons, and probably someone can explain better, but I believe that this is before all a question of manpower. So, maybe, a compromise would be that you contribute by yourself to such kind of maintenance of older versions (and I may then also help so that you are not alone). In particular, if enough will can be found in this direction, it could be an opportunity to backport also the kernel-critical bugs, which I think are important to backport.

**Comment by herbelin** [comment]
PS: submitting a PR against the 8.12 branch would be easy, and I could do it if noone finds it is inappropriate. The difficulty then would be to do packages afterwards. As you could probably observe, the cost of releasing is quite high, with a lot of coordination needed and often painful tiny worries. So, if the ability for users to opam-install an `8.12.dev` package is sufficient for your case, this is an easy part.

**Comment by CohenCyril** [comment]
I believed like @gares that `8.12.2` could happen someday. However, given what you and @Zimmi48 said, since there was no plan to release an `8.12.2` and no intention to do it, I'm ok with a simple backport #13436 to coq 8.12 dev branch, so as to remember this was something to backport. I am not going to backport kernel-critical bugs, I do not have enough time for that. Anyway, if someone does it or if other reasons to do a `8.12.2` come up, the PR we discuss here would already be ready for it if we merge it in the 8.12 branch as you suggested, and otherwise, well, never mind.

I certainly do not have the time to make a release either, except maybe if packaging becomes more automated someday...

**Comment by Zimmi48** [comment]
FTR I've added earlier today the question of releasing an 8.12.2 version to the topics of the next Coq Call.

**Comment by herbelin** [comment]
> except maybe if packaging becomes more automated someday...

That's the big issue! But a lot of things moving continuously on their side (gtk, brew, WSL, OS X, opam, and so on, and so on) in addition to our own changes, new surprises seem to come every time.

Retrospectively, the ability of our respective CIs to catch issues has never been as powerful. It seems to me that it is mostly that the scale changed. We automatize much more things, but there is a still a fringe where we have to intervene manually.

Leaving generalities aside, I'm ready to make a PR against 8.12 for this issue whenever I've got a signal from the 8.12 maintainers.

**Comment by ejgallego** [comment]
At the very least we can do a 8.12.2 that is source-only [opam will work] if we hit problem with the win/mac packaging.

**Comment by Zimmi48** [comment]
The backporting activity itself is trivial when there are no conflicts (which was the case for this PR). I've prepared #13604, which is testing things with CI, and then I'll push this backport to v8.12.

As I've said before to Cyril, the reason that his message was not answered is simply that it was not noticed by the RMs. Usually, RMs do not need to watch for all PR comments because a milestone will be used to signal the request for backporting, but in this case, there was no 8.12.2 milestone indeed, simply because there was no plan for a new release (because 8.13 was around the corner).

Releasing a source-only version (i.e. tagging and letting opam maintainers create a package) would be easy for us. Releasing unsigned packages would be easy as well if the infrastructure was not breaking again (it seems it is on Windows, but a platform release for 8.12 is planned for very soon anyway). Signing the packages requires some effort, but still reasonable.

When the packaging infrastructure is working, releasing patch-level frequently is not that difficult. I personally regret not releasing 8.12.1 earlier with fewer fixes. This would have allowed another feedback cycle and we could have released a more polished 8.12.2 by the time we released 8.12.1.

**Comment by Zimmi48** [comment]
FTR, it was decided that there will be an 8.12.2 release, which will include #13436, the test from #13473 and #13468. At least the latter was a fix resulting of the feedback we got on 8.12.1, demonstrating the usefulness of shortening the feedback cycle.

If there are other important fixes to backport, do not wait to call me out, because it won't be long before we put the tag.
