### ISSUE TITLE
Efficiency of representing local contexts

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13709]
Two thoughts.  First: I expect local contexts have more and more entries as you proceed from the top-level goal to its subgoals an so forth.  Is there a reasonable rule for determining when a hypothesis or variable is no longer relevant to the goal and can thus be removed?  For example, the variable definitions `PI`, `a` and `c` below are not relevant to `P` in that there's no longer a way to relate P to those variables.  (I'm not sure if 2 otherwise irrelevant hypotheses that contradict each other, e.g. x = 0 and x = 1 would pose a problem.  I don't know if that's possible or common.  Maybe that would only occur if `False` is provable.)

![image](https://user-images.githubusercontent.com/1253341/103450668-689a7a80-4c6e-11eb-9a9c-6809016906f8.png)

Perhaps it would be interesting to measure how many items are in the local contexts and their sizes for, say, #13576.
Another angle would be if proof scripts could explicitly clear hypotheses based on knowledge of the proof--provided that it's worth the trouble.

Second thought is that if local context is a list to which new items are added at the end, the linked list will need to be rebuilt for each added item (though the entries can be shared).  But the lists would have to be mighty long for this to be noticeable in execution time.

@ppderot @JasonGross Does this make any sense?

**Comment by silene** [comment]
> I'm not sure if 2 otherwise irrelevant hypotheses that contradict each other, e.g. x = 0 and x = 1 would pose a problem. I don't know if that's possible or common.

That is extremely common. It happens whenever you perform a proof by contradiction. It also happens when you do some case analysis, since some cases imply the consequent, while some others usually contradict the antecedents. As a matter of fact, the standard library contains about 500 occurrences of `exfalso` and `contradict`. (There are a lot more tactics that can be used to perform proofs by contradiction. For example, there are 3300 occurrences of `elim`, but it is hard to tell at first glance which ones are actually proofs by contradiction.) Automatically clearing the local context would be disastrous.

That said, if you have several variables that have the exact same type and they do not appear in dependent position (neither in the goal, in the local context, nor in the global context), then you can eliminate all of them except for one. Moreover, if you can prove that this type is inhabited, then you can safely remove the last one too. So, in your example, `a` and `c` appear nowhere else and they are member of an inhabited type, so they can be removed without endangering the proof. But I am not sure how often such a situation happens.

As for `pi` in your example, it can always be safely removed. But whether it is useful is another matter. For example, it would be awful to remove `pi` right after the user typed `set (pi := 3)`. So, guessing when a let-in binding is no longer useful would require a bit of mind reading.

**Comment by jfehrle** [comment]
OK, thanks.  Determining whether the hypotheses contradict each other must be undecidable.  So this appears to be a dead end.
