### ISSUE TITLE
rewrite at vs. setoid_rewrite at

### ISSUE THREAD

**Issue by AndrewTolmach** [coq/coq#13728]
#### Description of the problem

The documentation for `rewrite...at` says:

"The rewrite is always performed using setoid rewriting, even for Leibniz’s equality, so one has to Import Setoid to use this variant."

So the following different in behaviors is surprising:

```
apt@growlier:~/working/courses/510coq$ coqtop
Welcome to Coq 8.12.2 (December 2020)

Coq < Require Import Setoid.

Coq < Require Import PeanoNat.

Coq < Goal (1 + 2) + (3 + 4) = (2 + 1) + (3 + 4).
1 subgoal
  
  ============================
  1 + 2 + (3 + 4) = 2 + 1 + (3 + 4)

Unnamed_thm < rewrite Nat.add_comm at 2. 
Toplevel input, characters 0-25:
> rewrite Nat.add_comm at 2.
> ^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Tactic failure: Nothing to rewrite.

Unnamed_thm < setoid_rewrite Nat.add_comm at 2.
1 subgoal
  
  ============================
  2 + 1 + (3 + 4) = 2 + 1 + (3 + 4)

Unnamed_thm < 
```

At the least, the documentation seems misleading. But it would be much nicer if the system did behave
as the documentation implies, i.e. `rewrite at` and `setoid_rewrite at` behave identically. 

#### Coq Version
8.12.2.

**Comment by gares** [comment]
Cc @coq/doc-maintainers

**Comment by Zimmi48** [comment]
Thank you for the feedback! The explanation is that the setoid rewriting implementation is used in this case, but there are still differences of behavior between the two tactics `rewrite` and `setoid_rewrite` due to some parameters being tuned differently (probably mainly for compatibility reasons).

Just for your information, we have recently improved the doc of the rewrite tactic. See here for the new version: https://coq.github.io/doc/v8.13/refman/proofs/writing-proofs/rewriting.html. Let us know if you have additional feedback (also PRs are welcome if you see how to improve things).

**Comment by Zimmi48** [comment]
@AndrewTolmach We're adding more details on why `at` is behaving that way with `rewrite` in #13789.
