### ISSUE TITLE
Modules are allowed to be closed with remaining open proofs

### ISSUE THREAD

**Issue by olaure01** [coq/coq#13755]
#### Description of the problem

The following code is accepted in `Coq 8.13.0`:
```coq
Module M1.
Lemma t1 : True.
End M1.
Proof. exact I. Qed.
```
The behavior in `Coq 8.12.2` looks more natural : `Command not supported (Open proofs remain)` at `End M1.`.

This leads to `Anomaly` messages in `coqide` and `coqtop` for the following code:
```coq
Module Type Typ.
  Parameter Inline(10) t : Type.
End Typ.

Module M2 (A : Typ).
Lemma t2 (a : A.t) : True.
End M2.
(* in coqide 8.13.0:
Anomaly "Uncaught exception Not_found."
Please report at http://coq.inria.fr/bugs/.
Module M2 is defined
*)
(* in coqtop 8.13.0:
Module M2 is defined
*)

Proof. exact I. Qed.
(* in both coqide 8.13.0 and coqtop 8.13.0:
Anomaly
"File "clib/int.ml", line 46, characters 14-20: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
*)
```

#### Coq Version

Coq 8.13.0 (no issue with 8.12.2)

**Comment by SkySkimmer** [comment]
54788df72ce79998ee27db362401a56bda4daceb is the bad commit
VtNoProof for the `End` command was replaced by VtReadProgram which ignores proof state instead of erroring

The typed_vernac system was really only designed for the proof state, adding the orthogonal program state is pretty messy.

**Comment by SkySkimmer** [comment]
cc @ejgallego

**Comment by gares** [comment]
This can go to 8.13.1

**Comment by ejgallego** [comment]
> VtNoProof for the `End` command was replaced by VtReadProgram which ignores proof state instead of erroring
> 
> The typed_vernac system was really only designed for the proof state, adding the orthogonal program state is pretty messy.

Actually the idea was to merge all the tree proof states (*) into one, so that was meant as only a temporary state while doing the refactoring; I did some progress on handling scoping [section/modules] tho, but meanwhile we can just add the NoProof check on closing section / module, which is IMHO a big deal.

(*) the 3 ways we have now are: regular proof state [with things such as mutuals], dependent proof state (as used by equations) , obligations.

**Comment by ejgallego** [comment]
After writing the fix, indeed some part of the problems we have with the current state of affairs with the command representation are IMHO due to us being forced to enforce the static "opens/doesn't open" proof in the runtime layer, which is indeed too restrictive as this layer has not problem actually running the commands as it was done in the first version of the PR :( :(

**Comment by ejgallego** [comment]
Been thinking a bit more about this, and indeed it seems very unfortunate to me that the scoping of for example, interactive proofs is totally separate from the scoping of say sections or modules. It would help in many uses cases [specially when writing stuff such as document manager / incremental document processors] to actually have a unified notion of scope.

cc: @SkySkimmer , any thoughts?
