### ISSUE TITLE
Improve the "Conversion rules" documentation

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#13811]
The documentation lacks understandable definitions of beta, delta, iota and zeta reduction in language that will be understood by Coq users who are not intimately familiar with CIC theory.  These are essential concepts.  They need to be explained precisely and clearly using Coq syntax rather than mathematical notation (or perhaps in addition to mathematical notation) with some concrete examples that use Coq's reduction tactics.

The significance of eta-expansion is unclear.  If it's an important concept that users need to understand, it should be explained clearly, too.  The text mentions βδιζη-convertible, including eta.

Not sure what to make of the "Convertibility" section.  If it can be simplified and made more understandable to non-CIC experts that would be good.

Attn: @JasonGross

**Comment by jfehrle** [comment]
Also I'd like to understand and describe the `red_flag` values `match`, `fix` and `cofix`.

**Comment by JasonGross** [comment]
I'm not sure how to help with this issue because the notions are very clear to me, and I'm not sure what's confusing.  Perhaps if you take a stab at an explanation leaving blanks for the things you're unsure about, I can help improve and fill them in?

> The significance of eta-expansion is unclear.

Consider:
```coq
Definition compose {A B C} (g : B -> C) (f : A -> B) (x : A) : C := g (f x).
Infix "∘" := compose (at level 70).
Definition id {A} (x : A) := x.
```
Given `A`, `B`, and `f : A -> B`, we want `f ∘ id = f` and `id ∘ f = f`.  However, `f ∘ id` and `id ∘ f` reduce (under, e.g., `cbv`) to `fun x : A => f x`.  Without eta-conversion, there's no way to prove that this is equal to `f` without an axiom.

**Comment by jfehrle** [comment]
A quick example: only zeta will eliminate a `let in` construct, e.g.

```
Goal let i := 1 in i + i = 2.       (* let i := 1 in i + i = 2 *)
cbv zeta.                           (* 1 + 1 = 2 *)
```

I'd like to give a comprehensive list of reductions and associated Coq syntax that they operate on, with a reasonable number of examples.

Furthermore, you need the following to combine the `1 + 1`, which I think may deserve a bit more explanation:

```
cbv beta iota delta.  (* 1 + 1 = 2 *)
```

which could also be `cbv delta. cbv beta iota.`  But hard to explain without good definitions for the elementary reductions.

Does `lazy` stop after the first reduction is applied (while the others recur until no more reductions are possible)?

**Comment by JasonGross** [comment]
> I'd like to give a comprehensive list of reductions and associated Coq syntax that they operate on

- `zeta` eliminates `let`
- `match` eliminates `match`
- `fix` eliminates `fix` / `Fixpoint`
- `cofix` eliminates `cofix` / `CoFixpoint`
- `iota` is the same as `match fix cofix`
- `delta` eliminates `Definition`
- `beta` eliminates `fun`

Here are some examples:
- `zeta` you have an example for
- `match`: `Eval cbv match in match Some 1 with Some x => x | None => 0 end.`
- `fix`: `Eval cbv delta fix in Nat.add 1 1.`
- `cofix`:
```coq
CoInductive conat := coO | coS (_ : conat).
CoFixpoint inf : conat := coS inf.
Definition eta_conat (n : conat) := match n with coS n => coS n | coO => coO end.
Eval cbv delta beta in eta_conat inf.
(*      = match (cofix inf : conat := coS inf) with
       | coO => coO
       | coS n => coS n
       end
     : conat
*)
Eval cbv delta beta cofix in eta_conat inf.
(*      = match coS (cofix inf : conat := coS inf) with
       | coO => coO
       | coS n => coS n
       end
     : conat
 *)
Eval cbv delta beta match cofix in eta_conat inf.
(*      = coS (cofix inf : conat := coS inf) *)
```
- `delta`: any example with a `Definition` (or even a `Fixpoint` or `CoFixpoint`, which are really `Definition` + `fix`/`cofix`)
- `beta`: `Eval cbv beta in (fun x => x) nat.`


> Does `lazy` stop after the first reduction is applied (while the others recur until no more reductions are possible)?

No, the difference is only the order in which evaluation is run.  If you have `f x y z`, `cbv` will first weakly reduce `f` to, say, `f'`, then weakly reduce `x` to `x'`, then weakly reduce `y` to `y'`, then weakly reduce `z` to `z'`, and then will keep reducing in `f' x' y' z'` (for example, if `f'` starts with a lambda/`fun`, then there's more beta reduction to be done).  By contrast `lazy` will first reduce `f` to `f'`, then perform beta reduction in `f' x y z` if there is such, and only later on will it reduce `x`, `y`, and `z`.  This means that if you have something like
```coq
Fixpoint loop (x : nat) : unit
  := (fun _ => match x with
               | O => tt
               | S n => loop n
               end)
       (loop x).
```
(which is valid because the guard condition is modulo beta and hence does not care about unused let-bound terms), then `Eval cbv in loop 0.` will stack overflow / loop, because `loop x` will be reduced before beta reduction, but `Eval lazy in loop 0` will quickly return `tt`, because the first step is to beta reduce the application of the lambda, and hence `loop x` disappears before being evaluated because it is unused.  Note that both `cbv` and `lazy` work fine with
```coq
Fixpoint loop (x : nat) : unit
  := (fun _ => match x with
               | O => tt
               | S n => loop n
               end)
       (fun _ : unit => loop x).
```
because weak reduction stops when the term being reduced is headed by a lambda (or a blocked `match`, etc).  Note that when using the `cbv` strategy, being headed by an application of an opaque constant to function arguments *does not* count as weak-head normal form unless the arguments to that function are also in weak-head normal form.  (I believe this does not come up in the `lazy`, which does not put things in weak-head normal form until it needs to match on them or until they arrive in the head position.)  Hence the following also loops under `cbv`:
```coq
Axiom hold : unit -> unit.
Fixpoint loop (x : nat) : unit
  := (fun _ => match x with
               | O => tt
               | S n => loop n
               end)
       (hold (loop x)).
```
even though `loop x` is only a subterm of the argument to the function which drops its argument.

**Comment by JasonGross** [comment]
Btw, if you're looking for reference material to read on this, I think the following are good resources:
- https://github.com/HoTT/book/issues/995 and https://ncatlab.org/nlab/show/eta-conversion on eta
- https://ncatlab.org/nlab/show/beta-reduction
- chapter 1 (and perhaps appendices A.1 and A.2) of the HoTT book (https://homotopytypetheory.org/book/) for foundations of type theory / MLTT in general

**Comment by jfehrle** [comment]
The doc refers to "βδιζη-convertible", which IIUC includes eta _expansion_.  Is there a reason why cbv and the others don't have options for eta expansion?  (in 1-2 sentences max?)

**Comment by jfehrle** [comment]
Can you give a more realistic example for beta?  The following seems to get into a corner case that would distract rather than enlighten.

```
Goal (fun x => x) nat.
cbv beta.            (* nat *)
```

**Comment by JasonGross** [comment]
I'm not sure what corner-case you're talking about.  beta-reduction takes any application of a term starting with `fun` to any other term, and substitutes the argument into the body of the function.  Here's another example: `(fun x => x + x) 2` turns into `2 + 2` under beta reduction.

**Comment by JasonGross** [comment]
> Is there a reason why cbv and the others don't have options for eta expansion?

AIUI, it's just that no-one has bothered to implement it yet.  I requested this feature 8.5 years ago in #2860.

**Comment by jfehrle** [comment]
The corner case is explaining what the result `nat` means.  This is a bit more intuitive:

```
Goal (fun x => x) 2 = 2.
cbv beta.     (* 2 = 2 *0
```

**Comment by jfehrle** [comment]
What is short phrase (5-6 words max) that describes the purpose of eta-expansion?  (Akin to `match`: eliminates `match`.)

**Comment by JasonGross** [comment]
Eta-reduction/contraction eliminates needless function abstraction.  Eta-expansion forces function terms to be headed by explicit abstractions (function nodes)

**Comment by JasonGross** [comment]
Alternatively: eta-expansion inserts as many fun nodes as possible without creating any beta redexes.
