### ISSUE TITLE
coq_makefile not producing valid paths for native objects under Cygwin

### ISSUE THREAD

**Issue by t6s** [coq/coq#13827]
#### Description of the problem
Under Cygwin + OCaml-mingw64, I built Coq-8.13 (from github branch) with native-compiler turned on.  Then I tried to install MathComp-1.12.0. The build was successful, but `make install` failed:

```
$ make install
/usr/local/coq-8.13-github/bin/coq_makefile  -f Make -o Makefile.coq
make -f Makefile.coq --no-print-directory install
algebra.coq-nativeNmathcomp_algebra_all_algebra.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_finalg.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_countalg.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_fraction.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_intdiv.cmi does not exist
algebra.coq-nativeNmathcomp_algebra_interval.cmi does not exist
```

The problem seems to be at the definition of  `vo_to_obj` in `<coq root>/tools/CoqMakefile.in`:
```
vo_to_obj = $(addsuffix .o,\
  $(filter-out Warning: Error:,\
  $(shell $(COQTOP) -q -noinit -batch -quiet -print-mod-uid $(1))))
```
where the path returned by `coqtop -print-mod-uid` contains single backslashes which are unfortunately trimmed at somewhere in the later stages and are not available when the path is used at `make install`.

I applied a quick fix using `cygpath` as this:
```
vo_to_obj = $(addsuffix .o,\
  $(filter-out Warning: Error:,\
  $(shell $(COQTOP) -q -noinit -batch -quiet -print-mod-uid $(1) | cygpath -f -)))
```
Although this worked, this is too specific to my use-case and I could not figure out a nice generic solution.

#### Coq Version

The tools and settings are:
- Windows 10
- Cygwin for shell and unix tools
- OCaml-mingw64, manually compiled
- Coq-8.13, manually compiled with ./configure -local -native-compiler yes
- MathComp 1.12.0, manually compiled

**Comment by gares** [comment]
@MSoegtropIMC shouldn't we put all paths spit by coqc -config in cygwin's -m format ? I just realized c:/foo/bar is valid in windows even without cygwin.

**Comment by MSoegtropIMC** [comment]
I would recommend to work with forward slashes on Windows - working with \ is very hard to get right. This does work since DOS days btw. The C level OS functions did always understand forward slashes and backward slashes as path separators. The issue was always (and still is) that DOS command line programs have issues with this, because they use / to signal command line arguments, so a leading / can lead to fairly arbitrary - including dangerous results. Say if you give a file named `/S` to `del` you might not get what you want. If one does use /, one either has to stay away from `CMD` (as in cygwin, but take care of calling MinGW programs which might call CMD) or avoid absolute paths starting with / - better both.

Makefiles on Windows might call CMD and DEL and so on, so please be sure to double check this.
