### ISSUE TITLE
Feature Request: variant of hnf that runs on reduction engines other than simpl

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#13881]
I would like to be able to tell `cbv`, `cbn`, `lazy`, `vm_compute`, and `native_compute` to not recurse under binders after they reduce the term to weak-head-normal-form.  Ideally, I'd also be able to tell `lazy` whether or not to recurse into arguments of an application (or other non-function-like construction) after getting to weak-head-normal-form.  This would be useful for, e.g., evaluating something in the way that extraction would evaluate it, or for debugging computation gone wrong, because it allows setting a natural class of intermediate stopping points.

**Comment by ppedrot** [comment]
For `cbv`, `cbn` and `lazy` it's easy to do since the base operation is actually to perform a weak-head reduction. We call it recursively in the exposed user primitive.

For the VM and native I don't think it is possible, due to the way these reduction mechanisms work. They are NbE algorithms and by construction once you've sent something into the semantic world the only thing you can get out of it is a normal form.

**Comment by JasonGross** [comment]
I would be quite happy having this even just for `cbv`, `cbn`, and `lazy`.  Either as an extra flag for the reduction strategies (`cbv only_weak_head ...` or something) or as a separate user primitive (`hnf_cbv`, etc).

Re VM and native: oh, that's interesting.  I wonder if, once these mechanisms support blacklisting/whitelisting constants, there'd be a way to forbid just delta reduction under remaining lambdas?  (I'm not sure how delta fits with the NbE picture.)

**Comment by silene** [comment]
For `vm_compute`, I don't think it would be that complicated, at least not conceptually. The way it currently works is that it takes any remaining lambda-abstractions, apply them to dummy opaque arguments, and give them back to the bytecode interpreter in turn. More precisely, the lambda-abstractions directly come from the original term but their free variables are reduced values. But there is no reason to give the lambda-abstractions back to the bytecode interpreter, we could give them (or rather their original Gallina counterpart) to any other reduction engine. The free variables being already reduced, it is not difficult to retrieve them and pass them to another reduction engine.

**Comment by SkySkimmer** [comment]
cf https://github.com/coq/coq/pull/17503, although the cbv machine doesn't have a weak mode so not sure if it should count as closing this issue.

**Comment by Janno** [comment]
I was skimming the original `vm_compute` paper recently and it seemed to me that it is somewhat weak by default with extra steps added to traverse into subterms. Is that correct? In that case, it might be very easy to disable those extra steps. I rely heavily on weak head normalization in the automation code I write and the performance of the kernel's weak head normalization code is somewhat lackluster (though I can't really qualify this further). I wonder if a weak `vm_compute` would perform better.

**Comment by JasonGross** [comment]
> cf #17503, although the cbv machine doesn't have a weak mode so not sure if it should count as closing this issue.

I think this issue is still open: I would still like to see `cbv` reduce until the whnf contains only lambda arguments, and it sounds like @silene is claiming that the vm can be adjusted to support a similar mode.  (What about native?)

Moreover, I wouldn't be surprised if adding support for this sort of mode to vm casts made them more useful; my model is that we want the vm on ground terms and kernel conversion on unreduced terms under lambdas, so this might allow the productive use of vm casts even on terms with free variables, etc.

**Comment by JasonGross** [comment]
> . I rely heavily on weak head normalization in the automation code I write and the performance of the kernel's weak head normalization code is somewhat lackluster (though I can't really qualify this further). I wonder if a weak `vm_compute` would perform better

@Janno I would be interested in splitting apart the following possible cases:
1. The whnf reduction itself is slow
2. The reduction is fine, but the resulting term loses sharing and hence is larger than it needs to be for future computations
3. The resulting term is in fact quite large (due to bare fixpoints, etc), sharing would not make it smaller

I'm not quite sure how to split these apart, though.

Assuming that your use is evaluating the Mtac2 monad, and that this is sufficiently similar to how MetaCoq template monad evaluation works, perhaps another avenue for speeding up reduction is seeing if some support can be added for locally attaching custom reduction behavior to constructors, a la https://github.com/coq-community/reduction-effects/blob/master/redeffect.mlg, so that you can invert the control flow and run the entire program in a single call to reduction.

**Comment by Janno** [comment]
> Yes, but see my previous message.

I hadn't scrolled up properly. Sorry for the noise!

> Assuming that your use is evaluating the Mtac2 monad, [..]

Mtac2 would also benefit from weak `vm_compute`, I think. Mtac2 has some odd corner cases, though, such as needing to stop at let bindings to make sure our `let .. := reduce .. in ..` construct doesn't get reduced incorrectly. Also, just the fact that Mtac2 is call-by-name complicates the picture quite a bit. Together with the fact that reduction effects are documented to trigger only in *some* reductions (I doubt weak head reduction is one of them) I fear it might not actually benefit us.

> @Janno I would be interested in splitting apart the following possible cases:

My current use case is actually unrelated to Mtac2. The code I work on forces terms a lot (in the proof term) for Qed efficiency. To keep track of the terms at the tactic level I use weak head reduction to perform the forcing. This way I only need to write a single Gallina definition that can perform the computation both in the proof term as well as at the tactic level.

It's that weak head reduction in tactic code that I find to be too slow sometimes. So that would put my problem in category (1) in your list. And by "too slow sometimes" I mean that relatively small terms might take 3ms to reduce. It's too little time to warrant a thorough investigation but too much time given that similarly sized reductions with other terms finish in 1ms.

**Comment by herbelin** [comment]
> cf #17503, although the cbv machine doesn't have a weak mode so not sure if it should count as closing this issue.

The `cbv` strategy also got a weak mode (#18190), so probably can we close the request. If some important points of the discussion are worth being highlighted, it will still be possible to summarize them below.
