### ISSUE TITLE
cbn very slow on functions constructed using `decide equality`

### ISSUE THREAD

**Issue by Janno** [coq/coq#13896]
#### Description of the problem

The code below should illustrate the issue.

```coq
Inductive type : Set :=
    Tptr : type -> type
  | Tref : type -> type
  | Trv_ref : type -> type
  | Tint : type -> type -> type
  | Tvoid : type
  | Tarray : type -> type -> type
  | Tnamed : type -> type
  | Tfunction : type -> type -> type -> type
  | Tbool : type
  | Tmember_pointer : type -> type -> type
  | Tfloat : type -> type
  | Tqualified : type -> type -> type
  | Tnullptr : type
  | Tarch : type -> type -> type.
Definition type_eq_dec : forall (ty1 ty2 : type), { ty1 = ty2 } + { ty1 <> ty2 }.
Proof. fix IHty1 1.  decide equality. Defined.

Goal (if type_eq_dec (Tptr Tvoid) (Tptr Tvoid) then True else False).
  Fail Fail time lazy.          (* 0.0s *)
  Fail Fail time cbv.           (* 0.s *)
  Fail Fail time vm_compute.    (* 0.s *)
  Fail Fail time simpl.         (* 0.25s *)
  Fail Fail time cbn.           (* 3.5s *)
```
`simpl` already takes measurable time but still runs circles around `cbn`. Is there anything that can be done about this?

#### Coq Version
8.13.0

**Comment by ppedrot** [comment]
Looks like an actual algorithmic problem. `cbn` is quite complex, I don't know if there is a fix that does not change the semantics while resolving the underlying problem. Also, it seems that `simpl` is faster on this example on master (a5bea627d1fe742229497b466ca24b470c20d269).

**Comment by Janno** [comment]
I'd love to use `simpl` but it computes too much in several instances (ignoring `Arguments` annotations) so I don't have much of a choice here.

Should I be investing in a custom reduction machine?

**Comment by JasonGross** [comment]
If you want performant reduction, you should not use `simpl`/`cbn`.  Instead arrange your code so that you can call `lazy`/`cbv` with a whitelist or blacklist (and if you need super-fast reduction, put everything in a module functor parameterized over the definitions you want in your blacklist, so you can use `vm_compute` inside the module functor).

**Comment by Janno** [comment]
> If you want performant reduction, you should not use simpl/cbn. Instead arrange your code so that you can call lazy/cbv with a whitelist or blacklist

I was under the impression that `lazy` and `cbv` reduce indiscriminately, i.e.  they will unfold definitions in the whitelist (or not in the blacklist) even if their reduction doesn't lead to "useful" terms (whatever that may mean). We already use `lazy` with whitelists whenever we actually have a closed set of terms to reduce *all the way* but that is very rarely the case. In general our tactics need to be able to deal with `type_eq_dec Tvoid Tvoid` (by reducing it) as well as `type_eq_dec some_variable Tvoid` (by leaving it *exactly* as it is) as well as `type_eq_dec user_defined_term Tvoid` (by honoring the `Arguments` governing `user_defined_term`).

`cbn` (and, to a lesser degree `simpl`) offers this functionality but I am not aware of any other extensible (e.g. through `Arguments`) approach. Even with the support for `Arguments` we cannot fine-tune the reduction the way we want to.

**Comment by JasonGross** [comment]
Indeed, Coq doesn't currently have any performant mechanism for partial reduction.  I built a reflective framework for performing this sort of partial reduction (though it doesn't handle dependent types) in [this draft paper](https://people.csail.mit.edu/jgross/personal-website/papers/2021-rewriting-popl-draft.pdf) (GitHub [here](https://github.com/mit-plv/rewriter)).  The reduction strategy is to use NbE for β-reduction with rewrite rules at the leaves for ιδ-reduction, and to lift let-binders rather than perform ζ-reduction.  There's a similar strategy for evaluation at [this paper about Isabelle/HOL: A Compiled Implementation of Normalization by Evaluation, by Klaus Aehlig, Florian Haftmann, and Tobias Nipkow](https://www21.in.tum.de/~nipkow/pubs/tphols08.html).  I suspect that this NbE+rewrite rules is in fact the way to go for performant reduction-like behavior.  (I've found that `rewrite_strat` isn't quite configurable enough in the strategy it uses to walk the term and perform reductions, though it's possible that on relatively small examples it'll work fine.)

**Comment by ppedrot** [comment]
I've had a deeper look at the issue, and contrarily to what I've said the culprit is likely not cbn itself, but rather the naive algorithm for `Termops.replace_term`. It's kind of well-known but this is algorithm is quadratic (or maybe even cubic), due to the way binder are handled. The cbn tactic is not the only one suffering from it, but this example is hitting right where it hurts. I already thought a bit about how to tweak this but it's kind of linked to the crazy function we use to check for equality of terms and it's a dangerous area.
