### ISSUE TITLE
Redefine Ltac2 with `::=`?

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#13970]
I know that I can redefine an Ltac2 with `Ltac2 Set` if I added `mutable` in the original definition:

```coq
Ltac2 mutable foo () := Message.print (Message.of_string "implementation 1").

Ltac2 Set foo := fun () => Message.print (Message.of_string "implementation 2").
```

However, it would be nice if I could also redefine an `Ltac2` that was not defined with `mutable`, by using `::=`, like in Ltac1.
The use case I have in mind is to patch existing libraries without recompiling, for debugging and quickly trying out new ideas without having to wait until a whole project has recompiled, and without having to copy-paste all the definitions of the call stack leading to the definition I want to override.

Coq version: 8.13.0

**Comment by ppedrot** [comment]
I deeply believe this is an anti-feature of Ltac1. While I understand the advantage of monkey-patching in a script language, it also nudges users into writing messy code and breaking the invariants of a tactic library. If we want to move to a model where people can develop reliable tactic libraries that can be used at scale, we just can't let end-users poke into their internals.

Since the library writer has full control, I'd simply recommend that you wrap everything you want to play with inside a mutable reference. (As a nice side-effect, it also forces you to consider seriously the design of your tactic developments.)

**Comment by samuelgruetter** [comment]
I agree that using `::=` in published code is bad design. I think of it like `Require` inside sections or inside proofs, or like nested proofs (enabled by `Set Nested Proofs Allowed`): One should not commit any code that uses these features, and maybe they're deactivated unless you set some flag, and Coq will warn that you're not supposed to use them, but still, these features greatly speed up development.

For instance, if I'm using someone else's Ltac2 library that does not make its definitions mutable, and I suspect it might have a bug triggered by the proof I'm working on right now, and that the potential bug is in a function many calls down the call stack, if I can use `::=` to log some arguments and to patch it to confirm whether I'm right, it takes me much less time than copy-pasting all functions on the call stack, or recompiling the whole library plus (almost) my whole own project.

**Comment by Zimmi48** [comment]
If this were to exist, the syntax should make it clear that this is for debugging only. Relying on a debug flag doesn't seem enough because we are not safe against people using a `Global Set` and users using the debug feature without knowing. So `::=` seems too short and convenient for this purpose.

**Comment by samuelgruetter** [comment]
Or how about a warning on each `::=` that tells the user to use `Ltac2 mutable` instead? Of course one can still disable the warning, but that looks not as innocent as "setting some global flag" (even though it technically is the same), and also provides a way to find quickly all `::=` that have not yet been removed.

**Comment by Zimmi48** [comment]
That sounds reasonable to me. I'm not sure about @ppedrot though :wink:

**Comment by samuelgruetter** [comment]
It would also be useful to have a way to reference the original tactic that's being overridden, which is not possible in Ltac1, but possible in Ltac2 using the `as` clause in `Ltac2 Set ... as ...`.
So how about an `Ltac2 Redefine <name> as <oldname> := <new body potentially referencing oldname>`?
This would allow for debugging patterns like

```coq
Ltac2 Redefine foo as original_foo := fun (c: constr) =>
  Message.print (Message.concat (Message.of_string "foo is called with ") (Message.of_constr c));
  original_foo c;
  some_tweak ().
```

And it would emit a warning like

> Warning: Use of "Ltac2 Redefine" is for debugging only. If this feature is still needed in a finished proof script, it is recommended to mark the original definition as "Ltac2 mutable" and to use "Ltac2 Set" instead of "Ltac2 Redefine".
