### ISSUE TITLE
Segfault when using PArray

### ISSUE THREAD

**Issue by threonorm** [coq/coq#13998]
#### Description of the problem

vm_compute with PArray can segfault coqc:
```
Require Import PArray.
Require Import Int63.

Goal (forall (t:array unit), Some (set t 3 tt) = None).
vm_compute. (* segfault *)
```

I was not able to trigger a similar bug with the get primitive, and I saw that the test-suite for the get primitive actually seems to test for such issues, but not the test-suite for set.

This bug may be problematic if the segfault comes from an arbitrary memory unsafe set because maybe it can be exploited to  corrupt coqc memory silently, I did not investigate yet.

#### Coq Version

I observed that behavior with the following coqc:
```
The Coq Proof Assistant, version 8.13.1 (March 2021)
compiled on Mar 23 2021 20:49:34 with OCaml 4.12.0
```

#### Side Observation
How was the max size of array decided?
In kernel/parray.ml there is:
```
let max_array_length32 = 4194303
```
This value is 2^22 (unusual max length) and not 2^32 as the name suggest. I wondered if this is a "bug" or a deliberate choice.
I think it unlikely this is the source of the problem though.

**Comment by silene** [comment]
Ouch, the code that invokes OCaml primitives from the bytecode interpreter is completely wrong. The original author knew that there was an issue, so the code was tentatively protected by
```ocaml
assert (arity = Array.length args && arity <= 4);
```
This was meant to cause a brutal termination of Coq instead of the above issue.

Unfortunately, due to universes, the assertion is not quite right, so Coq does not abort, and goes on happily executing random code. (This is exploitable.) Since the testsuite does not test `PArray.set` on accumulators (only `PArray.get`), the issue was never detected.
