### ISSUE TITLE
Ltac2 broken with async

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#14156]
Since https://github.com/coq/coq/pull/14094
See https://gitlab.com/coq/coq/-/jobs/1187763526

**Comment by JasonGross** [comment]
Oops, sorry for merging #14094 without properly checking the allowed failures.

Should we revert?  Or @ppedrot do you know how to fix this?

**Comment by ppedrot** [comment]
I don't know what caused that but it's definitely suspect. Reverting seems a bit excessive for now, I hope I can find a fix soon.

**Comment by ppedrot** [comment]
Might be an avatar of #12807.

**Comment by ppedrot** [comment]
The problem comes from the emptiness of level 4 of the `ltac2_expr` grammar entry:
https://github.com/coq/coq/blob/d758cc5bb19d7abfcce13d2c26b5ae1c0fc1a439/user-contrib/Ltac2/g_ltac2.mlg#L161
This leads to the removal of this level from the grammar on backtrack, so that adding the notation for the dispatch tactical
https://github.com/coq/coq/blob/d758cc5bb19d7abfcce13d2c26b5ae1c0fc1a439/user-contrib/Ltac2/Notations.v#L86
fails with this uninformative error. It is the only notation added at that level by the core Ltac2 library.

I am not sure what to do. I think @herbelin had devised some trick for this kind of situation, so pinging him.

**Comment by ppedrot** [comment]
The PR #14158 fixes the problem but I don't know if this is the right solution. As advocated there I believe that this removal of level business does not make sense.

**Comment by herbelin** [comment]
Same conclusion.
