### ISSUE TITLE
Qualids not permitted for tactic name in "Ltac x.y := idtac."?

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14165]
`Ltac x.y := idtac.` gives the message `This expression should be a simple identifier`.  If there's no way to use a qualified identifier here then we should change the grammar to take only an `ident` (in the nonterminal `tacdef_body`) and update the documentation.  If it is allowed, we may still want to update the documentation.

**Comment by ppedrot** [comment]
Yes there is, if you use the update syntax: `Ltac x.y ::= idtac`.

**Comment by jfehrle** [comment]
Is `x` a module name or something else?  This isn't accepted:

```
Add LoadPath "/home/proj/mod1" as Mod1.
Require Import Mod1.foo.
Goal True.
x.                               (* prints "mod1" as expected *)
Ltac Mod1.x ::= idtac "huh?".    (* Error: "There is no Ltac named Mod1.x" *)
```

Where foo.v is just `Ltac x := idtac "mod1".`

**Comment by ppedrot** [comment]
You're not using the correct qualified names. To begin with, it's recommended against using `Add LoadPath` directly in a file, you should instead use the `-R / -Q` flags. This actually seems to be confusing you about the names of your scopes, since `Mod1.x` is an unbound name indeed. Instead it should read `Mod1.foo.x`, because that's where `x` is defined.

**Comment by jfehrle** [comment]
Indeed, I'm stumbling around.  Bear with me. The doc doesn't cover these details well, if at all.  On qualids, the capitalization is confusing.  Why is `foo` lowercase in `Mod1.foo.x` but we use uppercase in `Coq.Init.Logic.eq` (ignoring the last component)?  Is there a rationale to it to it or just they happened to be implemented differently?  In either case, it merits some explanation.
