### ISSUE TITLE
Anomaly when quitting coqtop with ^C^D

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#14199]
`Error: Anomaly "Uncaught exception Not_found."` in gramlib
Seems to date from https://github.com/coq/coq/pull/14075

**Comment by herbelin** [comment]
Indeed a consequence of #14075.

Actually it was not working very well since 8.5 already. From 8.5, after a Ctrl-C, `Coq <` is displayed and the next command produces `User interrupt` (while up to 8.4, Ctrl-C was producing the `User Interrupt`). I suspect e01597af2cd to have missed that in case of Ctrl-C, discard_to_dot should not be called.

Then, what do we want to see. Typically, I believe that what we expect is:
```
Coq < some-text-then-an-interruption^C
Error: User interrupt.
```
or maybe, as it was in 8.4:
```
Coq < some-text-then-an-interruption^C
User interrupt.
```
but:
- by default, there is a location: do we really want it?
- by default, `Error:` is printed immediatly after, resulting (after the original bug is fixed) into
```
Coq < some-text-then-interrupt^CError:
User interrupt.
```
How to fix this? I don't see how to fix it without a specific handling of `Break` when printing `Error:`. How would it scale to non-textual interfaces?
