### ISSUE TITLE
deprecated-hint-without-locality warning should be split for different kinds of hints

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#14216]
I would like to silence this warning for `Hint Rewrite`  (which does not support `Global` in older versions of Coq) and turn it into an error for `Hint Resolve` (there's no reason not to add `Global` right now, so that fiat-crypto doesn't break when things change).  Since not all hint commands acquired support for locality at the same time, I'd like to see this warning split so that I can toggle it for each hint commands separately.

**Comment by Zimmi48** [comment]
Note that we discussed the problem previously and said that if the hint name was kept the same, this would mean that the change of default locality would happen at the same time for all `Hint` commands. Given this, would you still prefer a different warning name? If yes, please open a PR.

**Comment by Zimmi48** [comment]
> Do you mean "warning name" rather than "hint name"?

Yes

Yes, annotating with `Global` and moving to `#[ export ]` at your own pace sounds good. But as you noticed `Hint Rewrite` won't even support `Global` until Coq 8.14. If you can't restrict your compatibility range (which is a bit extreme IMHO), then you will have to find a way of structuring your code so that `global` or `export` do not make any difference (at least for `Hint Rewrite`)

**Comment by JasonGross** [comment]
> Yes, annotating with `Global` and moving to `#[ export ]` at your own pace sounds good. But as you noticed `Hint Rewrite` won't even support `Global` until Coq 8.14.

Right, so my use-case for the per-hint-type warning flags is so that I can suppress the warning for hint types I can't annotate and so that I can have Coq make it an error to introduce new hints without the annotation for hint types that I can annotate.  Does this seem like a good enough reason to split the warning?

> If you can't restrict your compatibility range (which is a bit extreme IMHO)

Indeed, though I think it's nice to be able to support the latest LTS of Ubuntu and the latest Debian stable, especially as I expect the primary consumers of fiat-crypto are using the binary we produce rather than using it as a Coq library.

**Comment by ppedrot** [comment]
It's quite easy to trigger a different warning, that's what I did for instances. We can do that before 8.14 since the locality implementation for hint rewrite was introduced there, so there is currently no released version with a Hint Rewrite reusing the standard hint warning.

(Also, I think we should stop calling Hint Rewrite that way, they're really different beasts not using the same databases and relying on a completely different implementation.)

**Comment by Zimmi48** [comment]
>Right, so my use-case for the per-hint-type warning flags is so that I can suppress the warning for hint types I can't annotate and so that I can have Coq make it an error to introduce new hints without the annotation for hint types that I can annotate. Does this seem like a good enough reason to split the warning?

Yes, that sounds reasonable.

Marking this for 8.14 because if it is changed, that should happen before the release.
