### ISSUE TITLE
`dune build dev/shim/coqide-prelude` succeeds and `dune exec ...` fails with unclear error message when CoqIDE dependencies are not installed.

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [coq/coq#14292]
#### Description of the problem

Running `dune exec ./dev/shim/coqide-prelude` on a switch where coqide is not installed leads to the error
```
<project-root>/coq/_build/default/dev/shim/coqide-prelude: line 2: <project-root>/coq/_build/default/dev/shim//usr/bin/coqide: No such file or directory
```

If this cannot be easily fixed, I'd suggest this should at least be documented somewhere.

**Comment by Zimmi48** [comment]
That's not correct, but it might mean that you are missing some dependencies.

If I take the clean Coq repo master branch as of today and run `nix-shell` to get the dependencies through Nix (no opam), both building and executing `dev/shim/coqtop-prelude` and `dev/shim/coqide-prelude` work (although I recommend to build first otherwise you do not get feedback on the progress).

If I run `nix-shell default.nix --arg buildIde false --arg shell true` to get the Coq dependencies without the dependencies and I run `dune exec dev/shim/coqide-prelude`, I get the same error as you did:

```
<project-root>/_build/default/dev/shim/coqide-prelude: ligne 2: <project-root>/_build/default/dev/shim//run/current-system/sw/bin/coqide: No such file or directory
```

If I run `dune build dev/shim/coqide-prelude`, I get no output.

You can confirm that this was also your problem by running `./configure -profile devel`. It should print:

```
  CoqIde                      : no
```

IMHO, given that building with Dune doesn't require calling `./configure`, this is problematic that the CoqIDE target doesn't fail (at all, it exits with 0) and doesn't print a clear error message.

**Comment by SkySkimmer** [comment]
Looks like if dune can't build coqide it tries to get `%{bin:coqide}` from PATH, this is why you get a strange filename in the error.
If there's no coqide in PATH dune says
~~~
File "dev/shim/dune", line 51, characters 41-52:
51 |     (bash "echo '\"$(dirname \"$0\")\"/%{bin:coqide} -coqlib \"$(dirname \"$0\")\"/%{project_root} \"$@\"'")
                                              ^^^^^^^^^^^
Error: Program coqide not found in the tree or in PATH
 (context: default)
~~~

**Comment by LasseBlaauwbroek** [comment]
Ah indeed, I suppose that the switch was indeed missing some of CoqIde's dependencies.

**Comment by ejgallego** [comment]
Indeed we have to improve this, the error happens as @SkySkimmer details; there are few possiilities here actually.
