### ISSUE TITLE
Ltac2 should add $ and & to constr grammar only in Ltac2 code

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#14302]
I was surprised to notice that as soon as Ltac2 is `Require`d, when writing pure Gallina `Definition`s, I can write a `&` in front of variable references, eg `Definition foo(a: nat): nat := &a.`.
So it seems that the extensions to the constr grammar made by Ltac2 (such as `&` and `$` in front of identifiers) are active everywhere, instead of only in constrs appearing inside Ltac2 scripts.
So far, this seems to be a harmless pecularity, but I imagine that this could be bad for compatibility with existing libraries that use `&` or `$`:

```coq
Axiom op: nat -> nat -> nat.

Infix "$" := op (at level 30).

Definition a := 5.
Definition b := 6.

Definition x := a$b.

Require Ltac2.Ltac2.

Definition y := a$b. (* Error: Unbound value b *)
```

Coq version: master

**Comment by ppedrot** [comment]
Yes, this happened with Compcert. Unfortunately I don't think this can be solved, because we basically need to share the grammars otherwise it's an engineering nightmare. The rules are quite special though, since they require the absence of spaces, so notations may still work depending on the way they are written.

**Comment by samuelgruetter** [comment]
I see, so I guess that's a wontfix?

**Comment by andres-erbsen** [comment]
Could this notation at least follow `Import` (rather than `Require`) like user-defined notations?

We already use `$`, and we are incrementally picking up Ltac2. The most important use of Ltac2 in our developments is to access primitive operators not available in Ltac. This means that there is a small amount of Ltac deep in the guts of increasingly many tactic programs, turning up trouble when transitively `Require`d by code files already using `$` for something else.
