### ISSUE TITLE
No information how to declare scope

### ISSUE THREAD

**Issue by rnrand** [coq/coq#14366]
I'm getting this warning everywhere and there is no information in the warning (or, as far as I can tell, in the documentation) of how to actually declare something `local`, `global`, or `export`. https://coq.inria.fr/refman/proofs/automatic-tactics/auto.html#grammar-token-hint_info has no information and https://coq.inria.fr/refman/language/core/modules.html#coq:attr.local tells me that there is a `Local` and `Global` prefix (though not where they're applicable) but seemingly no `Export` prefix.

Looking through this repository, I see a fair amount of `#[local]` on top of `Hint`s (this would not have been in my first 100 guesses), so I'm going to use that. But you should update the warning and documentation to reflect that. 

https://github.com/coq/coq/blob/77d56f3da2e42bd5dbc45b44f98b79bc02b26c77/tactics/hints.ml#L1216

(Also, why not allow `Export Hint...`?)

**Comment by Zimmi48** [comment]
One of the issue in the current formulation of the warning message is that it doesn't contain the word "attribute", which would be a good clue as to where to look for documentation.

FTR, this part of the documentation https://coq.inria.fr/refman/language/core/modules.html#controlling-the-scope-of-commands-with-locality-attributes contains a link to the documentation of attributes (https://coq.inria.fr/refman/language/core/basic.html#attributes) but we should add much more links to this documentation so that users can find it more easily (almost at every occurrence of "attribute").

> (Also, why not allow `Export Hint...`?)

`Global` and `Local` are legacy syntax for the `global` and `local` attributes. The same couldn't be extended easily to `Export` because `Export` is also a command.

**Comment by Zimmi48** [comment]
I've added the link in the doc. I'll leave it to someone else to modify the warning message. It shouldn't be too difficult.
