### ISSUE TITLE
Extraction of Int63/UInt63...

### ISSUE THREAD

**Issue by mattam82** [coq/coq#14465]
#### Description of the problem

In MetaCoq we would like to extract primitive ints to their natural erased versions in OCaml. However there seems to be a clash: UInt63.v has the necessary `to_Z` function for example, while it should also bind to ocaml's own Uint63 module (bound in Coq's kernel). This name clash makes extraction impossible

#### Coq Version

Current Coq master (no problem in 8.13). Presumably introduced by the Sint63 introduction.

**Comment by JasonGross** [comment]
If I understand correctly, you're saying that because Uint63.v has the same name the Uint63 OCaml module, and they share functions of the same name but different implementations, extraction is impossible?

It seems to me there are three solutions:
1. Add `Extraction Inline` directives for all clashing constants.
2. Rename the constants on either the Coq or OCaml side
3. Implement https://github.com/coq/coq/issues/11987 so that you can add the relevant constants to a blacklist and get them renamed

Does this seem right?  Do you have thoughts on a preferred solution?

**Comment by mattam82** [comment]
None of these would work nicely. However adding an `Extraction Blacklist Uint63` renames `uint63.ml` to `uint0.ml` and everything works fine after that.

**Comment by mattam82** [comment]
This should definitely be mentioned in the doc, @ana-borges would you be so kind and update the doc about extraction? It should ideally be tested that it is simple to extract something using primitive ints and link it to Coq (and kernel.Uint63 there)

**Comment by ana-borges** [comment]
@mattam82 I'm having trouble reproducing your problem. Could you give me the exact commands that were leading to a conflict, or point me to the relevant file in meta-coq, please?
