### ISSUE TITLE
Possibly dangerous paradox

### ISSUE THREAD

**Issue by vporton** [coq/coq#14554]
I don't know whether you are aware of it, but I found a paradox new for me. You should make sure it does not affect Coq:

This shows something that appears to be a contradiction in ZF:

https://arweave.net/RJ4DRuRjdVWqJ5RBHB30SXDBXATzqmAV3Qs1b6f1ykw

(Note that by set-definition I mean it's numeric code, in an encoding such as Godel's encoding.)

---

It seems I understood why the error:

S is a function in a model of ZF, not in the formal system the proof is written. So, it's illegal to use it in the proof.

That's a very beautiful sophism.

What happens if we try to define S inside ZF? It should fail (unless ZF is contradictory). But how does it fails?

That is an practically useful question, because I really made this error today.

Digging deeper: If we would be able to prove that S exists, this would be enough to trigger the contradiction in ZF.

If we attempt to prove its existence, we try to map the set definition { x in A | P(x) } into the corresponding set, but we to fail to do that.

Note that this paradox is pertinent not to only to ZF but even to predicate logic:

Let P be encoding of a one-variable predicate. Then define the one-variable predicate S(Q) encoded by Q as S(Q)(P) <=> not (S(P))(P). Then S(Q)(Q) <=> not S(Q)(Q).

Oops! Mathematicians commonly do this trick: Let S be a function from some expression X of our formal system to another expression S(X) of our formal system. It is pertinent to logic studybooks! And that was an error! Possibly millions of math logic articles are wrong!

**Comment by Columbus240** [comment]
This isn’t "enough" to currently be problematic, eneither for Coq nor for ZF in general.

How I understood your argument:
Assume we are in the setting of ZF in first-order logic. Let ω denote the set of natural numbers inside ZF. Assume we have a function `S` from ω, characterized by the following property: Given some Gödel-encoding `G : ω → "Logical Formulae outside of ZF"`, we have that `S(n) = { x | G(n)(x) }` for all `n ∈ ω` for which their `G(n)` "makes sense" (syntactically well-formed and `x` is the only free variable).

I completely agree with you that in this situation, we can form the Russel-like-set `M` and get a contradiction. ([Russel’s paradox](https://en.wikipedia.org/wiki/Russell%27s_paradox)) This is completely sound logic you did there. The function `S` gives us something like the principle of unrestricted comprehension [[1]](https://en.wikipedia.org/wiki/Axiom_schema_of_specification#Unrestricted_comprehension) and we can form the Russel set.

But, as you noted, since `S` is a function inside ZF, it is a set in ZF, so we need to be able to construct it from the axioms of ZF. In most cases where people use principles of comprehension, it‘s possible to apply the axiom schema of specification [[1]](https://en.wikipedia.org/wiki/Axiom_schema_of_specification), so everything works out in ZF without contradiction.

If someone can come up with a construction in ZF of `S`, then they can (using your argument) arrive at a contradiction. Similarly, if an analogous construction could be made in Coq, we could use your argument to arrive at a contradiction inside Coq.
As long as nobody finds a construction of `S` or some other way to prove the principle of unrestricted comprehension (in a logical system that becomes inconsistent when adding it), this is a non-issue and could be closed.

**Comment by ppedrot** [comment]
I believe that if we find a contradiction in ZF we have much more to worry about than Coq being inconsistent as well. In particular, this is not an issue about Coq itself, so closing.

**Comment by vporton** [comment]
You misunderstood. It's not a contradiction in ZF (as far as I know), but a contradiction in the metalogic which is taught in most logic textbooks together with ZF.

Please reopen.

Coq or at least Coq proofs library may be vulnerable. Further investigation is necessary.

**Comment by vporton** [comment]
@JasonGross I use not the principle of unrestricted comprehension, but the "definition of a functional symbol" as commonly used in logic textbooks.

So, further checking whether Coq and its library are vulnerable is necessary.

**Comment by ejgallego** [comment]
> So, further checking whether Coq and its library are vulnerable is necessary.

Hi @vporton , indeed if Coq is vulnerable, you should be able to produce a Coq file showcasing the problem, otherwise it is a long shot for us to understand what could be possibly wrong.

**Comment by vporton** [comment]
> Hi @vporton , indeed if Coq is vulnerable, you should be able to produce a Coq file showcasing the problem, otherwise it is a long shot for us to understand what could be possibly wrong.

I do understand that this way would be the best. But I would need to install Coq, learn it again, and you would outsource you work to a Coq novice.

I found error in _most_ books about math logic. So, Coq is quite likely to be vulnerable. You need to take this most seriously.

The vulnerable thing is predicate calculus and Coq is lambda-calculus. But if there is some kind of metalogic (representation of Coq expressions as values) in Coq, then Coq is _very_ likely to be vulnerable too.

**Comment by ejgallego** [comment]
Coq doesn't offer such facilities, at least not likely in the way you would need.

> I do understand that this way would be the best. But I would need to install Coq, learn it again, and you would outsource you work to a Coq novice.

Then honestly I don't see the point to report the issue to the Coq bug tracker; this issue system is dedicated to the Coq system, so it seems strange to report an issue that has nothing to do with Coq, but with some logic books.

Thus indeed understand that unless you can produce a report where Coq is actually involved, issues like this will be considered off-topic.
