### ISSUE TITLE
I don't use principle of unrestricted comprehension

### ISSUE THREAD

**Issue by vporton** [coq/coq#14555]
I use not the principle of unrestricted comprehension, but the "definition of a functional symbol" as commonly used in logic textbooks.

So, further checking whether Coq and its library are vulnerable is necessary.

**Comment by JasonGross** [comment]
This issue makes no sense and is lacking context.  If it's supposed to be a follow-up of https://github.com/coq/coq/issues/14554, please continue the conversation there rather than opening new issues.  If it's supposed to be unrelated, please include more details on what exactly the issue is.  If you're not sure whether or not your concern is relevant to Coq, perhaps cstheory stack exchange or math overflow is a better place to ask your question.
