### ISSUE TITLE
Code style: Use of "let () = ... in"

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#14591]
I see over 1000 uses of the construct

`let () = <expr> in`

which could be shown more simply as

`<expr>;`

Is there a reason for using the longer, slightly less legible form?

**Comment by ejgallego** [comment]
They do have different implications w.r.t. syntax, compare
```ocaml
if foo then
  let () = bar 3 in
  zoo ();
```
vs 
```ocaml
if foo then
  bar 3;
  zoo ();
```
thus the first form is considered safer in some cases. But indeed, in a system like Coq we don't have a consistent choice for these cases, due to the very different provenance of code.

I'd recommend a critique of OCaml syntax, such as the one done by reason people to know more about these details. Also, formatting tools such as ocamlformat can reify this.

p.s: closing as IMHO a follow up belongs to any of the OCaml forums such as discuss.

**Comment by jfehrle** [comment]
The compiler should have an warning to flag occurrences of your second example (examining the indentation as Python does).  It's much to easy to make this mistake.

**Comment by ejgallego** [comment]
Indeed; I wonder if there is already a bug open in the OCaml bugtracker for that, this is a common problem that has hit everyone at least once.

Current solutions used in practice are to use a different syntax, or to use a code formatter that will highlight this problem.
