### ISSUE TITLE
Selection of pattern with Sprop subterms may break typing

### ISSUE THREAD

**Issue by herbelin** [coq/coq#14609]
#### Description of the problem

`Sprop` breaks the invariant that two convertible terms are of the same type. Here is an example with pattern selection where this leads to identify definitionally irrelevant proofs in incomparable types.
```
Inductive STrue : SProp := I.
Inductive SBool : SProp := T | F.

Axiom f : forall A, A -> unit.
Goal f _ (fun _ : unit => I) = f _ (fun _ : unit => T).
set (fun _ => _).
(* Ill-typed goal:
y := fun _ : unit -> T : SBool
============================
  f (unit -> STrue) y = f (unit -> SBool) y
*)
```

Note that on its side, ssr's `set` fails with a typing error.

#### Coq Version

Up to master.

**Comment by ppedrot** [comment]
FTR, this pattern problem is the reason why it is not possible to ignore the parameters of constructors of inductive types in the conversion. I tried to do this once for performance, but faced problems with `set` confusing various instances of the `nil` term. In this light, I believe the problem is not so much SProp than the fact that set and friends do not check for typing.

**Comment by herbelin** [comment]
Dropping the conversion of the parameters of constructors of inductive types would be nice (and more generally of any kind of implicit arguments, the day we'll have a metatheory of implicit arguments...).

I made #14610 to add typing in the selection algorithm used by `set` and `destruct`. That may be costly, but I believe this is reasonable.

PS: @gares, do you want me to add this extra typing also in ssr selection algorithm?
