### ISSUE TITLE
suff fails unexpectedly with a strange error message

### ISSUE THREAD

**Issue by ybertot** [coq/coq#14678]
#### Description of the problem

```coq
Require Import ssreflect.
Lemma toto (P Q:Prop) : P -> Q.
suff h : P.
```
#### Coq Version

The Coq Proof Assistant, version 8.13.2 (April 2021)
compiled on Apr 13 2021 12:31:09 with OCaml 4.10.0

(The same bug reproduces with coq 8.12.0 and with the master branch (commit 82fe22010e383ad013429c4afd9ec33d537c456b)

**Comment by Alizter** [comment]
`suff` seems to have trouble with the context. For example, this works:
```coq
Require Import ssreflect.
Lemma toto (P Q:Prop) : P -> Q.
suff h : Q.
```
and so does this:
```coq
Require Import ssreflect.
Lemma toto (P Q:Prop) : P -> Q.
revert Q.
suff h : P.
```

**Comment by gares** [comment]
This is roughly the implementation and the problem
```coq
Require Import ssreflect.
Lemma toto (P Q:Prop) : P -> Q.
About ssr_suff. (*
ssr_suff :
forall (Plemma : Type) [Pgoal : Type], (Plemma -> Pgoal) -> Plemma -> Pgoal
*)
refine (ssr_suff P _ _); [|]. (* OK *)
Undo.
apply (ssr_suff P); [|]. (* unlucky bug *)
```

This is where we build `ssr_suff P`
https://github.com/coq/coq/blob/01267bfcd928d15f7a2dec6a487d35d0f4b350f3/plugins/ssr/ssrfwd.ml#L333

And this is the code that calls apply.
https://github.com/coq/coq/blob/01267bfcd928d15f7a2dec6a487d35d0f4b350f3/plugins/ssr/ssrfwd.ml#L97

One could call refine instead, or, even simpler `Ssrcommon.applyn ~with_evars:true 2 t` which should pass 2 underscores exactly,
(and `t` would be the same `t` built by `basecuttac` here https://github.com/coq/coq/blob/01267bfcd928d15f7a2dec6a487d35d0f4b350f3/plugins/ssr/ssrfwd.ml#L95). I would not patch `basecuttac` but rather make a new function, since `basecuttac` is used elsewhere and changing the behavior could lead to unexpected results (which I don't see possible for `suff`).
