### ISSUE TITLE
Regression around implicit arguments of primitive projections

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#14703]
#### Description of the problem

The following code used to work fine up until Coq 8.13 (and even on the 8.14 branch it seems to work), but now fails on Coq master:
```coq
Definition type := nat.
Definition lft := bool.
Definition elctx := list lft.

Class TyWf (ty : type) := { ty_lfts : list lft; ty_wf_E : elctx }.
Arguments ty_lfts _ {_}.

Definition ty_outlives_E ty `{!TyWf ty} (κ : lft) : elctx :=
  ty.(ty_lfts).
```
```
Error: Projection ty_lfts expected 1 explicit parameter.
```
It looks like the projection syntax no longer accounts for implicit arguments set via `Arguments`?

This breaks LambdaRust on Coq master.

#### Coq Version

Coq master

**Comment by herbelin** [comment]
Hi, this is (indeed) related to #14606.

Are you saying that you mentally think at `ty` as being canonically equipped with an instance `TyWf0` of the class `TyWf ty` and thus `ty.(ty_lfts)` as a legitimate shortcut for technically projecting the field `ty_lfts` of `TyWf0`?

The example is interesting. How often do you use it (we found none in the CI)? That is, is it an interesting enough scheme to justify some support for it, rather than using instead the syntax `ty_lfts ty`? If yes, what would be the rule? That the last non implicit parameter of a projection from a class (whose corresponding argument is itself implicit) is considered to be the main argument of the `.(...)` notation?

**Comment by RalfJung** [comment]
> Are you saying that you mentally think at ty as being canonically equipped with an instance TyWf0 of the class TyWf ty and thus ty.(ty_lfts) as a legitimate shortcut for technically projecting the field ty_lfts of TyWf0?

I am thinking of `ty.(ty_lfts)` as a shortcut for `ty_lfts ty`.

But I recall we had to already change other things in lambda-rust when `.(...)` stopped working for things other than canonical projections. So this is probably consistent... even though I don't like this change, just like I didn't like that prior change. Oh well.

**Comment by RalfJung** [comment]
Closing as a duplicate of https://github.com/coq/coq/issues/11332.

**Comment by herbelin** [comment]
Up to #14606, `t.(f args)` was indeed just a notation for `f args t`. In particular, `u.(f t)` was the same as `t.(f) u` and this was leading to strange error messages when the implicit arguments did not match.

There is also an issue of printability. As of now, there is no way to print back `u.(f)` as `u.(f)` unless `f` is registered as a projection.

> Closing as a duplicate of #11332.

Note that #14606 is not about primitive projections but about projections in general (primitive or not). More precisely, it is about giving a status of main argument to the `t` of the `t.(f args)` syntax. So, I would not see it as a duplicate of #11332.

For instance, if the need is common enough, we could imagine assigning to a constant the status of "method" over a main argument, and use this back for printing the application of the method as `t.(f)`, even when the constant is not a projection.

In this case, you could (tentatively) say `Arguments ty_lfts main:_ {_}.`, declaring the first argument as pivotal for the syntax `t.(f)` and have `t.(f)` works both for parsing and printing.
