### ISSUE TITLE
Unexpected error during scheme creation: The label my_eq is already declared.

### ISSUE THREAD

**Issue by yforster** [coq/coq#14735]
```
Scheme my_eq := Equality for bool. 
```

fails with `Error: Unexpected error during scheme creation: The label my_eq is already declared.` Changing the label or replacing bool by another type yields the same error. `Scheme Equality for bool.` works as expected. 

Coq version:
```
jsCoq (0.13.0), Coq 8.13.2/81300 (May 2021),
  compiled on May 21 2021 16:42:15
OCaml 4.10.2, Js_of_ocaml 3.9.0
```

CC @gert-smolka

**Comment by Alizter** [comment]
Still an issue on 8.15+alpha.

**Comment by Alizter** [comment]
So I've had a look through the code and it seems that `Equality for ...` is generating two things not just one. This is in contrast to say `Minimality` or `Induction` since they generate only one thing.

It seems logical to me to disable the naming of the identifier for `Equality`. It doesn't make sense to give a single identifier to two things being generated.

Since users may want to actually name these `Equality` proofs, we should eventually add support for doing so. I believe there may be some bigger issues to solve here first however. I don't really understand the intended semantics of the `Scheme` command. What does it mean to write
```coq
Scheme foo := Induction for mutual1 Prop with bar := Equality mutual2.
```
for example? It looks like nonsense to me and coq even rejects, so I assume it was done to (naively) share the vernac syntax.

I think there should be another vernac command `Scheme Equality` that has nothing to do with the previous `Scheme` command. (Or perhaps we should drop `Scheme` for equality all together). `Equality` can't even be used with the `with := ..` syntax so it de facto acts like a separate vernac command at the moment anyhow.

**Comment by JasonGross** [comment]
> `Equality for ...` is generating two things not just one.

Four, actually: `Scheme Equality for bool.` generates `bool_beq` and its two correctness lemmas `internal_bool_dec_bl` and `internal_bool_dec_lb`, and also `bool_eq_dec`.

> I assume it was done to (naively) share the vernac syntax.

This is also my assumption

**Comment by Alizter** [comment]
@JasonGross In which case the message passed during the Scheme Equality command is incomplete.
