### ISSUE TITLE
[CoqIDE] Unicode input issue when Maj+Space is bound to unbreakable space

### ISSUE THREAD

**Issue by MevenBertrand** [coq/coq#14856]
#### Description of the problem
When using CoqIDE and entering the "\\" character followed by a (normal) space, the "Δ" character replaces both characters.
In #14501, @Zimmi48 reports the same issue, and links it to the presence of the Maj+Space key combination being bound to unbreakable space. I can confirm that I also have the same key combination bound, and that changing the keyboard configuration to one without that key combination solves the problem. It seems like the options of the IDE do not provide the possibility to opt out of the unicode input mode, which would probably be enough to at least be able to use CoqIDE without this issue.
Even if this issue seems not very widespread, I still believe that it is problematic since this key combination has been adopted in the recent normalization efforts for French keyboards disposition by the AFNOR (I was not able to confirm with certainty for the Azerty norm since the precise document is behind a paywall, but it is at least the case with the Bépo disposition).

#### Coq Version

Tested with Coq 8.13.0 and 8.11.2

**Comment by Zimmi48** [comment]
Thanks, @MevenBertrand, for opening this dedicated issue.

Let's cc @charguer who authored the (Unicode input) feature in case he's willing to look into it.

FWIW the current workaround (instead of disabling the Shift+Space key combination) is to pass `-unicode-bindings foo` for an empty file `foo` on the command-line.

Note also the point made in https://github.com/coq/coq/issues/14501#issuecomment-896611417: it suffices that there is one Unicode bindings defined to make the problem appear.

**Comment by MevenBertrand** [comment]
> FWIW the current workaround (instead of disabling the Shift+Space key combination) is to pass `-unicode-bindings foo` for an empty file `foo` on the command-line.

I can also confirm that this works on my system. But then my main use for CoqIDE is to quickly play around with Coq in a temporary buffer without having to create a new file, so needing an empty file kind of defeats that purpose as I can just open another IDE instead.

**Comment by Zimmi48** [comment]
> But then my main use for CoqIDE is to quickly play around with Coq in a temporary buffer without having to create a new file

Same.

That being said, you could have an empty file sitting on your computer somewhere and rebind your CoqIDE shortcut to call `coqide -unicode-bindings empty-file`.

Another option is to pass a non-existing file, which also works around the issue at the price of showing a warning when you start CoqIDE.

**Comment by charguer** [comment]
1) Have you tried  `-unicode-bindings local`, using an empty `coqide.bindings` file in `.config/coq`? It might 

2) It would be easy to add support for `-unicode-bindings disabled` if you think that's useful. Probably just 3 lines of code to implement.

3) Unbreakable spaces are terrible in CoqIDE, because you don't get to see them and the error messages are totally incomprehensible. It might make sense for CoqIDE to offer an option to treat an input of "unbreakable space" as the input of a conventional space. I personally have no use for unbreakable spaces, I just disable them system-wide using `setxkbmap -option "nbsp:none"` in `.bashrc`, though I understand this route might not work for everybody.

**Comment by Zimmi48** [comment]
> Unbreakable spaces are terrible in CoqIDE, because you don't get to see them and the error messages are totally incomprehensible. It might make sense for CoqIDE to offer an option to treat an input of "unbreakable space" as the input of a conventional space. I personally have no use for unbreakable spaces, I just disable them system-wide using `setxkbmap -option "nbsp:none"` in `.bashrc`, though I understand this route might not work for everybody.

Reading this and reading @ppedrot's comment at https://github.com/coq/coq/pull/14863#issuecomment-915201427, I'm wondering if the bug was well understood. The problem does not happen when we use unbreakable spaces but when we use normal space after a `\`.

Anyway, if that's not something that we can fix on our side, then yes, we should provide an option to disable Unicode bindings but also document that this is a known issue.

**Comment by charguer** [comment]
Ah, I was able to reproduce the bug, using `setxkbmap -option nbsp:level2` before launching coqide.
Let me investigate if it just needs a one-line patch.

**Comment by charguer** [comment]
Add to the file `.config/coq`the line `(gtk_accel_path "<Actions>/Tools/LaTeX-to-unicode" "<Primary>space")` will work around the issue, leaving `shift+space` to work for unbreakable space, and `ctrl+space` to perform the unicode replacement.

Besides, I've also implemented changes that should disable the completion after a backslash alone, and allow to support the option `-unicode-bindings off`. The diff is here: https://github.com/charguer/coq/commit/162c0a817bfdb76d251624a1b9474903a71c2740

  Unfortunately, I'm not able to test the change, because at the moment I face a `Warning: the file ide/default.bindings was not found in .`  when executing `bin/coqide` after a `configure -profile devel` followed with a `make coqide`. I don't know how to fix this---help welcome.

**Comment by Zimmi48** [comment]
> Unfortunately, I'm not able to test the change, because at the moment I face a `Warning: the file ide/default.bindings was not found in .` when executing `bin/coqide` after a `configure -profile devel` followed with a `make coqide`. I don't know how to fix this---help welcome.

Try building with Dune (`make -f Makefile.dune world`) and running `_build/install/default/bin/coqide` instead. It should work.

**Comment by herbelin** [comment]
> Unfortunately, I'm not able to test the change

What should be tested? `\` followed by normal space gives `\ `. Then, `\` followed by shift-space gives `Δ`.

BTW, how did this lead to the behavior observed in #14501?

**Comment by charguer** [comment]
After my changes: With `setxkbmap -option nbsp:level2`, the backslash followed by a plain space generates a delta. With  `setxkbmap -option nbsp:none`, backslash with a plain space generates a space, and backlash with shift+space generates delta.

After my changes:  backslash with a plain space or shift+space should not generate the delta, regarding of the system nbsp option.

**Comment by herbelin** [comment]
Then, on MacOS (thus not X), I get Δ only with shift-space, before and after picking charguer@162c0a8.

**Comment by ppedrot** [comment]
@charguer your change looks like a workaround to me, not a proper fix. You're just checking that the prefix is empty, but anybody writing `\` + non-empty prefix will still experience the bug. I agree it's making the bug exceedingly rare, but the underlying issue is still there, i.e. GTK believes that Space is Shift+Space when the xkb option is set.

**Comment by charguer** [comment]
@ppedrot as pointed out by @Zimmi48 I did not understand what the reported bug was exactly about in the first place.

Your PR seems appropriate, and I would even add to it the "off by default", with a entry in the menu (or the settings) to turn it on.

With your PR, my "off" command line flag becomes useful, indeed.

It might still be interesting to include in your PR the line `if prefix = "" then raise Abort;` to avoid attempting an arbitrary completing when no character was given.

**Comment by ppedrot** [comment]
> It might still be interesting to include in your PR the line

I think both PRs make sense independently. You should probably submit yours separately.
