### ISSUE TITLE
Warning settings are not passed to workers.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#14852]
As witnessed in https://github.com/coq/coq/pull/14803 , `AsyncTaskQueue` will filter option `-w` , thus, if disabling a warning when calling `coqc -async on`, the warning will not be disabled in the worker, thus creating spurious output.

In general, the whole handling of cmdline arguments for slaves seems a bit tricky.

**Comment by gares** [comment]
Note that it is not obvious that the settings are not passed. They are not passed on the command line, right, but any part of the `Summary` is passed as part of the state which is marshaled. I did not check, but I guess that the status of warnings is synchronized (otherwise undo would not work).
In the test we saw, the file is empty, so that initial state is possibly not sent to the worker.

I agree that chopping random arguments from the command line is ugly and fragile.

**Comment by ejgallego** [comment]
> I did not check, but I guess that the status of warnings is synchronized (otherwise undo would not work).

Actually I think the state of warnings is not synchronized.

**Comment by SkySkimmer** [comment]
>Actually I think the state of warnings is not synchronized itself, the state of the Set Warnings option is.

I don't think there's a difference

**Comment by ejgallego** [comment]
> I don't think there's a difference

How do you explain the problem in #14803 then?

**Comment by SkySkimmer** [comment]
I guess arguments are passed (and may warn) before the summary is installed.

**Comment by SkySkimmer** [comment]
So the master is called with `-w -native -native ondemand -async on`
The worker is called with `-native ondemand`, warns that -native is deprecated, and only after that sets the warning state

**Comment by ejgallego** [comment]
I tried to improve this in #15560 as otherwise using the non coqnative setup is a PITA, but that's 33% faster.
