### ISSUE TITLE
Inconsistent syntax between "is_var @term" and "is_const @one_term", etc.

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#15283]
is_evar, has_evar, is_var accept an `@term` while
is_const, is_fix, is_confix, is_constructor, is_ground, is_ind and is_proj accept `@one_term`.
That means `has_evar m = n` is valid, but parentheses are required for `is_fix (m = n)`.

For consistency, the ones with `@one_term` should get `@term`.  This would be backward compatible.

**Comment by JasonGross** [comment]
> For consistency, the ones with `@one_term` should get `@term`. This would be backward compatible.

I think instead they should all get `@one_term`, so that these tactics don't have special parsing rules separate from Ltac application.  (However, the manual seems to be wrong about the grammar of Ltac application:
![image](https://user-images.githubusercontent.com/396076/144329066-0036fb1b-d701-4e32-b858-baf47b09e75a.png)
suggests that
```coq
Ltac foo x := x.
Goal True.
  foo 1 = 1.
```
should parse with `foo` as `qualid` and `1 = 1` as a `term` in `tactic_arg`, but instead I get "Syntax error: [ltac_use_default] expected after [tactic] (in [tactic_command])."  So in fact I think `tactic_arg` takes `@one_term` not `@term`, and these tactics should be made to take `@one_term`, and the easy backwards-compatible fix should be made of wrapping arguments in parentheses.

**Comment by ppedrot** [comment]
I agree with @JasonGross 's analysis, this should force to wrap arguments inside parentheses when not atomic, so use `one_term`.

**Comment by ppedrot** [comment]
Hm, I just checked and these functions are all defined in the same way. @jfehrle you're complaining just about the doc, right, not the actual behaviour of the tactics? They're all parsing one_constr for me.

**Comment by jfehrle** [comment]
@ppedrot Pilot error on my part (I moved old text from tactics.rst to ltac.rst in a pending PR and forgot to run doc_gram_rsts.  doc_grammar doesn't update tactics.rst yet because it hasn't been converted, a manual process--but will be soon.)

**Comment by jfehrle** [comment]
@JasonGross The issue is that the grammar is ambiguous and/or that the parser only looks at the next symbol to make a parsing decision (with several hand-coded exceptions).  An exercise for the reader to figure it exactly what's happening.

In the example below, `@nat` can only be parsed as a `term`; it is not a valid `@one_term`.  So I think the grammar is correct.  Not sure if adding a note saying that you may frequently have to add parentheses would help or confuse users.

```
Ltac foo x y := idtac.
Goal True.
  foo @nat @nat.
```
