### ISSUE TITLE
store `ide/coqide/protocol/interface.ml` for every Coq version, for documentation purpose

### ISSUE THREAD

**Issue by Guest0x0** [coq/coq#15326]
#### Description of the problem
Coq's XML protocol is not detailedly documented. AFAIK the most complete and accurate source is `ide/coqide/protocol/interface.ml`. However, due to [#12337 Move CoqIDE to another folder](https://github.com/coq/coq/pull/12337) the history of this file is not easily accessible on github. The XML protocol itself has recently gone through some breaking changes for Ltac debug, so the master documentation of the protocol is incompatible with the most widely installed versions of Coq.

IMO it would be nice to have a  folder holding `interface.ml` or `/dev/doc/xml-proto.md` for every version of Coq, perhaps in `/dev/doc` or somewhere.

**Comment by jfehrle** [comment]
`dev/doc/xml-protocol.md` describes the protocol in prose.  Perhaps helpful.

**Comment by ejgallego** [comment]
Yes, we can add links to the file in github for each version of the protocol, but IMHO this is not so useful as the XML protocol is deprecated. Closing as won'tfix unless someone would like to improve the .md file with the proper links

(Also I think that the .ml file is poor doc actually)

**Comment by Zimmi48** [comment]
>XML protocol is deprecated

You are abusing the word deprecated. Deprecated means planned for removal. It is not yet planned for removal because the replacements have not been available for long enough yet. You can say that the XML protocol is legacy and minimally maintained instead. (Similarly to what we write for funind at https://coq.inria.fr/refman//using/libraries/funind.html.)
