### ISSUE TITLE
rewrite in H vs rewrite in * with maximally inserted implicit arguments

### ISSUE THREAD

**Issue by olaure01** [coq/coq#15395]
`rewrite H in *` and `rewrite H in H'` behave differently with respect to maximally inserted implicit arguments:
```coq
Section Rewrite_Implicit_Args.
  Variable f : forall X, X -> X.
  Variable Hf : forall {X} (x : X), f X x = x.

  Lemma rewrite_in (A : Type) a b : f A a = b -> a = b.
  Proof.
  intros Heq.
  Fail rewrite Hf in *.
  rewrite Hf in Heq.
  assumption.
  Qed.
End Rewrite_Implicit_Args.
```
The problem does not occur with variants in the type of `Hf` such as `forall X` or `forall [X]`.

**Comment by SkySkimmer** [comment]
Since this seems to have nothing to do with f and Hf being variables, let's use this as an example instead:
~~~coq
Axiom f : forall X, X -> X.
Axiom Hf : forall {X} (x : X), f X x = x.

Lemma rewrite_in (A : Type) a b : f A a = b -> a = b.
Proof.
  intros Heq.
  Fail rewrite Hf in *.
  rewrite Hf in Heq.
  assumption.
Qed.
~~~

**Comment by SkySkimmer** [comment]
The doc says 
~~~rst
   Tactics that select a specific hypothesis H to apply to other hypotheses,
   such as :tacn:`rewrite` `H in * |-`, won't apply H to itself.
~~~
but the actual restriction is a bit stronger: `rewrite term in *` will skip all variables mentioned in `term`. In the example `Heq` gets mentioned through the evar context for the implicit hole.
This was different before 7c8c9900b8c9eb20ba2db42fbe445c95e3aa149a

**Comment by ppedrot** [comment]
Isn't this a variant of #3051?

**Comment by olaure01** [comment]
Duplicate of #3051 and #8635.
