### ISSUE TITLE
Implicit behaviour of projection syntax should be documented

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#15457]
`f.(g)` changed in https://github.com/coq/coq/pull/14606 to be different from `g f` when considering implicit arguments. The new behaviour should be explained in the refman.

**Comment by SkySkimmer** [comment]
cc @herbelin do you think we can get this soon in order to have it in 8.15?

**Comment by herbelin** [comment]
> cc @herbelin do you think we can get this soon in order to have it in 8.15?

I can try if it is just adding a word at well-chosen places.

What is your idea? To add a section say "Interaction with dot notation for projections" after [Interaction with subtyping](https://coq.inria.fr/refman/language/extensions/implicit-arguments.html?highlight=implicit%20arguments#interaction-with-subtyping) + adding a word in the section on [`Set Printing Projections`](https://coq.inria.fr/refman/language/core/records.html?highlight=projection#coq:flag.Printing-Projections)? Maybe the latter would be enough since the dot notation is only scarcely documented. What do you think?

If it needs more restructuration of the refman, it might be too short for 8.15.

**Comment by SkySkimmer** [comment]
I didn't look at what the change does, document as you feel is best.

**Comment by herbelin** [comment]
Actually the refman is not really wrong. I made a minimal addition at #15460.
