### ISSUE TITLE
minus_plus is not superseded by Nat.add_sub

### ISSUE THREAD

**Issue by mattam82** [coq/coq#15544]
#### Description of the problem
While porting to Coq master, I found that `minus_plus :  forall n m : nat, n + m - n = m`
is deprecated in favor of `Nat.add_sub: forall n m : nat, n + m - m = n` but those don't have the same type.

#### Coq Version

master

**Comment by olaure01** [comment]
The exact conversion is in `Arith_prebase.minus_plus_stt` which is supposed to disappear in some future deprecation step.
I think the point is: do we want to keep both statements in `stdlib`? (and the same question holds for other similar pairs of statements).

**Comment by mattam82** [comment]
It's true that it only differs by a commutativity of addition, and likewise for `le_plus_minus_r`, maybe that's alright but the deprecation message could be more explicit and tell the user that he will need to combine more lemmas.

**Comment by Alizter** [comment]
I agree with Matthieu here. Perhaps having both lemmas wouldn't be a bad idea?

**Comment by olaure01** [comment]
Would something like `The Arith.Minus file is obsolete. Use Nat.add_sub (together with Nat.add_com) instead.` be OK?
(and I would do something similar for all the other `Definition`s in `Arith_prebase` since these are the statements not exactly matching `PeanoNat` ones).
I am not really in favor of keeping both, since then for uniformity it would be natural to do the same for many statements and it could make stdlib highly redundant.

**Comment by Alizter** [comment]
I guess changing the deprecation message would suffice.

**Comment by mattam82** [comment]
Yep, changing the deprecation message would suffice. It seems other libraries on nat like ssrnat also avoid redundant lemmas like these, that also goes in the direction of not adding redundant lemmas in the stdlib.

**Comment by RalfJung** [comment]
This still makes the port quite annoying -- one has to actually understand the proof script to be able to figure how to to write with Nat.add_comm in just the right spot.
