### ISSUE TITLE
`lia` needs manual rewrite with `nat` equation (incompleteness?)

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#15583]
Here's an example where `lia` fails, but succeeds if I first do a manual rewrite with an equality on `nat`.

```coq
Require Import Coq.ZArith.ZArith. Open Scope Z_scope.
Require Import Coq.micromega.Lia.

Goal forall (T : Type) (f : T -> nat) (vs1 : T) (w0 w1 w2 : Z),
    f vs1 = Z.to_nat ((w0 - w1) mod 2 ^ 32 / w2) ->
    ((w0 - w1) mod 2 ^ 32) mod w2 = 0 ->
    0 <= w0 < 2 ^ 32 ->
    0 <= w1 < 2 ^ 32 ->
    0 <= w2 < 2 ^ 32 ->
    (w1 + (w2 mod 2 ^ 32 * Z.of_nat (f vs1)) mod 2 ^ 32) mod 2 ^ 32 = w0.
Proof.
  intros.
  Z.div_mod_to_equations.
  Fail lia. (* Cannot find witness. *)
  rewrite H in *.
  lia. (* succeeds *)
```

Doing this rewrite exposes a `Z.of_nat (Z.to_nat _)` pattern, and it seems that this might be the missing piece of information that makes `lia` succeed.

Question: Could `lia` be changed so that the rewrite is not needed? Or if not, what exactly makes this example lie outside of the supported fragment of arithmetic?

Coq version: 8.15-rc1

/cc @fajb

**Comment by fajb** [comment]
This is outside the linear fragment.  Your rewriting is a non-linear operation: it is  performed within a product.

What is unfortunate is that `nia` seems to run forever.

**Comment by samuelgruetter** [comment]
Aah I see, thanks!

It seems, though, that `lia` does solve certain goals that are not strictly linear arithmetic, like this one:

```coq
Goal forall (a w1 w2 x1 x2: Z),
    x1 + x2 = w1 + w2 ->
    a * (x1 + x2) = w1 * a + w2 * a.
Proof.
  intros. lia.
Qed.
```

It also requires rewriting with the hypothesis inside a product. Is there a way to characterize the non-linear parts of arithmetic that `lia` supports? Or is this still linear for a reason I'm missing?
(`lia` is extremely useful for my work, and I depend heavily on it, so I'd like to develop a precise understanding of what fragment it supports, so that I can build robust tactics on top of it).

**Comment by fajb** [comment]
Humm. `lia` is sometimes too clever for its own good.
I checked the code. Indeed, it performs substitutions and that does rewrites under products.
If the goal is linear, there is no completeness loss.
If the goal is non-linear, this improves the matter but this is not reliable because the order of the rewrites matters.

If you want something robust, consider that `lia` only does the following:
1. run `zify`
2. develop polynomials
3. bound monomials using interval analysis (e.g. x >= 0 , y >= 0 -> x * y >= 0)
4. generalize each monomial by a fresh variable (to get a linear goal)
5. runs a  (complete) linear solver 

2. and 3. are the only non-linear reasoning steps you should rely upon.

There is a little bit more going on. It helps only for interactive proofs.

PS: It is unfortunate that your first goal is not solved because if you do 
``` Z.div_mod_to_equations.
  zify.
  intuition try lia.
```
You can (recursively) substitute equations of the form var = constant and solve the resulting goal with `lia`.
That could make sense to  incorporate this in `lia`...
PS': Probably, that was a mistake for `lia` to perform that  much non-linear reasoning.
