### ISSUE TITLE
Generate .opam files using dune

### ISSUE THREAD

**Issue by Alizter** [coq/coq#16071]
We should bump our version of dune and start generating opam files again as the upstream bug has been fixed.

**Comment by Zimmi48** [comment]
It's fine I think, given that both Debian stable and Ubuntu LTS have 2.9.1.

**Comment by ejgallego** [comment]
> Debian stable

Note Debian stable has 2.7.1 , not that I think we should hold by Debian, which unfortunately has a large manpower problem in the OCaml team (causing other issues)

We have been only caring about Debian due to @JasonGross caring about the packages, but it seems to me he would have saved a lot of time by switching to better maintained alternatives like Nix or Docker.

**Comment by Alizter** [comment]
8.17 is still 6 months away, there is plenty of time to release dune 2.9 in the meantime.

**Comment by ejgallego** [comment]
Next Debian stable is expected Aug 2023 , but again note that I don't think we should hold by this.

But indeed it is more worrying that Dune is still stuck at 2.9 in unstable, so indeed, that's worrying and it means that Debian packagers will need help if the wanna keep up with Coq versions

**Comment by Zimmi48** [comment]
I was confused with respect to what was the latest Debian stable version. I think that @JasonGross only cares about Ubuntu LTS, so this would be fine for him, but some other users may care about being able to build Coq with Debian-packaged dependencies. If we decide to not have this requirement anymore, then we should probably discuss in a Coq Call before doing any change.
