### ISSUE TITLE
arrow in Notation format specifier breaks arrow formatting generally

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#16262]
Mentioning -> in a Notation format removes spaces around pretty-printing of arrows even outside that scope.

```
Declare Scope foo.
Check (nat -> nat).
Notation "a -> b" := (a,b) 
   (b at level 200, only printing, right associativity, at level 99,
   format "a -> b") : foo.
Check (nat -> nat).
```

The first Check outputs,  `nat -> nat`  but the second one outputs `nat->nat` .  Notice that neither of those Check commands is done with the `foo` scope open.

This is in Coq 8.15.1.    (It's in Coqide in Windows but that is probably irrelevant).
See also [VST issue 594](https://github.com/PrincetonUniversity/VST/issues/594).

**Comment by andrew-appel** [comment]
The easy workaround is to remove  `format "a -> b"`  from the Notation command.  This doesn't seem to break anything important in my application.

**Comment by Alizter** [comment]
You seem to be overriding the notation as it is registered in the parser. In fact coq warns you about this:
```
Notation "_ -> _" was already defined with a
different format.
[notation-incompatible-format,parsing]
```

So I would not really classify this as a bug, but we could also try something stricter such as making this warning an error. I'm not sure it is possible to have `"_ -> _"` mean different formats since that literal string is how reserved notation lookups are keyed.

cc @herbelin

**Comment by Blaisorblade** [comment]
@Alizter is right, but in fact there is more that this code is redeclaring and shouldn't be. The correct code to write is:
```
Declare Scope foo.
Check (nat -> nat).
Notation "a -> b" := (a,b) : foo.
```

That's because, super-confusingly, scopes are _exclusively_ about the interpretation — parsing and pretty-printing are shared across scopes, and that's a fundamental property of the design. AFAICT, parsing is completed _before_ scopes begin to be considered.

As a side note, the format you'd need to get the extra spaces is probably `format "a  ->  b"` with double spaces — _sometimes_ you need two spaces in the format to get one in the output (because one space is taken as token separator).

@Alizter Modulo compatibility, it wouldn't be absurd to have warnings or errors forcing `Notation "a -> b" := (a,b) : foo.`  and rejecting redundant specifiers. How to best get there is up for discussion.
