### ISSUE TITLE
Frequent coq rebuilds due to dune updates

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#16325]
#### Description of the problem

I am not sure where is the right place to report this, but I feel like there are some pains caused by the dune migration that should be tracked somewhere. One issue is that dune seems to update fairly frequently, and every time it does, opam insists on rebuilding Coq and all Coq libraries. Paired together with the fact that building Coq with flambda takes quite a while (and without flambda, Coq is still slower on latest OCaml than it was with OCaml 4.07), this is fairly disruptive.

It would be great if things could be arranged such that a dune upgrade does not force a Coq rebuild. After all dune is just the build system; I also don't rebuild Coq whenever `make` changes.

#### Coq Version

Any Coq installed via opam will do.

**Comment by Alizter** [comment]
Have you considered pinning your version of dune? Something like
```
opam pin add dune.2.9.0
```
That will stop it from being upgraded in general.

**Comment by RalfJung** [comment]
Looking at the logs again, it's not just dune -- ocamlfind is another example of something that seems to be part of the build system, has had a few releases recently, and triggers a Coq rebuild for each release.

**Comment by gadmm** [comment]
I unearthed this related issue: <https://github.com/ocaml/opam/issues/3850>.

It seems that opam has (or had) an option to avoid rebuilding when build dependencies are upgraded. However this caused some issues when some people needed to downgrade their build system. It also had a subtle semantics which was not well uderstood by authors. In addition, according to a comment, _"we're going to have both a dune binary cache soon and the opam cache in the future, so the cost of this will disappear"_ (I do not know if/how this applies to your issue).

**Comment by Alizter** [comment]
@RalfJung If you are doing this in the CI, are you using the OCaml Github action? There is a way to enable Dune cache for that, which will reduce build times significantly.

**Comment by RalfJung** [comment]
No, we have our own CI setup. We are not on github.

**Comment by Blaisorblade** [comment]
@RalfJung since we are discussing what you do in CI, I'd at least do the `dune` and `ocamlfind` pinning in the base Docker image — I think (hope?) the coqorg images do that already. 

Can you also mention 
- why you call `opam` _at all_ in CI?
- why you let it pick versions?

Maybe both things are recommended, and some of that is probably _necessary_ for a public library... but that could be a daily/weekly job on `master`, not part of CI for MRs? At work we only call `opam` when we bump our dependencies and build new Docker images. And CI does _not_ let `opam` pick versions — our CI deps look _more or less_ like this:

```
  "coq-ext-lib" {(= "0.11.6")}
  "coq-iris" {(= "dev.2022-05-04.0.10e843d9")}
  "elpi" {(= "1.15.2")}
  "coq-elpi" {(= "1.14.0")}
  "coq-lens" {(= "1.0.4+8.15")}
  "coq-equations" {(= "1.3+8.15")}
  "zarith" {(= "1.12")}
  "coq" {(= "8.15.1+bedrock")}
  "dune" {(= "3.4.0")}
```

I probably should try https://opam.ocaml.org/doc/man/opam-lock.html.

**Comment by RalfJung** [comment]
Our Docker images contain opam, but no more than that. Each job then defines which versions of Coq and other dependencies it wants, and the first thing it does is use opam to do that setup. The result of that (the entire opam root) is cached.

Maybe there are better ways to do this, but as a total Docker noob, I didn't want to have to manage a fleet of docker images (one for each version of Coq that we test).

**Comment by Blaisorblade** [comment]
Since your cache works, we can ignore Docker. Opam lockfiles, or just `-dep` packages with tighter dependencies, could work.

> But this still seems like a work-around; whenever Coq changes, it should use the latest dune.

That conflicts with this approach.

> There is a way to enable Dune cache for that, which will reduce build times significantly.

That might indeed help; having `~/.cache/dune` in the CI cache and enabling dune caching gets you quite far if you limit the cache size by invoking `trim`; shipping a tarball like Gitlab does isn't ideal but might work out for you (we use `rsync` at work as recommended by Emilio/Rudi, but that's bespoke and possibly overkill).

--------

Separately, AFAICT the original report seems not really a Coq bug, hence I added the `kind: question` label. This behavior is an intentional choice by opam/dune/... per the issue linked in https://github.com/coq/coq/issues/16325#issuecomment-1185766294.

**Comment by ejgallego** [comment]
Indeed there is little we can do from Coq, this is an OCaml-wide issue and likely there is a bug report in Dune about this (my search was not lucky tho, but I have limited time)

Note that the original behavior of dune didn't do this: you could upgrade dune and no need to rebuid packages (dune was a build-only dep)

However, that did create many problems once `dune-package` files started to be installed, as in particular, they are versioned. This turned out to be a disaster if dune was marked for downgrade (older dune can't parse meta files generated with newer versions), so hence dune was declared build, and not build-only (there was a dune issue about that, can't locate it either)

The root of the issue is that opam can't really track dependencies in the granularity needed to make this kind of setup work well, so hence the huge over approximation.

**Comment by Blaisorblade** [comment]
FTR the OCaml issue is https://github.com/ocaml/opam/issues/3850 (linked above).

**Comment by RalfJung** [comment]
Well, that issue is about just giving up on this altogether and removing build dependency from opam. So then any dune update would *definitely* cause a full rebuild of The World. Great...

**Comment by Blaisorblade** [comment]
@RalfJung `build` was removed 3 years ago, so that's not the new part.

**Comment by ejgallego** [comment]
There is also at least one issue on the Dune repos, but I can't seem to find it (likely closed)

But yes, the current situation is not good, just that I think this issue got to be moved upstream, and quite costly to fix due to the meta-data problem.

**Comment by ejgallego** [comment]
> There is also at least one issue on the Dune repos, but I can't seem to find it (likely closed)

Oh actually the issue may be the one @Blaisorblade points to instead. Thanks!

**Comment by Blaisorblade** [comment]
A fix for https://github.com/ocaml/dune/issues/6162 could solve this problem for good (and https://github.com/ocaml/opam-repository/issues/14185 is related but less useful).
