### ISSUE TITLE
coqdep generates wrong dependencies when looking for META files.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#16571]
Dune's PR https://github.com/ocaml/dune/pull/6167 makes sure that the
needed `META` files are in place before calling `coqdep`/`coqc`
for Dune, which should make the new loading system in Dune
supported.

However, `coqdep` seems to produce broken dependencies.

We can reproduce as follows:

- rename `theories/dune.disabled` to `theories/dune`
- change `theories/Init/Ltac.v` to have `Declare ML Module "coq-core.plugins.ltac".` (without the compat syntax).

Now `dune build theories/Init/Ltac.v.d` will produce (simplified):

```
Init/Ltac.vo: Init/Ltac.v /home/egallego/external/coq-master/_build/install/default/lib/coq-core/META ../plugins/ltac/ltac_plugin.cmxs
```

which seems non-sense as the path to the plugin should relative to the `META`, that is to say:
`/home/egallego/external/coq-master/_build/install/default/lib/coq-core/plugins/ltac/ltac_plugin.cmxs`

This actually seems due to us passing the `-I` flag still to coqdep, and it picks the legacy one, however `coqc` will refuse to load it.

So this is bug one, coqdep and coqc exhibit different behavior here. If we call coqdep manually (with the `META` in place), we have a more puzzling error:
```
$ dune exec -- coqdep -boot -noinit -R theories Coq -dyndep opt _build/default/theories/Init/Ltac.v
*** Warning: in file _build/default/theories/Init/Ltac.v, declared ML module ./plugins/ltac/ltac_plugin has not been found!
```
So we have two problems here, first the path in incorrect, second, even if it findlib mode, we are relying on the `mlpack` file to be present, which we should not.

**Comment by SkySkimmer** [comment]
Probably related to https://github.com/coq/coq/issues/16495#issuecomment-1255282480 btw

**Comment by ejgallego** [comment]
> Probably related to [#16495 (comment)](https://github.com/coq/coq/issues/16495#issuecomment-1255282480) btw

That's related but a different problem: coqdep will emit the META dep non-deterministically (only iff it can find it)

So there are really 3 bugs:
- non determinism in meta file dep
- finding the meta, but then using the legacy resolution method due to still requiring mlpack
- finding the meta, and returning a wrong path.

**Comment by ejgallego** [comment]
For dune 1 won't be a problem as after 3.5.0 we will always call coqdep with the meta file in place.

**Comment by Alizter** [comment]
The second problem is probably https://github.com/coq/coq/issues/11026

**Comment by rlepigre** [comment]
> which seems non-sense as the path to the plugin should relative to the `META`, that is to say:
> `/home/egallego/external/coq-master/_build/install/default/lib/coq-core/plugins/ltac/ltac_plugin.cmxs`

Actually, this seems more complicated than just fixing this path: the `META` file is produced under `_build/install/...` while the plugin is rather built under `_build/default/...`, right?

I've played around a bit to try and solve the issue, but I'm not sure what really needs to be done since I don't exactly know what `dune` does with the output of `coqdep`.

**Comment by ejgallego** [comment]
> Actually, this seems more complicated than just fixing this path: the META file is produced under _build/install/... while the plugin is rather built under _build/default/..., right?

That's not a problem in the sense we can emit a dep for the plugin in the installed location, that's actually the right thing to do with the current architecture.

So indeed, you can do:
```
dune build plugin/foo.cmxs
```
or
```
dune build _build/install/default/lib/coq-core/plugins/foo.cmxs
```

**Comment by rlepigre** [comment]
I realized this morning than relative paths won't do it for dune, at least if we want to preserve compositionality. Indeed, the relative path to the `META` file depends on the workspace root, so a relative path is not good enough.

What I would suggest instead of a relative path is a package name: something like `PACKAGE(package-name)`. This way, dune would be able to directly ask `ocamlfind` for the `META` file location. This would probably require modifying how CoqMakefile deals with `META` files, but that does not sound too bad. Maybe every directories added with `-I` should just be added to the findlib path?

Any thoughts on that @ejgallego?

**Comment by ejgallego** [comment]
> I realized this morning than relative paths won't do it for dune, at least if we want to preserve compositionality. Indeed, the relative path to the `META` file depends on the workspace root, so a relative path is not good enough.

Do you have a concrete example? I don't see how the relative path breaks things.

Dune properly configures findlib, so coqdep is getting the right path IIUC.

**Comment by rlepigre** [comment]
> Do you have a concrete example? I don't see how the relative path breaks things.

Sure, that's easy. Let's assume you have the following directory structure:
```
parent
└── child
    ├── dune-project
    ├── plugins
    └── theories
```
So you are working in the `child` sub-directory, which is you dune workspace root initially. So when you compile your code, the `META` files for the plugins will be in `parent/_build/install/lib/package_name/META`. So the relative path when you compile from the `theories` folder will be something like `../install/lib/package_name/META`.

Now, let's assume you add a file `parent/dune-workspace`. Now, the correct path for the `META` file is `../../install/lib/package_name/META` (note the extra `../`).

**Comment by rlepigre** [comment]
And let me add that we have that exact situation in our setup, so this does happen.

**Comment by Alizter** [comment]
More perils of relying on something in the install directory.

**Comment by rlepigre** [comment]
Yeah, and combine that with a dune cache that is not invalidated if the workspace changes, and you suddenly depend on a file that does not exist! :unamused:

**Comment by rlepigre** [comment]
After thinking a bit more about this, maybe what we want to generate as a dependency is something like `$(shell ocamlfind query -format "%m" package-name)`, which will be understood by a Makefile, and is still easy to parse for `dune`. But for a Coq makefile that will only works if the `OCAMLPATH` is set correctly (i.e., if it includes all directories specified with `-I`).

**Comment by ejgallego** [comment]
> Now, let's assume you add a file `parent/dune-workspace`. Now, the correct path for the `META` file is `../../install/lib/package_name/META` (note the extra `../`).

Yes, and what's the problem with that?

Dune will have to rebuild everything, as it should because Dune doesn't support that kind of workspace sharing when vendoring, but other than that I don't see a problem, coqdep will be rerun with the new OCAMLPATH and you'll get to point to the new META.

**Comment by ejgallego** [comment]
> More perils of relying on something in the install directory.

What are these perils? I am not aware of any peril actually, or are you saying that for example using `(package foo)` in `deps` is a peril?

**Comment by Alizter** [comment]
@ejgallego If the META file was somewhere in the build directory then we wouldn't have a rebuild. This however doesn't make too much sense and I think we should stop relying on the META all together, but that is another issue.

**Comment by ejgallego** [comment]
> @ejgallego If the META file was somewhere in the build directory then we wouldn't have a rebuild. This however doesn't make too much sense and I think we should stop relying on the META all together, but that is another issue.

You would have a rebuild because the trace of all rules changes once the workspace root changes.

You think we should stop relying on META but I don't see why you think that way.

**Comment by rlepigre** [comment]
> @rlepigre the kind of sharing you want to do folks is not possible to do with the Dune model, however as I pointed out in the Dune issue there is a different workspace configuration that does what you want. I'm moving all my projects to it, but it requires the use of some quality-of-life scripts, I'm happy to work together / discuss that, and release these scripts, we can do that in Zulip, it is not a lot of work.

What dune issue are you talking about are you talking about here @ejgallego?

I'm not sure what you're saying is true, because we do achieve that kind of sharing (provided our workspaces have a similar shape). However, the current situation is that the dune cache is trashed because the output of coqdep depends on the workspace root, and the cache hits even when the workspace changes.

What would be wrong with the fix I proposed? I also feel like relying on the `META` files is not the right approach, depending on packages seems the right thing to do. Then the build system can decide what to do with that information.

> Let me re-state the basic idea: you never vendor in your workspace, instead of compose at the top-level, and select the entries present as you need (that's where a nice script is useful)

What do you mean by "vendor in your workspace"?

**Comment by Blaisorblade** [comment]
> > Let me re-state the basic idea: you never vendor in your workspace, instead of compose at the top-level, and select the entries present as you need (that's where a nice script is useful)

> What do you mean by "vendor in your workspace"?

@rlepigre I think Emilio is talking about https://github.com/ocaml/dune/issues/6005#issuecomment-1428554489: that issue shows that if you rearrange the contents of your workspace, _today_ dune cannot cache anything (tho improvements might be possible in other cases). OTOH, if you change the _absolute path_ of the workspace, dune is perfectly happy to reuse caches, so the absolute paths in the OP aren't acceptable.

My educated guess on Emilio's idea is to change conventions so that you never need to rearrange your workspace. For instance, instead of having `main-project`, `main-project/dep1` and `main-project/dep2` ("vendor in your workspace"?), Emilio suggests something like having a `workspace` containing no code directly, `workspace/main-project`, `workspace/dep1`, `workspace/dep2`. With that convention, relative paths never change when adding/removing projects, and caching works.
