### ISSUE TITLE
`Functional Case` and `Generate graph`: document or remove?

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#16847]
Funind introduces the two currently undocumented commands `Functional Case` and `Generate graph`. Since they are now listed in the reference manual, we should decide whether they are useful and in this case document them, or if they should be removed instead.

BTW, same question for `soft functional induction`, but it has been listed in the reference manual for longer.

cc @coq/funind-maintainers

**Comment by ppedrot** [comment]
There is this longstanding obsession of mine that *funind delenda est*, since it's a lot of dubious code and we have Equations now. At some point @maximedenes even started writing a PR to remove the few places in the stdlib where we were still using it. I think that if we have obscure undocumented and unused commands in funind, they ought to be removed, the sooner the better.

**Comment by Zimmi48** [comment]
> There is this longstanding obsession of mine that _funind delenda est_, since it's a lot of dubious code and we have Equations now.

FTR, last time I heard this being discussed, @mattam82 was saying that Equations was not a complete replacement for Funind yet.

But OK, point taken. Obscure and undocumented stuff should be removed, especially if it is not used. PRs welcome.

**Comment by Matafou** [comment]
These are mostly debugging commands.

The only thing that Equation does not do is the induction principle generated by Function: it follows the pattern matching written by the user (with wildcards) instead of the compiled one. Imho removing Function without this feature would make migration quite painful for users. I think this is mostly the only reason Function is not yet removed.

**Comment by Zimmi48** [comment]
Thanks for the feedback on both aspects. Are these debugging commands that users can make use of? If yes, do you have a suggestion on how to document them?

Regarding the more general question of removing / deprecating Function in favor of Equations, should we insert a warning at the beginning of the funind chapter to explain the current situation similar to what we had for `omega` until it could properly be deprecated?

**Comment by Matafou** [comment]
To my knowledge this is mainly for the developer, not the user, even if theoretically users could benefit of them.

The problem is that the delta between Function and Equation has been there for years now. So yes we can put a warning but maybe first find a volunteer to fill the gap?
