### ISSUE TITLE
The `only parsing` and `only printing` directives of the `Notation` command do not commute.

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#17316]
#### Description of the problem

I expect the two following pieces of code to have the same semantics.
- Parsing first, then printing, both are taken into account
  ```coq
  Notation "%" := 0 (only parsing).
  Notation "%" := 0 (only printing).
  Locate "%".
  ```
- Printing first, then parsing...
   ```coq
  Notation "%" := 0 (only printing).
  Notation "%" := 0 (only parsing).
  Locate "%".
  ```
  but the parsing directive is discarded with the following message:
  ``` 
  Warning: interpretation is used neither for printing nor for parsing, the
  declaration could be removed. [unused-notation,parsing]
  ```
  which I fail to understand...

This problem was encountered by @pi8027 and I in two distinct developments.

CC @herbelin 

#### Coq Version

At least Coq 8.16.1 and coq 8.17+rc1

**Comment by herbelin** [comment]
The rule here is to inherit the `only printing` flag from an existing notation (introduced by @ppedrot in 64e7be2e, apparently in 8.6, at the time `only printing` was introduced too). I guess the idea is that if you do:
```coq
Notation "%" := 0 (only printing).
Notation "%" := 1.
```
you expect that the redefinition does not change the absence of a parsing rule for the existing notation.

With the increase of the flexibility of the onlyparsing/onlyprinting mechanism, maybe this rule can be changed.

In any case, a workaround is to do:
```coq
Notation "%" := 0 (only printing).
Notation "%" := 0 (only parsing, at level 0).
Locate "%".
```
where the `at level 0` forces defining a parsing rule (in the absence of syntactic modifiers, there is indeed an ambiguity when redefining a notation about whether one redefines only the interpretation or also the syntax).

**Comment by herbelin** [comment]
Somehow, the flag `only printing` itself is ambiguous. Currently it is attached both to interpretations and to syntax.

[Attaching it only to interpretations and have a grammar rule deactivated iff all its interpretations are deactivated would not be possible in general because we sometimes need (for recursive definitions) to reserve grammar rules even before an interpretation is given.]

For instance, in `Notation "%" := 0 (only printing).` do we want that (1) a parsing rule is created for `%` and that the interpretation of `%` as `0` is deactivated, or do we only want (2) that `%` is not activated for parsing `0`, without even creating a parsing rule for `%`? Currently, it does (2) and does not create a parsing rule (and this is why `Notation "%" := 0 (only printing).` gives a warning), but this looks a priori ok (e.g. we can use `Reserved Notation` if one really wants a parsing rule).

Maybe, the optimal strategy would then be to interpret the presence of the flag `only parsing` as an indication that we do want to create a parsing rule even though the previous declaration did not create one??

**Comment by herbelin** [comment]
However, that `only parsing` enforces the creation of a parsing rule does not give an answer here:
```
Notation "%" := 0 (only printing).
Notation "%" := 0.
Locate "%".
```
Should the second line interpreted as wanting a parsing rule or as inheriting the absence of parsing rule?

So, there are at least the following three design choices to address the ambiguity about whether a redefinition without syntax modifier should inherit or not a parsing rule:
- doing nothing (and maybe modifying the warning so that it is clearer)
- stop inheriting the absence of parsing rule in all cases
- stop inheriting the absence of parsing rule when `only parsing` is present (i.e. seeing `only parsing` as an explicit syntax modifier)

**Comment by herbelin** [comment]
Anyway, I made #17318 that currently adopts solution 3 of the last comment.

**Comment by CohenCyril** [comment]
> Should the second line interpreted as wanting a parsing rule or as inheriting the absence of parsing rule?

I would personally found it more natural if it were interpreted as a wanting a parsing rule.

**Comment by herbelin** [comment]
> I would personally found it more natural if it were interpreted as a wanting a parsing rule.

So, this makes two ok with #17318 and noone against... Maybe can we adopt it...
