### ISSUE TITLE
.vo file changes when only whitespace changed in .v file

### ISSUE THREAD

**Issue by jdchristensen** [coq/coq#17312]
#### Description of the problem

(Edited to give even simpler examples.)

If I have any of the following lines in a .v file, then the resulting .vo file changes if I insert newlines before these lines or make other trivial changes to whitespace or comments:
```coq
Ltac bar := auto.
```
```coq
Tactic Notation "foo" := auto.
```
```coq
#[export]
Hint Extern 0 (_ = _) => idtac : typeclass_instances.
```
This causes dependencies to be rebuilt by dune even though only whitespace has changed.  In files that don't contain similar lines, I can make a variety of changes (not only to whitespace, but to the ways in which a proof is constructed) and the .vo file produced is bitwise identical.  To emphasize, any one of those lines is enough to cause an issue.

The three lines above are adapted from Basics/Overture.v in the HoTT library, but I tested this in a stock Coq setting using `coqc file.v`.

#### Coq Version

8.16.1 via opam on Ubuntu 22.04.

**Comment by jdchristensen** [comment]
Is this a known issue?  Can others reproduce it?  Are there known workarounds?

**Comment by ejgallego** [comment]
Hi @jdchristensen , this is indeed a known issue; there was some discussion about it recently, but the problem is that these commands are storing file locations (likely asts) nside the .vo files. Thus, in hash-based build systems like dune, a rebuild will happen.

There are two workarounds for now, none of them satisfying:
- use a different system such as [coq-lsp](https://github.com/ejgallego/coq-lsp) which can perform finer incremental checking. That won't be of help once you save the .vo file tho, so it will only help for editing the current file,
- patch Coq as not to save the location of these commands in the .vo file.

`coq-lsp` will soon gain full project build capabilities, but the organization of Coq's "libobject" database (where the contents of .vo files are stored) needs quite a few changes as to allow coq-lsp incremental engine to support your use case across .v files.

**Comment by SkySkimmer** [comment]
Indeed ltac keeps the locations in the internalized type (which is what's stored in the vo for `Ltac` definitions and tactic notations, extern hints, and anything else that defines a tactic for use by a later command).

Most of the time those notations are unused, for instance
~~~coq
Goal True.
let _ := constr:(Prop:Prop) in
idtac.
~~~
in this example the tactic is immediately evaluated. The error is precisely located at the `Prop`.
Meanwhile in 
~~~coq
Ltac foo :=
  let _ := constr:(Prop:Prop) in
  idtac.

Goal True.
  foo.
~~~
the error is still raised with the location of the `Prop`, but because many things break when we report a location outside of the current command it is then replaced with the location of the `foo` call.

However note that AFAIK the ltac debugger uses the locations for setting breakpoints, so they're not strictly useless.

--------

Other than ltac, anything storing internalized non-kernel terms (glob_constr) will also contain locations. For instance `preterm:(foo)` in ltac2. However many things that look close are actually a related type with no locations, for instance terms in notations.

Generalizable Variable keeps the loc.

Ltac2 Notation keeps the loc.

I don't know if there are others.

**Comment by ejgallego** [comment]
@SkySkimmer you mean to close this with "won'tfix" instead?

**Comment by SkySkimmer** [comment]
With "not a bug" imo

**Comment by ejgallego** [comment]
I think this is a valid feature request, but indeed as we discussed in the call some weeks ago, we may want to handle these high-level feature requests in a different way.
