### ISSUE TITLE
Primitive integer computation loops

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#17626]
The following example loops:
```coq
Require Import Uint63.

Eval compute in of_Z.
```

**Comment by SkySkimmer** [comment]
Does it really loop or does it spend a long time producing a size 2^63 partial evaluation?

For instance if we write 
~~~coq
Fixpoint of_pos_rec (n : nat) (p : BinNums.positive) {struct n} : int :=
  match n with
  | 0 => 0%uint63
  | S n0 =>
      match match p with
      | BinNums.xI p0 => Some (p0,1%uint63)
      | BinNums.xO p0 => Some (p0,0%uint63)
      | BinNums.xH => None
      end with
      | Some (p0, b) =>
          let p0 := of_pos_rec n0 p0 in
          (p0 << 1 lor b)%uint63
      | None => 1%uint63
      end
  end.
~~~
so that the recursive call doesn't get duplicated evaluating `of_pos_rec size` works fine.

**Comment by SkySkimmer** [comment]
We could also define `of_pos_rec` with structural argument the `positive` instead of the `nat`.

Currently the structural argument is auto-inferred so I don't know if much thought has been put into it.

**Comment by silene** [comment]
> We could also define of_pos_rec with structural argument the positive instead of the nat.

Why do we even need the `nat` argument? The following definition should work just fine, shouldn't it?

```coq
Fixpoint of_pos (p:positive) :=
  match p with
  | xH => 1
  | xO p => (of_pos p) << 1
  | xI p => (of_pos p) << 1 lor 1
  end.
```

(Granted, it does not have the same semantics for very large integers, but does anyone care?)

**Comment by ppedrot** [comment]
ping @maximedenes who was the one to introduce the code. Simply writing `{struct n}` is the least invasive change, but we can also implement the above proposal.
