### ISSUE TITLE
Inductive types and recursive functions documentation needs an intro

### ISSUE THREAD

**Issue by audreyseo** [coq/coq#17786]
There is no introduction for the [inductive types and recursive functions documentation](https://coq.inria.fr/distrib/current/refman/language/core/inductive.html). Since inductive types are so useful, it would be good to motivate them better with an introduction to the section, and also why they have been grouped with recursive functions, as well as some typical use cases.

Thoughts?

**Comment by herbelin** [comment]
I don't know if someone has plans about it. Moreover, the same question somehow holds for variants too.

Here are possible header proposals otherwise.

------
## Variant types:

The Variant command allows to define types by case on the inhabitants of the type. This includes enumerated types from programming languages, such as Booleans, characters or even the degenerate cases of the unit and empty types. Variant types more generally include enumerated types with arguments or even with parametric arguments such as option types, sum types, etc. It also includes predicates or type families defined by cases such as the Boolean reflection or equality predicates. Observing the form of the inhabitant of a variant type is done by case analysis using the `match` expression.

Each case is described by a *constructor* of the type, possibly with arguments. For instance, Booleans, the unit type and the empty types are respectively defined by:
```
Variant bool : Type := true : bool | false : bool.
Variant unit : Type := tt : unit.
Variant Empty_set : Type :=.
```
The option and sum types are defined by:
```
Variant option (A : Type) : Type := None : option A | Some : A -> option A.
Variant sum (A B : Type) : Type := inl : A -> sum A B | inr : B -> sum A B.
```
The Boolean reflection and equality predicates are defined by:
```
Variant reflect (P : Prop) : bool -> Set :=
  | ReflectT : P -> reflect P true
  | ReflectF : ~ P -> reflect P false.
Variant eq (A : Type) (x : A) : A -> Prop :=  eq_refl : eq x x.
```

When constructors have arguments in the type being defined, the type becomes recursive, in which case it can be Inductive (see ...) or CoInductive (see ...). The terminology Variant is specifically used to indicate a non-recursive type defined by constructors.

## Inductive types

The Inductive command allows to define types by case on the inhabitants of the type. On the contrary of types defined by the command Variant, constructor can recursively have arguments in the type being defined. So, inductive types include natural numbers, lists, well-founded trees, etc. Inhabitants of inductive type can recursively nest only a finite number of constructors. So, they are well-founded. This distinguishes them from CoInductive types (see ...) whose constructors can be nested infinitely. In Coq, Variant types (see ...) thus correspond to the common subset of inductive and coinductive types that are non-recursive.

Due to the recursive structure of inductive types, functions on inhabitants of an inductive type have in general to be defined recursively. This is provided by the `fix` expression and the `Fixpoint` command.

----
Note: I assume here that we accept the Coq practice to declare coinductive types with several constructors, but the point of view that coinductive types should have exactly one constructor is possible (and indeed, this is the case when studying them from a more semantical isorecursive point of view).

Note: we could say that the terminology is different from OCaml, where variant types includes recursive types (and no distinction is made between inductive and coinductive types).

Note: we could also link to the section on Record types, corresponding to the unary case.

Note: is there some particular reason that `Private` is in the `Variant` section?

**Comment by Zimmi48** [comment]
> Note: is there some particular reason that `Private` is in the `Variant` section?

The idea was that we would first present the non-recursive case (variants) and everything that is associated with inductive types that is general enough to also apply to the non-recursive case, so: the `match` construct and the `private(matching)` attribute.

**Comment by herbelin** [comment]
OK, so, I guess I can try to make a PR?

**Comment by Zimmi48** [comment]
That would be wonderful!
