### ISSUE TITLE
Incorrect universe inference with SProp definitional class

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#17796]
~~~coq
Axiom S : SProp.
Class C := c : S.
(*  The term "S" has type "SProp" while it is expected to have type "Prop". *)
~~~

**Comment by herbelin** [comment]
Error also with
```coq
Axiom S : SProp.
Record C := {c : S}. (* Universe inconsistency. Cannot enforce SProp <= Top.2. *)
```
Also:
```coq
Axiom S : SProp.
Inductive C :=  c : S -> C.
About C.
(* C : Prop *)
```
but I guess this is because it is intended to be template-polymorphic and there is no other lowest choice than Prop.

Conversely, is the point that an inductive type that can be put in `SProp` should not be considered template?

For Record and Class, the decision seems to be taken around this [line](https://github.com/coq/coq/blob/ce3025d6b962b0c6e6fd109b229be615ca0e13a3/vernac/record.ml#L218) of `record.ml`, I don't know much how to fix it. Was it that this code assumed subtyping to be a total order? If yes, it should stop setting an arbitrary universe variable and hoping it would be solved by unification??
