### ISSUE TITLE
native_compute + evars or binders + primitive floats gives a proof of False

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17871]
```coq
From Coq Require Import Floats.

Definition foo : { x : float | x <> 1%float }.
Proof.
  eexists.
  native_compute. (* wat 4.653666239109102e-310%float = 1%float -> False *)
  Set Printing All. (* wat wat forall _ : @eq 0x0.055aa9c318a1p-1022%float 0x0.055aa9c318a1p-1022%float 0x1p+0%float, False *)
Abort.

Definition foo : { x : float | if (x =? 1)%float then False else True }.
Proof.
  eexists.
  native_compute. (* match PrimFloat.eqb 0x0.055aa9c318a1p-1022 0x1p+0 return Prop with
  | true => False
  | false => True
  end *)
  cbv.
  exact I.
  Unshelve.
  exact 1%float.
Defined.
```

**Comment by JasonGross** [comment]
And here's an exploit that passes `Qed` (but not coqchk, which disables the native compiler):
```coq
From Coq Require Import Floats.

Definition foo : forall x y : float, (x =? 0x0.055bbc3ac8a1p-1022)%float = true -> (y =? 0x0.055bbc3ac8a1p-1022)%float = true.
Proof.
  intros x y H.
  native_compute.
  exact_no_check H.
Defined.
Lemma boom : False.
Proof.
  generalize (foo 0x0.055bbc3ac8a1p-1022 1).
  cbv.
  intro H; specialize (H eq_refl).
  congruence.
Qed.
Print Assumptions boom.
(* Axioms:
float : Set
eqb : float -> float -> bool
 *)
```

**Comment by gares** [comment]
Cc @coq/vm-native-maintainers @proux01 @erikmd

**Comment by silene** [comment]
Presumably, when converting back terms from the OCaml world to the Coq world, `nativevalues.ml` mistakes an accumulator for a floating-point value, which means that it reads the accumulator tag as a number. So, all the binders end up being interpreted as a single value. This leads to the following variant of the last example, since the kernel can no longer distinguish `x` from `y`:

```coq
From Coq Require Import Floats.

Definition foo x y : ((x =? 0.0) = (y =? 0.0))%float.
Proof. native_cast_no_check (eq_refl (x =? 0.0))%float. Defined.

Goal False.
Proof. now generalize (foo 0.0 1.0). Qed.
```

That said, I might be completely wrong, since the variant with just `x = y` is correctly rejected. So, it seems like the example needs to involve at least a floating-point operation for the confusion to happen. But something more seems needed, since even the variant `classify x = classify y` is rejected. So, it only impacts a few floating-point operations, e.g., `x + 0 = y + 0` is wrongfully accepted.
