### ISSUE TITLE
Inconsistent behavior for `Local Ltac`

### ISSUE THREAD

**Issue by robbertkrebbers** [coq/coq#17884]
#### Description of the problem

When using `Local Ltac bar` in a module `foo`, I cannot call `foo.bar`. This is inconsistent with the way `Local Definition` behaves. Also there seems to be no way to call the local `bar` at all.

```coq
Module foo.
  Local Ltac bar1 := idtac "bar1".
  Ltac bar2 := idtac "bar2".
End foo.

Goal True.
Fail foo.bar1. (* Bad: The reference [foo.bar1] was not found in the current environment. *)
Fail bar2. (* OK: The reference bar2 was not found in the current environment. *)
foo.bar2. (* OK *)
Abort.

Import foo.

Goal True.
Fail bar1. (* OK. *)
bar2. (* OK *)
foo.bar2. (* OK *)
Abort.
```

#### Coq Version

```
The Coq Proof Assistant, version 8.17.0
compiled with OCaml 4.13.1
```

**Comment by ppedrot** [comment]
This is, at least in my opinion, the expected behaviour. The reason we have Local Definition is to strike a middle ground between the vanilla behaviour of exposing everything, and the module-based approach which is much more heavy-weight. Since there are no dependent types in Ltac (or no types at all, for this matter) there is no point in having a middle-ground approach, which is why Local Ltac hides the tactic from the API.

**Comment by SkySkimmer** [comment]
>This is inconsistent with the way Local Definition behaves

Ltac isn't Definition so that's fine

>Also there seems to be no way to call the local bar at all.

It can be called in its defining module:
~~~coq
Module M.
  Local Ltac print x := idtac x.

  Ltac print_2 := print 2.
End M.

Goal True.
  M.print_2.
~~~

**Comment by RalfJung** [comment]
Is there any way to define an Ltac in a way that it behaves like `Local Definition` -- not imported by default, but still accessible? That would be quite useful to clearly indicate "do not call this" without making debugging impossible.
