### ISSUE TITLE
replace by tac should not mask tac's failure message

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#17959]
#### Description of the problem

```coq
Goal True.
  assert_succeeds replace True with False.
  Fail replace True with False; [ | exact I ].
  (* The command has indeed failed with message:
Ltac call to "exact (uconstr)" failed.
The term "I" has type "True" while it is expected to have type "False = True".
*)
  replace True with False by exact I.
  (* Error:
Ltac call to "replace (uconstr) with (constr) (clause_dft_concl) (by_arg_tac)" failed.
No applicable tactic.
   *)
```
#### Coq Version

8.19+alpha (61ee398ed32f9334dd664ea8ed2697178e6e3844)

**Comment by SkySkimmer** [comment]
It seems to be because `replace x with y by tac` runs `first [assumption | symmetry;assumption | tac]` on the subgoal and `first` eats the error. (`first` eating the error makes sense IMO)
cf https://github.com/coq/coq/blob/61ee398ed32f9334dd664ea8ed2697178e6e3844/tactics/equality.ml#L653-L657

I think when a tactic is explicitly given by `by` we shouldn't try `assumption`, (ie `replace x with y` tries assumption but `replace x with y by tac` doesn't).

Ot maybe we shouldn't try assumption at all but that would be more likely to break scripts in the wild.

We can also avoid using `first` and use `tclORELSE0` instead to avoid eating the error without changing behaviour.

**Comment by SkySkimmer** [comment]
BTW I don't get the "ltac call  .. failed" message, I guess you have ltac backtrace in coqrc or some such thing
