### ISSUE TITLE
No explicit configuration option to suppress ide or documentation

### ISSUE THREAD

**Issue by pmetzger** [coq/coq#18131]
Howdy! I'm updating the MacPorts coq package (which is many revisions behind) and I noticed the configure flags for suppressing build of CoqIDE and the documentation are now gone. Does anything replace them?

**Comment by ejgallego** [comment]
Hi @pmetzger , yes, Coq is now an almost standard set of OCaml packages using Dune.

` make` should provide with some help, basically different options are behind different targets / packages now.

Example:
- to build just coq, `./configure $flags && dune build -p coq-core,coq-stdlib,coq` + `dune install coq coq-stdlib coq-core $install_flags`
- to also build coqide , add `coqide-server,coqide` to the previous set of packages

The documentation package is still pending due to it needed a newer dune version than we support, docs can be built with the corresponding `make` targets for documentation. Docs will be built in the document directory in the target.

Another thing to remember when using Dune is that it has a `dev` and `release` buid mode, for example the `-p` flag will enable it `release` mode.

**Comment by pmetzger** [comment]
So for the benefit of people packaging Coq without ocaml as such for various linuxes and the Mac and such, it might be nice if the Makefile had targets to do this this by simply invoking dune correctly. I can kludge it in macports to call dune directly though.

**Comment by ejgallego** [comment]
We'd be happy to add such targets to the makefile, however, in general packagers have too many requirements, so it is not easy to have targets that cover them all.

Instead, I recommended that packagers treat Coq as any other dune-based package. This has several advantages, including that now Coq can be built using common infra for all Dune packages.

I am not familiar with macports, but other distributions do already support Dune-based packages out of the box.

If macports doesn't have such a thing indeed the correct way of building is what is specified in the docs / opam file:
```
$ make help-install
 $ ./configure -prefix <install_prefix>
 $ make dunestrap
 $ dune build -p coq-core,coq-stdlib
 $ dune install --prefix=<install_prefix> coq-core coq-stdlib
```

**Comment by pmetzger** [comment]
Okay, so I tried `dune build -p coq-core,coq-stdlib,coq` from our Portfile. It doesn't seem to build the stdlib and possibly not the `coq` package itself. I can't figure out what's going on, but when I look at the `coq` package stanza in the `dune-project` file it seems to depend on the ide? And unfortunately I cannot always build the ide.

I have to say that from the point of view of a packager, the documentation here is kind of poor. I get that everything in ocamlland is getting absorbed into the dunes, but it really doesn't feel like it's particularly easy to build without the ide even if you are using dune for the build.

**Comment by ejgallego** [comment]
Note that we consider the need to `make dunestrap` a misfeature of our build system, a fix will eventually happen.

**Comment by pmetzger** [comment]
It seems to want ounit2 for example. Or at least that's listed in the dune-project file.

There is no documentation that would have told me to type "make help" or "make help-install". INSTALL.md doesn't reference either thing, nor does "README.md". How should I have known to type "make help-install"?

As for "use a package manager", I keep trying to explain that I'm the package maintainer for MacPorts. There is no one for me to go to. If I can't get this working, no one who uses MacPorts gets Coq nicely packaged for them any more.

**Comment by pmetzger** [comment]
Oh, and as for the Makefile, it would be nice if there was a target that actually did something like "dune build -p coq-core,coq-stdlib" so that it isn't necessary for my package manager to install a script that does that but can just run a sequence of make targets. It's not strictly necessary of course.

**Comment by ejgallego** [comment]
> It seems to want ounit2 for example. Or at least that's listed in the dune-project file.

Indeed, that's close to #7146 , ounit is required to run the test-suite (as dune-project reflects), but indeed we should improve the documentation there, but I'd say this falls in the category of `dev/doc`.

> There is no documentation that would have told me to type "make help" or "make help-install". INSTALL.md doesn't reference either thing, nor does "README.md". How should I have known to type "make help-install"?

Typing `make` will print the help, we thought that would be easy to discover, if not, instructions are fully detailed in `INSTALL.md` tho. Did you see anything missing there?

> As for "use a package manager", I keep trying to explain that I'm the package maintainer for MacPorts. There is no one for me to go to. If I can't get this working, no one who uses MacPorts gets Coq nicely packaged for them any more.

My point is that MacPorts could have a generic recipe for dune packages, that should be easily used by any OCaml package that uses Dune including Coq.

> Oh, and as for the Makefile, it would be nice if there was a target that actually did something like "dune build -p coq-core,coq-stdlib" so that it isn't necessary for my package manager to install a script that does that but can just run a sequence of make targets. It's not strictly necessary of course.

We just to have that (see the release target) but turns out it never exactly met what packagers need, so we think it is better to have them call `dune` as they need.

**Comment by SkySkimmer** [comment]
>My point is that MacPorts could have a generic recipe for dune packages, that should be easily used by any OCaml package that uses Dune including Coq.

But we're not a generic dune package because of the dunestrap thing.
I don't remember, was there a reason not to make the generated files (promote)?

**Comment by ejgallego** [comment]
> But we're not a generic dune package because of the dunestrap thing. 

We could do this step in configure actually, so in this sense we are a generic dune package with a configure step; that's fine AFAICT, in the sense that all upstream packagers dune helpers I know do support this workflow of adding the conf step.

> I don't remember, was there a reason not to make the generated files (promote)?

I guess not willing to check auto-generated files in the CI; also we were convinced that Dune will fix `(:include )` to support our use case, but the PR got stuck last time I looked into it.

That's a bit of a pity as otherwise you can do what you need from ML very easily, it is just the surface language which doesn't support that.

**Comment by SkySkimmer** [comment]
Not sure what the status of this issue is but doesn't seem useful to leave it open.

**Comment by pmetzger** [comment]
The status is we haven't updated Coq in MacPorts in a long time, and we might not do so any time soon. It's not particularly easy to build, it's not particularly obvious how to build it, and even as a packager I find the problems challenging.
