### ISSUE TITLE
Documentation of `Instructions` should mention lack of support on i386

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#18257]
The documentation of the `Instructions` command from https://github.com/coq/coq/pull/17744 says https://github.com/coq/coq/blob/d52b7876c48f2b0c241acec1f7388ff7ac110470/doc/sphinx/proof-engine/vernacular-commands.rst?plain=1#L864-L869

According to [my packaging logs](https://launchpadlibrarian.net/696184695/buildlog_ubuntu-bionic-i386.coq_8.master~git~202311042302+24407-0~daily388-4e66de6e0f~ubuntu18.04.1_BUILDING.txt.gz), this doesn't seem to be quite accurate; `usr/lib/ocaml/stublibs/dllcoqperf_stubs.so` is installed only on x64 Linux, not on i386 systems.  While I haven't checked that this makes `Instructions` non-functional, it seems quite likely (please correct me if this is not the case).  I think either the documentation should be updated with this limitation, or the build/install should be fixed.

cc @rlepigre

**Comment by rlepigre** [comment]
That seems really odd: I was convinced that the `linux/perf_event.h` header would be available on all architectures on Linux. If it is not, the compilation of the perf bindings in Coq (and hence of Coq itself) should fail completely on that architecture and that sound pretty bad. If it is, I don't get how it is possible that `dllcoqperf_stubs.so` does not get installed as on x64. Unfortunately, I can't test since I don't have an i386 system on hand.

If we need to restrict the perf support to some architectures, we can do something like the following:
```diff
diff --git a/perf/dune b/perf/dune
index 2105e9bf37..382e9385ea 100644
--- a/perf/dune
+++ b/perf/dune
@@ -4,4 +4,10 @@
  (public_name coq-core.perf)
  (wrapped false)
  (foreign_stubs (language c) (names perf))
- (enabled_if (= %{system} linux)))
+ (enabled_if
+  (and
+   (= %{system} linux)
+   (or
+    (= %{architecture} amd64)
+    (= %{architecture} xxx)
+    (= %{architecture} yyy)))))
```

**Comment by JasonGross** [comment]
Can we print out the value of `%{system}` in `./configure` or something?  (Have it say "building perf / not building perf because system is %{system}" or w/e?). Maybe i386 has a more esoteric value of system, a la https://github.com/thierry-martinez/pyml/issues/68

**Comment by JasonGross** [comment]
See also https://discuss.ocaml.org/t/a-zoo-of-values-for-system/8525/4.  Can we decide based on the presence / compilation success of a test file using `linux/perf_event.h`, in the standard autoconf / configure way, rather than testing `%{system}`?

**Comment by rlepigre** [comment]
The value of `%{system}` directly comes from the output of `ocamlc -config`, so it should be easy to test its value. According to what I read in https://github.com/ocaml/dune/issues/4895, a reasonable fix could be something like what is done [here](https://github.com/talex5/eio/commit/2fa5bc474f3ee8cf7b818aba2c708cb1ed768ff1), which means:
```diff
diff --git a/perf/dune b/perf/dune
index 2105e9bf37..d0d476c984 100644
--- a/perf/dune
+++ b/perf/dune
@@ -4,4 +4,11 @@
  (public_name coq-core.perf)
  (wrapped false)
  (foreign_stubs (language c) (names perf))
- (enabled_if (= %{system} linux)))
+ ; (enabled_if (= %{system} "linux")))
+ ; See https://github.com/ocaml/dune/issues/4895
+ (enabled_if
+  (or
+   (= %{system} "linux")        ; Linux-x86
+   (= %{system} "linux_eabihf") ; Linux-arm32
+   (= %{system} "linux_elf")    ; Linux-x86_32
+   (= %{system} "elf"))))       ; Linux-ppc64
```
Also, it seems that https://github.com/ocaml/ocaml/pull/12405 makes it so that we'll consistently get `linux` starting with OCaml 5.2.

**Comment by JasonGross** [comment]
That fix looks good to me.  According to [my logs](https://launchpadlibrarian.net/696341422/buildlog_ubuntu-xenial-i386.coq_8.master~git~202311052322+24408-0~daily391-d52b7876c4~ubuntu16.04.1_BUILDING.txt.gz) system on i386 is indeed `linux_elf`. Do we want any of the other ones (the complete list is beos, bsd, bsd_elf, cygwin, dragonfly, elf, freebsd, gnu, linux, linux_eabi, linux_eabihf, linux_elf, macosx, mingw, mingw64, netbsd, openbsd, solaris, unknown, win32, win64 as per [here](https://github.com/ocaml/ocaml/blob/12523517cf5c6c782563f8b76e661b67748e010b/configure.ac#L1044-L1132))?  

Although feature testing rather than OS name testing still seems like a better solution to me.  (Does `dune` have it's own replacement for `./configure`-like feature testing?  cc @ejgallego / @coq/build-maintainers )

**Comment by rlepigre** [comment]
OK, I created an MR (linked above), and took all the Linux variants (`linux_eabi` was missing according to your list). Other values do not indicate a Linux system as far as I can say.

We could perhaps do something at configure time, but I would not be super confident to get it right.
