### ISSUE TITLE
Array pretyping introduces unnecessary universe constraints

### ISSUE THREAD

**Issue by yannl35133** [coq/coq#18480]
#### Description of the problem
```coq
Require Import PArray.
Universes u v.

Definition a : array@{v} nat := [| | 0 |]@{u}.
Print Universes Subgraph (u v).
(* Set < u, Set < v *)
Definition b : array@{v} _ := [| | 0 |]@{u}.
Print Universes Subgraph (u v).
(* Set < u, Set < v, v <= u *)
```

This additional constraint is added here:
https://github.com/coq/coq/blob/db93e18bd758c68f62753392b8606f2f089f8294/pretyping/pretyping.ml#L1390

#### Coq Version
8.18.0, 8.20+alpha

**Comment by SkySkimmer** [comment]
The univ variable on the array literal is needed so that we can give it a type when algebraics are involved, eg `[| | nat : Set |]` needs a univ to put in the instance for `array@{??} Set` (we can't use `Set+1` since it's algebraic).

If we required that `array` is always fully applied we could eliminate the instance (like template poly, so `array Set : Set+1`) but we currently don't have a notion of "always fully applied constant".

While keeping the instance I guess the only option is to do retyping if we want to keep bidirectionality. Or we can accept the constraint, it's basically like doing 
~~~coq
Definition a : array@{v} (nat:Type@{v}) := [| | 0 |]@{u}.
~~~
and there we have to produce the constraint if we want to keep bidi I think (ie the `0` is typechecked with expected type `nat:Type@{v}` and therefore returns that casted nat as its type).

**Comment by SkySkimmer** [comment]
>While keeping the instance I guess the only option is to do retyping

ie https://github.com/coq/coq/pull/18481
