### ISSUE TITLE
Single-branch match expressions not being properly simplified.

### ISSUE THREAD

**Issue by dragazo** [coq/coq#18912]
### Description of the problem

There are some cases where single-branch match expressions fail to simplify. For instance, given the following definition:

```coq
Inductive foo : Type := | A | B | C.
```

The following match expression (where `x` is an arbitrary instance of `foo`) fails to simplify `match x with | A | _ => B end` despite the fact that this clearly should always result in `B`. If the wildcard is used alone like `match x with | _ => B end`, this works, but the first should also work.

I think a special case for simplifying single-branch match expressions could be added to fix this.

### Small Coq file to reproduce the bug

```coq
Inductive foo : Type :=
    | A | B | C.

Goal forall (x: foo), match x with | A | _ => B end = B.
Proof.
    intros.
    simpl. (* this fails to simplify *)
    reflexivity. (* which causes this to fail *)
Qed.
```

### Version of Coq where this bug occurs

8.19.1

**Comment by silene** [comment]
As explained on Discuss, this is not a bug.

**Comment by dragazo** [comment]
I don't see how this could possibly not be considered a bug. Any expression of form `match <expr 1> with | <pattern> => <expr 2> end` is incontrovertibly and trivially equivalent to `expr 2` (possibly using destructed terms of `pattern`).

**Comment by ppedrot** [comment]
@dragazo decidability of type-checking in presence of definitional η-expansion for non-recursive inductive types is an open problem. If you happen to know how to prove it, I know a few persons that would be interested.

**Comment by dragazo** [comment]
@ppedrot This isn't solving the general problem of decidability. This is a very specific case where there is a pattern match that contains only a single branch/outcome. That's certainly not an open problem.

**Comment by ppedrot** [comment]
> This is a very specific case where there is a pattern match that contains only a single branch/outcome

That's precisely the one case that corresponds to η-expansion, and as trivial as it sounds, it's definitely an open problem.

**Comment by Janno** [comment]
I really wonder if the bug report and/or the discussion are conflating two separate versions of `match`: Coq's pretyper (I think, I couldn't find the exact place where this happens) turns `match x with _ => y end` into just `y`. This step is not performed by any reduction or simplification engine because there is no actual, proper term of the form `match x with _ => y end`. It is merely an illusion at the level of parsing.

Any naming of even just a single one of the constructors will produce an actual `match` term. AFAICT all these terms here are actually identical once Coq interprets them:
```coq
match x with | A | _ => y end
match x with | B | _ => y end
match x with | A | B | _ => y end
match x with | A | C | _ => y end
match x with | B | C | _ => y end
match x with | A | B | C | _ => y end
```
and they are all printed as `match x with | A | _ => y end` or, with `Set Printing All` or just `Unset Printing Allow Match Default Clause`, as `match x with | A => y | B => y | C => y end`.

This doesn't change the facts discussed in previous comments but maybe it will help other people who were as confused as myself when I started to look into this. The fact that the "volatile" version of matches exist at the syntax level is often useful for notation hacks. Unfortunately this volatility also makes them very surprising and weirdly special compared to very similar looking match terms.

**Comment by dragazo** [comment]
Although if simplifying single-arm matches is not ok, why is `match x with _ => y end` being parsed as just `y` ok? Is it just because it doesn't name any constructors and so `y` can't be a function of any un-introduced destructed terms of `x`?

I mean I'll trust all of you in that this reduction can't be done, but I'm having trouble coming up with a counter example to make it make sense. So it's just very confusing given how simple it (falsely) appears to be...

**Comment by silene** [comment]
You are comparing simplification (which we prefer to call reduction and/or conversion), which happens inside the logical system according to its rules, with parsing, which happens once and for all at the beginning, before the logical system is even involved. So, the fact that the latter is OK does not make the former OK, since their relation is tenuous at best. (And whether the latter is actually OK is debatable. As far as I am concerned, this was an ill-advised choice.)

As for why `match x with _ => y end` is parsed as just `y`, it is a consequence of the way complex pattern matching (which only exists in the surface language) is transformed into the primitive one which exists in the logical system. The motivation was that the following code
```coq
match x, y with
| O, _ => true
| _, O => false
| S x', S y' => rec x' y'
end
```
would be compiled as
```coq
match x with
| O => true
| S x' => match y with O => false | S y' => rec x' y' end
end
```
instead of
```coq
match x with
| O => match y with O => true | S _ => true end
| S x' => match y with O => false | S y' => rec x' y' end
end
```

**Comment by lrworth** [comment]
I'm working through Logical Foundations and encountered this same problem. I can _sort of_ understand the problem but the book has not covered this stuff yet, and perhaps adding some beginner-friendly explanation to this thread could help someone in the future.

It seems that in `match x with | A | _ => B end` the `_` would match no matter what `x` is, so the whole expression should be judgmentally equal to `B`. Why is this not the case? My guesses:
- `x` is not necessarily of the same type as `A` — though in the example code we have `forall (x: foo)` so this shouldn't be a problem
- `x` could be undecidable — it _seems_ that `forall (x: foo)` with finite `foo` should refute this

Where am I going wrong?

**Comment by SkySkimmer** [comment]
For instance `match x as y return y = tt with tt => eq_refl tt end` cannot be reduced to `eq_refl tt`, because `eq_refl tt : tt = tt` does not have the required type `x = tt` when `x` is unreducible (typically a variable in the context).

While we could imagine checking that the return predicate is constant before reducing, I don't know if that would produce a well behaved theory and anyway it would be costly. So we only reduce matches when the thing being matched reduces to a constructor.
