### ISSUE TITLE
github: Projects (classic) will be sunset on August 23, 2024

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#19156]
Does our backport & milestone automation work with new projects?

**Comment by Zimmi48** [comment]
Thanks for raising the issue! I hadn't noticed the alert yet.

>Does our backport & milestone automation work with new projects?

It doesn't. The whole API is different. The sunset announcement includes a different timeline for the REST API of Projects (classic) and doesn't say anything about the GraphQL API (the API has not been marked as deprecated yet). So the automation may or may not keep working for a few more months. However, migrating sooner would be better and safer.

This was my plan for migrating to Projects V2: https://github.com/coq/bot/issues/278.

Something even more urgent to fix is https://github.com/coq/bot/issues/303. We only have until the end of June to deal with it. It looks like migrating to the Project V2 API would be sufficient to fix this, but given the short timeline, it seems likely that an intermediate (but easier to implement) step will be required.

**Comment by Zimmi48** [comment]
There's actually another issue affecting us already, which is that the creation of new projects (classic) has been disabled since May. This means that for the upcoming 8.20 project (branching supposed to happen today), we cannot create a new project.

There are two options:

1. we somehow manage to migrate to Projects V2 *today*
2. we repurpose an existing project (classic) to be the 8.20 release management project until we can migrate to Projects V2, probably during the summer.

I should clearly not be working on this right now given the other urgent things that I have to do, but given that we will anyway have to do the migration at some point soon, it would be cleaner to do it from the beginning for 8.20. So I will spend a few more hours on this topic today, trying to see if I can accomplish (1), otherwise I will implement (2).

cc @proux01

**Comment by SkySkimmer** [comment]
What was it before being repurposed?

**Comment by proux01** [comment]
RM 8.13

**Comment by Zimmi48** [comment]
This was a very small project related to RM for 8.13, but the main one (for tracking backporting) was https://github.com/coq/coq/projects/43 actually and has been preserved.
