### ISSUE TITLE
Strange error location in coqtop

### ISSUE THREAD

**Issue by Matafou** [coq/coq#19355]
### Description of the problem

The error location in `coqtop` (didn't test in other interaction mode) usually gives the error location with character location *inside the last command*, for instance:

```coq
Unnamed_thm < rewrite toto.
Toplevel input, characters 8-12:
> rewrite toto.
>         ^^^^
Error: The variable toto was not found in the current environment.
```
the position (8-12) refers to current command only. But I found at least one situation where the location is completely wrong (probably counting from the "beginning"?)

```
Welcome to Coq dell-5750-Matafou:/home/courtieu/coq/v8.20/_build/default,v8.20 (a27916b9cff870b2a8b1819adb4a1a7dd05c74fe)

Coq < Goal True.
1 goal
  
  ============================
  True

Unnamed_thm < }
Toplevel input, characters 11-12:
Error: The proof is not focused

Unnamed_thm < }
Toplevel input, characters 13-14:
Error: The proof is not focused

Unnamed_thm < 
```

Each attempt to write the wrong command again gives a increasing location.

We would like to rely on his poosition information to locate error reliably in ProofGeneral, so this is a bit annoying.
I 

### Small Coq file to reproduce the bug

```coq
Goal True.
}
```

### Version of Coq where this bug occurs

8.20

**Comment by SkySkimmer** [comment]
I guess the `<` at https://github.com/coq/coq/blob/65ff3388b4076eed7720a45b21be13515deb54fc/toplevel/coqloop.ml#L143 is too strict and should be `<=`. With that fixed on
~~~coq
Goal True.
}
}
~~~
we get "toplevel input, characters 0-1:" for the first `}` but the second gets "characters 2-3".

In fact any command immediately following `}` has locations off:
~~~coq
Goal True /\ True.
split. { exact I. }
exact 0. (* characters 26 - 27 *)
exact 0. (* characters 6-7 *)
~~~

AFAICT this is because https://github.com/coq/coq/blob/65ff3388b4076eed7720a45b21be13515deb54fc/toplevel/coqloop.ml#L39-L47 relies on the newline character after the latest command having been read (for https://github.com/coq/coq/blob/65ff3388b4076eed7720a45b21be13515deb54fc/toplevel/coqloop.ml#L65), which seems to be the case when parsing commands ending in `.` but not for `}`.

The lexer always peeks after seeing a `.`, maybe we can just add a peek after `}` to force reading the newline?
Coq will still be confused if there's a space between `}` and newline but that's already the case if there's a space between `.` and newline. IIUC PG strips ending spaces for this already.

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/19363

**Comment by Matafou** [comment]
Now that we want to rely on this info: yes indeed we remove blanks at the end of a command before sending it to coqtop.

**Comment by Matafou** [comment]
Is this problem also present in serapi and other protocols?

**Comment by ejgallego** [comment]
> Is this problem also present in serapi and other protocols?

AFAICT this problem is exclusive to `coqtop`.
