### ISSUE TITLE
Check takes forever in presence of type classes, whereas About does not

### ISSUE THREAD

**Issue by Matafou** [coq/coq#5977]
#### Version
8.7
8.6

#### Operating system
Linux

#### Description of the problem

The check at the end of this code never returns. Note that About does return instantly.

```coq
Require Import SetoidDec.
Generalizable All Variables.
Class FSet `{EqDec key} :=
  {
    set : Type;
    In : key -> set -> Prop;
  }.

Check In.
```
PS. This is code originates from S. Lescuyer container library.

**Comment by herbelin** [comment]
Note that `Check @In` succeeds and `Lemma lemma : In = In.` loops (or at least is very long).

`Set Debug Typeclasses` suggests that it is indeed a loop on the following application:
```
Debug: 2.4-1.4-1.4-1.4-1.4-1.4-1.4-1.4-1.4-1.4: simple apply @bool_function_eqdec on (EqDec (eq_setoid ?A)), 1 subgoal(s)
```
where `bool_function_eqdec` recursively expects to find an instance for `EqDec (eq_setoid ?A)`.

**Comment by mattam82** [comment]
I think this indicates We should set the mode of EqDec in the library using Hint Mode EqDec + : typeclass_instances. Does it solve your problem?

**Comment by Matafou** [comment]
Indeed any of this seems to solve the issue:

```Hint Mode EqDec + + : typeclass_instances.```
```Hint Mode EqDec + - : typeclass_instances.```
```Hint Mode EqDec ! - : typeclass_instances.```
```Hint Mode EqDec ! + : typeclass_instances.```
```Hint Mode EqDec ! ! : typeclass_instances.```

Now I need to understand what this means :).

Remark: Are we happy with "Check" showing existentials and "About" showing the real type? I would expect the reverse.
￼

**Comment by herbelin** [comment]
> Remark: Are we happy with "Check" showing existentials and "About" showing the real type? I would expect the reverse.

Personally, I'm happy that `Check` inserts maximal implicit arguments, in the sense that `Check` takes an arbitrary term as argument and behaves consistently with what one would get by using e.g. `Definition`, but I heard complaints about the fact that `Check` shows unresolved existentials, if that is the question. In the latter case, maybe could be provide too variants of `Check` (e.g. `ECheck` vs `Check`)?

**Comment by Matafou** [comment]
What do you mean by "inserts maximal implicit arguments"? About also shows the implicit arguments doesn't it?

**Comment by herbelin** [comment]
`Check` takes an expression as argument, "elaborates" it into a constr and returns it with its type (when typable). In the process of elaboration (i.e. interning + pretyping), it adds maximal implicit arguments whenever needed, so `Check` adds them to `In`, and try to infer them since these arguments are typed in a class. `Check` does not report about implicit arguments per se. `Check` is about type-checking, not about reporting informations attached to a global reference.

`About` takes a global reference as argument. It reports about the implicit arguments declared for this reference, about its type, and about many other attributes of this reference. `About` is not about type-checking.

It happens that this basically coincides when giving to `Check` a global reference without maximal implicit arguments, but the intent and the processus are different.

**Comment by Matafou** [comment]
It make sense. It is just very ugly when unsolved implicits are there.

**Comment by SkySkimmer** [comment]
So do we want to change this behaviour (I guess we could avoid solving typeclasses in Check)? If not we should close the issue.

**Comment by Matafou** [comment]
I think we can let things as they are now. And advertise “About” a bit more.

Le ven. 30 mars 2018 à 16:42, Gaëtan Gilbert <notifications@github.com> a
écrit :
