### ISSUE TITLE
Augmenting the truck factor of Coq by reducing its dependencies

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#6017]
Camlp5 is a critical component of Coq. It is used for two different purposes.
- As a parsing engine for the Coq language. We depend so much on its quirks that switching to another engine would definitely break grammar rules in the wild.
- As a macro language for OCaml. There are four subcases.
  - Definition of grammar rules per se with the GEXTEND macro, provided by Camlp5 distribution.
  - Coq-specific TACTIC EXTEND.
  - Coq-specific VERNAC EXTEND.
  - Coq-specific ARGUMENT EXTEND.

Camlp5 t is a behemoth library that does a lot of unrelated things, and thankfully the only part that one cannot really change is the parsing engine itself. More generally, Camlp5 is tied to the OCaml AST and therefore is very brittle. It is broken by virtually any OCaml release. Also, it is expanded on a by-need basis and doesn't handle all of the OCaml syntax.

Camlp5 is currently ~160kloc (compared to ~610kloc for Coq). We only really need the LL(1) parser which fits in about 2.5kloc.

The Master Plan.
- Get rid of Coq-specific macros.
- Get rid of GEXTEND.
- Integrate the engine part of Camlp5 into Coq. It is a relatively small piece of code that is much less fragile than the whole Camlp5.
- Get rid of Camlp5.

The first two points are solved by writing our own extension parser for Coq. It's actually pretty-much straightforward and done.

The second plan is not very complicated technically. It would perhaps be nice to have the work done by @roglo, so that he provides us with just the parsing engine as a separate package.

**Comment by ejgallego** [comment]
I am extremely confused about the title of this PR, as in particular, I have been running Coq with 4.06 for quite a while...

**Comment by ejgallego** [comment]
I am also disagreeing on getting rid of camlp5, it seems to me that the remedy is going to be worse than the problem here.

**Comment by jhjourdan** [comment]
Is there a reason why Camlp5 cannot use Bytes instead of String ?

**Comment by ppedrot** [comment]
@ejgallego Look at [my branch](https://github.com/ppedrot/coq/blob/camlp5-parser/grammar/gramext_parse.mly) to see that the code required for our own parser is ridiculously small compared to [what Camlp5 needs to do](https://github.com/camlp5/camlp5/blob/master/etc/pa_o.ml).

**Comment by ppedrot** [comment]
Also, I stand corrected, indeed Camlp5 does seem to compile on 4.06. That said, the criticism against the fact it is a huge library for tiny needs is still valid.

**Comment by ejgallego** [comment]
@ppedrot either rename this issue or get it closed as I repeat, Coq runs very well in 4.06 and very few of your reasons seem to be valid.

**Comment by ppedrot** [comment]
For the record, Camlp5 is currently ~160kloc compared to ~610kloc for Coq while we only really need the LL(1) parser which fits in about 2.5kloc.

**Comment by ejgallego** [comment]
You should also edit the issue main text as it contains quite a few factual mistakes.

**Comment by ejgallego** [comment]
> For the record, Camlp5 is currently ~160kloc

Is that number including all the OCaml cut&paste interfaces. If so, that is not a fair comparison.

**Comment by roglo** [comment]
Camlp5 compiles with -warn-error A, so there are no problems with the Byte and String. It was taken into account some months ago.

**Comment by ppedrot** [comment]
Fine then. But do you think it would be still possible to provide the parsing engine alone? This would be a much stabler package than the whole machinery to manipulate OCaml ASTs...

**Comment by maximedenes** [comment]
I find the communication around this suboptimal to say the least. The final aim is not to "get rid of camlp5", but to better interface with it, and separate concerns. The camlp5 of today implements (at least) two orthogonal features: preprocessing of augmented OCaml syntax, and extensible parsing. We currently use both but the claim we make here is that we fundamentally need only the later. So we should try to work with @roglo to see if we could depend only on the extensible parsing engine, which is a much smaller than the entire camlp5. @roglo, do you like the idea?

**Comment by ejgallego** [comment]
> I find the communication around this suboptimal to say the least.

Indeed I urge we are more careful with communication, in particular the very festive and joking tone we love to use sometimes in meetings may be totally misunderstood outside of them.

I agree with @maximedenes in that the goal is not to stop depending on camlp5, a tool which has been invaluable for Coq development. However, for some time there has been a feeling than depending on the internal OCaml parsetree was a bit inconvenient now that OCaml is shipping a new release every 6 months. It turns out that Coq use of macros is simple enough as to be decoupled of OCaml's syntax, so indeed the idea of moving to a custom macro system could be worth the improved OCaml compatibility time.

However, I am not sure the role this issue plays exactly, so indeed I am proposing we close it and instead do:

- Discuss the new Coq macro language on its own pull request.
- Open an issue in camlp5/camlp5 's repository to propose to @roglo a modular build system so the parsing engine can be built without the dependency on the OCaml parse tree so Coq could be liberated from that dependency.

What do you think folks?

**Comment by ppedrot** [comment]
@ejgallego LGTM indeed.

Also, I might have opened this PR too much in a rush, and I'm definitely not good at PR (public relations, whoo, polysemy). Although I doubt @roglo has taken offense, my intention was not to troll him about CamlpX whatsoever.

Thence let's close this PR.

**Comment by roglo** [comment]
I don't understand what you mean with separating the parsing engine of Camlp5. It is already separated. It is grammar.ml. And you really need the syntax with GEXTEND since if you remove it, you cannot use the extensible grammars for Coq, the generated code of GEXTEND being too complicated to be manipulated. Camlp5 is very small, I don't understand why you want it to be smaller.

**Comment by maximedenes** [comment]
I believe that what @ppedrot means is: the parsing engine is much less tightly coupled to specific OCaml versions than the syntax extensions of Camlp5 are. So having, say, a separate target to build only the parsing engine (from which we could make a package) would be convenient for us. That build target would have more relaxed constraints on the version of OCaml. Does it sound feasible?

As for the few uses of `GEXTEND` we have, they are either circumventing limitations of the Coq API (like in ssreflect), so we could work on improving the API, or they implement a full parser (for terms, for example), but that doesn't really require to parse OCaml syntax (Pierre-Marie wrote a small tool that relies on simple delimiters, if I understood correctly).

**Comment by ppedrot** [comment]
@roglo Yes, indeed, it is `grammar.ml`. I meant is that it would be better from a separation of concerns point of view to have it shipped as a standalone library. In practice, we rely heavily in Coq on the fact that the parser is extensible, and apart from a few hard-written GEXTEND files, we actually generate the parsing rules programatically, not through the parsing extension. Also, the API is type-unsafe and we rely on a safe wrapper implemented with GADTs.

**Comment by ejgallego** [comment]
Indeed @roglo , I guess we would like to have a way not do depend on OCaml's AST interface so Coq is easier to test with OCaml's `trunk`; on the other hand `grammar.ml` is written in `camlp5` , so I am not so sure it will be easy to decouple from the AST.

**Comment by roglo** [comment]
Sorry I still don't understand. Camlp5 is the minimum. If you remove something, you cannot use the extensible grammars feature.

**Comment by ppedrot** [comment]
@roglo No, that's not true. In the Coq implementation, term and tactic notations call directly the Grammar API at runtime through `Gram.extend`, without ever generating code. This is what I meant by programatically.

**Comment by roglo** [comment]
This is not a question of Camlp5 but how Camlp5 was used in Coq. If a Coq programmer used Gram.extend directly, it is a bad use of Camlp5.

**Comment by ppedrot** [comment]
> If a Coq programmer used Gram.extend directly, it is a bad use of Camlp5.

@roglo This is the key feature of Camlp5 instead. Most other parsing engines in the wild are static, while we crucially rely on a dynamically extensible parser. From the top of my head, the only other dynamic parser in OCaml I know is dypgen.

**Comment by maximedenes** [comment]
@roglo, I think you underestimate the power and usefulness of the extensible parsing engine of Camlp5 :) But maybe I misunderstood, why do you say it is a "bad use"?

**Comment by maximedenes** [comment]
> is written in camlp5

@ejgallego you mean in the revised syntax ? But it is easy to port it to the standard OCaml syntax, PMP already did it.

**Comment by herbelin** [comment]
> you mean in the revised syntax

By the way, even if this means going in the direction of more camlp5, what about using ourselves a bit of the revised syntax? As far as I could understand, it is less prone to errors (e.g. with nested "match"), and care for robustness is an argument that I hear often about Coq, thus worth to be taken into account.

Would it thus be good for the community that we give an example of such good practices?

**Comment by gares** [comment]
> what about using ourselves a bit of the revised syntax

`do { Have do { you do { ever tried }}}` ?  ;-)

**Comment by roglo** [comment]
Because Gram.extend is ill typed. You need to add Obj.magic and type constraints to be correct. It is what GEXTEND does. The statement GEXTEND generates a call to Gram.extend. If you use Gram.extend directly without adding the Obj,magic and type constraints at the good places correctly, you get memory faults at run time.

**Comment by maximedenes** [comment]
Yes, but like Pierre-Marie said, the interface we use can be made type safe using GADTs. And it's even elegant! So I guess we could work on a type safe interface for the extensible parser. How does it sound?

**Comment by roglo** [comment]
GADT did not exist when I programmed Camlp4. When they added it, I tried to change that, but it is a lot of work. And I am not so sure it is possible. It has to be tested.

**Comment by roglo** [comment]
It is also easy to port OCaml syntax, which is confusing, into the revised one. Do you want me to explain the list of the problems of "normal" syntax?

**Comment by maximedenes** [comment]
> GADT did not exist when I programmed Camlp4

Yeah, sure, it was not a complaint. Rather, an opportunity for improvement now that they are here.

> tried to change that, but it is a lot of work. And I am not so sure it is possible. It has to be tested.

I guess @ppedrot could evaluate the work. And of course, we could participate.

**Comment by maximedenes** [comment]
> Do you want me to explain the list of the problems of "normal" syntax?

Not necessary, thank you. I daily use programming languages for which I don't like some aspects of the syntax (including OCaml indeed). I can't change what other people use, so I live with it because I want to communicate with them, and usually I don't care so much in the end.

**Comment by roglo** [comment]
> I can't change what other people use [...]

You are right. Don't change the world. It is very good as it is. For example, don't try to put GADTs in Camlp5, since it is a change that nobody cares.

**Comment by maximedenes** [comment]
> For example, don't try to put GADTs in Camlp5, since it is a change that nobody cares.

Really? You wrote above that you tried earlier, so I thought you cared. I'm a bit lost. I have the feeling that the syntactic debate is interfering with this discussion, which has essentially nothing to do with it.

**Comment by roglo** [comment]
> Really?

Perhaps you did not understand the irony of my previous post.

> interfering with this discussion, which has essentially nothing to do with it

In that case, it was not necessary to add fuel to the fire.

**Comment by maximedenes** [comment]
> Perhaps you did not understand the irony of my previous post.

Indeed, but that's good news. It means we could try to generalize the GADT-based interfaces we use in Coq to the one of camlp5's extensible parser.

> In that case, it was not necessary to add fuel to the fire.

Sorry, but I have nothing to do with the exchanges between @herbelin and @gares that were unrelated to this discussion.

**Comment by ppedrot** [comment]
@roglo Actually you don't even need GADTs to make the grammar API type-safe. GADTs are only needed to make the *implementation* type-safe. The transition is fairly easy, you can have a look at [extend.ml](https://github.com/coq/coq/blob/master/intf/extend.ml#L69) to see how it's possible to have type-safety.

**Comment by ejgallego** [comment]
> But it is easy to port it to the standard OCaml syntax, PMP already did it.

Well, but that is a pretty big change that goes beyond just modularizing camlp5, isn't it?

**Comment by maximedenes** [comment]
Big, I'm not sure, but controversial certainly. So I suggest we separate the two issues. @ppedrot is preparing a patch to make camlp5 expose the type safe API without changing the syntax.

**Comment by herbelin** [comment]
Sorry, the following message is a bit transversal to the interesting discussion on GADT and type safety in camlp5, but I cannot not react to @gares, whose joke is excellent (and which I hope  Haskell people will also appreciate!) but whose splitting effect cannot remain unanswered.

So, to be serious, I never really tried the revised syntax, and, personnally, I'm enough used to the current syntax of ocaml for not needing a change. My remark was mainly to add some balance in the discussion and to remember that, long time ago, the culture of taking time to listen to opinions of others, such as a platform like github allows these days, was not as well developed, and that some suggestions about the syntax of ocaml, though perfectly relevant, unfortunately did not make their way, with the attempts we see now a posteriori to compensate the small overlooks of the past with recommendations to e.g. overuse `begin`/`end`, and so on... `begin what; begin did; you; already; say; begin about; that; end end end`? ;-)

Well, let's not also forget that camlp5 comes with skeletons in the closet - like ssreflect actually - and that the only reasonable way I see to get out of the irrationality that led to these skeletons is to set things down factually and constructively as the current discussion is doing, with, in my opinion, a pretty great success sofar (and at least with a success which contrasts with the hyperemotionality of yesterday and with the rudeness from two week ago at some PR open on camlp5 github site).

Otherwise, about using the revised syntax, I'm sure Coq has enough impact to play a role in diffusing it if one really would like to. After all, software projects work also a lot by mimetism, isn't it? But is there a strong enough motivation to change a syntax which we are now used to, it is however unclear.

**Comment by JasonGross** [comment]
Reading this, it seems like there might still be a bit of miscommunication.  Here is what I'm reading:

@ppedrot wants a separate opam package that contains just `grammar.ml ` and `Gram.extend`, and builds with OCaml trunk (without needing frequent updating) (implicit assertion: camlp5 often does not build with OCaml trunk, and it's not reasonable to ask for it to do so).  Reason: Coq wants to live at the tip of OCaml development.

@roglo heard, I think "Coq wants a smaller camlp5", and claims that camlp5 is small, that having `grammar.ml` alone is not useful, maybe also that there was a one-time update needed to let camlp5 build with current trunk?

There is also some back-and-forth about how to make `Gram.extend` type-safe with ADTs.

Is that basically accurate?

**Comment by ejgallego** [comment]
@JasonGross you are maybe missing that `grammar.ml` is written in a special dialect of OCaml which needs a working camlp5 to compile, so the plan is not going to work as-is, unless `grammar.ml` gets rewritten.

**Comment by ejgallego** [comment]
Coq mainly wants not to indirectly depend [via camlp5] on the unstable OCaml internal parse tree.

**Comment by ppedrot** [comment]
@ejgallego Let's do it piecewise. First, a type-safe API, then we'll see. It's not hard to port to standard OCaml though, and I already did it actually.

**Comment by ppedrot** [comment]
For people interested in this discussion, I recommend switching to camlp5/camlp5#15.
