### ISSUE TITLE
On the meaning of the radio button "Approve" in pull requests reviewing

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6046]
Hi, I started a [wiki page](https://github.com/coq/coq/wiki/On-the-radio-button-%22Approve%22-in-pull-requests-reviewing) summarizing the current state of a discussion started in PR #6036 with the idea that this wiki page can serve as a reference for what is expected from a review.

At the same time, I'm opening this issue (as recommended by @mattam82), so that the discussion can continue on a better-identified and better-searchable support.

In addition to what I put on the wiki (which is basically an excerpt of what @mattam82 and @ejgallego said), I have the following question:

@Zimmi48 said:
>It is not the RM role to take a decision whether a PR should go in or not so having a clear approve allows him to merge without having to try to understand from the tone of the comments what the reviewers think (which is a hard task given that everyone expresses oneself differently).
>
> So see this approve as: I'm OK to commit this with no changes. If some changes are suggested at the time of an approve it still means that the RM can merge without these changes being done.

I opened a section on the wiki about that but I let it unfilled because I don't understand the conclusion yet. Should "approve" being interpreted as a demand that the PR is being merged without further changes or discussion needed, as I understand you're saying? (Compared to @mattam82 saying "I don't see the approve button as an end of discussion" or to @ejgallego saying "an informal 'looks good to me'".)

**Comment by ejgallego** [comment]
> Should "approve" being interpreted as a demand that the PR is being merged without further changes or discussion needed, as I understand you're saying?

I am with @mattam82 here in that we may want to avoid over-formalization/over-definition of the processes, as I am not sure we will gain a lot from such an effort. "Approve" means "it is OK for me" and I guess reasonable common sense and individual criterion should do the rest wrt merging in each case.

Merging doesn't imply that the change is final and that it won't be refined in the future, IMHO other than caring about compatibility, we should favor an integrative stanza so inertia about the development is built.

**Comment by Zimmi48** [comment]
@herbelin What I meant is that even if you can give an approval while making some further suggestions, the approval applies to the current state: that is "even if my suggestions are not taken into account, I agree that this change be merged". Like @ejgallego says: "merging doesn't imply that the change is final and that it won't be refined in the future". Of course if you approve and make suggestions at the same time, the PR shouldn't merged right away. But if a couple working days later, the author of the PR hasn't reacted to them, then it should still be considered for inclusion.

What I would like to avoid would be someone approving a PR and then criticizing the RM for having merged it (this has never happened and I'm not expecting this to happen). However, like @mattam82 said, an "approve" doesn't mean the end of discussion and if in fact a discussion is still going on, on a PR thread, even if the PR is in "approved" state, it is likely that it is a good idea to wait a bit before merging it. On the contrary, if the PR discussion has stalled, there is no "needs" flag, and the PR is in "approved" state, then it's an obvious candidate for merging.

Let me emphasize this once more in another way. The "approve" button is useful because it helps communicating intents more clearly.

BTW your summary on the wiki page looks very good to me.

**Comment by herbelin** [comment]
I'm not sure to get a very clear picture of the process (e.g., is a single "approve" with no "needs" flag an immediate green light or not?) but as long as it is admitted that the process is informal, friendly, and reversible (and that rude use of capital letters is part of the past), I shall probably continue preferring to try to give explicit comments (and thanks!) preferably to clicking on the "approve" button, if that's ok for everyone.

**Comment by Zimmi48** [comment]
We should talk IRL about this because I'm having a hard time understanding what pushes you away from this button. Plus, I understand that this episode that you are constantly referring to as been a traumatic experience but Maxime has apologized and I don't think it should have any thing to do with the current discussion.

**Comment by SkySkimmer** [comment]
Everything changed when the new merging process arrived, so if something is unclear it probably fits in a new issue.
If I'm wrong this one can still be reopened.

**Comment by Zimmi48** [comment]
Indeed, I share your concern Hugo, but I've discovered than what could be polite even while requesting changes, and it feels especially important when talking to new contributors. For instance, requesting changes but starting the review by "Thank you for your contribution. Here are some remarks to address before merging:"

**Comment by Zimmi48** [comment]
This is BTW the kind of review comments given by GitHub on their own examples: https://help.github.com/articles/about-pull-request-reviews/
