### ISSUE TITLE
Test-suite fails when ./configure is run with -annotate

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6120]
#### Version

8.7

#### Operating system

Linux

#### Description of the problem

I get the following test-suite failures when compiling Coq with `./configure -local -annotate`:

```
    coq-makefile/coqdoc1/run.sh...Error!
    coq-makefile/coqdoc2/run.sh...Error!
    coq-makefile/mlpack1/run.sh...Error!
    coq-makefile/mlpack2/run.sh...Error!
    coq-makefile/multiroot/run.sh...Error!
    coq-makefile/plugin2/run.sh...Error!
    coq-makefile/plugin3/run.sh...Error!
    coq-makefile/uninstall1/run.sh...Error!
    coq-makefile/uninstall2/run.sh...Error!
```

The error is always: `ocamldoc: unknown option '-bin-annot'`

According to https://github.com/coq/coq/blob/d9f79d97dbc503e149cba2df1b228a94d7ac970b/configure.ml#L371-L374

this may have something to do with the presence of `ocamlmerlin` in my path.

**Comment by gares** [comment]
The bug is in CoqMakefile.in that passes these flags to ocamldoc
  https://github.com/coq/coq/blob/master/tools/CoqMakefile.in#L406-L415
ocamldoc needs to receive flags like `-I`, this is why we pass `$(CAMLFLAGS)`.
Unless ocamldoc is fixed upstream to accept and discard all compiler flags... we have to split `$(CAMLFLAGS)` into `$(CAMLPATHFLAGS)` and `$(CAMLOTHERFLAGS)`, or something like that.
