### ISSUE TITLE
Regression in ring_simplify over nat

### ISSUE THREAD

**Issue by herbelin** [coq/coq#6191]
#### Description of the problem
I'm reporting a regression described on coq-club by Ilmārs Cīrulis on 17 Nov 2017.
```coq
Require Import ArithRing.
Goal (2+2=4).
ring_simplify (2+2).
(* "N.to_nat 4 = 4" instead of "4 = 4" *)
```
This is related to 6532ee2d and in particular to the change
```
-    pol_cst "Pphi_dev", (function -1|8|9|10|12|14->Eval|11|13->Rec|_->Prot);
+    pol_cst "Pphi_dev", (function -1|8|9|10|11|12|14->Eval|13->Rec|_->Prot);
```
However I don't understand what is the correct fix. To backtrack on the treatment of the 11th `phi` argument of `Pphi_dev`? Or another fix maybe specific to `ArithRing`?

@silene, may we require your help?

**Comment by silene** [comment]
> Or another fix maybe specific to ArithRing?

I suppose that adding `postprocess [ unfold to_nat ]` at the end of `plugins/setoid_ring/ArithRing.v` would do the trick.

**Comment by herbelin** [comment]
@silene: it helps, but then, there is `BinPos.Pos.to_nat`, and then `BinPos.Pos.iter_op Nat.add`, so I'm unsure of what is the exact correct incantation to fully evaluate `N.to_nat`. For instance, would `unfold BinNat.N.to_nat, BinPos.Pos.to_nat, BinPos.Pos.iter_op, Nat.add`, which works here, be ok, or too strong, or too weak in general?

**Comment by silene** [comment]
Then I would try something like the following, instead of just `unfold`:

```coq
repeat match goal with
| |- context [to_nat ?x] =>
  let v := eval cbv in (to_nat x) in
  change (to_nat x) with v
end
```

As to whether it will be too strong in general, the answer is yes. Indeed, if the user ever used `to_nat` on an uninterpreted subterm of the term to be simplfiied, it will get reduced by `ring_simplify`, which will not be pretty. The issue is that `ring_simplify` performs the postprocessing after reinterpreting the terms rather than before. Fortunately, this degenerate case is easily avoided in practice.

**Comment by herbelin** [comment]
@silene: I made a quick hack at #6205. Not very proud of it but maybe an acceptable compromise. Tell me what you think.
