### ISSUE TITLE
Bounty bug: _super_safe_section_

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6389]
I'd like to have a developer-only flag, _`super_safe_section`_  that submits Coq into re-type-checking every cooked term.

**Comment by maximedenes** [comment]
What's the bounty? :D

**Comment by ejgallego** [comment]
Le Père Noël rapportera des surprises cette année !

**Comment by maximedenes** [comment]
When I first saw this issues, I thought the point was to evaluate the cost of a potential change to a kernel that would be skeptical w.r.t. sections. But since then, #7118 has shown that performance of such a change (without other changes to the system) is a showstopper.

But it seems that @egjallego still want #7118 to be merged, so I realized I misinterpreted the motivations. I asked about it and got the following answer:

> My motivation indeed was related as to start exploring a different approach to sections that could enable, for example, easier parallel proof checking. As we know, Sections seems to be a quite hard problem so it makes sense to try to document a bit the magic that goes there.

I'm still not sure I understand the concrete use case for the option. "Documenting the magic" seems orthogonal.

So concretely, do you expect end users to use this option? Developers? What would they use it for?

**Comment by ejgallego** [comment]
I don't have a lot of answers as this was really exploratory territory. I dunno about the option, but in principle it seems useful to have better isolation in the trusted base.

Indeed, as I commented on #7118, for this option to be considered as more than an experiment, we would need to provide a way to disable typechecking inside sections. It is a pity I don't have my stm / proof trees ready yet, as the behavior of `Qed` today surfaces a bit more, and I'm sure there is a lot to understand about our current implementation today.

**Comment by maximedenes** [comment]
Don't get me wrong, I fully agree with the goal of trying to isolate section handling from the kernel. But since the option is not practical, as shown by the timings, I'm sure we want to merge an experiment.

But of course the experiment was very valuable, and that leads to something I've been wondering for a long time: what is the appropriate place to store the results of such experiments? In the past, a lot of similar data around the kernel conversion, or functor applications was lost (AFAIK). Now we have at least the PRs that is there (even if we close it), but we may want to put the data in a place that is easier to find, WDYT?

**Comment by ejgallego** [comment]
> the option is not practical, as shown by the timings, I'm sure we want to merge an experiment.

Well, "not practical" here may have many meanings. If you cost per line of TCB is way higher than your cost of type checking then it is going to be a super practical option. I am not sure "practicality" is the relevant factor here.

I am not expert on the kernel of course, but I am not sure what is the problem with merging this option. Does it create a maintenance burden? It looks like it has very little cost and brings some interesting stuff to the table, as I said, it could be used as a model for STM extension for evaluation in sections, etc...

**Comment by herbelin** [comment]
My own 2c: independently of the question of providing or not a `_super_safe_section_` option, the simplest approach to me would be that we double-check the code for discharging, tag it as TCB and move it to the kernel.

Then, whether, we want to implement cross-verifications on parts of the kernel shall be another story.

**Comment by maximedenes** [comment]
> Well, "not practical" here may have many meanings. If you cost per line of TCB is way higher than your cost of type checking then it is going to be a super practical option. I am not sure "practicality" is the relevant factor here.

I don't buy the TCB option, because AFAIK `coqchk` already provides an answer.

**Comment by ejgallego** [comment]
I feel like sections and a couple of other topics, such as what's going on with `Qed` could warrant a session at the IM to discuss a bit; IMHO the issue is quite complicated to discuss here as they are many subtle interactions and points of view.

My point of view is about doing parallel processing for example, so that's quite different.

About the TCB I am not an expert, just wanted to point out that "practicality" can be a quite vague notion in practice.

**Comment by maximedenes** [comment]
> About the TCB I am not an expert, just wanted to point out that "practicality" can be a quite vague notion in practice.

In fact my question was very simple: can you give an example use case for this option?

**Comment by ejgallego** [comment]
> In fact my question was very simple: can you give an example use case for this option?

Maybe not in its current incarnation, but it was already of great help at least to me personally to improve my understanding on some stuff. So I don't see the urgency of closing this right away.

**Comment by ejgallego** [comment]
And thanks for the comments, indeed, I'll then reformulate / close the bug when I have a bit of time about to think tranquilement, maybe I should just focus on #6254

**Comment by ejgallego** [comment]
This is not a PR @ppedrot

**Comment by ppedrot** [comment]
Sorry, I thought I was posting in PR #7118! See, the dualism PR/issue is going to drive me crazy if we post on both sides!

**Comment by ejgallego** [comment]
I understand your point folks, I just mean that there is not urgency to act on this IMO, I couldn't even read Skyskimmer PR well and you already want to close it. Let's discuss this with calm, I'll take care of garbage collection if needed.

**Comment by ejgallego** [comment]
Well, after one month passed, I am OK letting the kernel maintainers to close this [note thou that @SkySkimmer won the bounty]

The experiment was interesting but it seems like the discussion can be archived.

**Comment by maximedenes** [comment]
Thanks!
