### ISSUE TITLE
When should a PR include a CHANGES entry?

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#6396]
This is easy to miss and indeed I missed it resulting in https://github.com/SkySkimmer/coq/commit/0ad26633a4589d77de1f864733d1d953dab9ea91
>@tchajed 
>Why is this breaking change not documented anywhere? Our class's code was broken by this change and I had to bisect to find this.

**Comment by Zimmi48** [comment]
Thanks for raising this question. That's something that I have been wondering as well and which has blocked me in #975. Clarifying this would also help streamlining the release process.

The README describes this file in the following way:

> There is a file named CHANGES that explains the differences and the incompatibilities since last versions. If you upgrade Coq, please read it carefully.

(making no mention of COMPATIBILITY)

This led me to think that we should archive the COMPATIBILITY file and only use CHANGES to describe compatibility-breaking changes. But it also looks like an adequate place to document any new user-visible feature  and any major bug fix.

**Comment by Zimmi48** [comment]
More precisely, we could consider that as soon as an overlay was needed, the change should be documented. If an overlay was needed for an external library, then it should be documented in CHANGES. And if overlays were needed only for external plugins, then it should be documented in `dev/doc/changes`. 

We could consider automatizing this check by having Travis add a "breaking change" label to PRs when they have overlays (so that the information is not lost when the overlays are removed) and check that CHANGES or `dev/doc/changes` were modified when the PR has the "breaking change" or the "feature" label. I don't know if it is worth the hassle though...

**Comment by SkySkimmer** [comment]
Overlay presence doesn't sound reliable to me.

**Comment by Zimmi48** [comment]
Indeed, in fact I agree.

**Comment by tchajed** [comment]
I think the following should be in CHANGES:
- Any breaking change: could currently working code's behavior change due to this change?
- Any new user-facing feature, for example commands, options, standard library definitions, but also changed or improved behavior.
- Significant bug fixes, especially those that might impact how users write code. Sometimes a change removes a limitation and could be considered either a bug fix or a feature; these should be documented.

Putting too much in CHANGES isn't as much of a problem as putting too little. One objective is that users can use CHANGES to guide upgrading: in particular, any change in behavior should have an entry the user can refer to. Another objective is that users read CHANGES to find out how to write better code in the new version if they don't want backwards compatibility.

I like the [OCaml Changes file](https://github.com/ocaml/ocaml/blob/trunk/Changes) as inspiration - they are quite careful about documenting.

**Comment by ejgallego** [comment]
Yup, certainly an area that absolutely needs to be improved. I get the impression thou than OCaml has an easier job than us. Unfortunately in Coq, it is very hard to predict if a change will be visible by the user due to the complexity of the codebase and the many languages involved. I think @herbelin is one of the most careful devs with documentation, pinging him.

**Comment by Zimmi48** [comment]
The PR templates now explicitly asks a CHANGES entry for all new features / compatibility-breaking bug fixes and it's presence serves as an efficient reminder. Let's see for a few more weeks if we are satisfied by the result and then close this issue if we are.

**Comment by Zimmi48** [comment]
I think we can close this now. Please re-open if you think that there are still questions to address or that the documentation needs to be improved.
