### ISSUE TITLE
Improve / fix linking of the VM in bytecode builds.

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#6475]
#6038 introduced a bug when linking the VM in bytecode mode as it doesn't set the path properly (which likely causes #5992):

```makefile
  -I kernel/byterun -dllpath $(abspath kernel/byterun) -cclib -lcoqrun -dllib -lcoqrun \
```
which is obviously incorrect as the path should be `$(COQLIBINSTALL)/kernel/byterun`.

However, a couple of questions appear wrt VM linking in the byte version:
- do we still want to link dynamically the VM, or should using `-I kernel/byterun -custom kernel/byterun/libcoqrun.a` be a better strategy?
- is the use of `VMBYTEFLAGS` when linking `kernel.cma` still necessary?

**Comment by ejgallego** [comment]
After some brief chat with @xavierleroy (thanks!), it seems that the only drawback of statically linking Coq's VM would be that the resulting file format is a bit of a strange mix, so packages should be careful, for example when calling `strip`. @gares , do you think that this would be a problem in Debian?

Also, quoting https://caml.inria.fr/pub/docs/manual-ocaml/intfc.html#sec418

> For new or rarely-used libraries, static linking is much simpler to set up in a portable way.

So indeed, given the totally "private" nature of Coq's VM I am inclined here to propose that we build standalone `coqtop.byte` executables. Derived toplevels such as SerAPI already link the VM statically [otherwise managing the .so becomes a bit annoying].

This would certainly require a changes entry.

**Comment by xavierleroy** [comment]
@ejgallego, you're misunderstanding how much packagers for Linux distributions hate the bizarre ELF-executable-with-OCaml-bytecode-appended file format produced by `ocamlc -custom`.  First, the `strip` command destroys the bytecode, so packagers must make special exceptions not to strip those files after installing.  Second, Debian, always of the opinionated kind, told us in no uncertain terms that they refuse to have executable files that are neither ELF nor scripts.  

That discussion took place >10 years ago, and as a result both the OCaml distro and the Coq distro stopped using `ocamlc -custom`, switching to DLLs instead.  Why do you want to regress on this issue?  The work to turn the VM interpreter in a DLL has already be done!  

> For new or rarely-used libraries, static linking is much simpler to set up in a portable way.

This feels like it was written 15 years ago, when DLL support in OCaml was the exception rather than the rule.  Today it *might* remain true for executables that are used only locally and never installed, but not for stuff that users and esp. packagers will see.

**Comment by ejgallego** [comment]
> Why do you want to regress on this issue?

The motive I wondered about going back to static linking is that AFAICT, there is no way to teach an  `ocamlfind` META file about the absolute path needed by `-dllpath` in bytecode dynamic linking builds.

Of course, we could generate `META` depending on the `-prefix`, but I was wondering if we could avoid yet another automatically generated file in this case.

**Comment by ejgallego** [comment]
Another very fringe annoyance is that sometimes developers like to rename their local build directory, and for that `coqtop.byte` needs a rebuild, but not a big deal.

Anyways we will refactor the VM linking a bit so indeed using `-custom` is possible for those who want it.

**Comment by ejgallego** [comment]
Closing this, in #6478 we go back to the defaults of 8.7 for byte. That is to say, `-custom` is used in Mac and Windows and a generated-at-configure-time `-dllpath` is used on Linux.

It is still possible to pass `-custom` on Linux to regain static linking of the VM [for those wanting self-contained binaries]

**Comment by Zimmi48** [comment]
Usually, we wait until a PR is merged to close the corresponding bug. Or were you expressing that there was actually no bug?

**Comment by ejgallego** [comment]
This was more of a design question than an actual bug. [The actual bug was indeed closed before merge, but that's OK]
