### ISSUE TITLE
constr_eq performance is sensitive to where the term came from (failure of hashconsing?)

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6538]
#### Version

8.8+alpha (e2d1c676b23a335b4fb8a528c99dfca2b82a1a39)

#### Operating system

Linux

#### Description of the problem

(See Also #3280)

There are cases where `constr_eq x y` is slow (but succeeds) when `constr_eq x x` is instantaneous.  As far as I can tell, no universes other than `Set` are involved.  I think both should be instantaneous.

```coq
Fixpoint twos (n : nat) (A : Type) :=
  match n with
    | 0 => A
    | S n' => twos n' (prod A A)
  end.

Tactic Notation "display" string(tacname) tactic3(tac) :=
  match goal with |- let n := ?k in _ => idtac k "Time" tacname end;
  lazy [twos];
  time tac ().

Notation "'hide'" := (_ = _) : type_scope.

Goal let n := 21 in twos n Set = twos n Set.
  display "constr_eq" (fun _ => lazymatch goal with |- ?x = ?y => constr_eq x y end). (* 0.394 *) Undo. 
  display "constr_eq x x" (fun _ => lazymatch goal with |- ?x = ?y => constr_eq x x end). (* 0.0s *) Undo. 
```

**Comment by ppedrot** [comment]
Indeed, in the second case the compared terms are physically equal and the function takes a fast path. I don't think hashconsing would help here, you'd just pay a tremendous amount for systematic hashconsing while only gaining on corner cases such as the one presented here. We're already paying a high toll due to hashconsing, I doubt adding any would do any good.

**Comment by SkySkimmer** [comment]
wontfix
