### ISSUE TITLE
"rewrite" fails with "-noinit"

### ISSUE THREAD

**Issue by DanGrayson** [coq/coq#6623]
#### Version
coqtop version 8.7.1 (January 2018)
#### Operating system
macOS 10.13.2
#### Description of the problem

The "rewrite" tactic fails in situations where the rewritten term has another term depending
on it, if one uses the "-noinit" option.  Loading Coq.Init.Logic enables the rewrite to succeed, but
in UniMath we'd like to be independent of the prelude.

The attached file explains how to run it in a comment at the top.

[isolated_bug_rewrite.v.txt](https://github.com/coq/coq/files/1647741/isolated_bug_rewrite.v.txt)

**Comment by ejgallego** [comment]
see also #186

**Comment by peterlefanulumsdaine** [comment]
After some digging into this with Dan: the core issue here is that some of the internal lemmas produced by the `rewrite` tactic make use of Coq’s internal equality type `Eq`, even though the overall rewrite is happening in the user’s preferred equality type.

Specifically, the scheme `sym_involutive` defined in [`eqschemes.ml`](https://github.com/coq/coq/blob/9aa2464375c1515aa64df7dc910e2f324e34c82f/tactics/eqschemes.ml) proves that symmetry on the user’s equality type is involutive; but the involutivity is *stated* using Coq’s equality type `eq`.  As far as I can tell, the culprit is `get_coq_eq` in [line 249 of `eqschemes.ml`](https://github.com/coq/coq/blob/9aa2464375c1515aa64df7dc910e2f324e34c82f/tactics/eqschemes.ml#L249).

The effect is that the user gets a proof-term containing `eq` (and hence `Prop`) without realising it.  This is undesirable in both the `UniMath` and `HoTT` libraries, where we strongly want to avoid `Prop` for theoretical reasons.

Would it be possible to avoid this invocation of `eq`, at least in the case where the user’s equality type (i.e. the inductive type being used for the rewrite) is sufficiently similar to Coq’s `eq` that it could be used instead for the statment of involutivity?

(The offending `get_coq_eq` appears to be used similarly at one other point in `eqschemes.ml`, in [the `l2r_rew`/`rew_dep` rewrite scheme](https://github.com/coq/coq/blob/9aa2464375c1515aa64df7dc910e2f324e34c82f/tactics/eqschemes.ml#L353), which is the scheme that invokes `sym_involutive`.)

**Comment by SkySkimmer** [comment]
>see also #186

That PR is merged in 8.10 so it should be possible to fix this issue now.

**Comment by ejgallego** [comment]
Indeed 8.10 should fix this, waiting for confirmation to close.

**Comment by DanGrayson** [comment]
I just tried it (from the master branch), and it doesn't seem to be fixed yet:
```
$ ../sub/coq/bin/coqc "-indices-matter" "-type-in-type" "-noinit" "-w" "-notation-overridden,-local-declaration,+uniform-inheritance,-deprecated-option" isolated_bug_rewrite.v 
Error: not found in table: core.eq.type
$ ../sub/coq/bin/coqc --version
The Coq Proof Assistant, version 8.10+alpha (November 2018)
compiled on Nov 14 2018 7:58:25 with OCaml 4.06.0
$ (cd ../sub/coq; git log -1)
commit 778213b89d893b55e572fc1813c7209d647ed6b0 (HEAD, origin/master, origin/HEAD)
Merge: 5bcf956b8 71e95436c
Author: Hugo Herbelin <Hugo.Herbelin@inria.fr>
Date:   Fri Nov 16 00:46:26 2018 +0100

    Merge PR #8888: Proof runcountable rebase
```

**Comment by DanGrayson** [comment]
Oh, thanks.  I've added enough "Register" commands so that it doesn't complain about things missing, but now an earlier rewrite command fails by not finding a matching subexpression.

File attached.
[isolated_bug_rewrite_2.v.txt](https://github.com/coq/coq/files/2591777/isolated_bug_rewrite_2.v.txt)

**Comment by ejgallego** [comment]
Cool, thanks @DanGrayson ; maybe @vbgl is interested on this problem too.

**Comment by DanGrayson** [comment]
By the way, we don't really want to have the line `Register paths_ind as core.eq.ind` there, because it uses Prop, but I put it in temporarily.  It would be nice to find out whether it needs that one registered, and if so, whether `Register paths_rect as core.eq.ind.` would work as well.

**Comment by ejgallego** [comment]
The example you have attached has a lot of mistakes so it doesn't compile; I'm afraid that you'll have to either provide a better test case or we will have to close this bug as unreproducible.

> Register paths_rect as core.eq.ind.

You can use `coq.eq.rect` to register the rect principle.

**Comment by DanGrayson** [comment]
Here you go.  I've brought it up to date with the latest Coq on the master branch.

[isolated_bug_rewrite_3.v.txt](https://github.com/coq/coq/files/3034240/isolated_bug_rewrite_3.v.txt)

**Comment by ejgallego** [comment]
Thanks!

**Comment by ejgallego** [comment]
That's a really weird bug!

**Comment by haselwarter** [comment]
I seem to have hit the same bug, this time while working on coq-hott. 

Let's see if I'll get this right. I summon thee, coqbot!

@coqbot: minimize
```
opam install -y coq
eval $(opam env)
git clone --depth 1 --branch pre-infinitary-ua https://github.com/andreaslyn/HoTT/ 
cd HoTT
./autogen.sh && ./configure && make -j8
wget 'https://gist.github.com/haselwarter/f05657237ad3d07cec679fc6e0cc6e4c/raw/b3132a2c919fab1d963d153e4bbad39276375cd6/rewritebug.v'
coqc -noinit -indices-matter -native-compiler no -R theories HoTT -Q contrib HoTT.Contrib rewritebug.v
```

**Comment by Zimmi48** [comment]
@JasonGross Here's an example use of the bug minimizer where it failed with `wget: command not found`.

**Comment by JasonGross** [comment]
Should be fixed by https://github.com/coq-community/run-coq-bug-minimizer/commit/484e7221bcfaeda0b5c7db1bbd76b0cd8c048a61, let's try again
@coqbot: minimize
```
opam install -y coq
eval $(opam env)
git clone --depth 1 --branch pre-infinitary-ua https://github.com/andreaslyn/HoTT/ 
cd HoTT
./autogen.sh && ./configure && make -j8
wget 'https://gist.github.com/haselwarter/f05657237ad3d07cec679fc6e0cc6e4c/raw/b3132a2c919fab1d963d153e4bbad39276375cd6/rewritebug.v'
coqc -noinit -indices-matter -native-compiler no -R theories HoTT -Q contrib HoTT.Contrib rewritebug.v
```

**Comment by JasonGross** [comment]
Hm, did you get the wrong file? "Error: not found in table: core.eq.type"
