### ISSUE TITLE
What does -q do in coqc?

### ISSUE THREAD

**Issue by jimyu94** [coq/coq#6662]
I find it not clear to me what the `-q` command does in `coqc`. In the manual of `coqtop`, it says `-q` means "skip loading of rcfile." However, what does rcfile do? And in what cases shall we not load them? I believe this should be stated in the manual, since beginners like me don't understand.

Sorry that I don't know if this question is suitable for the Issues page. If not, where shall I raise this kind of questions? Thanks!

**Comment by ejgallego** [comment]
Sure @jimyu94 , requests to improve the documentation are very welcome here!

**Comment by herbelin** [comment]
Pretty late answer. I believe that the corresponding section in the [reference manual](https://coq.inria.fr/refman/practical-tools/coq-commands.html?highlight=coqrc#by-resource-file) explains correctly enough what a `rc` file is. I also added a few line as part of PR #7493 to expand `rc` into `resource file` in the man page. I'm otherwise afraid that the man page is designed to give only short descriptions (compared to what the reference manual gives).
