### ISSUE TITLE
Kernel conversion / reduction is much, much slower than `Eval lazy`, and seems super-linear in intermediate term size

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#6667]
#### Version

8.7.1

#### Description of the problem

```coq
Inductive is_even : nat -> Prop :=
| even_O : is_even O
| even_SS : forall x, is_even x -> is_even (S (S x)).

Definition invert_Some {A} (x : option A) : match x with
                                           | Some _ => A
                                           | None => True
                                           end
 := match x with
    | Some x => x
    | None => I
    end.
Fixpoint try_prove_is_even (n : nat) : option (is_even n)
  := match n with
     | O => Some even_O
     | S O => None
     | S (S n) => option_map (even_SS n) (try_prove_is_even n)
     end.
Time Eval lazy in true = if try_prove_is_even (10 * 10 * 10 * 10 * 10) then true else false. (* 0.24 *)
Time Eval lazy in true = if try_prove_is_even (10 * 10 * 10 * 10) then true else false. (* 0.014 *)
Time Check eq_refl true : true = if try_prove_is_even (10 * 10 * 10 * 10) then true else false. (* 1.285 *)
Time Eval lazy in true = if try_prove_is_even (10 * 10 * 10 * 10 * 2) then true else false. (* 0.04 *)
Time Eval cbv in true = if try_prove_is_even (10 * 10 * 10 * 10 * 2) then true else false. (* 0.05 *)
Time Check eq_refl true : true = if try_prove_is_even (10 * 10 * 10 * 10 * 2) then true else false. (* 6.39 *)
```

This seems unnecessarily slow...

**Comment by ppedrot** [comment]
Probably related to the unfolding of constants, that keep requiring going through the stack. I'll have a closer look.

**Comment by ppedrot** [comment]
Indeed, it looks like most of the time is passed into zipping the stack, because the reduction machine doesn't try to compute the normal form of the right hand side in one go, although this is eventually the only meaningful reduction. I know @maximedenes had some plans regarding the conversion algorithm, in particular this exact issue. Not sure when it's going to be implemented though.

**Comment by maximedenes** [comment]
Is it really zipping or comparing the stacks that takes time?

**Comment by maximedenes** [comment]
I had a patch that gets rid of the `pure_stack` construction. I can try to resurrect it. Is it the bottleneck on this example?

**Comment by ppedrot** [comment]
@maximedenes Nope, (microscopically) the problem is zipping and to a lesser extent, useless computation of shifts in `eqappr`. But macroscopically the problem is a stupid unfolding heuristic.

I wrote a trivial patch that follows your idea about forcing δ-reduction in flex/constructor case in the kernel and it makes the comparison from 7s down to 0.2s. It's [here](https://github.com/ppedrot/coq/tree/rigid-constructor-conversion) if you're curious.

I'll bench it on more realistic examples, but the benching machine is already somewhat saturated right now.
