### ISSUE TITLE
Feature request: even stricter subproofs

### ISSUE THREAD

**Issue by dfoxfranke** [coq/coq#6689]
`Set Bullet Behavior` should accept an argument named something like `"Enforce Subproofs"`. When this option is active, proofs must be bullet-structured throughout. That is, whenever more than one goal is in focus, a new level of bullet must precede the use of any tactics.

**Comment by Zimmi48** [comment]
This is an old idea that was never implemented. @aspiwack proposed to implement this by having a new goal selector e.g. `unique:` which would apply a tactic to the current goal if it's the only one under focus and fail otherwise. Setting this goal selector as the default goal selector would then be enough to obtain the requested behavior.
