### ISSUE TITLE
Option Standard Proposition Elimination Names

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#6822]
Undocumented option Standard Proposition Elimination Names was introduced in f9517286637fd0891a3ac1aac041b437e157f756 by @herbelin, then deprecated and marked as "remove in 8.8" in 180b3739bb6601ff9aaf951e4b87e0bb45341b77 by @silene as part of a commit claiming to deprecate options that were introduced for compatibility with 8.4. The problem seems that this option was likely never used because it was undocumented and off by default.

Is it correct to deduce that this was deprecated by mistake?

I would still like to make the remark that undocumented "experimental" options are **useless** (OK, so it had a CHANGES entry, maybe some people actually used it, but still). What should be the next steps for this option? Undeprecate and document?

**Comment by maximedenes** [comment]
Can you write a sentence here saying what this option does?

**Comment by Zimmi48** [comment]
From the CHANGES file:

https://github.com/coq/coq/blob/0c5f0afffd37582787f79267d9841259095b7edc/CHANGES#L1107-L1109

From comments in the code:

https://github.com/coq/coq/blob/0c5f0afffd37582787f79267d9841259095b7edc/engine/namegen.ml#L426-L430

**Comment by silene** [comment]
> Is it correct to deduce that this was deprecated by mistake?

My memory is a bit fuzzy, but I think the reasoning was as follows (hopefully, @herbelin will correct me if I got it wrong). We do want this kind of option, but the current mechanism is not completely satisfactory, so I ended up deprecating its name so that we could reuse the option without any compatibility concern the day we get the mechanism right.

**Comment by Zimmi48** [comment]
Thanks for the reply. Usually, when I remove a deprecated option I try to remove as much dead code as I can as well. Would you say that in that case we want to keep the code that provides this option or we should rather clean it up and restart from scratch when it is time?

**Comment by herbelin** [comment]
That's indeed what @silene said.

The context is the question of auto-generated names (see #268, #6582, ...). However, with "Set Standard Proposition Elimination Names", the question is not strictly directly the question of robustness wrt naming, but rather the question of "prettyness" of generating names, so that they are "intuitive" (relatively to some practice considered as standard). This is typically useful in a prototyping phase, where we don't necessarily want to name everything and where we are glad that Coq invent "pretty" names. Similarly I think in a context of teaching Coq.

The typical situation addressed by the option is with an elimination from a non-Prop inductive type or with a dependent elimination from a Prop inductive type with arguments which are propositions:
```coq
Goal forall x, {x=0}+{x<>0} -> x=x.
destruct 1.
(* Without the option: generated names are "e" and "n", because of "eq" and "neq" *)
(* With the option: generated names are "H" and "H" *)

Goal forall H : True/\False, H = H.
destruct H.
(* Without the option: generated names are "t" and "f", because of "True" and "False" *)
(* With the option: generated names are "H" and "H0" *)
```
So, basically, I found that the names "e" and "n" were ugly  (no symmetry between them, difficult to understand that it comes from the name "eq" and "neq" of connectives). Something had to be done to improve this (again at least for prototyping or teaching).

On the general idea:

I have no idea how this choice of name is perceived in general. Personally, I like the idea of a system which produces convenient names, relatively to some notion of "convenient" which itself could be programmed (and I have a branch somewhere which proposes different naming schemes depending on taste of the user). And, again, it is not about robustness, but about the feeling of working with a system which is "smart" enough in the names it invents.

On the technical side:

The feature is incomplete in the sense that there are cases which are not taken into account by the strategy. For instance `Goal forall l : unit+unit, l = l. induction l.` still don't use `H` but the generated names are `a` and `b` (just because the naming strategy is different for a `match`, as used by `destruct` and for a `foo_ind` scheme, as used by `induction`).

In any case, I'd prefer to preserve the underlying code, even if I have a branch generalizing this feature somewhere.

**Comment by Zimmi48** [comment]
OK thank you for the answer. In that case, I'll let someone else remove the deprecated option.

**Comment by Zimmi48** [comment]
#6899 was merged
