### ISSUE TITLE
pre-commit hook incorrectly complains about "leftover conflict marker"

### ISSUE THREAD

**Issue by maximedenes** [coq/coq#6986]
Steps to reproduce the problem:
- create a file `foo.rst` which contains:
```
=======
   
```
(note the whitespaces on the second line)
then `git add foo.rst && git commit -m foo`

**Comment by SkySkimmer** [comment]
I think the complaint is correct, 7 `=` (or > or <) form a conflict marker. The script's interpretation of diff --check's return code is incorrect resulting in confusing messaging.

I don't know exactly what git does with the conflict markers but we should probably avoid having them occur in files. Even if it doesn't make scripts do strange things it seems like it could make merge/rebase conflicts more difficult to read.
If `=======` is a normal line in rst we can avoid its being a conflict marker by changing the length from the default to something that won't otherwise be encountered, eg 100 as in https://stackoverflow.com/questions/11394150/changing-git-conflict-markers/11394584#11394584
Since I haven't used rst I'll let you decide if we should do it.

I'll make a PR regardless to fix the confusing messaging.

>(note the whitespaces on the second line)

As far as I can tell it does nothing (ie `printf ======= > foo.rst; git ...` also complains).

**Comment by ejgallego** [comment]
Should this bug be closed?

**Comment by maximedenes** [comment]
I don't think so, has the problem been fixed?

**Comment by SkySkimmer** [comment]
Not really a bug, you shouldn't put conflict markers in files.
