### ISSUE TITLE
Unification blows up, even with "simple apply" and "Opaque"

### ISSUE THREAD

**Issue by andrew-appel** [coq/coq#6998]
#### Version 
8.7.2

#### Operating system 
Windows 10, 32-bit mode Coq

#### Description of the problem

As we all know, "apply" does unification, and unification can blow up unfolding terms.
Supposedly "simple apply" does less unification, so it should not blow up as often.
But still, "simple apply" blows up much too often.
Here is an example of a general problem that has been troublesome for a years, across many versions of Coq:

```coq
Require Import Arith ZArith.
Fixpoint repeat (n: nat) : list unit := 
  match n with
  | S n' => tt :: repeat n'
  | O => nil
  end.

Definition f (n: Z) := repeat (Z.to_nat n).
Opaque f.

Definition BIG := Z.pow 2 19.
Opaque BIG.

Definition BIG' := Z.add BIG 1.
Opaque BIG'.

Inductive R: list unit -> list unit -> list unit -> Prop :=
  CR : forall a b, R a b a.

Ltac carefully_apply_CR :=
  match goal with
    |- CR ?A ?B ?C => constr_eq A C; apply CR
  end.
Goal  R (f BIG) nil (f BIG').
Proof.
  Fail carefully_apply_CR.  (* fails quickly, as it should *)
  simple apply CR.  (* should fail quickly, but instead gets stack overflow *)
```

Notice that I have made a "really simple apply" tactic called carefully_apply_CR.  
It's annoying to do this for every lemma.  I suppose I could do some tactical programming wizardry,
and make a really_simple_apply(F) tactic that examines the type of F and determines
what constr_eq to test, but the user should not have to do this!

I propose that "simple apply" should not unfold Opaque definitions.  This would solve the problem, I believe.

**Comment by ejgallego** [comment]
There are a few orthongonal issues here. First, `apply` and its unification framework as such is deprecated. You should either use `refine (CR _ _)` or `apply: CR` etc... which use the newer unification engine [which seems to perform a bit better].

Second, `Opaque` is also in a kind of "limbo" status as it doesn't really work. If you need true opaque constants you need to seal them with `Qed` and use a type class or module to unseal it.

I think there is no clear plan on the future of `Opaque` but my feeling is that it won't be fixed in the short term. With regards to `apply`, the change in semantics is almost here see #991 . Of course, there will be a compatibility flag.

**Comment by andrew-appel** [comment]
Sorry, but    refine (CR _ _)   blows up -- which is different than failing --  so how is that a solution?
And please do not make me import ssreflect (which seems to be needed for "apply:" ).

**Comment by andrew-appel** [comment]
I know that Opaque does not give "true opaque constants", it is intended only to control the "simpl" tactic, and it is reversible via the Transparent command.   In that sense, it is *not* in limbo, and it *does* really work, and I use it.   When I want true opacity I do use Qed or Module Type.

Here I propose that Opaque could also, very reasonably, control the "simple apply" tactic.

I don't understand your reference to #991.   It appears that pull request concerns the behavior of apply with unification variables.  The issue in my report here is not about unification variables.

**Comment by maximedenes** [comment]
Hi Andrew,

Sorry, this is only a superficial answer, as I'm busy with the beta release. There are actually two unification algorithms in Coq (with different strategies). `apply` currently uses the legacy unification algorithm, and #991 ports it to the more recent one, so that's why @ejgallego mentioned it (it could have an impact on the problems such as the one you report).

I would need more time to investigate your example, but about `apply:`, I'm a bit curious: do you encounter specific issues when importing ssreflect (say locally to a proof)?

**Comment by maximedenes** [comment]
(anyway, if `refine` blows up, it is very unlikely that `apply:` solves your problem since it basically calls `refine` with some heuristics to guess the right number of arguments)

**Comment by andrew-appel** [comment]
You can see why refine blows up:   it is simplifying (Z.to_nat (Z.pow 2 19)).

**Comment by maximedenes** [comment]
There seems to be a comment related to this behavior in the code: https://github.com/coq/coq/blob/master/pretyping/unification.ml#L266

Maybe @herbelin knows more.

**Comment by maximedenes** [comment]
I think I understand what is going on in the code, but not why we do that:

https://github.com/coq/coq/blob/master/pretyping/unification.ml#L395 does tell unification to not unfold any constant in some unification steps. But it seems there are other steps (like conversion) that are controlled by other flags whose default value tells unification to unfold all constants, including `Opaque` ones:

https://github.com/coq/coq/blob/master/pretyping/unification.ml#L330

I don't know why `simple apply` doesn't change those default values.

**Comment by mattam82** [comment]
Probably compatibility...

**Comment by gares** [comment]
Dear Andrew, thank you for the minimized example but I'm afraid it makes it hard for me to understand exactly your needs. On one hand you seem to want to program proof search, and you need an "apply" that quickly fails; on the other hand you have a concrete value (2^19) in your terms, as if you were willing to compute this value at some point.

I don't think Coq (nor ssreflect) offers good support at the tactic level for this style, and it seems your request is about that.

Maybe its a simplistic proposal, but would help me to understand your request: why not working with a context that says something along these lines:
```
size : Z
size_def : size = 19
```
and unfold size (by rewriting size_def) only when it is really needed? It is impractical in your real use case?

In the mathematical components library there are some occurrences of similar problems, and we managed to "lock" some operations (like `^` here) and replace them by their computational body only when needed (sometimes using the Module Type trick you mention, sometimes by less persistent means like using a Qed-opaque identity function and its unfolding equation to insert/remove it on the spot).

**Comment by herbelin** [comment]
> Probably compatibility...

This is indeed what I was going to reply too...

This line 330 mentioned by @maximedenes has historically been (from at least the mid-90s I would say) one of the heuristics implemented by `apply`, and thus by `simple apply` which is just the legacy version of this old years' `apply`.

This was of course at a time when there was no big awareness of the impact of this or that naive unification design choice on large-scale developments. Since then, our knowledge increased about how to organize and control the unification heuristics along clearer axes (and @mattam82's work on what is called "unif-all" is probably one of the most advanced step in this direction) but we keep falling on the question of compatibility, with various propositions around to address the compatibility of former development, but no conclusion yet:
- restoring compatibility with `Set` options, as we do since a very long time now, but with the risk of proliferation of very specific such options;
- putting tactics in scopes so that e.g. we could write `V8_7.apply` to mean that `apply` should be used with its `8_7` semantics; but tactic names are defined by ad hoc grammar rules and not by functions with a uniform syntax as it would have been in a programming language, so this seems to hardly scale;
- having tactics put in modules and saying `Require Import TacticSimpleApply_8_7` to tell to activate the `8_7` semantics of `simple apply` (of course, when I say `8_7`, it is just an example, since there is no such mechanism currently); but then, do we want to be as precise as being able that in a module using `8_7` tactics we can also use the same tactic with the `8_6` semantics, e.g. providing a syntax `with version 8_6 do apply foo`;
- or to use a translator of tactic scripts, but,  up to now, the fear that the task is too difficult limited our courage to try to do so;
- or to use different tactic names for new semantics, using names say such as `simple apply'` or `simple apply#`, or even, to be extreme, `truly-no-delta simple apply`, ... but that seems to contaminate our everyday way to do proofs while it seems to me that what we want (maybe wrongly?) is to have the nice name for what has the nicest semantics and to accept on the contrary to use less nice names when it is only about preserving the past at minimal cost (after all, Coq is also important for teaching and nice names with nice semantics are good for teaching);
- or maybe to consider that we should simply live with our time, that users have to adapt their developments to the new versions if they want to take benefit of the improvements (though this unavoidably reach at some time a limit in terms of human cost, as @JasonGross often reported it).

In practice, it happened that no consensus could emerge about how to deal with compatibility, so we basically continue to live with the tactics as they are, with their limitations. My feeling is that this issue of compatibility, developers will not be able to solve it alone. My feeling is that we need feedback and advices from users about what they think would be the most reasonable compromises to address the compatibility issue. And this is why I'm saying all this to you, if ever you have an opinion on what to do which would give us some hints, some directions on how to deal with the compatibility issue, i.e. on how to be able to provide tactics with more regular and more user-controllable semantics without pain in adapting former developments.

Back to a concrete example, assuming that we change `simple apply` so that it never uses delta-conversion, but that this change breaks the behavior of other calls to `simple apply` on existing developments, how would you like we address the compatibility issue?

PS: This comment engages only myself. Maybe there are simpler approaches and I'm lacking freshness of mind to see them. For instance, I don't know what @mattam82 and unif-all are proposing for `simple apply`. I don't know what @ppedrot and Ltac2 have to propose for `simple apply`, etc.

**Comment by JasonGross** [comment]
This seems like the subject of #3389, where I request a variant of `Opaque` which means "opaque to conversion as well as unification/reduction"

**Comment by mattam82** [comment]
```Require Import Arith ZArith.
Fixpoint repeat (n: nat) : list unit :=
  match n with
  | S n' => tt :: repeat n'
  | O => nil
  end.

Definition f (n: Z) := repeat (Z.to_nat n).
Hint Opaque f : mydb.

Definition BIG := Z.pow 2 19.
Hint Opaque BIG : mydb.

Definition BIG' := Z.add BIG 1.
Hint Opaque BIG' : mydb.

Inductive R: list unit -> list unit -> list unit -> Prop :=
  CR : forall a b, R a b a.

Ltac carefully_apply_CR :=
  match goal with
    |- CR ?A ?B ?C => constr_eq A C; apply CR
  end.
Goal  R (f BIG) nil (f BIG').
Proof.
  Fail autoapply CR using mydb.
```

**Comment by andrew-appel** [comment]
I'm not proposing "simple apply does not do delta-conversion".
I'm proposing "simple apply does not do delta-conversion of definitions marked Opaque."

But it looks like the solution with "autoapply" is exactly that -- just with every Opaque I must also add a Hint Opaque to a database.   So maybe we can declare that this is the answer, and close this issue.

**Comment by mattam82** [comment]
Hint Opaque has the advantage of not turning things Opaque after their
definition which can be a source of failure of subject reduction. I would
advocate for the generalization of “using (some reference to a transparency
database)". Maybe simple apply should just do what you advocate. Personnaly
I’m fine with adding an option to enable this behavior of respecting opaque
everywhere that we should deprecate once everyone switches to the uniform
behavior.
Le jeu. 15 mars 2018 à 18:38, Andrew Appel <notifications@github.com> a
écrit :

**Comment by maximedenes** [comment]
> turning things Opaque after their definition which can be a source of failure of subject reduction

?! Do you have an example?

**Comment by maximedenes** [comment]
> assuming that we change simple apply so that it never uses delta-conversion

This is not what I would expect. As Andrew said, you simply expect `simple apply` to obey the `Opaque` directive. In technical terms, it is not about setting the various fields to `empty_transparent_set`, but rather to not overwrite the user provided value by `full_transparent_state`. I don't understand why `default_core_unify_flags` does that. Can you elaborate about how compatibility plays a role there? Were people relying on `simple apply` unfolding `Opaque` constants?

**Comment by maximedenes** [comment]
@andrew-appel I just submitted #7004 which solves your problem. Let's see what CI reveals w.r.t. compatibility. I can do a larger clean-up around `transparent_state` (to avoid bypassing user directives) after the release.

**Comment by maximedenes** [comment]
By the way, about `Opaque` the manual says:

> The command tells not to unfold the constants qualid1 … qualidn in tactics using δ-conversion (unfolding a constant is replacing it by its definition).

So any tactic unfolding `Opaque` constants is a bug.

**Comment by anton-trunov** [comment]
> So any tactic unfolding Opaque constants is a bug.
> I just submitted #7004 which solves your problem.

@maximedenes Is it possible to make `rewrite` respect `Opaque` as well? We would like to have it for the FCSL library. (We build the library on top of SSReflect/Mathcomp).

**Comment by herbelin** [comment]
@mattam82: cool, I'm still learning Coq...

@andrew-appel: well, if you take it as simply as that, I withdraw my long question!

@jasongross: It makes sense to me to have such kind of modifier. I can try at some time, when unif-all is merged (I'm a bit afraid to base work on the "old" unification algorithm currently used by `apply` since it is supposed to disappear/be frozen).

@maximedenes: Great. I did not even finished writing my answer and you made the expected patch. I'm impressed.

[What I was starting to say is that I don't remember all the small details by heart, but from what I'm recalling, the origin of the internal version of `simple apply` was the compatibility of `auto`. The user-level syntax `simple apply` was introduced for compatibility of code for which the addition of delta by default in `apply` was too strong (generally, this was Ltac functions with backtracking). From the user point of view, there is no reason that `simple apply` does not preserve opacity in situations where it uses conversion. From the `auto` point of view, I have no idea how it would impact `auto` that the internal `simple apply` respects opacity. In the absolute, if we had what @jasongross is asking for, I believe that we wouldn't need `simple apply` as a stand-alone tactic. We could just do something like `set delta [] in apply H`, or whatever syntax for it, or even `set conversion delta [] in apply H` (excluding the effect on conversion of closed subterms) and I believe that this would roughly gives what we expect from `simple apply` in general. We could even have the fine-grained `set delta -[repeat] in apply CR` in the above case.]

> So any tactic unfolding Opaque constants is a bug.

I would tend to think so also!

**Comment by maximedenes** [comment]
@anton-trunov In fact, I wasn't aware it didn't respect it, I discovered it while writing the patch. It should be easy to fix, I'll synchronize with @gares to make sure I'm not missing some subtleties.

**Comment by herbelin** [comment]
@maximedenes: but wait, based on "The [Opaque] command tells not to unfold the constants qualid1 … qualidn in tactics using δ-conversion (unfolding a constant is replacing it by its definition).", you should apply the same trick for `apply` and @andrew-appel would not even have to make a difference between `apply` and `simple apply`...

**Comment by maximedenes** [comment]
Yes, that's my idea (in fact almost all occurrences of `full_transparent_state` should go away). But I did the patch only on `simple apply` as a first step because I expect fewer compatibility issues. And the bug is more critical for `simple apply`, because that's what you tend to use when you want to carefully control computation.

Unfortunately, gitlab CI failed for a totally unrelated Sphinx timeout, I'll fix that, to then see the result of this fix.

**Comment by maximedenes** [comment]
@mattam82 this also looks like a bug, right?

https://github.com/coq/coq/blob/c921825a257571953e92ee4717bfb49f7ec6eb12/pretyping/unification.ml#L915-L919

(it was introduced by 92682297f528c3570dc8449118d2f2cd2be7cc53)

**Comment by mattam82** [comment]
@maximedenes that's a thorny issue. At this point we are comparing types not values and in many cases you want a different set of transparent values. E.g disallow unification from unfolding "compose" because you want to work at that level of abstraction at the term level, but still allow it to be unfolded in type unifications.

**Comment by mattam82** [comment]
In unifall I explicitely used two transparent states just for this (there's no difference between conversion and unification otherwise)

**Comment by maximedenes** [comment]
@andrew `immediate` seems defined in VST as:

```
Ltac immediate := (assumption || reflexivity).
```

right?

So I guess this is about `assumption` and `reflexivity` respecting `Opaque`.

**Comment by andrew-appel** [comment]
Oops, sorry about that.  Yes, in this case it is about `assumption` respecting `Opaque`.

**Comment by maximedenes** [comment]
@andrew-appel The second attempt for a patch to fix this, at #7004 looks much better in terms of compatibility. Ironically, it breaks only VST. So it seems you rely somewhere on `simple apply` not respecting `Opaque` : https://gitlab.com/maximedenes/coq/-/jobs/59515506

I'll investigate more soon.

**Comment by maximedenes** [comment]
> Yes, in this case it is about assumption respecting Opaque.

That one will be tricky to fix. I have a patch, unfortunately the standard library relies on the bug...

**Comment by andrew-appel** [comment]
OK, then leave "assumption" alone for now.
