### ISSUE TITLE
feature-request: editor-independent incremental compilation and feedback

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#7066]
This is a feature request, spinned off from https://github.com/coq/coq/issues/7055#issuecomment-375904541 and https://github.com/coq/coq/issues/7055#issuecomment-375905358. In short, I think it would be very useful to have a Coq equivalent of LaTeX `xdg-open *pdf & while : ; do make ; inotifywait -e modify *.tex ; done` that would produce a goal and error display regardless of the editor used for the source file. I think this would be valuable for new users (enabling them to get their feet wet quickly) and as a low-tech option for when the favorite IDE of the day is not available.

In particular, it would be cool if just saving the `.v` file triggered
- immediate cancellation of processing of sentences that are no longer present in the file (or whose dependencies have changed)
- backtracking of the proof state to the common prefix document of the processed proof state and the file contents
- parallel processing of new sentences

The goals and feedback could be displayed in a separate terminal windows, and perhaps there could be example scripts for running this in the correct layout under tmux/xmonad/emacs/etc.

This entire setup should not depend on gtk or anything else not strictly required for proof processing. Even inotifywait might be better connected to stdin instead of compiled into the binary for better portability.

I would probably be willing to do the implementation work for this if it is considered desirable and I figure out what I would be doing well enough.

@ejgallego do I understand correctly that currently I need to compile my own copy of Coq if I want to use SerAPI?

**Comment by ejgallego** [comment]
SerAPI / Coq will support this at some point, as most of the features here indeed do belong to a document manager / toplevel, but some changes to the core are needed.

> @ejgallego do I understand correctly that currently I need to compile my own copy of Coq if I want to use SerAPI?

SerAPI can be compiled against a normally-installed Coq or installed using OPAM. Are you on Windows? If so, I have no idea how things work there, but I'd be happy to prepare a windows package.

**Comment by ejgallego** [comment]
> I would probably be willing to do the implementation work for this if it is considered desirable and I figure out what I would be doing well enough.

I think that Coq is currently missing a critical bit of infrastructure in order to do a proper implementation of this idea, namely, the document model is not exported to clients. I have a now a model that indeed could be exposed to clients, but it is not gonna be tomorrow when the model is merged into Coq.

However, I could add the model as a shim to SerAPI [and build a simulator, in the style of https://github.com/ejgallego/jscoq/blob/aa5674ba91c32650bb64e486d8bde8e92fa64d65/coq-js/jscoq_doc.ml ] so you could try a first common-prefix implementation.

**Comment by ejgallego** [comment]
Another thing that will be a problem is that asynchronous error-reporting is unreliable as of today ( #5479 ) but that should not be a showstopper.

**Comment by andres-erbsen** [comment]
Thanks for the honest overview of the state of the relevant interfaces.

I am on Linux. It does look like I would need to build coq to use serapi (I will do it if that's the way we want it to work).

~~~~~~~
browse@ashryn ~/Downloads/coq-serapi (git)-[v8.8] % ocamlbuild -use-ocamlfind -j 4   sertop/sertop.native
+ ocamlfind ocamldep -package cmdliner -package coq.intf,coq.stm,sexplib -modules sertop/sertop.ml > sertop/sertop.ml.depends
ocamlfind: Package `coq.intf' not found
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.

browse@ashryn ~/Downloads/coq-serapi (git)-[v8.8] % pacman -Ql coq | grep -i intf
coq /usr/lib/coq/intf/
coq /usr/lib/coq/intf/constrexpr.cmi
coq /usr/lib/coq/intf/constrexpr.cmx
...
~~~~~~~

However, if even serapi would need a shim to track the document state, is there still good reason to use serapi instead of calling `stm` methods directly? I imagine that there would be an argument for that if serapi provided everytihng we need and was more stable than the stm ML interface, but right now it is not obvious to me what would be gained by doing this through serapi.

Regarding asynchronous error-reporting, I don't actually know how it should work. If just processing until the first error is not good enough for this interface, I can go and learn about async error reporting (I guess I should install coqide and make a document with a bunch of errors and see what it does?). I do not find this feature nearly as important as incremental compilation corner cases like backtracking into sections, though.

**Comment by ejgallego** [comment]
> I am on Linux. It does look like I would need to build coq to use serapi (I will do it if that's the way we want it to work).

In Linux, SerAPI should be able to be used as long as ocamlfind can find a coq package [please open a but if that's not the case]

So in your case, it seems that coq is not registered with `ocamlfind`. What does `ocamlfind list | grep coq` shows? If you have placed Coq in a non-standard location, you need to set the `SERAPI_COQ_HOME` variable.

In your case, it seems strange that your package manager didn't register Coq with `ocamlfind`.

> is there still good reason to use serapi instead of calling stm methods directly?

SerAPI is indeed a thin layer over the Stm `OCaml` interface. The main reason to use it is if you don't want to deal with ocaml directly. SerAPI also serves as a kind of experimental test-bed for new Coq features. For example, 8.8 init code was first written for SerAPI, then merged into Coq itself.

As its name indicates, SerAPI is mainly a "serialization" of the ML-level API. So that's what you gain, a sexp-to-ml interface.

> Regarding asynchronous error-reporting, ...

The importance of asynchronous protocols is more in the sense of avoiding a client-side, stateful queue. These kind of queues are in general pretty hard to maintain, so async gives you a simpler "reactive", "do what you see" model.

**Comment by shym** [comment]
Interesting idea. Following up from @gares’s [comment](/coq/coq/issues/7055#issuecomment-375897894) in #7055, I think that the main features that are missing in `coqtop` to make it usable for the kind of uses you suggest are debugger-like.

Here is a proposition of UI:

- add a (`coqtop`-specific, of course) vernacular command, say `Interactive Load <file.v> <line> <column>`, to get into a state corresponding to loading the content of a file up to the given position (or the last complete sentence before that position, to be forgiving) from the _initial_ state; _initial_ because the meaning of the content of a file should not depend on what was done interactively before and, above all, because that would allow incremental evaluation: successive `Interactive Load`s could, and should, reuse as much of the “current document” as possible, so that we can use this command to evaluate a .v step by step, in effect adding only one sentence at a time;
- optionally add commands such as `Step`, `Back`, `Goto`, for the particular cases where `coqtop` should not even check that the beginning of the current file.v has not changed.

Along with maybe some terminal automation (such as `tmux send-keys` or similar) might provide a comfortable environment (if a bit old-fashioned) for proof edition without much editor support.
What do you think?

**Comment by andres-erbsen** [comment]
Yes, I think `Interactive Load` could be used to implement the system I am wishing for if it properly supported cancellation and reused the common prefix with the already processed document. In particular, I think I would want to run `while : ; do echo 'Interactive Load a.v 99999999 99999999' ; inotifywait -e modify a.v 2>/dev/null > /dev/null ; done | coqtop a.v --something-about-_CoqProject`. I don't know what `Step`, `Back`, and `Goto` would do, but it looks like that I would already be happy without them? I haven't used `coqtop` directly so I may be missing something simple here.

**Comment by gares** [comment]
I think the easiest way to achieve what you want is to build on sertop, implement there the common-prefix thing, then simply execute edit_at and add. This is what pidetop does BTW (it is used by Coqoon, the main difference is that Coqoon does so every time you edit the file, not just when you save it).

As Emilio points out you need to keep some representation of the current document (eg a list of text + unique ids). Then you can compute the diff and see which is the first sentence that changed.
Executing edit_at to that point will do most of the job (the Stm will interrupt workers running on outdated jobs and so on). Then you have to Stm.add the new text, and for this sertop has a nicer (multi sentence) API IIRC. Finally you trigger the computation with Stm.finish.

**Comment by andres-erbsen** [comment]
Thanks @gares, the general outline makes sense. By "build on top of sertop", do you mean it would be better to interact with sertop through standard its input or to use with the ocaml STM API in a way similar to what sertop does? I would probably be programming in ocaml regardless.

**Comment by ejgallego** [comment]
@andres-erbsen the next version of sertop will support incremental document checking as required by LSP, in fact, such support should be added to Coq itself but I have some questions to resolve about the document model before I push to github.

**Comment by ejgallego** [comment]
Note that `dune --watch` may get close, tho of course it lacks intra-document incrementality.

**Comment by ejgallego** [comment]
@andres-erbsen coq-lsp support many of your requests, but not others, in particular only the "parallel" part is missing, as indeed, as Coq is designed today, it is not possible to do this very reliably, maybe with OCaml 5 but that will require a lot of work.

If you are interested I'd suggest to follow up the discussion to the coq-lsp repository.

I'm unsure if we should close this issue; I will but feel free to reopen, but IMHO incremental checking of something as complex as Coq documents is beyond the scope of what an issue can handle (way too many details and design tradeoffs)
