### ISSUE TITLE
Anomaly with letin in arity of an inductive and normalization

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7068]
@herbelin https://github.com/coq/coq/pull/6749#issuecomment-375951466 said:
>Actually, @skyskimmer is right that there is here an issue in the kernel: `build_branches_type` (called by `Inductive.type_case_branches`) expects the return predicate to be of the form `fun arity_context => fun x : I dom(arity_context) => body` (where the arity has form `forall arity_context, sort` with the `let-in`s not reduced) but no code is checking that this invariant holds before calling `build_branches_type`.

Since normalization will reduce those letins we can produce an anomaly:
```coq
Inductive foo : let T := Type in T := .

Definition bob := Eval lazy in foo_rect.
```

NB: still active as of 8.11

**Comment by herbelin** [comment]
I had a branch 2½ years ago which started treating predicates (and branches) morally as pairs of a context and a conclusion. I worked again a  bit on it and, in this branch, your example works for `lazy`, `cbv`, `cbn`, `vm_compute` and `native_compute`. I shall write a cep going in the direction of enforcing a context-based structure to the return predicate and branches, so that this can be discussed.
