### ISSUE TITLE
Structure for CHANGES

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7075]
Previously, Coq used to ship a `COMPATIBILITY` file whose intent was to collect all the changes that could be a source of user-level incompatibility between versions.

Now, these changes are buried in the more detailed `CHANGES` file and it is indeed hard to spot what kind of changes may need immediate source-action.

IMHO, we should either resurrect the `COMPATIBILITY` file, or provide `CHANGES` with a more principled structure, maybe à la OCaml.

**Comment by ejgallego** [comment]
@maximedenes points out that there is a `needs: CHANGES` tag. However, I am not sure we don't want a more refined approach so `needs: CHANGES` would be used for most PRs and `needs: COMPAT` for changes that introduce user-level observable changes, so they deserve even more attention.

**Comment by Zimmi48** [comment]
FTR this file has been buried because anyways it was not consistently updated and CHANGES was updated instead. We could indeed structure CHANGES more but, contrary to OCaml, the changelog between two versions of Coq is not so long and reading it entirely is not such a difficult task.

So: not opposed to giving more structure to CHANGES if you have a proposal, but I wouldn't tend to worry about it unless some users complain.

@tchajed You are a user of Coq master branch and you indicated in the past that you rely on CHANGES to spot compatibility problems. What is your opinion on this question?

**Comment by tchajed** [comment]
I agree with your assessment that the Coq CHANGES file is short enough to read.

I think it’s easy to get carried away with lots of structuring. I would recommend just three categories:

1) internal: API changes that only impact plugin developers and other Coq developers.
2) new features: things that shouldn’t impact any existing code but are good to know about
3) user-facing: any change that might affect users’ code

If in doubt, I would classify a change higher (since as a reader I might skip category 1 changes, for example). Drastic performance changes belong in category 3 as well, just in case. For simplicity I think bug fixes can be lumped into category 3 as well.

**Comment by Zimmi48** [comment]
Note that category 1 is already well separated as it belongs to `dev/doc/changes.md`

**Comment by Zimmi48** [comment]
For future reference, this automatic changelog generator was mentioned on GitHub: https://github.com/skywinder/Github-Changelog-Generator
We could consider using such a tool and a good language of labels to automatically generate a detailed and structured changelog. However, it has quite low priority to my eyes.

**Comment by tchajed** [comment]
I don't like the idea of an automatically-generated changelog - I think it's a good opportunity to write a succinct description of just the changes, and should in general be more carefully written than Coq's commit messages and PR descriptions.

If we want to make minimal changes to the `CHANGES` file, we could adopt the OCaml policy of using a `*` rather than ` -` for entries that could affect existing code (everything else is a new feature, or a bug fix for a previously rejected program).

**Comment by aspiwack** [comment]
I'm not arguing either way. But I think all participants in this debate should probably have a look at the automated tools before dismissing them (here's another one written in Rust: https://github.com/clog-tool/clog-cli , for those among us who will recognise themselves ;-) much fewer users, and less frequent updates though). Read their design, and arguments. Look at what the produced changelogs look like.

For one thing, these are people who thought much more about changelogs than probably any of us did (here is by the way an initiative trying to standardize changelogs: https://keepachangelog.com/ ). Thus we all have a lot to learn from them.

But anyway, if we are to argue against something, it's better to argue against what it is (oh, and here is a somewhat standardised commit format, originated in Google's Angular project: https://conventionalcommits.org/ ) than against a straw man.

I don't personally have an opinion. So I'll leave it to you.

**Comment by ejgallego** [comment]
Well, my original idea when opening this issue was to curate CHANGES more, I'm not sure how an automatic system is gonna help with that [it could indeed, but I am not sure we can achieve the commit discipline or predict things so accurately].

**Comment by Zimmi48** [comment]
The current situation (documented in https://github.com/coq/coq/tree/master/doc/changelog#unreleased-changelog) has added much more structure to the changelog. It seems to me it is good enough for now, but we might still want to add some more information, like a marker for compatibility-breaking changes. Closing this now, but please reopen if you think more action is needed.

**Comment by ejgallego** [comment]
Thanks @Zimmi48 ; indeed maybe we could try to adopt some kind of "breaking" marker as OCaml does.

IMHO it should be easy enough as to be doable quickly.
