### ISSUE TITLE
Warning on accord singular/plural in some commands

### ISSUE THREAD

**Issue by herbelin** [coq/coq#7128]
There is a warning on `Variable`/`Variables`, `Parameter`/`Parameters`, `Implicit Type`/`Implicit Types`, ... when used with a number of arguments which does not match the corresponding singular/plural form.

I'm opening this side issue to collect (argumented) opinions. Does the satisfaction of a grammatically correct sentence really challenge the burden of having to possibly change the spelling of the command when we add or remove arguments? Isn't this grammatical correctness a bit gratuitous and artificial considering that the language of commands is anyway not proper English but before all a language borrowing words from English corpus. Doesn't the duplication of singular and plural forms of commands make grepping, highlighting, and other mechanical process uselessly complex? Would it bad to keep only the plural form, thinking at the arguments as a list of arbitrary length (hence plural), and length 1 as a particular case of an arbitrary length (hence accepting a plural form)?

**Comment by Zimmi48** [comment]
Isn't it the `pendantic` category (which is disabled by default)? If yes, it doesn't do much harm to keep this warning for the users that may want to use it (but are there some?). `grepping` is not affected by this AFAICT since the only difference is a `s` at the end. That being said, Coq must be one of the only languages to provide such duplicated constructs.

**Comment by maximedenes** [comment]
Indeed the warning already exists, but is disabled by default.
