### ISSUE TITLE
Windows build script: enable incremental builds and provide documentation for debugging Coq

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#7157]
The Windows build scripts as is can build Coq, but they don't support development of Coq on Windows well. The main issues are:

1.) incremental builds are not supported - the build system always clears the complete build folder - an "incremental" option is required

2.) it should be possible to build byte code variants for debugging.

3.) Documentation for debugging is required.

**Comment by jfehrle** [comment]
1 and 2 would be a good step forward.  A better approach (if possible, and probably much more work) would be to have
- a minimal .bat script to set up cygwin and download components such as labgtk, patch their source code and then build them
- then do the final build for installation and incremental developer builds using makefiles that are also used to build for other OS's such as Linux

For 3, there are already some notes (including a few from me) in debugging.md.

**Comment by MSoegtropIMC** [comment]
at least for Coq my build scripts do this:

- get the sources
- do some very minor patching
- run configure
- run make

The configure and make files used are (except for the very minor patches) identical to those used on Linux. So as far as I understand what you describe above is completely covered by just supporting incremental builds. Or put in other words: I don't understand where the difference is between what you proposed and what I proposed.

Maybe you can have a look at the make_coq function in my script and tell in which way you would change it in addition to enabling incremental builds and debug builds.

All the rest of the shell script creates support libraries and the installer and is not required at all on Linux, where such libraries exist out of the box. Many of the libraries are meanwhile taken from cygwin (GTK for MinGW didn't exist in cygwin when I started). The functions to build these libs are still there but actually not used (there is an option to use them). So the build process as is is already very very close to what happens on Linux, at least for Coq itself.

**Comment by Zimmi48** [comment]
Could this very minor patches be integrated directly in the Makefile without breaking the compilation on Linux?

Make already supports incremental compilation so I think that what @jfehrle means is just that if there is an initial script to setup the right compilation environment, then the developers working on Windows can just setup this environment once, then use configure / make for the compilation proper (in particular, using the `-local` option instead of `-prefix ...`).

**Comment by MSoegtropIMC** [comment]
> Could this very minor patches be integrated directly in the Makefile without breaking the compilation on Linux?

I guess so, I think it is just some wrong tool paths or names.

Regarding incremental builds: I guess we all mean the same then. Currently the scripts are made at a module wrapper level (coq being a single module here) such that each module is always compiled completely from scratch. If the previous build was not successful, the whole module folder is erased, sources are retrieved, configure is run and so on. This is appropriate for making reliable release builds (the main purpose of these scripts), but not for development. As far as I can tell this is the only thing which needs to change.

What I have in mind is something like that the top level script can be instructed to setup the environment for development of a specific module, e.g. Coq, but later it could also be a specific plugin or OCaml or whatever. The top level script would then setup everything and also compile the module, but not make a make clean. One can then run the top level script again for an incremental build or call make directly.

What needs to be discussed if the build scripts should be able to make builds in an existing Coq git repo. Currently the build scripts copy the repo to a local folder, but that wouldn't be hard to change.

**Comment by jfehrle** [comment]
> Make already supports incremental compilation so I think that what @jfehrle means is just that if there is an initial script to setup the right compilation environment, then the developers working on Windows can just setup this environment once, then use configure / make for the compilation proper (in particular, using the -local option instead of -prefix ...).

Yes, that is the idea.


I omitted some important details.  I'm able to build coqtop, both binary and bytecode, full builds and incrementally without much trouble.  The problem is building coqIde.  When I run the configure script, I get the following output and error:

```
$ ./configure
You have OCaml 4.02.3. Good!
You have OCamlfind 1.7.3. Good!
You have Camlp5 7.03. Good!
You have native-code compilation. Good!
No such directory 'C:/OCaml64/home/Jim/.opam/4.02.3+mingw64c/lib/ocaml/lablgtk2' (in OCaml library).
LablGtk2 not found:
=> no CoqIde will be built.
Where should I install the Coq binaries [C:/coq/bin]?
...
```

So I'm not able to build coqide with the makefile.  Makefile.ide refers to files lablgtk.cma, lablgtksourceview2.cma, lablgtk.cmxa and lablgtksourceview2.cmxa, whereas makecoq_mingw.sh seems to use 2 DLLs that end up in the coq/bin directory (LIBGTKSOURCEVIEW-2.0-0.DLL and LIBGTK-WIN32-2.0-0.DLL).  I think that's part of the problem (though that's based on memory and a very quick look at the script.)

I'm able to compile and run the coqtop binary from the source tree with the command "bin/coqtop -coqlib .".  To run coqtop.byte, I use the same arguments, however the byte code needs kernel/byterun/dllcoqrun.dll, so I add kernel/byterun to my PATH.  It would be a nice touch if the makefile build copied this DLL to the ./bin directory.

More important, there are about 30 DLLs that makecoq_mingw.sh puts in the output bin directory.  It would be helpful if the makefile would copy them there automatically.  (Perhaps I should be specifying -local as @Zimmi48  suggests--or "./bin" for "Where should I install the Coq binaries?" above--but I didn't investigate since the makefile doesn't even generate coqide.exe.)

**Comment by Zimmi48** [comment]
Using the local option would avoid you passing the coqlib argument.

**Comment by MSoegtropIMC** [comment]
@jfehrle : the gtk library is build by my scripts. I will concentrate on methods based on these scripts. In my opinion it doesn't make sense to come up with yet another build method (besides opam and my scripts) for the purpose of development. I am confident that I can deliver a nice and seamless developer experience on Windows.

@Zimmi48 : I agree that integrating some of the Windows specifics into the original make file rather than working around them from the outside. Some things, like collecting licenses and readme files in a single place, also make sense for Linux.

**Comment by jfehrle** [comment]
> Using the local option would avoid you passing the coqlib argument.

Great!  That also copied the 30 DLLs and eliminates the need to add kernel/byterun to my path.

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform.

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
