### ISSUE TITLE
Fixpoint check in the kernel introduced by #407 is not enough 

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#7262]
The following code is wrongly accepted by the kernel as of 8.8.
```
Fixpoint foo (x y : unit) : unit := match x with tt => tt end.
```

**Comment by maximedenes** [comment]
You don't even need the match. That's because `unit` is not declared as a record. In fact, reading #407, it is not obvious to me that this is not the intended behavior:

"We limit fixpoints to Finite inductive types, so that BiFinite inductives (non-recursive records) are excluded from fixpoint construction."

**Comment by ppedrot** [comment]
Really? Didn't we have an example from parametricity showing that even for non-records fixpoints on non-recursive types were evil?

**Comment by maximedenes** [comment]
> Really? Didn't we have an example from parametricity showing that even for non-records fixpoints on non-recursive types were evil?

I'm afraid we have to be more precise with the words we use.

First, despite what the release notes claimed at some point, AFAIK #407 was never meant to fix parametricity. For that, you'd need to forbid fixpoints without recursive calls.

Second, I agree that #407 was expected to fix one example of SR breakage, and failed to do so. But read again the sentence "We limit fixpoints to Finite inductive types, so that BiFinite inductives (non-recursive records) are excluded from fixpoint construction".

What does it mean? AFAIK, BiFinite inductive types are Finite inductive types, so the first part is vacuous. Second, non-recursive records (which have to be declared by the user) are not the same thing as non-recursive inductive types in record form.

Now, to add to the confusion, this `BiFinite` business seems very strange to me. The kernel can obviously not infer if a type should be read as `Inductive` or `CoInductive`. On the other hand, it can infer if a type is recursive or not. So mixing all this in a type with three states meant that it would reflect user declaration rather than kernel inference. In particular, basing a restrictive rule (as in forbidding `BiFinite` types somewhere) is not going to lead anywhere.

**Comment by maximedenes** [comment]
> BiFinite inductive types are Finite inductive types

Btw, this contradicts the datatype used in the kernel, but I don't understand that one in the first place.

**Comment by SkySkimmer** [comment]
>So mixing all this in a type with three states meant that it would reflect user declaration rather than kernel inference.

Yes finiteness is decided in parsing:
https://github.com/coq/coq/blob/ed5ec093c216bef6629657f69d7f94256e3ec009/parsing/g_vernac.ml4#L241-L248

**Comment by mattam82** [comment]
You're right, I got confused by the nature of the Finite/BiFinite flag which reflects the user intent. I would prefer a solution where we allow the user to write Inductive for unit but the kernel relies on its own inference to realize it is not recursive and disallows fixpoints, with the idea that "inferred nonrecursive" can be put into any of Finite/BiFinite/CoFinite. Maybe warning the user that he should write Variant instead of Inductive/CoInductive if the definition is inferred to be non-recursive. Does that reasoning sound good to you guys?

**Comment by Zimmi48** [comment]
What is the difference between `Variant` and `Record`? Do you get primitive projections only with the second one?

**Comment by SkySkimmer** [comment]
Variant does not allow record syntax, it's like Inductive but not recursive.

```ocaml
let declare_mutual_inductive_with_eliminations mie pl impls =
   (* spiwack: raises an error if the structure is supposed to be 
non-recursive,
         but isn't *)
   begin match mie.mind_entry_finite with
   | Declarations.BiFinite when is_recursive mie ->
       if Option.has_some mie.mind_entry_record then
         user_err Pp.(str "Records declared with the keywords Record or 
Structure cannot be recursive. You can, however, define recursive 
records using the Inductive or CoInductive command.")
       else
         user_err Pp.(str ("Types declared with the keyword Variant 
cannot be recursive. Recursive types are defined with the Inductive and 
CoInductive command."))
   | _ -> ()
   end;
```

Gaëtan Gilbert

**Comment by SkySkimmer** [comment]
Not actually an issue, #407 was about SR breakage and there is none here.
