### ISSUE TITLE
do 1000 (do 1000 (do 1000 idtac)) allocates gigabytes of RAM

### ISSUE THREAD

**Issue by cpitclaudel** [coq/coq#7385]
#### Version

a76730b8479b9036e814cc3ff5e7f32d46fc942c (master)

#### Operating system

Linux _ 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

#### Description of the problem

Running an infinite idtac loop using `do` seems to leak memory:

```coq
Goal False.
  do 5000 (do 5000 (do 5000 (do 5000 idtac))).
```

When I run this using `coqc infloop.v`, Coq allocates increasing amounts of memory, seemingly linearly.  I killed it at around 6GB.

This started in 8.5, apparently.  Is it due to the new backtracking semantics?

**Comment by ppedrot** [comment]
The memory is indeed allocated by the tactic monad. But there is something very fishy here, because according to the memory profiling information this is specifically due to backtracking primitives. There is a priori no backtracking involved in this piece of tactic, so it looks like there is some under-optimal implementation choices of Ltac going on here. An educated guess would blame that on the half-broken debugging mechanism.

**Comment by ppedrot** [comment]
Suspicion confirmed: it is due to the implementation of backtraces. The following patch that removes the instrumentation of Ltac call frames makes your example run in constant memory:
```diff
--- a/plugins/ltac/tacinterp.ml
+++ b/plugins/ltac/tacinterp.ml
@@ -171,9 +171,9 @@ let catch_error call_trace f x =
     catching_error call_trace iraise e
 
 let catch_error_tac call_trace tac =
-  Proofview.tclORELSE
+(*   Proofview.tclOR *)
     tac
-    (catching_error call_trace (fun (e, info) -> Proofview.tclZERO ~info e))
+(*     (catching_error call_trace (fun (e, info) -> Proofview.tclZERO ~info e)) *)
 
```

**Comment by ppedrot** [comment]
The best I can do is to provide a flag to turn off the backtrace printing in Ltac. Whether it should be on by default is worth a discussion.
