### ISSUE TITLE
What is the appropriate level of abstraction on which a sentence location should be attached?

### ISSUE THREAD

**Issue by herbelin** [coq/coq#7409]
Currently, there is a `locate_if_not_already` which adds a location to errors of `Vernacentries.interp` in case there is not already a finer location.

In the `stm`, there is `process_transaction`, `query`, `reach` and `perform` which call `Vernacentries.interp`. The method `process_transaction` comes with a location but not `query`, `reach` and `perform`. There are parts of `process_transaction` which are a priori liable to raise errors but which do not call `interp` and which may then not necessarily be encapsulated with a location. Shouldn't they be encapsulated?

At the current time, I did not investigate the purpose of each part of `process_transaction`, the purpose of `query` and the one of `perform`, and the one of `reach`, assuming that more experts than me could explain.

So, the question remains open at this time (for at least @ejgallego and me, see discussion at #7134): what are the exact entry points where a sentence location is relevant.

**Comment by ejgallego** [comment]
@herbelin , the location of a sentence is stored in the `aast` type in the STM. This is the canonical one; and all the methods above have access to it except `process_transaction` which is the one creating the node itself.

As for `locate_if_not_already`, let me remark that this is used in error handling. Usually, exception contain location information as to refine the part of the sub-sentence that should be displayed. If no such location information is present, then the method tries to attach the location of the sentence.

Now we need to distinguish two scenarios as the current situation is derived from them and a bit tricky:
- The STM was supposed to provide asynchronous error handling. In this scenario, every error comes with a location, which is added by the document traversal. Due to the way document traversal works this is hard to do and it doesn't always work. Also, if there is not location info the span id can be used to retrieve the location, modulo bugs such as #6884 .

- As for exceptions, again it seem the place to add this information would be the document traversal code, however this is a bit tricky to hook today. In my opinion the best place may be `stm_vernac_interp`.

**Comment by ejgallego** [comment]
`parse_sentence` is a bit special and should do it's own bookkeeping for errors / locations.

**Comment by maximedenes** [comment]
Closing this question issue as it was answered, feel free to reopen if more information is needed.
