### ISSUE TITLE
4811.v non deterministic

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#7483]
Here is a recent spurious failure due to [4811](https://github.com/coq/coq/blob/master/test-suite/bugs/closed/4811.v): https://gitlab.com/Zimmi48/coq/-/jobs/67687015

FTR, the log is the following:

```
==========> TESTING bugs/closed/4811.v <==========
While loading initial state:
Warning: Cannot open src [cannot-open-path,filesystem]
While loading initial state:
Warning: Cannot open Bedrock [cannot-open-path,filesystem]
While loading initial state:
Warning: Cannot open coqprime-8.5/Coqprime [cannot-open-path,filesystem]
Finished failing transaction in 1. secs (0.7u,0.016s) (failure)
File "/builds/Zimmi48/coq/test-suite/bugs/closed/4811.v", line 1685, characters 2-25:
Error: Timeout!

0m0.000000s 0m0.000000s
0m2.010000s 0m0.490000s
==========> FAILURE <==========
    bugs/closed/4811.v...Error! (bug seems to be opened, please check)
```

Once again, the source of non-determinism is the use of the `Timeout` command. In light of #7408, #7430, shouldn't we remove all the tests that rely on this command?

**Comment by ejgallego** [comment]
> In light of #7408, #7430, shouldn't we remove all the tests that rely on this command?

I think we should instead fix `Timeout`, I do think it is possible but I'll talk about that in the proper issue.

The good news is that indeed I think we have finally understood the reason why these bad failures happened.

**Comment by Zimmi48** [comment]
I had a new occurrence: https://gitlab.com/Zimmi48/coq/-/jobs/73460133
Three already reported non-deterministic tests failed because of `Timeout` (see also #7388, #5982).

**Comment by Zimmi48** [comment]
New occurrence: https://gitlab.com/coq/coq/-/jobs/93028883

**Comment by Zimmi48** [comment]
And another one here: https://gitlab.com/coq/coq/-/jobs/93040622
@JasonGross could it be the sign of anything else than bad luck? (Note that the two failures I noted are from the v8.8 branch.)

**Comment by JasonGross** [comment]
@Zimmi48 I'm not sure.  Given that the bug report was `f_equal` loops, it should be perfectly fine to bump `Time Timeout 1` to `Time Timeout 2` at the end of the file.  However, the timing recorded from 8.4 is `Finished transaction in 0. secs (0.3u,0.s)`, and the log from one of these says `Finished failing transaction in 1. secs (0.236u,0.022s)`.  I'm kind-of suspicious about where the missing .7 seconds of real time are coming from.

Perhaps the test-suite should be run with `-j1` rather than with `-j "$NJOBS"`?

I think it would help significantly if there were a `UserTimeout` command which measured user-time rather than real-time.  Based on https://stackoverflow.com/a/34206961/377022, a decent way to do this might be to use `ulimit -t` (or whatever the appropriate version of that is in OCaml), and spawn the vernac command in a separate process.  Alternatively, and perhaps even better, might be to provide `CPUCyclesTimeout` and `CPUCyclesTime` commands, based on [`clock()`](https://www.gnu.org/software/libc/manual/html_node/CPU-Time.html#CPU-Time), which would allow specifying numbers of cpu cycles rather than real times.  This should be more processor- and work-load- independent.

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/102208976

**Comment by SkySkimmer** [comment]
https://gitlab.com/coq/coq/-/jobs/118082164

**Comment by JasonGross** [comment]
Once again, we have somehow lost .8 seconds somewhere, as we have "Finished failing transaction in 1. secs (0.179u,0.s) (failure)"

**Comment by Zimmi48** [comment]
https://gitlab.com/coq/coq/-/jobs/134555062
