### ISSUE TITLE
Post-mortem description of kernel soundness bugs

### ISSUE THREAD

**Issue by ppedrot** [coq/coq#7604]
Following a proposition made in PR #7521, I think that every kernel soundness bug should give rise to a post-mortem describing the root of the problem, the consequences and the fix that has been implemented. This is on par with what is performed the domain of security breaches.

**Comment by herbelin** [comment]
To work in a systematic way as suggested by @ppedrot, a possible direction is to define an OCaml record structure for the database, together with a small tool to extract the information to a web page or a text file. Let's take the example of a critical bug with template polymorphism that I introduced in 2006 and which was fixed in 2011. Typical informations I see at the current time are the following:
```
  component: universes	
  subcomponent: template polymorphism
  summary: issue with two parameters in the same universe level	
  introduced: trunk/master, 23 May 2006, 9c2d70b, r8845, Herbelin
  impacted released versions: V8.1-V8.1pl4, V8.2-V8.2pl2, V8.3-V8.3pl2
  impacted development branches: none
  fixed in: v8.1 branch (a8fc2027, 5 Oct 2011, Herbelin), v8.2 branch (3333e8d3, 5 Oct 2011, Herbelin), V8.3pl3 (bb582bca2, 5 Oct 2011, Herbelin), trunk/master/v8.4 (8082d1faf, 5 Oct 2011, Herbelin)
  found by: Barras
  exploit: test-suite/failure/inductive4.v
  GH issue number: none
  risk: unlikely to be activated by chance
```
@mattam82, are you ok on the principle? @ppedrot, what do you think? @maximedenes, any comment? In any case, I can start with a prototype which we can make evolve afterwards.

**Comment by mattam82** [comment]
In principle yes, I think it's fine to document those. I would go for a lightweight, textual format following a template (e.g. markdown with links) and not overengineer this.

**Comment by herbelin** [comment]
The reason I was thinking at a machine-readable format is for making requests easier, e.g. getting the list of bugs in a given version number, automatically producing the list of test-suite files to run to check that the bug is not there, automatically computing the life span of a bug, etc.

It is also that I had a hard time producing opam files from the `description` file of coq-contribs (and @gares had a hard time too), to not try again to machine-process textual files. When using  Unix tools available for text processing, there are always issues with spaces, with newlines, with quotes, ... At the end, I moved to a more sophisticated tool and had to reconstruct a database in this sophisticated tool anyway. (I still have to make this opam work public actually.)

On the other side, we could try to have a well-formatted text file which could be read both by machine and human. Somehow, the above is an example. So would you prefer we codify the example above? Then, is the proposed format ok?

**Comment by Zimmi48** [comment]
One thing that is not always very clear is the “introduced” field. For instance, #7798 fixes a bug by mostly reverting a commit dating back from Coq 8.1. But the soundness bug that was exhibited uses recent features. In some cases, it may not be clear whether the bug could have been exploited from the beginning, even if the soundness issue was lurking.
