### ISSUE TITLE
Show Proof uses the wrong environment 

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq#7622]
```coq
Variable x : nat.
Lemma foo : ((nat -> nat) * (nat -> nat))%type.
Proof.
  split.
  intros y. exact x.
  intros x. Show Proof. (* (fun _ : nat => Top.x, fun x : nat => ?Goal) *)
  exact x.
Qed. Print foo. (* foo = (fun _ : nat => x, fun x : nat => x) *)
```
Not sure if we can trick it into printing something wrong or if it's just going to over-qualify in rare situations.

**Comment by herbelin** [comment]
I suspect it is because the open goal potentially depends on the (new) `x`, so the occurrence to the section variable and the new occurrence have to be distinguished. If you `clear x` before `Show Proof`, you'll see the same as outside the proof (i.e. using `x` for the section variable, since there is no more clash of names).

**Comment by JasonGross** [comment]
This happens even if you replace `Variable` with `Axiom` and do this outside a section.
