### ISSUE TITLE
`cbn` fails to unfold even though argument is a constructor

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7674]
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem
Description embedded in the code:

```coq
Require Bool.

Definition do_something (p q : bool) (a b : nat) : option nat :=
  if Bool.eqb p q then Some a else Some b.
Arguments do_something !_ !_ _ _ /.

Lemma test a b :
  exists x, do_something false true a b = x.
Proof. intros. eexists.
(* Now the goal is do_something false true a b = ?x.
   I'd expect the following to unfold [do_something] because the
  argument specification is satisfied. However, nothing happens. *)
Fail progress cbn [do_something].
(* However, adding the boolean comparison function to the list of
  symbols enables the unfolding. *)
progress cbn [do_something Bool.eqb].
reflexivity.
Qed.
```

So it seems that whether the occurrence of a symbol *inside* a definition makes a difference for whether or not the definition itself is unfolded. This is such a "wtf" that it took me forever to figure out.

**Comment by anton-trunov** [comment]
I think this is expected behavior.

`cbn [do_something]` makes `cbn` unfold *only* `do_something`, so it would not unfold `Bool.eqb`.
Also, `simpl` and `cbn` only unfold a constant if it leads to 𝜄-reductions.
But since `Bool.eqb` is kind of opaque in this case, no 𝜄-reduction can happen and `cbn` leaves the goal intact.

**Comment by RalfJung** [comment]
> Also, simpl and cbn only unfold a constant if it leads to 𝜄-reductions.

Wait, what? That would explain this behavior, but I have never heard about this restriction. (And which ones are 𝜄-reductions anyway?)

Moreover, `About do_something` says that

> The reduction tactics unfold do_something when the 1st and
  2nd arguments evaluate to a constructor and when applied to 4 arguments 

This is factually incorrect currently.

**Comment by RalfJung** [comment]
Moreover, if I remove the `!` from the `Arguments`, `cbn` *does* unfold `do_something` even though that does not lead to any further reductions.

**Comment by anton-trunov** [comment]
> Wait, what? That would explain this behavior, but I have never heard about this restriction. (And which ones are 𝜄-reductions again? I keep mixing them all up.)

The manual says that `simpl` and `cbn` "unfold a constant if and only if it leads to a 𝜄-reduction, i.e. reducing a match or unfolding a fixpoint" ([here](https://coq.inria.fr/distrib/current/refman/proof-engine/tactics.html#coq:tacn.cbn)).

>Moreover, if I remove the ! from the Arguments, cbn does unfold do_something even though that does not lead to any further reductions.

Indeed, this is strange. I think the refman needs further clarification on this. Let me link #7389 here, since that is related and could be covered with the current issue.

**Comment by RalfJung** [comment]
> The manual says that simpl and cbn "unfold a constant if and only if it leads to a 𝜄-reduction, i.e. reducing a match or unfolding a fixpoint"

Thanks. This could explain why, after many years of using Coq, I still have no internal model of what either of these tactics do.

I find this a very surprising choice.

> Let me link #7389 here, since that is related and could be covered with the current issue.

I totally agree with that issue. The issue tracker here has quite a few simpl/cbn-related issues that are probably related (like when `simpl` unfolds things that are `simpl never`, but somehow that's not a bug).

However, it seems there is another issue here: The clause about requiring an 𝜄-reduction is not actually correct for cbn.

**Comment by anton-trunov** [comment]
> The issue tracker here has quite a few simpl/cbn-related issues that are probably related

At Coq Implementors Workshop 2018 we discussed with @Zimmi48 that the [Performing computations](https://coq.inria.fr/distrib/current/refman/proof-engine/tactics.html#performing-computations) section needs to be improved. I volunteered to make some improvements [probably in July, when on vacation ;)]. 

I'm wondering if it's possible to arrange some kind of project on GitHub to group those related issues.

**Comment by anton-trunov** [comment]
@Zimmi48 Awesome, thank you!

**Comment by Janno** [comment]
What is the status of this issue? The initial comment says this is intended behavior but the difference between just `/`  and`!` + `/` seems to muddy the waters quite a bit.

We find ourselves adding only `/` to `Arguments` of simple (non-recursive) definitions so that `cbn` will simplify them despite the fact that we really only want them to simplify when they are applied to constructors (for some arguments, at least).

Here's a smaller example that, I think, shows the same behavior as the original example:
```
Definition foo (n : option nat) : nat := 0.

Goal forall n, foo (Some n) = 1.
  intros.
  Arguments foo !_ /.
  Fail progress cbn.
  Arguments foo _ /.
  progress cbn.
```

**Comment by maximedenes** [comment]
I guess the root of the problem is that the combination of `!` and `/` was never specified , AFAIK. So of course `simpl` and `cbn` implement different behaviors.

@gares In the last example, you'll see `Fail progress cbn`. At that point, `simpl` does reduce, though. Which one has the expected behavior for this set of flags? We can take care of documenting it and fixing the one which is wrong.

The questions are:
- does `!` maintain the "needs a iota-step" condition or not?
- does `/` maintain it? (the `volatile` example in the manual says no)
- what does the combination of `!` and `/` mean?

**Comment by maximedenes** [comment]
In fact, this last example is the same as https://github.com/coq/coq/issues/4555. I had attempted to fix it there, but the problem was that `cbn` unfolds then refolds the constant.

> the more principled `cbn` tactic

IMHO, when you look at the way it is implemented, it is debatable whether it is really "more principle" than `simpl`. In particular the refolding part.

**Comment by Janno** [comment]
> In fact, this last example is the same as #4555. I had attempted to fix it there, but the problem was that cbn unfolds then refolds the constant.

This seems to match what I see with `Set Debug RAKAM` where it seems the algorithm traverses into `foo` but throws away the result of that.

> IMHO, when you look at the way it is implemented, it is debatable whether it is really "more principled" than simpl. In particular the refolding part.

I see. Once aspect in which I thought it was more principled was performance. While it seems generally slower, it is also way more predictable in my experience. We were originally motivated to switch from `simpl` because `simpl` was taking minutes to finish on some terms. I am not sure if we ever figured out the exact root cause. (I see that https://github.com/coq/coq/pull/13769 went into 8.14 so we'll know once we upgrade if that change helped.)

Switching to `cbn` fixed this kind of performance issue. However, we also saw a measurable but small general slowdown. This is preferable to multi-minute spikes, though. (Sadly, we still need to call `simpl` every now and then when `cbn` doesn't make progress.)

**Comment by gmalecha** [comment]
> The questions are:
> 1. does ! maintain the "needs a iota-step" condition or not?
> 2. does / maintain it? (the volatile example in the manual says no)
> 3. what does the combination of ! and / mean?

I can't comment on 1 and 2, but for 3 I *expected* the answer to be a conjunction, i.e. reduce if all conditions are satisfied. That seems to fit @RalfJung's mental model as well where he wants to reduce `do_something` only if both arguments evaluate to constructors.

**Comment by RalfJung** [comment]
Yes, that is what I would expect -- it is what I typically want in such a situation.
I am not sure when I would want a disjunction.

**Comment by gares** [comment]
IIRC `/` was added to let one unfold constants which *do not* contains a iota step. In MathComp we had a hack for "simplifying definitions" which had a dummy match on a unit argument which was always passed via a notation.

Said that the iota condition (typical of simpl before Arguments) is disable with `/` but also superseeded by `!` which is more precise. So I agree with @gmalecha that the intended meaning is conjunction: do not need a iota step, but requires the argument to be a constructor.

IIRC my wording in the manual was ambiguous, but that was fixed (by @maximedenes) IIRC. Then making cbn behave as simpl was maybe not easy. But the refolding thing seems to suggest that cbn as well does unfold foo (giving the same meaning as simpl) but then magically reverts it as a side effect of refolding. Maybe the refolding step should be run only for definitions containing a `fix` (that is what refolding is for, to not see unnamed fixpoints in the resulting expression).

**Comment by Blaisorblade** [comment]
I agree with the proposed change, but I suspect it's hard to reason about `cbn`'s spec in terms of unfolding and refolding... I wonder if the spec should be expressed in terms of the rewrite equations that are desired, following also the example of Agda and Coq-Equations.

**Comment by gares** [comment]
This is what I've been saying for a long time, simpl should be a rewriting system based on (oriented, non conditional) equations which hold by reflexivity and whose LHS is searched for using FO matching (where all non-user written subterms are wildcards, like implicit arguments). Stuff like Equations would start from these equations to define the fix, while Fixpoint would go the other way around (in this case the user did not write a fix explicitly, so the branches are already kind of refolded). If one overrules these equations with hand written ones he can easily simulate `!` and `/` and `: never`. Given that these equations are proved by reflexivity, the procedure can recurse under binders unlike regular rewrite (the proof term will be vacuous, so no problem there).

But that would be a very different code base with a different, hopefully more predictable, behavior. And maybe it won't work well in the end, but for sure it is more "principled" than simpl and cbn.
