### ISSUE TITLE
Associativity differs between /\ and * and between \/ and +

### ISSUE THREAD

**Issue by olaure01** [coq/coq#7676]
#### Version
Coq 8.8.0

#### Operating system
Ubuntu 16.04

#### Description of the problem
Binary constructors ```/\``` and ```\/``` (Prop -> Prop -> Prop) associate to the right while * and + (Type -> Type -> Type) associate to the left, thus leading to a strange behaviour when one wants to move from Prop to Type.

```
(* Constuctors \/ and + associates differently *)
(* Constuctors /\ and * associates differently *)

(* \/ associates to the right *)
(* A \/ B \/ C = A \/ (B \/ C) *)
Goal forall A B C : Prop, B -> A \/ B \/ C.
Proof.
intros.
(* Check (A \/ (B \/ C)). *)
right.
left.
assumption.
Qed.

(* + associates to the left *)
(* A + B + C = (A + B) + C *)
Goal forall A B C : Prop, B -> {A} + {B} + {C}.
Proof.
intros.
(* Check (({A} + {B}) + {C}). *)
left.
right.
assumption.
Qed.

(* + associates to the left *)
(* A + B + C = (A + B) + C *)
Goal forall A B C, B -> A + B + C.
Proof.
intros.
(* Check ((A + B) + C)%type. *)
left.
right.
assumption.
Qed.



(* /\ associates to the right *)
(* A /\ B /\ C = A /\ (B /\ C) *)
Goal forall A B C : Prop, A /\ B /\ C -> B.
Proof.
intros A B C H.
(* Check (A /\ (B /\ C)). *)
destruct H as [H1 H2].
destruct H2 as [H2 H3].
assumption.
Qed.

(* * associates to the left *)
(* A * B * C = (A * B) * C *)
Goal forall A B C, A * B * C -> B.
Proof.
intros A B C H.
(* Check ((A * B) * C)%type. *)
destruct H as [H1 H3].
destruct H1 as [H1 H2].
assumption.
Qed.
```

**Comment by Zimmi48** [comment]
cc @maximedenes 
(That's the kind of issues that should be gathered in a GitHub project so that these historical mistakes are not made again in Standard Library 2.0.)

**Comment by herbelin** [comment]
To feed the discussions, note the following constraints we had at the time of moving from 7.0 syntax to 8.0 syntax:
- Since `sumor` takes its `Type` argument on the left, `+` has to be associative on the left.
- To nest `exists` and `and`, it is better to have `and` associative on the right. Then, we can also use the `&` intro pattern.

In 7.0, `*` was associative on the right. We apparently moved it associative on the left for 8.0, probably by consistency with `+`, but not fully sure of the motivation.

See also #306.

PS: To the risk of repeating, this is the kind of changes for which a translator would be useful.

**Comment by andres-erbsen** [comment]
As multiplication is also defined for numbers, `*` and `+` must remain as-is so that `a/c*b` and `a-b+c` parse as expected. A separate grammar entry for types and values would help here but I don't think we want this in a dependent type theory.
For `/\` and `\/`, it makes sense that the clause presented first in concrete syntax is at the root of the syntax tree and proven first through `split`/`left`, so changing to match `*` and `+` would not be desirable.

Allowing `*` to land in `Prop` ([cep](https://github.com/coq/ceps/pull/55/files#diff-b31fa53e71b53379eaefdad44a29d141a7d5b7e18b724dde4e42576bc83ff179R51-R72)) could allow `*` and `/\` to be used to choose the associativity, which seems actually quite nice to me.
