### ISSUE TITLE
We should avoid merging PRs with outdated CI

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#7718]
Recently, we have seen quite a few failures due to PRs with stale successful CI being merged. We need to avoid this.

Ideally, we would have a bot comparing the md5 sum of the CI files and adding a `needs:rebase` label to those outdated.

**Comment by Zimmi48** [comment]
A policy could be to discard CI builds when the base branch is outdated. GitHub supports this but this is too much for us because that would seriously impact the speed of PR merging.

An alternative is the one advocated by https://github.com/graydon/bors and supported by @aspiwack: instead of merging, assignees ping the bot which does a batch of merges on a temporary branch, and only pushes to master if the batch of merges went through CI OK. This is ideal as it prevents semantic conflicts. However we are still far from a state where we could use this approach. Most notably, we should have a more reliable CI (no spurious failing tests). I'm mentioning this approach because I'm keeping it in the back of my mind for later.

What you propose is actually a lighter test. You propose to only require a new run if the CI files in the base branch are outdated. This sounds like a pretty reasonable approach to me. I don't think an action from the bot is required here though: I think the merge script could include this check instead. I may have a look at this in a few days, unless someone self-assigns before me.

**Comment by ejgallego** [comment]
Sounds good @Zimmi48 , I fully agree with your proposal but I also think we are not yet ready to implement it. @maximedenes said that we should have some significant machine power so that would really help to avoid CI problems.

**Comment by ejgallego** [comment]
The would actually help the maintainer to lose time as if the check is in the script you have: "merge -> fail check -> go to github -> tag -> wait for submitter -> retry". With the bot such occurrence should happen less often, tho it would be great to have both the bot and the merge-script test.

**Comment by Zimmi48** [comment]
Indeed, you are right it would save some cycles to have the bot do this.
