### ISSUE TITLE
Provide a way to show information about a notation

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7730]
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem

This is a feature request: It would be really useful to be able to print information about a notation; in particular the levels and other specifiers that were given when the notation was defined. Frequently, I want to define an operator that uses the same levels as some existing one (say, "same as `->`"). Then I have to grep my way through my dependencies and the standard library as, AFAIK, there is no way to have Coq tell me *where* a particular notation was introduced, let alone with which specifiers.

**Comment by anton-trunov** [comment]
[`Print Grammar constr`](https://coq.inria.fr/distrib/current/refman/user-extensions/syntax-extensions.html#coq:cmd.print-grammar-constr) + the `Locate` command might help.

**Comment by RalfJung** [comment]
`Locate` shows neither levels nor where the notation was defined.

`Print Grammar constr` shows something with `LEVEL` but I don't know how to reverse-engineer the thing you have to *write* at `Notation` from that.

Neither of them show the format specifier.

**Comment by anton-trunov** [comment]
@RalfJung You are right. I would also love to have this feature. I think those two commands are almost only tools we have as of now.

Also, this #4436 issue is related.

**Comment by herbelin** [comment]
Has someone plans to work on this?

**Comment by herbelin** [comment]
Any idea on the user interface to provide these informations:

For instance, generalize `About` so that it works not only with logical declarations but also with notations? One would be able to do `About "_ <= _ <= _"` or `About "x <= y <= z"` and it would tell to what it is bound, with which format, with which precedences, in which module it is defined. Then, in case a notation is bound exactly to a declaration, like e.g. `"+"`, one would give information both on the declaration and on the notation.

Avoid the confusion and add a new command `About Notation` giving these informations? But then, one may be surprised that `About "+"` and `About Notation "+"` do different things (respectively talking about `Nat.add` and talking about the properties of the notation `"+"`).

**Comment by ppedrot** [comment]
@herbelin What about `Print Notation "+"`? We already have several entry points for the `Print` vernacular, it looks natural to add this command under that syntax.

**Comment by anton-trunov** [comment]
It would be great if a solution to this issue also took into account `Tactic Notation`.

**Comment by Alizter** [comment]
The `Print Notation` command has been added.
