### ISSUE TITLE
Printing bug: Newline added in incorrect place

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7731]
#### Version

8.8.0

#### Description of the problem

Consider the following file:
```coq
From Coq Require Import Utf8.
Section test.
Context (atomic_update : forall {TX TY : Type} (Eo Em : nat) (α : TX -> Prop) (β Φ : TX -> TY -> Prop), Prop).
Context (val loc : Type) (mapsto : loc -> val -> Prop) (XX: nat).

Notation "'AU' '{{' ∀ x : Tx , α } } @ Eo , Em '{{' ∃ y : Ty , β , 'RET' Φ } }" :=
  (atomic_update Tx Ty Eo Em (fun x => α) (fun x y => β) (fun x y => Φ))
  (at level 20, Eo, Em, α, β, Φ at level 200, x, y at level 99, format
"'[   ' 'AU'  '{{'  ∀  x  :  Tx ,  α  } }  '/' @  Eo ,  Em  '/' '[   ' '{{'  ∃  y  :  Ty ,  β ,  '/' RET  Φ  } } ']' ']'").

Notation "l  ↦  v" := (mapsto l v) (at level 20).

Definition PRE (P : Prop) := P.
Definition ENT (P : list Prop) (Q : Prop) := Q.
Definition AND (P Q : Prop) := P /\ Q.

Notation "P ∗ Q" := (AND P Q) (at level 80, right associativity).
Notation "⊤" := XX.

Notation "Γ  '_' : P" := (cons (PRE P) Γ)
  (at level 1, P at level 200,
   left associativity, format "Γ '_'  :  '[' P ']' '//'", only printing).
Notation "" := nil (only printing).

Notation "Δ '--------------------------------------' ∗ Q" :=
  (ENT Δ Q)
  (at level 1, Q at level 200, left associativity,
  format "Δ '--------------------------------------' ∗ '//' Q '//'", only printing).


Lemma test (Φ : nat -> Prop) l x :
  ENT (cons (PRE( AU {{ ∀ xx : val, l ↦ xx ∗ l ↦ xx ∗ l ↦ xx }} @ ⊤, ⊤
            {{ ∃ yyyy : val, l ↦ yyyy ∗ l ↦ x ∗ l ↦ x ∗ l ↦ x ∗ l ↦ x ∗ l ↦ x,
               RET Φ 0 }})) nil)
  True.
Proof. 
Show.
Abort.
End test.
```
and run it using `coqc filename.v`. That shows the following output:
```
1 subgoal
  
  atomic_update : ∀ TX TY : Type, nat
                                  → nat
                                    → (TX → Prop)
                                      → (TX → TY → Prop)
                                        → (TX → TY → Prop) → Prop
  val : Type
  loc : Type
  mapsto : loc → val → Prop
  XX : nat
  Φ : nat → Prop
  l : loc
  x : val
  ============================
  _ : AU {{ ∀ xx : val, l ↦ xx ∗ l ↦ xx ∗ l ↦ xx }} @ 
         ⊤, ⊤
         {{ ∃ yyyy : val, l ↦ yyyy ∗ l ↦ x ∗ l ↦ x ∗ l ↦ x ∗ l ↦ x ∗ l ↦ x,
            RET Φ 0 }}
  --------------------------------------∗
  True
```
Notice how, in the line starting `_ : AU`, there is a linebreak after the `@` even though the format for that notation says to break *before* the `@`! So, I think there's a bug here, and I'd expect the linebreak to occur either before the `@` or after the second `⊤`.

Note that this example is extremely fragile. Changing `Γ  '_' : P` to remove the `Γ` (because we only have a singleton context here) makes the bug disappear. Using `0` instead of `⊤` makes the bug disappear. Also I was not able to reproduce this bug in a way that it shows in emacs, but only when using `Show.`. I suppose getting it in emacs is possible though, I just have not found the right term.

**Comment by herbelin** [comment]
Quick question without taking time to test myself: You said `Using 0 instead of ⊤ makes the bug disappear`. Do you mean that there is potential dependency on the number of bytes of the encoding of a unicode character?

In any case, note that Coq is basically delegating formatting to OCaml's `Format` library.

**Comment by RalfJung** [comment]
> Do you mean that there is potential dependency on the number of bytes of the encoding of a unicode character?

I had that theory. However, I just tried using `$` instead of `⊤` and the bug remains. So maybe it's not about unicode after all.

> In any case, note that Coq is basically delegating formatting to OCaml's Format library.

I see. I guess that would mean the bug should be forwarded upstream? Ideally by someone that actually knows that library?

**Comment by herbelin** [comment]
I opened an (issue](https://caml.inria.fr/mantis/view.php?id=7804) on OCaml's bug tracker to know if the behavior is expected.

Even if relatively minor and somehow occuring only in exceptional cases, I made a workaround at

The technical cause is the notation `Notation "⊤" := XX.` which inserts a box around `⊤` and this box is used as a break hint (which is strange since there are already break hints in the ongoing box).

A workaround on your side is to force the printing of `⊤` without a box, as in:

```coq
Notation "⊤" := XX (format "⊤").
```

**Comment by RalfJung** [comment]
@herbelin Thanks!

Is it documented anywhere that
```
Notation "⊤" := XX.
```
and
```
Notation "⊤" := XX (format "⊤").
```
are not equivalent? I assumed they would be. I had no idea boxes are inserted automatically in some cases.

**Comment by herbelin** [comment]
This is "documented" in the source code. Documenting it in the reference manual, and documenting the heuristics used to build a formatter, and documenting the possible errors, and possible warnings, and maintaining this documentation up-to-date is beyond my capacities (but I'm open to any hints on how to improve the way to document features).

**Comment by RalfJung** [comment]
I see, I wasn't aware there's a whole set of heuristics. Also the documentation *does* mention that heuristics happen, I just hadn't read that part carefully enough. Fair enough.

Would it make sense to extend the heuristics such that, if the notation is just a single symbol, no box is added?

**Comment by RalfJung** [comment]
I noticed the ocaml issue has been closed as "works as intended". However, from what I can tell, what has not come up in that discussion is that a newline has been added not just at a strange place, but also where no newline was even necessary -- removing the extra box didn't shift the newline elsewhere, it entirely got rid of the newline! There is enough space for everything on one line after all, so why should this extra newline even happen? That still seems like a bug to me, and unrelated to the discussion about whether it can break and the inner box or has to use the outer breaks.

**Comment by herbelin** [comment]
> removing the extra box didn't shift the newline elsewhere, it entirely got rid of the newline

Yes, I suspect this is the difference that the algorithm makes between `margin` and `max_indent`. The algorithm don't open a box beyond `max_indent` but the break preceding the `@` only looks at the `margin`.

Otherwise said, at `/` before `@`, the algorithm sees that `⊤, ⊤` fits, so it does not break. However, at the time of opening the box around `⊤`, it is beyond `max_indent`, so, it preventively breaks without checking if the contents of the box will actually induce a break (which would indeed violate the `max_indent` constraint if ever there were one).

So, yes, I now catch a glimpse of how the algorithm could somehow be improved. At the time of seeing a box, it could use the knowledge that there is a preceding `/` which decided not to break to ensure that the content of the box shall not introduce breaks and that the preventive break is overkill.

Thanks for noticing that.
