### ISSUE TITLE
No direct links to the variants of a tactic in the manual

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#7763]
#### Version

8.8.0

#### Description of the problem

There is no direct way to link to e.g. `rewrite term in clause` variant of the `rewrite` tactic.
I can link to [`rewrite term`](https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.rewrite) and to the error messages, but not to the variants. `rewrite` is just a concrete example, this issue is very frequent across the manual.

**Comment by anton-trunov** [comment]
CC @Zimmi48, @cpitclaudel

**Comment by Zimmi48** [comment]
Indeed, variants of tactics and commands do not have an index by default. In the case, where the name of the tactic and the command is the same, it's not a huge problem because you can always find your way to the main variant. We had indices one by one when we find them necessary (especially when the variant has a different name).

**Comment by anton-trunov** [comment]
I mean I'm fine with variants not present in the indexes. But I'd like to be able to send the direct permalink to some variant.

E.g. I can link to [this error](https://coq.inria.fr/refman/proof-engine/tactics.html#coq:exn.tactic-generated-a-subgoal-identical-to-the-original-goal-this-happens-if-term-does-not-occur-in-the-goal), but not to a `rewrite` variant.

**Comment by Zimmi48** [comment]
The two are not separate. I suggest you open PRs to add indices that you are missing. We can also discuss the general question of having systematic indices for variants here.

**Comment by anton-trunov** [comment]
>The two are not separate.

I didn't know that. I think adding all the variants would just bloat the indexes. Is there an easy way to separate them? Can we maybe treat the variants as subsub...sections? (just a wild guess)

**Comment by cpitclaudel** [comment]
I used to auto-generate names, but I removed that upon request from Maxime.
I want to add an "index" property separate from the "name". The name would be the anchor that appears in HTML links, and the index the index entry.  index would by default be derived from name, but could be mentioned separately. And you could add `no-index` if you want a name but no index entry.

**Comment by Zimmi48** [comment]
This issue is becoming less relevant because we are removing all uses of `tacv` in the reference manual (because `tacn` are the ones that are checked by the `doc_grammar` tool). We do use indented `tacn` to highlight some variants (not syntax variants, because these are being merged into a single piece, but other names for the tactic). We could go back to using `tacv`, but then we would definitely need to introduce the name auto-generation mechanism.

cc @jfehrle

**Comment by jfehrle** [comment]
I have been systematically condensing tacvs and cmdvs into tacns and cmds to make it easy for readers to learn all their features without having to read lots of repetitive text.

While it may be helpful to have more hyperlinking points (eg to examples), also keep in mind that the doc has been evolving and needs considerably more work over the coming years. Links we add now may not be very permanent.

Perhaps @anton-trunov could say more about the use cases for such links, perhaps in a new PR with a new description.

**Comment by Zimmi48** [comment]
Closing as this is becoming less relevant (as explained above).
