### ISSUE TITLE
Injectivity patterns don't work with destruct

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7885]
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem
```coq
Lemma ex_rewrite (a b : nat) : (S a = S b) -> a = b.
Proof.
(* This works: *) intros [= ->]. Undo.
(* But this does not: *) intros H. destruct H as [= ->].
```
shows error
```
Error:
Syntax error: [or_and_intropattern_loc] expected after 'as' (in [as_or_and_ipat]).
```
The same pattern should work on the same term in both cases.

**Comment by gares** [comment]
I think the syntax is `as [  [= ->]  ]`.

In ssr `move=> pats` and `case ... => pats` would run the same parsing entry, but here it is not the case.

**Comment by gares** [comment]
> 8.8.8

;-)

**Comment by RalfJung** [comment]
That works, but how does it make any sense? For other patterns, we have
```
Lemma test (a b : nat) : (True /\ False) -> a = b.
Proof.
(* This works: *) intros [A B]. Undo.
(* And this works: *) intros H. destruct H as [A B]. 
```

**Comment by RalfJung** [comment]
Actually @gares that syntax parses but it doesn't work: There is a warning "Warning: Unused introduction pattern: [=->] [unused-intro-pattern,tactics]", and the effect is to just throw away the assumption.

**Comment by gares** [comment]
> how does it make any sense?

Hum, it does not. I guess I'll continue to live happily with `=>`.

**Comment by gares** [comment]
Assigning to @herbelin since I think he is the last one that touched `[= ...]`, but I've no clue if the bug comes from there.

**Comment by RalfJung** [comment]
I see. However, changing this would be (mostly) backwards compatible, right? As in, making the `destruct` action depend on the pattern and only performing the "inductive destruct" when the pattern is `[ID...]`, not when it is `->` or `[= ID...]`. The two latter are meaningless currently, and while they are not errors they are also not useful so changing their behavior shouldn't break many things?

**Comment by herbelin** [comment]
Yes, it would be backwards compatible, as far as I can judge. But that would be maybe difficult to a explain that when you don't provide an `as` clause, it defaults to case analysis or tuple destruction. I think this was the motivation for a `on do` where the pattern would be mandatory in the syntax.

Conversely, to comply with the (too general?) meaning of the word `destruct`, maybe we could indeed generalize it as you say. Would be curious about spontaneous opinions about that.

**Comment by anton-trunov** [comment]
>Would be curious about spontaneous opinions about that.

Hi @herbelin, I personally think that Ralf's suggestion that `destruct H as X` should be equivalent to `revert H; intros X` makes perfect sense. I'd love to see this change in Coq.

**Comment by RalfJung** [comment]
> But that would be maybe difficult to a explain that when you don't provide an as clause, it defaults to case analysis or tuple destruction.

That's a matter of the default destruct pattern. From what I can tell, the default behaves exactly like `destruct ... as []`.

**Comment by gares** [comment]
What would then be hard to explain is why `destruct H` does something in the first place (the destruction is not because of the `as` pattern, it is because of `destruct` and the `as` clause is just for naming...)

@anton-trunov @RalfJung I'm kind of amused that you want tactics to adhere to a stack model, but it is not how tactics (but for the ones provided by ssr) were designed in the first place, I'm afraid. Hence retrofitting that semantics may not be easy/possible.

**Comment by RalfJung** [comment]
No, I don't have a stack model in mind here at all. I want tactics to behave the same when similar syntax is used in a similar way -- e.g., intro patterns should do the same no matter where they are used.

For example, the Iris proof mode doesn't use a stack model at all (and it's not clear how to make it adhere to one), and still we have that the patterns for `iIntros` and `iDestruct` mean the same thing. An, in fact, why would one ever want to have *two* kinds of patterns, one used for `intros` and one for `destruct`?

**Comment by RalfJung** [comment]
IOW, I can also say that I expect `intros pat` is equivalent to `let tmp := fresh in intro tmp; destruct tmp as pat`. In fact that's how `iIntros` is implemented.

Am 22. Juni 2018 10:03:44 MESZ schrieb Enrico <notifications@github.com>:

**Comment by herbelin** [comment]
Moving the semantics of `destruct` from the current Coq semantics towards the more general Iris semantics is tempting. We would however lose an explicit tactic name to reflect the concept of "case analysis" and "tuple destruction" if `destruct` stops to carry these concepts.

I mean that the current story is that we have a correspondence between destruction tactic names and destruction patterns (`rewrite` and `->`/`<-`, `injection` and `[=...]`, `apply in` and `%`/`/`). What should be bound to `[...]` and `(...)` if `destruct` is not any more the tactic name attached to those?

The natural candidate for case analysis is of course `case`. However `case` is already used in another meaning. A solution would be to rename the  current `case` to `case:`, thus releasing `case` for the current `destruct`, additionally highlighting the similarity of current `case` and ssreflect `case:`.

Somehow, `case` is however too specific: a tuple destruction is not a case analysis. Then, a possible approach would be to extend the scope of the name `split` so that it is usable both for introduction and elimination. Moreover, by doing so, #410 would come more naturally in the story. And we would have a nice correspondence between `case` and `[...]`, and between `split` and `(...)`. To meditate.

**Comment by Zimmi48** [comment]
Duplicated by #13205.
