### ISSUE TITLE
Type inference/unification unable to propagate information on dependent types

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#7910]
#### Version

8.8.0

#### Operating system
Linux

#### Description of the problem

Consider the following example:
```coq
From Coq Require Import Utf8.
Set Default Proof Using "Type".

Local Set Universe Polymorphism.

(** Telescopes *)
Inductive tele : Type :=
  | TeleO : tele
  | TeleS {X} (binder : X → tele) : tele.

Arguments TeleS {_} _.

(** The telescope version of Coq's function type *)
Fixpoint tele_fun (TT : tele) (T : Type) : Type :=
  match TT with
  | TeleO => T
  | TeleS b => ∀ x, tele_fun (b x) T
  end.

Notation "TT -t> A" :=
  (tele_fun TT A) (at level 99, A at level 200, right associativity).

(** An eliminator for elements of [tele_fun].
    We use a [fix] because, for some reason, that makes stuff print nicer
    in the proofs in iris:bi/lib/telescopes.v *)
Definition tele_fold {X Y} {TT : tele} (step : ∀ {A : Type}, (A → Y) → Y) (base : X → Y)
  : (TT -t> X) → Y :=
  (fix rec {TT} : (TT -t> X) → Y :=
     match TT as TT return (TT -t> X) → Y with
     | TeleO => λ x : X, base x
     | TeleS b => λ f, step (λ x, rec (f x))
     end) TT.
Arguments tele_fold {_ _ !_} _ _ _ /.

(** A sigma-like type for an "element" of a telescope, i.e. the data it
  takes to get a [T] from a [TT -t> T]. *)
Inductive tele_arg : tele → Type :=
| TargO : tele_arg TeleO
(* the [x] is the only relevant data here *)
| TargS {X} {binder} (x : X) : tele_arg (binder x) → tele_arg (TeleS binder).

Definition tele_app {TT : tele} {T} (f : TT -t> T) : tele_arg TT → T :=
  λ a, (fix rec {TT} (a : tele_arg TT) : (TT -t> T) → T :=
     match a in tele_arg TT return (TT -t> T) → T with
     | TargO => λ t : T, t
     | TargS x a => λ f, rec a (f x)
     end) TT a f.
Arguments tele_app {!_ _} _ !_ /.

Coercion tele_arg : tele >-> Sortclass.
Coercion tele_app : tele_fun >-> Funclass.

(** Operate below [tele_fun]s with argument telescope [TT]. *)
Fixpoint tele_bind {U} {TT : tele} : (TT → U) → TT -t> U :=
  match TT as TT return (TT → U) → TT -t> U with
  | TeleO => λ F, F TargO
  | @TeleS X b => λ (F : TeleS b → U) (x : X), (* b x -t> U *)
                  tele_bind (λ a, F (TargS x a))
  end.
Arguments tele_bind {_ !_} _ /.

(** Telescopic quantifiers *)
Definition tforall {TT : tele} (Ψ : TT → Prop) : Prop :=
  tele_fold (λ (T : Type) (b : T → Prop), ∀ x : T, b x) (λ x, x) (tele_bind Ψ).
Arguments tforall {!_} _ /.
Definition texist {TT : tele} (Ψ : TT → Prop) : Prop :=
  tele_fold ex (λ x, x) (tele_bind Ψ).
Arguments texist {!_} _ /.

Notation "'∀..' x .. y , P" := (tforall (λ x, .. (tforall (λ y, P)) .. ))
  (at level 200, x binder, y binder, right associativity,
  format "∀..  x  ..  y ,  P").
Notation "'∃..' x .. y , P" := (texist (λ x, .. (texist (λ y, P)) .. ))
  (at level 200, x binder, y binder, right associativity,
  format "∃..  x  ..  y ,  P").

(** The actual test case *)
Definition test {TT : tele} (t : TT → Prop) : Prop :=
  ∀.. x, t x ∧ t x.

Notation "'[TEST' x .. z , P ']'" :=
  (test (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))
        (tele_app (λ x, .. (λ z, P) ..)))
  (x binder, z binder).
Notation "'[TEST2' x .. z , P ']'" :=
  (test (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))
        (tele_app (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))
                  (λ x, .. (λ z, P) ..)))
  (x binder, z binder).

Fail Check [TEST (x y : nat), x = y].
(* The type of this term is a product while it is expected to be "?TT -t> ?T". *)

Check [TEST2 (x y : nat), x = y].
```
I'd expect `Check [TEST (x y : nat), x = y]` to succeed because I am explicitly giving the implicit argument to `test`, so if unification had a look at the types of `test` and `tele_app`, it'd realize that the telescope in `tele_app` has to be the same as in `test`.

The `TEST2` notation shows how we can work-around that, but that work-around has its problems: When using this notation for printing, it requires the types in both telescopes to be *syntactically* equal, which sometimes is not the case when e.g. coercions come into play. So to properly work around this, we would have to duplicate the notation and add another "only printing" variant that doesn't require the telescope to be the same. Unfortunately, in my actual use-case, that would amount to duplicating >100 lines of notation declarations.

May be related to https://github.com/coq/coq/issues/7597.

**Comment by maximedenes** [comment]
This seems to me like a lack of bidirectionality: the expected type for the `tele_app` application is not used to type its arguments.

@gares has a nice plan to address this: make it possible to annotate definitions (à la `Arguments`) to say "once you've collected all the arguments before the mark, typecheck the application against its expected type, and use that information to typecheck the remaining arguments".

I'll try to implement a prototype.

**Comment by RalfJung** [comment]
> This seems to me like a lack of bidirectionality: the expected type for the tele_app application is not used to type its arguments.

This shouldn't be needed... even just inspecting the first argument(s) for `tele_app` would inform typechecking the rest of them.

**Comment by maximedenes** [comment]
I may be a bit lost, but that in the `TEST1` case, precisely, the arguments are not enough. How would Coq now that `(λ x, .. (λ z, P) ..))` has indeed type `tele_fun ? ?` ?

**Comment by maximedenes** [comment]
I thought it was meant to infer the implicit argument of `tele_app` from the *expected* type of the application `tele_app (λ x, .. (λ z, P) ..))`, no?

**Comment by maximedenes** [comment]
@RalfJung ping

**Comment by RalfJung** [comment]
I am giving `(TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))` to `test`. So all it has to do is consider `test (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))` and simplify its type before type-checking `test`'s second argument.

Or maybe this is a case of bidirectionality? I know nothing about how one actually implements type checking.^^

**Comment by maximedenes** [comment]
But are you sure the problem comes from typing the application of `test`? I thought it came from typing the application of `tele_app`.

> I am giving `(TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))` to `test`. So all it has to do is consider `test (TT:=(TeleS (fun x => .. (TeleS (fun z => TeleO)) ..)))` and simplify its type before type-checking `test`'s second argument.

Ok, but it also needs to make use of the computed expected type for this second argument when typing the application of `tele_app`, right?

What I mean by bidirectionality is that in order to typecheck the application of `tele_app`, Coq has to guess the telescope. In order to guess the telescope, it has to take information from the context (the expected type it has computed for the second argument of `test`).

Today the typing of an application only uses the types of the head and the arguments (respectively `f` and `x1`...`xn` in `f x1 ... xn`. In order to solve this problem, we need Coq to also use typing information from the context. Do you agree with that?

**Comment by RalfJung** [comment]
> Ok, but it also needs to make use of the computed expected type for this second argument when typing the application of tele_app, right?

Hm, I guess so?

I am not very knowledgeable with type checking algorithm. Maybe a way to do this without context information would be to see that the only way for `tele_app (fun x => t)` to type-check is for `tele_app`'s first argument to be such that this expects a function type? Not sure if that is easier or harder than propagating in the telescope we gave explicitly elsewhere.

**Comment by maximedenes** [comment]
> the only way for `tele_app (fun x => t)` to type-check is for `tele_app`'s first argument to be such that this expects a function type

This problem does not have a unique solution (essentially, you're asking unification to guess a positive number, together with some binder names).

However, this should be fairly easy to do with canonical structures (or unification hints). So I'm wondering now what your real need is.

If it is to propagate the information that you gave by hand from the outer term to its subterm, I can try to implement the plan described above.

If it is to have Coq build the telescope itself, you can already use canonical structures for that.

**Comment by RalfJung** [comment]
> If it is to propagate the information that you gave by hand from the outer term to its subterm, I can try to implement the plan described above.

I think this is what would help us most.

> If it is to have Coq build the telescope itself, you can already use canonical structures for that.

That might however also be a nice example to put into some canonical structure tutorial/documentation; I do not have the slightest idea how one would use canonical structures to do this.^^

**Comment by gares** [comment]
> That might however also be a nice example to put into some canonical structure tutorial/documentation; I do not have the slightest idea how one would use canonical structures to do this

It is quite involved, mostly because CS cannot be overlapping *and* because they must be records/projections, that is not very intuitive in this case. We do use that technique in MathComp for reifying direct sum expressions, but I would not recommend it.

The idea can be grasped by looking at the https://www.cs.unibo.it/~sacerdot/PAPERS/tphol09.pdf
section 4, and by thinking at CS as a restricted case of unification hints. The technique to encode overlapping/order using CS is explained in https://people.mpi-sws.org/~beta/lessadhoc/ section "Tagging".

A simple example is here http://www-sop.inria.fr/members/Yves.Bertot/proofs/canonical_reification.v but, being simple, does not need/use overlapping.

**Comment by Janno** [comment]
Using CS/TC will not really help here. While it is possible to make it work, it still requires *at least* wrappers around every function like `tele_app` to insert projections in the right places and, even worse, it might still require an extra batch of printing only notation to make everything look homogeneous. 

Furthermore, using CS will be particularly hard because `∀ x y, T` sometimes corresponds to `🔭 x y, T` and other times to `🔭 x, ∀ y, T`. And to even get to that problem one needs to figure out how to key on `∀` in the first place.

We use a combined CS and TC with `Hint extern` approach in Mtac2 for basically the same problem. The code is now somewhat outdated and some restrictions that lead to its complexity seem to no longer apply. Still, I spent so much time getting to work that I do not recommend anyone to recreate this experiment. 

Allowing users to change the typechecker's behavior seems like a much more sane approach. 

P.S.: In fact, if Coq were to have a marker (as mentioned above) that stands for "check until here and then proceed with extra knowledge" then maybe this could be implemented by calling out to a tactic that has to return the expected type of the remaining application. That would be very flexible and super nice for Mtac. But I don't want to hijack this discussion too much.

**Comment by gares** [comment]
> Allowing users to change the typechecker's behavior seems like a much more sane approach.

I could not agree more

**Comment by maximedenes** [comment]
> If it is to propagate the information that you gave by hand from the outer term to its subterm, I can try to implement the plan described above.

I have a working prototype, it works well on your example. I'll try to submit ASAP.

**Comment by maximedenes** [comment]
@RalfJung with #10049, your example succeeds by simply changing the `Arguments` annotations for `tele_app` to: `Arguments tele_app {!_ _} | _ !_ /`.

**Comment by RalfJung** [comment]
That's pretty cool, thanks!
