### ISSUE TITLE
nested notations fail to print, and fail to correctly bind scopes

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8126]
#### Version

8.8.1

#### Description of the problem

This code mis-behaves:
```coq
Inductive foo := tt.
Bind Scope foo_scope with foo.
Delimit Scope foo_scope with foo.
Notation "'HI'" := tt : foo_scope.
Definition myfoo (x : nat) (y : nat) (z : foo) := y.
Notation myfoo0 := (@myfoo 0).
Notation myfoo01 := (@myfoo0 1).
Check myfoo 0 1 HI. (* prints [myfoo0 1 HI], but should print [myfoo01 HI]  *)
Check myfoo0 1 HI. (* prints [myfoo0 1 HI], but should print [myfoo01 HI]  *)
Check myfoo01 tt. (* prints [myfoo0 1 HI], but should print [myfoo01 HI]  *)
Check myfoo01 HI. (* Should not fail, but fails with Error: Unknown interpretation for notation "HI". *)
```

cc @herbelin

**Comment by herbelin** [comment]
Fixed in #8133.

For the record, note that there is a special treatment of toplevel `@` in notations. Assume that `f` has implicit arguments `x`, `y` and an other argument `z`. If I do `Notation g := @f`, then `g t` shall be interpreted as `(@f) t` (*), i.e. with the implicit arguments `x` of `f` deactivated. If I do `Notation g := (@f t)`, then `g u` shall be interpreted instead as `f (x:=t) u` (**) with `u` taking the place of `z`, not as `(@f t) u` where `u` would have taken the place of `y`. The empirical reason for (*) is that this allows notations hiding the need for a `@`. The empirical reason for (**) is that this allows to have notations providing part of the implicit arguments and keep taking into account the other implicit arguments and scopes of `f`.
