### ISSUE TITLE
anomalies with elim

### ISSUE THREAD

**Issue by Gopiandcode** [coq/coq#8134]
#### Version

```
The Coq Proof Assistant, version 8.8.0 (July 2018)
compiled on Jul 18 2018 11:50:33 with OCaml 4.05.0
```

#### Operating system
Ubuntu 18.04 LTS

#### Description of the problem

```
From mathcomp.ssreflect
Require Import ssreflect ssrbool ssrnat eqtype.


Lemma example (m : nat) : forall n, n == 0.
Proof.
    elim Hm: m => [n | m'].
(* Anomaly "File "plugins/ssr/ssripats.ml", line 369, characters 15-21: Assertion failed." Please report at http://coq.inria.fr/bugs/. *)

```

**Comment by anton-trunov** [comment]
A bit smaller test:

```coq
From mathcomp Require Import ssreflect.

Lemma example (m : nat) : nat -> True.
Proof. elim Hm: m => [? | ].
```

If I leave out `Hm` (or `?`, of course), then the anomaly goes away. Also, quantification in the goal is essential as well: replacing `nat -> True` with `True` makes the anomaly disappear too.

**Comment by gares** [comment]
Thanks for reporting and minimizing the bug!

**Comment by gares** [comment]
The problem is that when elim or case are used in conjunction with the equation generation feature, as in `elim E : t => [stuff]` then `stuff` can only introduce *less* items than the ones coming from the constructors (because the equation is generated just after then `[]` block.

Note that one ca write `elim: m => [|m'] n` to introduce `n` on both branches.
