### ISSUE TITLE
Policy on squashing commits before merging PR

### ISSUE THREAD

**Issue by herbelin** [coq/coq#8197]
Hi, do we want to have a policy or recommendation on the internal organization of commits within a PR? Incidentally, do we consider it to be the task of the person who proposed the PR to do some squashing or do we consider that it might also be the case of the person who merges?

I have a concrete case: #8151. It is common, when we address questions from reviewers/commenters to add new commits to the PR. This seems to be a good practice in that it allows to reflect the history of the discussion in the commits. However at merging time, it seems to be a source of complication for the future to have commits internal to a PR which amend part of what previous commits of the PR have done.

Often, one asks persons who did the PR to eventually squash just before merging, but this has the drawback of adding a new level of interaction, new delays, new context switches on both the side of the proposing person and the side of the merging person.

Shall we consider for instance to be good practice that the merging person does some trivial squashing him/herself?

Note: In the meantime, I pushed #8151 as it was.

**Comment by Zimmi48** [comment]
In the concrete case you mention, I think it is OK to have merged as-is because these amending commits are quite clear and limited but we want typically to avoid PRs containing large commits that are undone in subsequent commits.

The traditional method to deal with this is to squash the whole PR in a single commit at merge time. In Coq, we are not using this method, and indeed we generally prefer that large PRs are divided in smaller commits when they make sense individually. So it seems good practice when contributors push amending commits to take reviewer comments into account then squash when the PR is ready. We could even encourage contributors to use the standard commit message format "fixup! Message of my commit to fixup" so that the last step can be performed automatically with a `git rebase master -i --autosquash`.

When squashing is needed, I tend to prefer that the author do it, to have the committer be the author, but if they are not responding or are unable to perform it, I can also take care of it as the assignee of the PR (if the author let me push to their branch, which is the case most of the time since this is an opt-out option on GitHub).

There should probably be info on this question in `CONTRIBUTING.md` and `MERGING.md`.

**Comment by maximedenes** [comment]
Closing since this has been answered. Feel free to reopen if more feedback is needed.
