### ISSUE TITLE
Documentation for setoid_replace has the order of arguments wrong

### ISSUE THREAD

**Issue by siddharthist** [coq/coq#8213]
#### Version
8.8

#### Operating system
n/a

#### Description of the problem
The documentation has the following:
```
setoid_replace term with term [in ident] [using relation term] [by tactic]
```
resulting in keyword order `with, in, using, by`, whereas [the implementation] is as follows:
```coq
Tactic Notation "setoid_replace" constr(x) "with" constr(y)
  "using" "relation" constr(rel)
  "in" hyp(id)
  "by" tactic3(t) :=
  setoidreplacein (rel x y) id ltac:(t).
```
resulting in keyword order `with, using, in, by`. Looks like the fix is to make the switch [here](https://github.com/coq/coq/blob/15331729aaab16678c2f7e29dd391f72df53d76e/doc/refman/Setoid.tex#L541-L545):
```latex
\tacindex{setoid\_replace}
\texttt{setoid\_replace} \textit{term} \texttt{with} \textit{term}
~\zeroone{\texttt{in} \textit{ident}}
~\zeroone{\texttt{using relation} \textit{term}}
~\zeroone{\texttt{by} \textit{tactic}}
```
cc @mattam82

**Comment by Zimmi48** [comment]
I don't know where you found this version of the code of the manual but it's pretty outdated. Here is the actual line that needs changing:
https://github.com/coq/coq/blame/master/doc/sphinx/addendum/generalized-rewriting.rst#L547
(I'm using the blame version because GitHub refuses to show me the code source otherwise).
Would you be willing to submit a PR?

**Comment by siddharthist** [comment]
Ah, I must have followed an old link. Sure, I can fix it.
