### ISSUE TITLE
Grammar for SSReflect style Inductive types

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#8223]
#### Version

Coq 8.8.1

#### Operating system

macOS 10.13.6

#### Description of the problem

I failed to find the grammar for SSReflect style `Inductive` definitions in the reference manual. An example of such a definition can be found [here][1]:

```coq
Inductive list (A : Type) : Type := nil | cons of A & list A.
```

[1]: https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#anonymous-arguments

**Comment by gares** [comment]
@amahboubi do you recall if the documentation of that syntax was in the latex user manual and was lost during the migration to sphinx?

**Comment by gares** [comment]
JFTR, such notation is available everywhere, you can even write
```coq
Lemma foo of False & True.
```

**Comment by anton-trunov** [comment]
> FTR, such notation is available everywhere

Oh, I didn't know that, thank you! But you probably meant something like this?
```coq
Lemma foo of False & True : False.
```

Otherwise I get:
> Error: Syntax error: ':' expected after [constr:binders] (in [vernac:gallina]).

**Comment by herbelin** [comment]
BTW, what is the general feeling about this notation? It is a bit a trick to provide `of t` as a strict abbreviation for `(_:t)` but the OCaml-reminiscent syntax `Inductive list (A : Type) : Type := nil | cons of A & list A.` is somehow cool.

Currently, it is a hack, since e.g. you can also write `Inductive list (A : Type) : Type := nil | cons & A of list A.` which is difficult to justify, but I guess we could agree on a clean improvement of it.

@mattam82, @ppedrot, @anton-trunov, @gares, ... what do you think?

**Comment by anton-trunov** [comment]
@herbelin Having a uniform syntax would be great, indeed!

**Comment by Zimmi48** [comment]
Honestly, I can't see the gain of this syntax over
```
Inductive list (A : Type) : Type := nil | cons (_ : A) (_ : list A).
```

Trying to reproduce OCaml syntax seems generally like a bad idea to me because the choices made for the syntax of OCaml are often pretty bad (and in particular in the case of the definitions of constructors of ADTs).

However, I also think that it's bad that the SSR plugin is more than just about tactics, so if people like this syntax and care about it, I wouldn't mind having it moved (with a cleaner implementation) outside of the plugin and made generally available.

**Comment by amahboubi** [comment]
HI @gares, in the first message of this issue, @anton-trunov cites the documentation paragraph in the sphinx version, which obtained from the latex one. Nothing was lost. Note that the paragraph does not say that the syntax is restricted to Inductive, but since there is a single example, I agree it might be confusing.

**Comment by gares** [comment]
Ok, i probably misread anton's request. i guess we should only add a box where the term non terminal is extended using of and & in order to solve this issue.

**Comment by anton-trunov** [comment]
@gares Yes, I was referring to a formal grammar like this one: https://coq.inria.fr/distrib/current/refman/language/gallina-specification-language.html#coq:cmd.inductive

**Comment by amahboubi** [comment]
Sorry, I do not see what should go in this box. As the syntax is available everywhere, it cannot be strictly a formal grammar like the one @anton-trunov is citing. As the syntax is (currently) only available once the plugin is loaded, it cannot appear as early as in the [syntax of terms](https://coq.inria.fr/distrib/current/refman/language/gallina-specification-language.html#terms). @gares, @anton-trunov  do you mean adding a line in the paragraph like: " `binder ::= binder | & term | of term` ? If so I can submit a PR rephrasing the 1st paragraph along this line.

**Comment by Zimmi48** [comment]
@amahboubi You have support in coq-sphinx for grammar extensions (see `prodn` in https://github.com/coq/coq/tree/master/doc/sphinx#objects). This is already quite used in the SSR chapter BTW.

**Comment by anton-trunov** [comment]
> This is already quite used in the SSR chapter BTW.

For instance here: https://coq.inria.fr/distrib/current/refman/proof-engine/ssreflect-proof-language.html#pattern-assignment

**Comment by amahboubi** [comment]
Many thanks! However, my question was more about the expected content than about the technique. Since you answered both, I will do that.

**Comment by amahboubi** [comment]
I am working on top of commit https://github.com/coq/coq/commit/bf1446294dba45d3ea9b7bb39d2fc96617848c03, and I do not manage to `make sphinx SPINXWARNERROR=0`. I get the error message:
Running Sphinx v1.3.6

Extension error:
Could not import extension sphinxcontrib.bibtex (exception: No module named 'sphinxcontrib')

Any suggestion? where should I ask for help?

**Comment by anton-trunov** [comment]
@amahboubi I had the same problem a while ago, and if I recall correctly
```
pip3 install sphinxcontrib-bibtex
```

helped. You can checked the list of dependencies here: https://github.com/coq/coq/tree/master/doc#dependencies.

**Comment by amahboubi** [comment]
Many thanks @anton-trunov, as I had worked on the porting, I thought I was up to date. I checked my list of dependencies. I have all the packages listed [here](https://github.com/coq/coq/tree/master/doc#dependencies), but
`sudo apt-get install python3-sphinxcontrib.bibtex` raises an error, saying that it was unable to find the package. The `pip3 install` version fails as well, with the message:
`PermissionError: [Errno 13] Permission non accordée: '/usr/local/lib/python3.5/dist-packages/oset-0.1.3.dist-info'
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

Thus I did install `pyton-pip`, and ran the suggested upgrade command. But strangely, this command also emit the warning:
`Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

My OS is Ubuntu 16.04 but the dependecies do not mention a version of pip explicitly as far as I can see?

Sorry, the time I could devote to this (more than that in fact) has elapsed...

**Comment by anton-trunov** [comment]
@amahboubi Sorry, I don't know, I'm a macOS user. Perhaps @Zimmi48 could help?

**Comment by gares** [comment]
I think you forgot sudo in the pip install.

**Comment by amahboubi** [comment]
Thanks @gares. I just tried `sudo   pip3 install sphinxcontrib-bibtex` which indeed seems to have succeded: it says `Successfully installed PyYAML-3.13 latexcodec-1.0.5 oset-0.1.3 pybtex-0.21 pybtex-docutils-0.2.1 sphinxcontrib-bibtex-0.4.0` but still complains about my version of `pip`. But `make sphinx` still fails with `Extension error:
Could not import extension coqrst.coqdomain (exception: No module named 'sphinx.util.logging')`.

**Comment by Zimmi48** [comment]
This could be that your version of sphinx is too old? If you installed it with `apt-get` maybe you should try to remove it and install it with `pip` instead? Maybe @cpitclaudel can help. I personally don't use `apt-get` nor `pip`. I use `nix-shell` and it pulls in all the requested dependencies.

**Comment by amahboubi** [comment]
Many thanks @Zimmi48, your suggestion worked. It would be useful to document the minimal requirements on the versions, if not all of them are supported.

**Comment by Zimmi48** [comment]
Indeed @amahboubi. Would you mind opening a bug report about this? In particular, doc/README should warn users of older Ubuntu / Debian distribs.

**Comment by amahboubi** [comment]
Sure, I just did here #8371. I am afraid I did not have time to investigate the problem and provide more informative feedback.

**Comment by cpitclaudel** [comment]
Btw @amahboubi, you can pass `--user` to pip to install a package locally (instead of system-wide).
The version warnings are a bit puzzling, but they are due to pip being able to update itself.  That's why when you install it from the distribution's repositories it emits a harmless complaint after most operations, to let you know that it could also update itself (to a version more recent than the latest one supplied by your distro).

**Comment by cpitclaudel** [comment]
The `import` issue you ran into could have been due to an incorrect recent change, too (I think we were originally hoping to not depend on anything too recent in Sphinx; it could be that I or someone else recently used a new feature without meaning to)

**Comment by amahboubi** [comment]
Thanks a lot for the comments @cpitclaudel, they are really helpful. And I did not know about the `--user` option.

**Comment by Zimmi48** [comment]
AFAIU this has been resolved.
