### ISSUE TITLE
The -noinit option and Ltac

### ISSUE THREAD

**Issue by Zeimer** [coq/coq#8271]
#### Version

The Coq Proof Assistant, version 8.8.1 (August 2018)
compiled on Aug 16 2018 22:07:07 with OCaml 4.05.0

#### Operating system

Ubuntu

#### Description of the problem

```
Ltac wut := idtac.
```
When running coqide/coqtop with the -noinit option, this gives me

"Error: Syntax error: illegal begin of vernac."

Without the option it works fine. This behavior was not present in 8.5/8.6 I believe. Is this intended?

**Comment by andres-erbsen** [comment]
I believe this is intended, aiming to make way for a future where Ltac2 is used instead of Ltac and Ltac is not even `Require`d. I have been able to access Ltac with -noinit by doing

~~~~~
Declare ML Module "ltac_plugin".
Local Set Default Proof Mode "Classic".
~~~~~

(from https://github.com/andres-erbsen/coq-experiments/blob/master/experiments/ltac1core.v)
