### ISSUE TITLE
Out of memory on reasonably sized proof.

### ISSUE THREAD

**Issue by Gbury** [coq/coq#8277]
#### Version

The Coq Proof Assistant, version 8.8.1 (August 2018)
compiled on Aug 4 2018 12:29:40 with OCaml 4.07.0

#### Operating system

Linux

#### Description of the problem

Coq raises an Out of Memory on my machine (about 8G of RAM) when checking a proof term of "reasonnable size", whereas an equivalent proof script type-checks in less than a second. Both file are available on [this gist](https://gist.github.com/Gbury/6d42a203e44d73be8cacc4f15e489593) (as term.v and script.v respectively).

For the context: this proof was automatically generated by a theorem prover, which generated both the script (`script.v` in the gist), and the proof term (`term.v` in the gist), in about 0.1s. The term in `term.v` should be relatively identical to the term built by the script. Note that essentially the same proof term was generated for the [dedukti logical framework](https://github.com/Deducteam/Dedukti) (modulo some encoding), which had no problem checking it instantly.

Maybe this is related to the structure of the generated proof (using a lot of let bindings). If so, I'm open to suggestions on how to produce better proofs.

Finally, this proof was generated from a series of problem of increasing size (from 1 to 100), and the example in the gist was produced using the the smallest size that Coq did not manage to verify on my machine (which is size 6). Thus, if needed, bigger (and smaller) instances of the same kind of proof can easily be generated (up to about size 50).

**Comment by ppedrot** [comment]
The difference between the two due to the use of tactics vs. terms, at least not directly. The problem actually stems from the fact that the term-based definition is transparent (i.e. as if you were using `Defined` in the script) and that triggers the VM compilation and evaluation of this term, leading to the blowup you observe. I guess that's a use case for the Opaque definition feature @Zimmi48 has been working on.

**Comment by Gbury** [comment]
Would it help if I uploaded a smaller proof with the same structure, but that also takes a long time to check (longer than one would expect) ?

**Comment by ppedrot** [comment]
I don't think I'll need it: the reason is quite obvious reading the code. The first optimization phase expands toplevel let-bindings where the argument is (amongst others) structured constants (i.e. closed recursive applications of constants and blocks) or functions. This can lead to a huge code blowup, as witnessed by your example that happens to fall squarely in this fragment.

@bgregoir, @silene, @maximedenes: is that a conscious design choice?

**Comment by silene** [comment]
I am not sure to follow. What is wrong with expanding toplevel let-bindings that are structured constants? Sure, there might be a bug in the implementation. But you seem to say that there is a more fundamental issue.

**Comment by ppedrot** [comment]
@silene I checked and indeed for structured constants, you're right, the compilation scheme is clever and allocates them globally as much as possible.

But for functions, this is completely wrong: it happily and systematically substitutes the body of let-bound functions, so it is easy to trigger an exponential blowup of clambda code size. That seems definitely wrong to me.

**Comment by silene** [comment]
I agree that it is wrong. I don't know what the rationale was. Here is a small example of exponential blowup, with bytecode growing as 3 * 2**n - 1:
```
Definition b :=
  let x y := y in
  let x y := (x y, x y) in
  ...
  let x y := (x y, x y) in
  x tt.
```
