### ISSUE TITLE
Coq should be built with compatibility-notation,deprecated set as an error

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#8381]
#### Version

8.9+alpha

#### Description of the problem

There are a number of test-suite files which use 8.6 compatibility notations (such as `sigS`), without using `-compat 8.6`.  I think this should not be the case.

**Comment by Zimmi48** [comment]
The standard library itself is built with all warnings as errors. As long as we consider that the expected behavior of compatibility aliases is only to generate a deprecation warning even without using the `-compat` option, it makes sense to test this in the test-suite (see also #6840).
A path to solve the inconsistency in #6840 and thus this issue as well would be to make the deprecated attribute (see https://gitlab.com/coq/coq/-/jobs/artifacts/master/file/_install_ci/share/doc/coq/sphinx/html/language/gallina-specification-language.html#attributes) work with Definitions / Notations as well. Then this use case would be handled by this other mechanism and we could change the semantics of compatibility aliases.

**Comment by Zimmi48** [comment]
@JasonGross This was fixed in #8634, correct?
