### ISSUE TITLE
Deprecate omega / romega

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8385]
If the deprecation is done in time for 8.9, it allows removing these two tactics from the codebase (#7878) right after the branching without any compatibility layer.

**Comment by maximedenes** [comment]
What would be the story for `Require Coq.omega.Omega`?

**Comment by Zimmi48** [comment]
Right, can you remind me the issues at stake? What's in there other than the `omega` tactic?
IIRC we don't yet have a way of deprecating a module, and it might not be easy to implement.

**Comment by ejgallego** [comment]
Deprecating a module is not too hard, a flag that is checked a require time should do the job; the main issue we had is what would be the syntax for enabling it. I do still think that we want to go the way OCaml attributes are, not the way we have proposed now.

**Comment by samuelgruetter** [comment]
Regarding deprecation, I see two features we'd want:
1)    Mark a whole file as deprecated, and emit a warning when the file is `Require`d.
2)    Mark any definition, lemma, inductive, module, Ltac, etc as deprecated, and emit a warning when a reference to it is resolved.

Am I correct in assuming that you're a only trying to solve 1) here?

I used to think that 1) and 2) should be implemented together, as one feature, but while trying to think how, I noticed that they're quite different:
*    They emit warnings at different moments
*    Inside a Coq file, there's not yet a way to refer to "the current file", whereas each definition made inside a file can be referred to by its name

So I now think it's better to implement 1) and 2) as separate features (until someone convinces me otherwise, I guess :wink:).

Here's a simple way of implementing 1) which requires no new syntax: If I want to deprecate the file `MyFile.v`, I create an empty file called `MyFile.vo.deprecated` in the same directory (and commit it with git if I use git). Whenever Coq loads `MyFile.vo` through a `Require`, it checks if `MyFile.vo.deprecated` exists in the same directory, and if so, it emits a deprecation warning. And if `MyFile.vo.deprecated` contains some text (such as "use XY instead"), this text is included in the deprecation warning.

**Comment by ejgallego** [comment]
Deprecating a file only makes sense because we have this strange stuff which is effects at "Require time". Deprecation should only be triggered on use, so maybe a better path is to get rid completely of `Require`-time effects and then 1) is not a problem.

**Comment by Zimmi48** [comment]
There is one side-effect of `Require foo` that nobody will discuss: it is allowing you to access new objects through qualified `foo.bar`. Thus, it makes perfect sense to deprecate a file and send a warning at require time. It is btw what other languages such as Python (where most users only require and rarely import) do.

**Comment by maximedenes** [comment]
> There is one side-effect of Require foo that nobody will discuss

why not? we've discussed that many times already

**Comment by SkySkimmer** [comment]
Is python require transitive though?

**Comment by samuelgruetter** [comment]
> Deprecation should only be triggered on use, 

Why? What if a file does `Require Coq.omega.Omega`, but never uses `omega`? I'd still like to get a deprecation warning in that case.

**Comment by ejgallego** [comment]
> There is one side-effect of Require foo that nobody will discuss: it is allowing you to access new objects through qualified foo.bar.

I do deem this "side-effect" as redundant; scoping should be controlled by the right library options (such as `coqc -package streams`) and I shouldn't be forced to do a `Require foo` in order to access `foo.bar`.

p.s: I've heard terrible things about Python require.

**Comment by Zimmi48** [comment]
No, I was not defending the transitive behavior so maybe using the term "side-effect" was not really appropriate.

**Comment by Zimmi48** [comment]
So @ejgallego you are in fact defending a model closer to the one of OCaml. Yeah, indeed that would make sense as well but would be further away from the current model.

**Comment by ejgallego** [comment]
> Why? What if a file does Require Coq.omega.Omega, but never uses omega? I'd still like to get a deprecation warning in that case.

In the model we are discussing `Require Omega.` doesn't even exist anymore. You would do `Import {tactics, notations} From Omega`.

And indeed IMHO in that case you would not want to get a deprecation warning, but a "unused import warning" à la OCaml.

**Comment by samuelgruetter** [comment]
If you indeed want to have a *private* require-time deprecation mechanism, I think it would be best to enforce this by making it *impossible* to use for 3rd parties (otherwise you'll have to find a mechanism to deprecate the deprecation mechanism :rofl:). For instance, this could be achieved by extending the code which processes a `Require` with a test of the form `if filename in list_of_deprecated_files then emit_warning`, where `list_of_deprecated_files` is pretty much hard-coded, or loaded from a file in the Coq source tree.

**Comment by Zimmi48** [comment]
romega has been deprecated in 8.9 and removed in master. IIUC omega is going to be staying around for a while, although I recommend completing the work needed to remove it, so that it can be deprecated (e.g. in 8.10) and removed in the following version.
