### ISSUE TITLE
tar --exclude-vcs-ignores does not work, some 

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq/coq#8391]
If in the Windows build script makecoq_mingw.sh the --exclude-vcs-ignores tar option is used  (as discussed in PR #8243) to exclude build artifacts in the transfer of sources from a specified local director to the coq build directory, some to be installed files are missing:

```
coq-local-make-install.err: install: cannot stat 'tools/coqdoc/coqdoc.css': No such file or directory
coq-local-make-install.err: install: cannot stat 'tools/coqdoc/coqdoc.sty': No such file or directory
```

I would think this is an incompatibility in the interpretation of the `.gitignore` file between git and tar. Possibly this can be fixed by e.g. giving full paths in the `.gitignore` file or other means.

Fixing this would solve some issues in coq Windows development use cases brought up by @jfehrle.

**Comment by SkySkimmer** [comment]
>I would think this is an incompatibility in the interpretation of the .gitignore file between git and tar.

It is rather because those files are checked in git regardless of matching a gitignore pattern (they were added before gitignore).

Presumably the gitignore pattern could be made more precise to avoid this.
coqdoc.sty is ignored since 4d9cfa5472d05b17ddbd93b60c8c7deb0c796190 (@letouzey 2009)
coqdoc.css is ignored since 6aaf4e17812aeaed41a4a3f7d9170c9d95de8751 (@ejgallego 2018)
Not sure if these patterns are still relevant / what exactly they're meant to apply to.

**Comment by MSoegtropIMC** [comment]
@SkySkimmer : thanks for the root cause analysis!

I would think these files are ignored, because they are copied a few times during creation of documentation. So we want to .gitignore the copies but not the original files. If there are only a few copies, these could be explicitly excluded. Otherwise I guess one needs something to express "exclude all coqdoc.sty files except the original".

**Comment by MSoegtropIMC** [comment]
This is deprecated with Coq Platform.

**Comment by MSoegtropIMC** [comment]
The PR which removed the old build scripts and switched to Coq Platform was (#13598).
