### ISSUE TITLE
[make] coqpp circular dependency

### ISSUE THREAD

**Issue by gares** [coq/coq#8405]
```
make[1]: Circular coqpp/coqpp_parse.cmi <- coqpp/coqpp_parse.cmo dependency dropped.
```
This on a fresh checkout of master + configure + make states.
I guess this is on pmp

**Comment by SkySkimmer** [comment]
I think this is because of `$(MLWITHOUTMLI:.ml=.cmi): %.cmi: %.cmo`
coqpp_parse is WITHOUTMLI so we have 
~~~
coqpp_parse.cmo: coqpp_ast.cmi coqpp_parse.cmi # exact rule in the makefile
coqpp_parse.cmi: coqpp_parse.cmo # from WITHOUTMLI
~~~
Since there is no coqpp_parse.mli the cmo does not depend on the cmi, so the exact rule should just have `coqpp_parse.cmo: coqpp_ast.cmi`.

**Comment by ppedrot** [comment]
Doesn't compile.

**Comment by SkySkimmer** [comment]
Oh I see ocamlyacc produces the mli, so the issue is that we don't put those generated mlis in MLIFILES.
I actually tested this time ^^
