### ISSUE TITLE
FR: line editing in interactive coqtop

### ISSUE THREAD

**Issue by nlewycky** [coq/coq#8480]
Feature request: Please add support for readline-style line editing to coqtop.
* ← and → to move the cursor around in the line, delete and backspace remove characters at the cursor, other keys insert at that character
* home and end to go to the beginning of the line and the end of the line
* emacs keys ^A and ^E equivalent to home and end
* ^Q to insert the next character literally even if it has another meaning (such as ^A or ^Q itself)
* ^T to "twiddle", swap the character under cursor with previous character and advance the cursor. No effect when cursor is on the first character. Affects last two characters when cursor is one past the end and does not advance cursor.
* ^←and ^→ to advance to the beginning of the next word, or one past the end of the previous word
* ^K to cut from cursor to the end of the line and put it in a copy-paste buffer, ^Y to paste
* ^W to cut from cursor back to beginning of current/previous word (going left, cut whitespace followed by non-whitespace), ^Y to paste
* ↑ and ↓ to navigate through the current and previously executed lines.

One way to do this is to depend on Lambda-Term, and that could be made an optional dependency. Another would be a platform-specific implementation based on the Unix module.

**Comment by anton-trunov** [comment]
There is a workaround for this issue: one can use [rlwrap](https://github.com/hanslub42/rlwrap) or [ledit](http://pauillac.inria.fr/~ddr/ledit/). The latter is available on OPAM:

```
$ opam info ledit
             package: ledit
             version: 2.03
          repository: default
        upstream-url: http://pauillac.inria.fr/~ddr/ledit/distrib/src/ledit-2.03.tgz
       upstream-kind: http
   upstream-checksum: 3a70ee7d5d5e2dfb905a1ac2e1e60276
             depends: camlp5
   installed-version:
   available-version: 2.03
         description: Line editor, a la rlwrap
One-line editor written in OCaml. It provides line editing for the
Caml toplevels, as well as other interactive Unix commands.
```

**Comment by ppedrot** [comment]
I think that indeed coqtop went the way of the OCaml toplevel, that is, not providing an expressive terminal and relying instead on external tools. Not sure if this is going to change anytime soon.

**Comment by nlewycky** [comment]
OK, this makes sense to me. Thanks for the links!

**Comment by ejgallego** [comment]
> OK, this makes sense to me. Thanks for the links!

Let me know if you would need help to port `utop` for example to Coq.

**Comment by herbelin** [comment]
> I believe many of us think that even CoqIDE shouldn't exist

Your formulation is a bit strange! CoqIDE is the daily tool of many of us and it has to "exist". And we should indeed (also) provide (or help provide) support for many (third-party) editors.

**Comment by Zimmi48** [comment]
Note that I said "many of us" not "all of us" ;-)

**Comment by ejgallego** [comment]
The truth is that if we had good integration with let's say, VSCode few of us would miss CoqIDE.

**Comment by herbelin** [comment]
I hope however that you don't mean that "many of us want CoqIDE not to exist". That would be a very negative attitude :worried:

**Comment by ejgallego** [comment]
> That would be a very negative attitude

Oh, I don't see it that way Hugo ( @herbelin ) , it is more like most of CoqIDE functionality is available in other editors, so in a sense it seems like a bit overkill to have to develop our own IDE, which is an extremely hard thing to do.

Also, custom IDEs tend to be disadvantageous for the user; imagine we had to use a different IDE for each different programming language, with their own keybindings, issues, configuration files, etc... that would be painful.

Indeed I think the tendency for Coq should be to phase CoqIDE away and focus on more powerful IDEs (emacs/VSCode) and new interaction systems [such as Jupyter / JsCoq].

By the way let me do a shameless plug and remind that at Mines / INRIA we have internships open for people willing to work on Jupyter / Web for Coq.

**Comment by ejgallego** [comment]
Oh sure, who's impeding work on CoqIDE? I don't have any negative view on CoqIDE itself, how did you infer that?

Reality says tho that there has been few changes to it in the last years, and due to architectural issues it may be very hard to implement modern fancy stuff. That, together with few of us willing to move from more established editors is why I think that the prevalent opinion in the team is to focus on other UI efforts.

**Comment by Zimmi48** [comment]
I'm sorry @herbelin I realize that I started this with a quite negative tone so let me explain again what I meant: If all these great editors and their large package ecosystems had existed at the time CoqIDE was developed, it wouldn't have been necessary to develop CoqIDE and time could have been spent more usefully on providing good support for modes in these various editors. But the context was not the same and now that we have CoqIDE, I am not saying that we should throw it away. However, we should seriously consider giving more priority to e.g. supporting vscode. For instance it would make things much less painful if the Windows package did not have to include CoqIDE; as for the macOS package, if we stopped packaging CoqIDE, we could even completely stop distributing a macOS package which would be a *huge* gain given that none of the people that are currently caring about the packages are actually mac users. So suppose good vscode support for Coq finally lands, I would be in favor of splitting CoqIDE to an external package, and since you say that there are volunteers willing to work on it, let these volunteers take care of the packaging as well and make it independent of the release process of Coq itself.

**Comment by ejgallego** [comment]
> I would be in favor of splitting CoqIDE to an external package,

Note that since #180 CoqIDE is already an external package that happens to be built with Coq.

**Comment by herbelin** [comment]
@Zimmi48 
> If all these great editors and their large package ecosystems had existed at the time CoqIDE was developed, it wouldn't have been necessary to develop CoqIDE and time could have been spent more usefully on providing good support for modes in these various editors.

At the time CoqIDE was created, there was no long term view. It was started shortly after lablgtk was released and, my perception from outside was that CoqIDE was before all an experiment for fun to exploit lablgtk. I believe it took only a few weeks for Benjamin Monate to make something already nice and then a synergy developed with contributions from Pierre L, Jean-Christophe F, ... in the sociologic context of showing that OCaml had something to say in the domain of GUI.

I'm not a specialist of languages for graphical applications at all, but the history seems to not have given reason to GTK, with the complicated 2.X / 3.0 upgrade, with the portability problems, and, maybe also inherent problems of the threading mechanisms of GTK (???).

So, is it a correct reading between your lines that the problem you see with CoqIDE is not CoqIDE itself but gtk and in particular its portability issues and the pain it apparently induces in building the windows and macos x packages, in a context where other GUI models would be more transparently cross-platform?

In any case, the time spent on CoqIDE, at least at the beginning, was not a lost of time, but instead a pleasant and instructive adventure which federated several people at the time, maybe similar to the spontaneity with which jscoq has been developed.

**Comment by Zimmi48** [comment]
>So, is it a correct reading between your lines that the problem you see with CoqIDE is not CoqIDE itself but gtk and in particular its portability issues and the pain it apparently induces in building the windows and macos x packages, in a context where other GUI models would be more transparently cross-platform?

Absolutely. And even if CoqIDE was indeed a nice and successful experiment it is becoming more of a burden nowadays (even if it's still the only editor to properly support all of Coq's features -- and this is a shame).

>In any case, the time spent on CoqIDE, at least at the beginning, was not a lost of time, but instead a pleasant and instructive adventure which federated several people at the time, maybe similar to the spontaneity with which jscoq has been developed.

Sure, I totally get that.

**Comment by herbelin** [comment]
> Absolutely. And even if CoqIDE was indeed a nice and successful experiment it is becoming more of a burden nowadays (even if it's still the only editor to properly support all of Coq's features -- and this is a shame).

So, could you give a short summary of the difficulties to support CoqIDE on Windows and MacOS X so that I get an intuitive picture of what shall have to be done if my affection for CoqIDE eventually pushes me to take over the packaging?

**Comment by ejgallego** [comment]
@herbelin you can start at https://github.com/garrigue/lablgtk/issues/2

**Comment by Zimmi48** [comment]
Regarding Windows, @MSoegtropIMC can tell you better than I can.
Regarding macOS, @maximedenes (and now @vbgl) are confronted to the problem of the package signing. The process is not clear, not well documented, and even more complicated when you have to go through a VM because you don't own a Mac yourself. If we stopped distributing CoqIDE as part of the main Coq distribution, then we wouldn't have to provide a new official macOS package at each release. This would be quite cool. (And in fact, a CoqIDE that assumes that Coq is installed wouldn't need to be updated as frequently: the same version could very well talk to Coq 8.8.0 or 8.8.2 installed through opam or brew.)

**Comment by MSoegtropIMC** [comment]
@herbelin : regarding Windows: initially it was quite hard, because GTK was only available for MSys/MSys2 and both were unusable for building complex Linux oriented projects like Coq. It took me quite a while to cross compile GTK and all its dependencies for MinGW under Cygwin. Meanwhile MinGW GTK packages are supplied by Cygwin and building and packaging CoqIDE for Windows is close to zero maintenance effort. It might get tough again if someone decides to discontinue the MinGW GTK-2 Cygwin packages - my build scripts are still there, but it takes ages to build (2 hours or so).

But I think what @Zimmi48 meant is that maintaining an IDE which keeps up with the high expectations of users set e.g. by VSCode is generally hard. Things like GIT support with one click graphical comparison are expected by many users from an IDE these days.

**Comment by herbelin** [comment]
> If we stopped distributing CoqIDE as part of the main Coq distribution, then we wouldn't have to provide a new official macOS package at each release.

That would be a pity, after all the efforts made by @maximedenes to improve the building of packages.

**Comment by herbelin** [comment]
@MSoegtropIMC: Thanks, taking note.

I'm supporting high expectations of users in IDE, but what do we have to propose at the time of today? I don't have recent news, but what is for instance the status of @siegebell's [VSCode](https://github.com/siegebell/vscoq) plugin?

**Comment by ejgallego** [comment]
@herbelin indeed this is an area we are lacking and indeed there are quite a few reasons we do so.

A lack of manpower, a lack of IDE expertise, some strange technical / management choices, and a lack of understanding of what people on the UI side need are just a few factors that mean we are not looking great so far.

Admittedly, UI are very hard to begin with, but yeah, we could do way better.

**Comment by maximedenes** [comment]
> Admittedly, UI are very hard to begin with, but yeah, we could do way better.

Any suggestion of what could be a concrete action on that topic? I've heard rumors that you had an intern working on the topic. If that is correct, why not make this effort a bit more open / public, so that we can see where we can help?

**Comment by ejgallego** [comment]
> Any suggestion of what could be a concrete action on that topic?

I have complained/suggested already way too many times about some topics I understand essential in order to have effective development. I am not sure what is the point in stating them for N+1 time; in that sense, I have the feeling that any effort towards effective development in Coq is hopeless these days so I dunno.

**Comment by Zimmi48** [comment]
>I'm supporting high expectations of users in IDE, but what do we have to propose at the time of today? I don't have recent news, but what is for instance the status of @siegebell's VSCode plugin?

Indeed @herbelin I agree that at the current time, we have nothing better than CoqIDE to propose.

>That would be a pity, after all the efforts made by @maximedenes to improve the building of packages.

Well even after all these efforts, the situation wrt to macOS is quite bad. @maximedenes can confirm but I feel like he would drop the macOS packages with great pleasure.

>any effort towards effective development in Coq is hopeless these days so I dunno.

More communication can never hurt. Of course, you might be reluctant because it would take some of your time to communicate on this. Maybe you could ask your intern to open an issue and regularly report their progress on it.

**Comment by ejgallego** [comment]
> More communication can never hurt.

Oh well, more communication when what you have to say is not positive can indeed hurt, so it is better just to move on.

**Comment by Zimmi48** [comment]
True. I meant more communication on what you are doing, not on what you think of others.

**Comment by MSoegtropIMC** [comment]
@herbelin : I tried @siegebell's VSCode plugin last shortly after the workshop in Nice. I am still using CoqIDE ... The main issues is speed but also Coq feature wise it is behind (things like background and parallel proofs). And it is a bit tricky to setup. For users like university students, it should work out of the box.

Actually I typically use both, CoqIDE and VSCode together, but the latter without the plugin. I tend to use VSCode for "bulk editing and refactoring" as plain text editor / git UI and CoqIDE for interactive proof development. One CoqIDE feature which would make this work style easier is a "file changed on disk" warning.

I am fairly pragmatic in these things.

**Comment by anton-trunov** [comment]
> CoqIDE ... (even if it's still the only editor to properly support all of Coq's features ...

@Zimmi48 I'm just curious, what features are unique to CoqIDE? Or, an alternative formulation: what feature PG does not have compared to CoqIDE?

(I recently switched to spacemacs and from time to time I'm trying to tweak my [spacemacs-coq](https://github.com/anton-trunov/spacemacs-coq) fork, so I'd be interested in implementing those features and would eventually try to add them to the vanilla PG)

**Comment by maximedenes** [comment]
> I have complained/suggested already way too many times about some topics I understand essential in order to have effective development. I am not sure what is the point in stating them for N+1 time; in that sense, I have the feeling that any effort towards effective development in Coq is hopeless these days so I dunno.

Ok, as you like. Can you at least say if you do have an intern working on the topic or not?

**Comment by ejgallego** [comment]
> I meant more communication on what you are doing,

Well, I am actually doing nothing these days UI-wise [other than to finish the work started with the package format]. What I wanted to do is just not possible to do. Think of what happened in Isabelle, an effort on the scale of implementing modern UI support in Coq is not something we can achieve with the current development model. In Isabelle, Macarious just took a "dictatorial role" and did what he wanted; even so, he took large amounts of flak and critic, but in the end, he delivered something working even thou is mostly his personal work, no doubt he could have benefited from more input IMHO. In Coq, as of today, even trivial PRs are delayed for months or rejected using totally bogus [or at best shortsighted] technical reasons; put that reality against the effort level required for modern UI support and you quickly arrive to the conclusion that such initiative is just not feasible today.

**Comment by ejgallego** [comment]
> Can you at least say if you do have an intern working on the topic or not?

Of course, our intern just finished work over LSP and Dedukti. I am gonna look for a new intern on the topic of proof documents but I am skeptical I will recommend they to contribute directly to Coq. I still have to write the concrete proposal for this year but wanna discuss first with some potential co-advisors.

Regarding the rest, I feel like I have nothing more to say that I haven't repeated several times before, so I dunno, I don't want to be insistent. I am OK with the current reality, it is the one it is; but IMHO it makes UI development unfeasible. No hard feelings colega.

**Comment by ejgallego** [comment]
> I haven't repeated several times before

Note that I am OK repeating what I think N+M times, I just don't see the point of doing so, and in fact I am even afraid of being "bullied" again.

**Comment by maximedenes** [comment]
@ejgallego ok, thanks for the clarification!

**Comment by ejgallego** [comment]
> I still have to write the concrete proposal for this year but wanna discuss first with some potential co-advisors.

No problem, note that internship proposals will be uploaded to my web page https://www.cri.ensmp.fr/people/gallego/ in fact, you can still see the ones of last year.

@anton-trunov , indeed, PG is in need of a full revamp. We tried something long time ago (https://github.com/cpitclaudel/elcoq) , however, right now there are some hard-to-solve technical limitations in particular due to STM architecture.

**Comment by maximedenes** [comment]
Where can we read a report about the LSP + Dedukti work? I guess it will give us a good idea on the feasibility of an LSP-based middleware between Coq and UIs.

**Comment by ejgallego** [comment]
> I don't know exactly what you are referring to, as far as UI-related dev is concerned. If you mean some previous exchanges @gares, I think it was more a matter of overintepreting some comments. I don't see any real obstacles to resuming normal development efforts there. In fact, I'm pretty sure @gares would welcome some more cleanups on the document model, the STM implementation, etc.

I'm afraid I have to differ [and won't comment more as it is offtopic] in both accounts. Regarding personal interaction, I was described in unfair, and far from flattening terms repeated times. Regarding technical interaction, I have to say that many of the PRs I have been trying to push in order to improve the interface offered to the upper layers / serialization have not been welcomed at all.

> Where can we read a report about the LSP + Dedukti work?

I have the report but I ignore if it is going to be uploaded to some public place.

> I guess it will give us a good idea on the feasibility of an LSP-based middleware between Coq and UIs.

Umm, I do have an exact idea on the feasibility of such project having already written two prototypes of LSP servers for Dedukti and Coq. My opinion is that it is unfeasible, for the reasons stated above.

**Comment by ejgallego** [comment]
That's Ismail page for the atom plugin: https://github.com/lachhebo/dedukti-editor , that's the Dedukti server https://github.com/ejgallego/lambdapi/tree/plof/lp-lsp written by me

[the Coq one is not public as it requires a heavily patched Coq]
