### ISSUE TITLE
New Windows spurious CI failures.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq#8514]
I've seen two recent spurious failures of the Windows CI builds:
- https://gitlab.com/coq/coq/-/jobs/98687333
- https://gitlab.com/coq/coq/-/jobs/99619726

One is on win32 and the other on win64.
In the two cases, it fails during the installation step of ocamlbuild. I have no idea what could be going wrong. The logs that were uploaded as artifacts do not show any error...

cc @MSoegtropIMC

**Comment by MSoegtropIMC** [comment]
I would say this is caused by not deleting cygwin. If a cygwin is reused, ocamlbuild already exists and the installation of it fails.

Commit 6a8c37c02504463afaa677641d75d9977020edf6 should fix this and also help in debugging such issues. This is very easy to port from v8.8 to master, so I think it would make sense to do this as a separate PR (the addons might take a bit longer).

**Comment by MSoegtropIMC** [comment]
Since the logs show this behavior

- cygwin is deleted and freshly installed
- ocaml, sed and flexdll are build and installed
- ocamlfind is build

Then magically, before installing ocamlfind, this folder exists:
```
C:/cygwin64/usr/x86_64-w64-mingw32/sys-root/mingw/libocaml/ocamlbuild
```
exists. The only explanation for this I have, besides ocaml randomly installing ocamlfind, is that the cygwin folder is used by someone else.

Shall I switch to randomly generated or otherwise unique folder names? Cleaning up might be a bit tricky ...

**Comment by MSoegtropIMC** [comment]
@Zimmi48 : just wanted to ask if you experienced any spurious windows CI failures after the fix. Should we doe more testing?

**Comment by Zimmi48** [comment]
No more failures indeed.
