### ISSUE TITLE
[ssr] dispatch intro pattern is too permisive

### ISSUE THREAD

**Issue by CohenCyril** [coq/coq#8544]
#### Version
 ```
The Coq Proof Assistant, version 8.8.1 (September 2018)
compiled on Sep 1 2018 9:56:03 with OCaml 4.06.1
```

#### Operating system
```Linux [...] 4.14.67 [...]-NixOS SMP Fri Aug 24 11:09:23 UTC 2018 x86_64 GNU/Linux```

#### Description of the problem

The following should fail because there should be two members in the dispatch.
Now the intro pattern between brackets is applied to the first subgoal.
```coq
Require Import ssreflect.
Goal True \/ True -> False.
case => [a].
```

**Comment by CohenCyril** [comment]
@thery

**Comment by CohenCyril** [comment]
@gares do you know when this became possible?

**Comment by gares** [comment]
I guess it was when the ipats were ported to the tactic monad. The line
https://github.com/coq/coq/blob/master/plugins/ssr/ssripats.ml#L219
seems fishy, since it extends the dispatch with idtacs.

**Comment by gares** [comment]
Can you confirm it is only the first `[]` (the ssr exception where `[]` is not doing case, again) is affected?
Because this code changed, I pre-process the ipat by turning a `IpatCase` to `IpatDispatch` and that one was, I don't know why, implemented with a non-strict semantics (and it has no concrete syntax, but it will get one with the new ipats...).

Thanks for reporting.

**Comment by CohenCyril** [comment]
@gares Yes, for example
```coq
Goal True \/ True -> False.
Fail move=> [a].
```
has the right behaviour.

Also, you might already know, but the same bug extends to other cases, e.g.
```coq
Inductive three := zero | one | two.
Goal three -> False.
case=> [|].
```
does not complain, even though there are only two intro patterns, etc...

**Comment by gares** [comment]
please write your +1 on the PR! #8556

**Comment by anton-trunov** [comment]
@gares Done! :)
