### ISSUE TITLE
"Add LoadPath" broken on Windows; poor documentation for directory/path setup; use with OPAM

### ISSUE THREAD

**Issue by jfehrle** [coq/coq#8592]
#### Description of the problem

1. The doc doesn't describe the syntax for `dirpath` (the Coq name to assign)--whether it's quoted or not, what to use on Windows vs Linux, etc.  Also the name `string` doesn't clearly suggest that it's the OS name for the directory.  So hard to figure out what `dirpath` should be without reading the source code.

2. The documentation needs a section describing clearly and fully how to set up directories and paths.  Some of this information is scattered around the manual, e.g. -Q and -R command line parameters in one section (Do they work/should they be used for CoqIde?), the _CoqProject file is mentioned only in the Utilities chapter with a thin description, while it appears CoqIde will use it.

3. Is Coq set up to play nicely with OPAM as a mechanism for downloading libraries?  If so, we should document it.  I tried using OPAM to install mathcomp from https://github.com/math-comp/math-comp but I ran into a couple problems:
- What directory do I pass to Coq for mathcomp using -Q, -R, _CoqProject, ...?
- When I compare the contents of `/home/Jim/.opam/4.06.0+mingw64c/lib/coq/user-contrib/mathcomp` with mathcomp source from git, it appears only the ssreflect subdirectory is present.
- OPAM compiled Coq but not CoqIDE.  On Windows, the latter has very specific compilation requirements that OPAM probably can't meet.
Am I mistaken to expect Coq and mathcomp will work together out of the box?
See https://github.com/math-comp/math-comp/issues/231

```
Coq < Add LoadPath "tup" as "/home/Jim/.opam/4.06.0+mingw64c/lib/coq/user-contrib/mathcomp/ssreflect".
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Syntax error: [Prim.dirpath] expected after 'as' (in [as_dirpath]).

Coq < Add LoadPath "tup" as /home/Jim/.opam/4.06.0+mingw64c/lib/coq/user-contrib/mathcomp/ssreflect.
Toplevel input, characters 22-23:
> Add LoadPath "tup" as /home/Jim/.opam/4.06.0+mingw64c/lib/coq/user-contrib/mathcomp/ssreflect.
>                       ^
Error: Syntax error: [Prim.dirpath] expected after 'as' (in [as_dirpath]).

Coq < Add LoadPath "tup" as "C:\OCaml64\home\Jim\.opam\4.06.0+mingw64c\lib\coq\user-contrib\mathcomp\ssreflect".
Toplevel input, characters 22-105:
> Add LoadPath "tup" as "C:\OCaml64\home\Jim\.opam\4.06.0+mingw64c\lib\coq\user-contrib\mathcomp\ssreflect".
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Syntax error: [Prim.dirpath] expected after 'as' (in [as_dirpath]).

Coq < Add LoadPath "tup" as C:\OCaml64\home\Jim\.opam\4.06.0+mingw64c\lib\coq\user-contrib\mathcomp\ssreflect.
Toplevel input, characters 23-24:
> Add LoadPath "tup" as C:\OCaml64\home\Jim\.opam\4.06.0+mingw64c\lib\coq\user-contrib\mathcomp\ssreflect.
>                        ^
Error: Syntax error: '.' expected after [vernac:command] (in [vernac_aux]).
```

**Comment by Zimmi48** [comment]
First of all, I agree with you: the documentation on these things is quite bad. I had much trouble until I finally grasped it. On the LoadPath question, you are probably right that this is a bug. The LoadPath command is probably not tested enough. That being said, you should almost never need to use LoadPath.

The -R and -Q options and the _CoqProject file are for when you are *developing* a library, and *not* for using it.

There are two ways to enable Coq to discover a library: either you install it where Coq expects it relative to the Coq installation directory, i.e. something like `lib/user-contrib/` if `coqtop` is in `bin/`. Or you install it anywhere else and you setup the environment variable `COQPATH` to point to the *parent* directory, i.e. if math-comp is in `/foo/user-contrib/mathcomp` set `COQPATH=/foo/user-contrib`. Then use `From mathcomp Require Import all_ssreflect.` to load the file `all_ssreflect` from the library `mathcomp`.

There are a few reasons why people will generally install *both* coq and their libraries with OPAM instead of just the latter:
- Coq libraries depend on a given version of Coq, which is made explicit in the OPAM file. Thus OPAM will automatically install coq as well when installing a given library. There currently is no support for allowing to install Coq libraries with a system provided Coq. This is unfortunate and this also affects Linux users who would want to use their distribution provided package to install Coq.
- The libraries will be installed in the expected location relative to the location of Coq inside the opam root. So no further configuration is required.

To use libraries installed with OPAM with a system-install of CoqIDE you have two options (this also applies to users of macOS or Linux):
- Configure CoqIDE to use the OPAM-installed coqidetop. (You can change the location where CoqIDE will look for coqidetop in the settings.)
- Continue using CoqIDE with the system-installed coqidetop but setup `COQPATH` so that it will know where to look for libraries.

If you open PRs to improve this part of the documentation, I will review them gladly. Note that there is also this page https://coq.inria.fr/opam/www/using.html regarding OPAM and Coq whose source is https://github.com/coq/opam-coq-archive/blob/master/USING.md and we might want to document some of the most esoteric setups on the wiki instead of the manual (for instance I want to try out installing pure Coq libraries with Nix in Bash on Ubuntu on Windows and running them from a CoqIDE installed using the Coq Windows installer).

**Comment by ejgallego** [comment]
> Add LoadPath "tup" as "/home/Jim/.opam/4.06.0+mingw64c/lib/coq/user-contrib/mathcomp/ssreflect".
> >                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error: Syntax error: [Prim.dirpath] expected after 'as' (in [as_dirpath]).

Well you swapped the logical and the physical path so no suprise this doesn't work. Try
`Add LoadPath "/home..." as tup.`

Regarding the rest of the bug, most of it seems invalid / or questions so I am leaning to close it, as the only valid part seems a request for documentation improvements.

**Comment by jfehrle** [comment]
> Regarding the rest of the bug, most of it seems invalid / or questions so I am leaning to close it, as the only valid part seems a request for documentation improvements.

No, don't close it.  We should certainly allow filing PRs against the documentation.  Indeed, I'd like to revise this section of the manual eventually.  This is already tagged as `documentation`.  The `resolved: invalid` is not appropriate--the documentation doesn't describe feature well enough to use it.

**Comment by ejgallego** [comment]
> No, don't close it. We should certainly allow filing PRs against the documentation. Indeed, I'd like to revise this section of the manual eventually. This is already tagged as `documentation`. The `resolved: invalid` is not appropriate--the documentation doesn't describe feature well enough to use it.

Then please: update the bug title and description, remove all the invalid items, and remove the tag, thanks!

**Comment by ejgallego** [comment]
This was not acted upon, after 4 years we can close.

The short answer is that the recommended way to use math-comp is using your package manager + build system setup (coq makefile has a global namespace , dune infers a namespace from user-contrib`)
