### ISSUE TITLE
SSReflect's Search tool does not take Search Blacklist table into account

### ISSUE THREAD

**Issue by anton-trunov** [coq/coq#8663]
#### Version

Coq 8.8.1

#### Operating system

macOS 10.13.6

#### Description of the problem

Please see the comments in the snippet below:

```coq
Print Table Search Blacklist.
(* Current search blacklist :  _subterm _subproof Private_. *)

Axiom T : Type.
Axiom Private_t : T.
Axiom NonPriv_t : T.

(** the standard search tool respects the blacklist *)
Search T.
(* NonPriv_t: T *)

(** but ssr does not *)
From Coq Require Import ssreflect.
Search _ T.
(*
NonPriv_t  T
Private_t  T
*)
```

**Comment by Zimmi48** [comment]
Probably the best fix here is to remove the Search tool of SSReflect and merge whatever special features are useful in the main one.

**Comment by tchajed** [comment]
From the [SSReflect documentation](https://coq.inria.fr/refman/proof-engine/ssreflect-proof-language.html#ssr-searching-tool) the features missing from the built-in Search are:

1. A special conclusion-only first pattern. This isn't the same as `SearchHead` (which only matches the head of the conclusion) and is anyway more powerful because it can be combined with other patterns that match anywhere. Note that this only provides more precise filtering.
2. When searching for a notation, SSReflect reports the notation and its expansion in addition to including it in searches.
3. Diagnostics around multiple matching notations, when a partial notation is given. Coq `Search` doesn't support partial notations.
4. Issues a warning if a notation has another interpretation in a different scope.

Of these, to me (2) is the most useful to port while the others aren't really necessary. (3) and (4) are better handled by `Locate` in any case (eg, neither the built-in nor ssreflect `Search` handle the `exists2` notation for `ex2` correctly). (1) is kind of nice, but the way SSReflect handles it (the first pattern is special) is confusing UI and I don't think it's a necessary improvement over `SearchHead`. I've never felt I needed better filtering tools for `Search`.

**Comment by Zimmi48** [comment]
Maybe no need to overthink this if actual use cases are already covered by `SearchHead`. It would be interesting to have more feedback from users.

**Comment by ana-borges** [comment]
SSR Search has been removed in https://github.com/coq/coq/pull/13760, solving this issue.
