### ISSUE TITLE
What are the shelves for?

### ISSUE THREAD

**Issue by mattam82** [coq/coq#8770]
I'd like to get a confirmation of my current understanding of the shelves in Proof and Proofview. 

It seems that the shelf in Proofview should only be of temporary use. Each run_tactic gathers the Proofview's shelf at the end of the tactic run and puts that in the Proof.t shelf. It resets the future_goals of the current Proofview evar_map, and its local shelf. Then the Unshelve command calls Proof.unshelve which empties its current (global) shelf and puts it as subgoals in the current proofview. It should be an invariant that run_tactic always starts with a proofview with an empty (local) shelf but that's unclear to me. @aspiwack @herbelin can you confirm that view?

I'm wondering if a different view could be used for the Proofview shelf, allowing tactics such as Proofview.unshelve to manipulate the local shelf, e.g. to create new subgoals from evars.
Imagine use cases like `evar (?a : nat); exact (some_complicated_term a); unshelve ?a`. It looks technically doable. Another use case I have is for typeclass resolution: say I apply a tactic t to a goal which generates some subgoals, on which resolution succeeds, but also shelved subgoals on which I would like resolution to be performed as well. In that case I need to call a kind of [unshelve_goals] tactic on the current proofview shelf. Does that sound reasonable?

There are also use cases for typeclass resolution where I want to leave the shelved goals shelved (typically this allows to implement forward hints).

**Comment by ejgallego** [comment]
cc: #8386 , #6292

**Comment by mattam82** [comment]
Haha. Well now I don't think anymore that they can be "merged" really. It's more like the Proofview shelf is a temporary receptacle for globally shelved goals in the Proof.t shelf, it seems. OR maybe we can keep everything in the Proofview's shelf and maintain it there, if that plays well with focusing.

**Comment by aspiwack** [comment]
Sorry… I had forgotten about this :confused: 

> It should be an invariant that run_tactic always starts with a proofview with an empty (local) shelf but that's unclear to me.

This is correct. The shelve in the proofview was conceived of as as "writer" effect. Every tactic execution is supposed to start with an empty local shelf, and they would all be flushed to the global shelf at the end of the tactic execution.

> Imagine use cases like evar `(?a : nat); exact (some_complicated_term a); unshelve ?a`

Naïvely, I would use the more functional approach to great a goal `?a : nat` then focus on the rest of the goals (`[2,-1]:` I suppose), run `exact (some_complicated_term a)` there, then unfocus. Any reason why pulling things out of the shelf would be desirable here? (there is also a local `unshelve` tactic, I believe, so that `unshelve t` is like `t` but concatenates all the goals shelved by `t` at the end of the focused goal list. I believe @ppedrot  implemented that)

> on which resolution succeeds, but also shelved subgoals on which I would like resolution to be performed as well. In that case I need to call a kind of [unshelve_goals] tactic on the current proofview shelf. Does that sound reasonable?

It's unclear to me what rule you would use to pull goals from the shelf. An alternative would be to not shelve goals immediately, just focus them out, and when you are ready to decide which goals you want to pursue and which you want to just leave to unification, you can unfocus and shelve or solve. (considering the `unshelve` tactic, you can just shelve goals and  call `unshelve resolve_type_classes` so that all these goals that you need to decide suddenly pop back into focus. This avoids a more complex manipulation of the focus stack).

That being said, it's not unreasonable to have a more state-like manipulation of the shelved goals. With things entering and leaving it. But you probably don't want to distinguish the local and the global shelf, for that purpose.

> OR maybe we can keep everything in the Proofview's shelf and maintain it there, if that plays well with focusing.

It's probably possible. There's been a trend to move more things out of the `Proof.t` and into the proofview for tactics to be able to control them (it's even been considered to move the focus stack there). You'd have, however, to be careful with the interaction with the scoped `unshelve` tactic which I've mentioned a few times already. If I had to choose between this scoped tactic and a state-like manipulation, I'd go for the scoped tactic (as it behaves less like a global effect). But maybe we can have both?

**Comment by mattam82** [comment]
Thanks for the explanations @aspiwack I believe the scoped solution is better behaved as well and now that I understand the model a bit better I think it should stay like this (at least for the use cases I had in mind), making use of `unshelve` to explicitly manipulate dependent subgoals.
About @Zimmi48 's example, I think the global nature of the global shelf is unavoidable for dependent subgoals. One can be explicit and use `unshelve eexists _` to force the generation of a subgoal in the first branch here. You could also imagine a mode of strict focusing that disallows unfocusing a proof that extended the global shelf, forcing to use `unshelve eexists _` or `Unshelve` in the first branch.

**Comment by Zimmi48** [comment]
>You could also imagine a mode of strict focusing that disallows unfocusing a proof that extended the global shelf, forcing to use unshelve eexists _ or Unshelve in the first branch.

That sounds like a good solution.
