### ISSUE TITLE
-mangle-names fails on inductive definition

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#8790]
#### Version

8.9.dev (but this was already broken with 8.8)

#### Operating system
Linux

#### Description of the problem

Consider this example file:
```coq
From Coq Require Import List.
Export ListNotations.

Inductive TCForall {A} (P : A -> Prop) : list A -> Prop :=
  | TCForall_nil : TCForall P []
  | TCForall_cons x xs : P x -> TCForall P xs -> TCForall P (x :: xs).
```
And compile it using `coqc -mangle-names mangled_ test.v`. I'd expect that to work, because the file does not refer to any auto-generated names.

Unfortunately, it fails:
```
File "/home/r/Desktop/test.v", line 5, characters 19-27:
Error: The reference mangled_0 was not found in the current environment.
```

This is really sad, because I was so happy when I saw this feature and wanted to use it on CI for all our projects immediately :(

I should also note that I thought I had reported this already half a year ago, but cannot find that original report any more...

**Comment by Zimmi48** [comment]
cc @jashug

**Comment by jashug** [comment]
A possible fix is given in #7254, which is blocked on a unification failure I'll need help to understand. (has a link to the gitter discussion of this issue, which I'll summarize below)

There are two interacting weird design decisions interacting here:
* The implicit argument subsystem of coq (with `mangle-names` set) calculates that the displayed type of `TCForall` will be `TCForall : forall _0 : Type, (_0 -> Prop) -> list _0 -> Prop`, and so sets the key of the implicit type argument `A` to be `_0` (so `TCForall` needs to be applied as `TCForall (_0 := A) P`). We're already being too clever by half here; I believe that we shouldn't automatically assign implicit argument keys to anything but what is written in the code. I want to fix this, and it has an issue #6785, but no PR yet.
* When elaborating implicit inductive parameters, we secretly add `(key := key)` for all the implicit parameters that aren't explicitly specified (with `@` or with an explicit binding `(key := value)`). When the `key` is the name of the corresponding parameter, this works fine; when it is renamed by `-mangle-names` (or without, `Inductive foo {A:Type} {A:A -> nat} := bar : foo.` runs into the same problem) you get what you have here, which is `TCForall (_0 := _0) P []` while you have `A : Type` in the context, so `_0` is not found. This problem is what #7254 solves.

**Comment by RalfJung** [comment]
@maximedenes we talked about this at POPL, and you asked me to give you the current status. Looks like the current status is that this bug is still open, meaning that `-mangle-names ` remains not useful for production developments.

**Comment by RalfJung** [comment]
Cc https://github.com/coq/coq/pull/11579

**Comment by RalfJung** [comment]
https://github.com/coq/coq/pull/11579 landed. I'll re-try mangling with our developments soon.

**Comment by RalfJung** [comment]
Okay, the particular failure this issue is about is fixed. We are getting 100 lines further into the first file of std++, then we get the next issue. I'll report that separately though.

**Comment by RalfJung** [comment]
Opened https://github.com/coq/coq/issues/12001
