### ISSUE TITLE
eexists guesses class instantiations

### ISSUE THREAD

**Issue by lennartberinger** [coq/coq#8792]
#### Version

8.8.1 and 8.8.2

#### Operating system
Ubuntu

#### Description of the problem

It appears that eexists occasionally immediately instantiates the evar it introduces, 
as in the following snipped, where it seems to pick the most recently declared
instance of class foo. This prevents the user from using eexists to have instantiations
be 'lazily' figured out during the proof.

Require Import ZArith.
Class foo := {f : nat }.

Instance foo2 : foo := {| f:=2 |}.
Instance foo5 : foo := {| f:=5 |}.

Goal exists y: foo, @f y > 3.
  eexists. (*eexists picks foo5 here; which happens to be ok for this proof*) simpl.
  omega. 
Qed. 

Instance foo3 : foo := {| f:=3 |}.

Goal exists y: foo, @f y >3.
  eexists. (* now eexists picks foo3, so the goal becomes unsolvable*) simpl.
Abort.

**Comment by ppedrot** [comment]
I believe this is the expected behaviour. You defined a class with instances, so tactics try to solve them when they see a hole with a type of that class. In this light, you're the one responsible for the clever definition of your logic programming solver (or user lower-level tactics when you don't want typeclasses to be solved). I am thus inclined to close this as an INVALID report.
