### ISSUE TITLE
Coq LICENSE file needs an update

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8828]
Coq `LICENSE` file should not contain the text of the LGPL 2.1 but provide an overview of the different components of the system and their license.

I tend to use a machine-readable format, see for example: https://github.com/ejgallego/coq-serapi/blob/v8.8/LICENSE

**Comment by Zimmi48** [comment]
The problem of the machine readable format that you use is that GitHub doesn't know how to read it. I suggest to keep the text of LGPL 2.1 in `LICENSE` since this is the license for *most* of the code (and the recommended practice to ship the license with the code). However, we could add another file `COPYING` that provides the overview that you mentioned.

**Comment by Zimmi48** [comment]
AFAICT Coq is currently following recommended best practices (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#where-does-the-license-live-on-my-repository). If there are references to licensing best practices that Coq is not following, please reopen with a pointer to documentation of these best practices.
