### ISSUE TITLE
if and tryif syntax errors w/ goal selectors

### ISSUE THREAD

**Issue by eluuk** [coq/coq#8897]
#### Version

8.8.1

#### Operating system

Linux

#### Description of the problem

It would be helpful if at least some of the lines triggering syntax errors would compile instead:

```
Check if true then ltac:(all: idtac) else ltac:(idtac).
(* Syntax error: ')' expected after [tactic:tactic_expr] (in [constr:operconstr]). *)
Ltac main := tryif split then (all: idtac) else idtac.
(* Syntax error: ')' expected after [tactic:tactic_expr] (in [tactic:tactic_expr]). *)
Ltac main := tryif split then all: idtac else idtac.
(* Syntax error: 'else' expected after [tactic:tactic_expr] (in [tactic:tactic_expr]). *)
```

This may be a feature request on `if` and `tryif` syntax w/ goal selectors rather than a bug

**Comment by Zimmi48** [comment]
@eluuk What are you trying to do? These examples do not show much but it seems to me that you are missing some insight on the semantics of the `all:` selector which explains why it can only be used at top-level. On the contrary, other goal selectors like `1,2:` can be used in the middle of some Ltac thanks to the `only` keyword (see https://coq.gitlab.io/-/coq/-/jobs/115950212/artifacts/_install_ci/share/doc/coq/sphinx/html/proof-engine/ltac.html#coq:tacv.only -- linking to the doc for master because apparently Coq's website is down!)

**Comment by eluuk** [comment]
@Zimmi48 I missed the fact that in `tryif tac then tac0 else tac1`, `tac`s are taken to end w/ `;`, so no `all:` is necessary (and as you said, `only` can be prepended to other selectors). Sorry, closing, feel free to delete
