### ISSUE TITLE
[ci] fiat-crypto is consistenly failing with OOM

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#8993]
`fiat-crypto` is failing with OOM in the gitlab CI; we should implement a countermeasure.

cc: @JasonGross

**Comment by JasonGross** [comment]
Which files are OOMing?

I did recently implement a change that made it more memory hungry (but less False).

**Comment by ppedrot** [comment]
@JasonGross I think this is the call to the native binary `word_by_word_montgomery` while building `p384_32.c`. Computing free variables of a huge term thrashes the memory.

**Comment by ejgallego** [comment]
@JasonGross see any recent log such as https://gitlab.com/coq/coq/-/jobs/120323405

**Comment by JasonGross** [comment]
@ppedrot Thanks!  I'm taking what you're saying to mean that the memory intensive bit is `compute_live_counts'` on a huge term (which makes sense, since it's basically building an enormous `PositiveSet.t` for every single binder); I'm going to see if I can make it less memory intensive by using a different `var` type.
