### ISSUE TITLE
small manual proof takes 1min to Defined and 3min to print

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9029]
#### Version

~~~~~
The Coq Proof Assistant, version 8.8.2 (October 2018)
compiled on Oct 1 2018 0:22:50 with OCaml 4.07.0
~~~~~

#### Operating system

Arch Linux, up to date as of yesterday.

#### Description of the problem

I made a (relatively) self-contained example of a slow proof that I hope will be instructive for hunting down performance issues that affect bedrock2 and fiat-crypto (and perhaps other projects in the academic geneology of Adam Chlipala and @JasonGross).

The statement of the lemma applies a verification condition generator fixpoint to an imperative implementation of the binary exponentiation algorithm. The fully  normalized verification condition would contain a bunch of ∃, /\\, some ∀, and leaves which I think are relatively fast. The proof script is written very carefully to avoid generating large proof terms, in hope that it would improve performance. In particular, the size of the goal is kept modest at all times. The individual proofs steps correspond roughly to variants of `destruct`, `eexists`, and `apply`, and take up less than 200 lines when written out by hand. Proofs of nontrivial leaves are factored out using `abstract`, and the proof ends in `Defined` to avoid potential slowdown from recombination and hashconsing. Actually, the leaves could probably be admitted, but I haven't tried that yet. I took care to keep the proof term relatively readable, although adding notations would probably help even more. In particular, order of subproofs in the proofterm should match the order of parts of the imperative program whose safety they argue.

Executing the proof script takes around 10 seconds. Defined takes 1 minute. Printing the proof term takes 3 minutes.

The proof is at
https://github.com/mit-plv/bedrock2/blob/24abd309a46c039e22e732f9390aabeba4516fce/bedrock2/src/Examples/ipow.v#L134 and relies on lightweight tactics defined earlier in the same file. https://github.com/mit-plv/bedrock2/blob/24abd309a46c039e22e732f9390aabeba4516fce/bedrock2/src/WeakestPrecondition.v#L50 is probably relevant to understand what the goal is. The 500-line proof term is at eac425acac9139580fa15be1e363b603 using notations from https://github.com/mit-plv/bedrock2/blob/24abd309a46c039e22e732f9390aabeba4516fce/bedrock2/src/Examples/ipow.v#L116.

The proof really isn't that big. Some statistics:

~~~~~
browse@ashryn ~ % cat /tmp/a | grep -c let
71
browse@ashryn ~ % cat /tmp/a | grep -c ex_intro
20
browse@ashryn ~ % cat /tmp/a | grep -c conj    
15
browse@ashryn ~ % cat /tmp/a | grep -c eq_refl
36
browse@ashryn ~ % cat /tmp/a | grep -c need   # notation for let+ex_intro
22
~~~~~

I am very interested in finding out what is actually taking time here, and willing to immediately put in a couple of hours each day this week to investigate this and prototype solutions and workarounds. However, I would appreciate if somebody who knows the implementation side of what I am poking at here helped me out. @ppedrot?

**Comment by ejgallego** [comment]
@andres-erbsen something very easy to do and that would be very helpful is to actually profile the different printing stages. There are many potential hotspots, and even if the most likely one is some super-linear algorithm in `Detyping`, having a view of each pass would help a lot with these kind of problems in the future. The passes are:
- `Constr.t` -> `glob_constr` [detyping]
- `glob_constr` -> `constr_expr` [externalization]
- `constr_expr` -> `Pp.t` [printing]
- `Pp.t` -> output format [serialization / display]

**Comment by JasonGross** [comment]
@andres-erbsen Your first call to `reduce_locals_map` takes about 3 s.  At this point, (after `Require Import Coq.Compat.AdmitAxiom`), it takes 9.7 seconds to run
```coq
Time let T := match goal with |- ?T => T end
     exact_no_check match proof_admitted return T with end.
```
If I take the list of identifiers in `reduce_locals_map` and issue `Strategy -1 [list_of_qualids]`, then it only takes about 5 s to run the admit-this-bit tactic.

Note, however, that you can prove the following lemma:
```coq
Require Import Coq.Logic.Eqdep_dec.
Lemma path_SortedList_rep {p} {x y : @SortedList.rep p}
  : SortedList.value x = SortedList.value y -> x = y.
Proof.
  cbv [SortedList.value]; destruct x as [x px], y as [y py].
  intro; subst y.
  apply f_equal, UIP_dec; decide equality.
Qed.
```
whence replacing `reduce_locals_map` with `apply path_SortedList_rep; reduce_locals_map` goes from about 3 s to about 0.01 s, and the subsequent admitting becomes instantaneous.  If I make only this change to the proof, the time for `Defined` goes down to 0.187 s on my machine, and `Time Print ...` is 0.414 s.  (Without this change, `Time Defined` is 34 s, and `Time Print ipow_ok.` is 105 s.)

This is a bit strange, though, because the diff of the printouts is small:
```diff
$ diff bedrock2/src/Examples/{before,after}.log
224c224,225
<                                         conj eq_refl (conj eq_refl eq_refl)))) in
---
>                                         conj (path_SortedList_rep eq_refl)
>                                           (conj eq_refl eq_refl)))) in
488,489c489
< <infomsg>Finished transaction in 105.214 secs (105.115u,0.107s) (successful)
< </infomsg>
---
> <infomsg>Finished transaction in 0.406 secs (0.403u,0.s) (successful)</infomsg>
```

However, if, in the version without the `apply`, right after the `reduce_locals_map`, we do `repeat match goal with H : _ |- _ => clear H end. Unset Printing Records. Set Printing Implicit.`, you can notice that Coq takes an enormous amount of time to print the goal.  (The goal is 123,742 lines long, on my machine, and has 334,329 whitespace-separated words.  `Time Show` tells me that it takes Coq 205 seconds to construct the string to print this goal.)  I believe your `cbv` unfolds some of the unapplied function arguments to things like `SortedList.parameters.Build_parameters`, and this results in enormous terms.

So a great deal of time is taken up dealing with arguments that never actually show up in the output.  @ejgallego is this the detyping phase?

----

My takeaway from this (on the user-side): Don't use `cbv` to reduce in something which is an index for some other type, unless you are tracking the dependencies carefully.

**Comment by ppedrot** [comment]
I'd bet this is due to detyping. For some reason perf is broken right now on my machine, but judging from @JasonGross description it's clearly due to some crappy algorithmic there, as usual. I have started working on a fix, but this will most likely be a flag, because printing would be different as it is now, most likely less 'optimal' in binder-choosing.

**Comment by samuelgruetter** [comment]
It turns out that if you simply comment out the invocation of `reduce_locals_map`, the proof still works, and `Defined` takes 0.14s, and `Print` takes 0.308s on my machine.

**Comment by andres-erbsen** [comment]
Okay, it seems that the slowdown here was for a different reason than what I expected. Now I am torn between being glad that it is likely an easy fix and being disappointed that this fix does not carry over to other proofs I wish were faster. But for now, this means that bedrock2 program logic development can continue. And perhaps the way this was resolved should make me slightly more optimistic that if I continue to be meticulous about proof term structure, I will either end up with a debuggable performance issue or an acceptably fast program logic. Thanks!

I will confirm the helpful findings of @JasonGross and @samuelgruetter tomorrow and most likely adopt `apply path_SortedList_rep`. I'd even say that speeding up the printing probably should not be considered a high-priority task. Should I close this issue, or update the original posting to highlight that the `Defined` part has been resolved?

**Comment by andres-erbsen** [comment]
"resolved enough" in https://github.com/mit-plv/bedrock2/commit/3e3b2820632c4f7f01e3522bf14e3ddf8a36dafe. The printing slowness seems minor enough that I am closing this issue.

**Comment by andres-erbsen** [comment]
While I did not reproduce the exact tests Jason did, I think the explanation that "cbv unfolds some of the unapplied function arguments to things like SortedList.parameters.Build_parameters, and this results in enormous terms" is accurate. This means that the performance issue was in fact in my program, and only Coq's fault to the extent that `cbv` isn't easy to use for controlled partial reductions.

**Comment by JasonGross** [comment]
@ppedrot I have reported #9034 just now, which is a more self-contained version of the printing issue.
