### ISSUE TITLE
[ci] Windows CI builds are testing too much making them impractical

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#9040]
Current Windows CI builds are often in red, due to them testing not just Coq, but a wide variety of 3rd party contributions that are often broken by PRs.

This means that even breaking a small plugin will result in a red status for the Windows build, a so far they are red so often that we end up ignoring them; #8045 has a bit of blame here too.

Please, disable building of such artifacts in pull requests, or at least don't make the build fail if a 3rd party development does.

**Comment by ejgallego** [comment]
See my comment at https://github.com/Mtac2/Mtac2/pull/127#issuecomment-442335322

**Comment by MSoegtropIMC** [comment]
Just a note: my plan is to modularize the Windows build so that first the basic Coq without installer is build, then the various plugins are build using this and finally the installer. Then we also have a more fine grain verdict (like Coq for Windows builds fine, but Mtac-2 not).

I can look into the Unicoq install path issue, but not before next week.
