### ISSUE TITLE
Assertion failed in pretty printing with QuickChick

### ISSUE THREAD

**Issue by Tuplanolla** [coq/coq#9360]
See QuickChick/QuickChick#136.

#### Version

Coq 8.8.2

QuickChick 1.0.2

OCaml 4.07.1

#### Operating system

Red Hat Enterprise Linux Workstation 7.4

#### Description of the problem

The following code causes an anomaly.

```coq
From QuickChick Require Import QuickChick.
Require Import Nat.

QuickChick (forAll (arbitrarySized 10) (leb 0)).
QuickChick (let n := 10 in forAll (arbitrarySized n) (leb 0)).
```

```
Anomaly
"File "printing/ppconstr.ml", line 399, characters 14-20: Assertion failed."
```

#### Notes

This is not a duplicate of #7867,
even though the observable result is identical.

I reported this bug to the Coq project
with a reference in the QuickChick project,
because I do not know whether this bug is caused by one or the other.

**Comment by SkySkimmer** [comment]
What does it do in Coq master?

**Comment by Alizter** [comment]
I tried very hard to find the cause of this, but ultimately failed. It is reproducible in coq 8.9.1 and the 8.9 branch of quickchick. In coq 8.10.2 and the 8.10 branch of quickchick, there is no problem. I even tried git bisecting quickchick but the incompatible versions of libraries in between cause a huge headache.

On the face of it, this bug is "resolved" but I am not sure if it is because of a change in quickchick or changes in coq.

**Comment by SkySkimmer** [comment]
We can just close IMO
