### ISSUE TITLE
outdated -emacslib configure option should not be mentioned in INSTALL

### ISSUE THREAD

**Issue by Moisan** [coq/coq#9418]
#### Version

8.9.0

#### Operating system

MacOS Mojave

#### Description of the problem

When building Coq with the option `-emacslib` I get the following error:

```
./configure.ml: unknown option '-emacslib'
```

However the INSTALL file still list this option. Was that removed intentionally or is it a bug? I did not see any release change regarding this option.

**Comment by Zimmi48** [comment]
This was removed as part of #7843 (Remove Emacs modes). This is mentioned in CHANGES (https://github.com/coq/coq/pull/7843/files#diff-e4eb329834da3d36278b1b7d943b3bc9) although not specific enough apparently. Since it seems that you are asking about this option just because you are packaging Coq and not because you were using this Emacs mode, I recommend to just remove the option from the building process.

Is it OK to close this?

**Comment by Zimmi48** [comment]
Sorry I read too fast.
