### ISSUE TITLE
Stack overflow with custom entries

### ISSUE THREAD

**Issue by Janno** [coq/coq#9583]
#### Description of the problem
The following piece of code causes a stack overflow.
```coq
Declare Custom Entry bla.
Notation "[ t ]" := (t) (at level 0, t custom bla at level 0).
Notation "] t [" := (t) (in custom bla at level 0, t custom bla at level 0).
Notation "t" := (t) (in custom bla at level 0, t constr).
Check [ ] 0 [ ].
```

Note that this parsing problem is not even ambiguous.

#### Coq Version
master

**Comment by vbgl** [comment]
Could reproduce on 8.9.0 too.

**Comment by andres-erbsen** [comment]
potentially related #9519

**Comment by maximedenes** [comment]
@herbelin can you be the assignee?

**Comment by Janno** [comment]
The code above no longer produces a stack overflow. Coq does report a parse error but I cannot say if that is the right behavior or not. In any case, I am going to close this issue.

**Comment by ejgallego** [comment]
Same than other bugs, it would be nice to check if we added a test case (cc @herbelin )

**Comment by herbelin** [comment]
Hi @Janno,

>  Coq does report a parse error but I cannot say if that is the right behavior or not. In any case, I am going to close this issue.

Yes, this is the right behavior: because `constr` is at level 200, which is higher than the level 10 of applications, it parses `0` as a function and `[ ]` as a potential argument of the function. But after `[`, a `custom bla at level 0` is expected which it does not find.

In particular, it works with `Notation "t" := (t) (in custom bla at level 0, t constr at level 9).`

**Comment by Janno** [comment]
Thanks for the detailed explanation and thanks for fixing this (and adding a test case, too)!
