### ISSUE TITLE
coq.dev opam package fails to build

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#9613]
#### Description of the problem

The coq.dev opam package fails to build, meaning many of our CI jobs are currently failing:

```
#=== ERROR while compiling coq.dev ============================================#
# context              2.0.3 | linux/x86_64 | ocaml-base-compiler.4.07.0 | pinned(git+https://github.com/coq/coq.git#master#924468eb)
# path                 /builds/iris/stdpp/opamroot/ocaml-base-compiler.4.07.0/.opam-switch/build/coq.dev
# command              /usr/bin/make -j39
# exit-code            2
# env-file             /builds/iris/stdpp/opamroot/log/coq-749-865888.env
# output-file          /builds/iris/stdpp/opamroot/log/coq-749-865888.out
### output ###
# [...]
# Fatal Error: Failure: Validation failed: tuple size: found 11, expected 12 (in mutual_inductive_body).
#              Please report at http://coq.inria.fr/bugs/.
# Makefile.build:826: recipe for target 'theories/Logic/Hurkens.vo' failed
# make[1]: *** [theories/Logic/Hurkens.vo] Error 1
# COQCHK    Coq.Numbers.DecimalFacts
# Fatal Error: Failure: Validation failed: tuple size: found 11, expected 12 (in mutual_inductive_body).
#              Please report at http://coq.inria.fr/bugs/.
# Makefile.build:826: recipe for target 'theories/Numbers/DecimalFacts.vo' failed
# make[1]: *** [theories/Numbers/DecimalFacts.vo] Error 1
# make[1]: Leaving directory '/builds/iris/stdpp/opamroot/ocaml-base-compiler.4.07.0/.opam-switch/build/coq.dev'
# Makefile:166: recipe for target 'submake' failed
# make: *** [submake] Error 2
```

Is building master broken, somehow?

**Comment by RalfJung** [comment]
Hm, interestingly I cannot reproduce this locally. And yet it happens reliably in the opam builds of one of our projects.

**Comment by SkySkimmer** [comment]
I guess this is an example build? https://gitlab.mpi-sws.org/iris/stdpp/-/jobs/24670

You have `VALIDATE=1` in the environment, so after coq compiles each stdlib vo it will coqchk it.
And #9560 made -boot ineffective on it so it looks for coqlib in the opam. Since you cache opam it finds it and uses the cached(outdated) Coq to satisfy requires, so it breaks.
Our CI doesn't use that path for coqchk since we want to run it in one go (not once per file) and we run it after installing the files so we have custom code.
So we need to fix our coqchk invocation.

Meanwhile you can workaround by unsetting VALIDATE while compiling Coq.

Additionally this is unexpected
>`# command              /usr/bin/make -j39`

@ejgallego opam should be using dune for compiling Coq no?
Maybe some other opam cache issue, IDK

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/9614 should fix.

**Comment by ejgallego** [comment]
> @ejgallego opam should be using dune for compiling Coq no?
> Maybe some other opam cache issue, IDK

The `coq.dev` package is still on makefile; you need to pin for the local opam file to override the old one.

**Comment by RalfJung** [comment]
> You have `VALIDATE=1` in the environment

Oh, that is surprising that random unscoped environment variables affect the build.
