### ISSUE TITLE
Coercion open_constr/uconstr to a pattern leads to surprising results

### ISSUE THREAD

**Issue by RalfJung** [coq/coq#9630]
#### Description of the problem

I'm afraid I don't even know how to summarize what is going on, it's just *really strange*... consider the following code
```coq
Class Eq (x y : nat) := Eq_eq : x = y.
Class invG (x : nat) : Set := InvG {
  foo : Eq 1 x;
}.

Definition my (x: nat) `{!Eq 1 x} := tt.

Ltac destruct_ t := match goal with
  | H : t |- _ => destruct H
end.
Hint Extern 12 (Eq _ _) => destruct_ uconstr:(invG _) : typeclass_instances.
Hint Extern 12 (Eq _ _) => destruct_ open_constr:(invG _) : typeclass_instances.

(* These TC hints are not enough to make the definition work *)
Fail Definition my2 x `{!invG x} := my x.

(* But with *another copy of the same hint*, the definition works. *)
Hint Extern 12 (Eq _ _) => match goal with
  | H: invG _ |- _ => destruct H
end : typeclass_instances.
Definition my2 x `{!invG x} := my x.
```
The comments explain what is weird about this: I'd like to abstract the `match goal ...` into a separate tactic, but when I do, that makes TC search fail *with an otherwise exactly identical tactic*.

Curiously, if I instead define `destruct_` as
```
Ltac destruct_ t := match goal with
  | H : ?t' |- _ => unify t t'; destruct H
end.
```
then things work. Also, if I trigger TC search from a lemma instead of as part of writing a `Definition`, the issue does not arise.

Consider me confused.^^

#### Coq Version

8.9.0

**Comment by ppedrot** [comment]
The `open_constr` hint fails because this is #4482. The `uconstr` one fails because this is #9321.

**Comment by JasonGross** [comment]
The suggested solution of #9321 is porting to Ltac2 (which I consider somewhat unsatisfactory, especially because (a) Ltac2 is still not shipped with Coq by default, (b) there is still no satisfactory replacement for `idtac` during debugging, and (c) Ltac2 seems to be in stasis / I haven't seen much response to issues in the past couple of months).  Does `Hint Extern` support Ltac2?    Does Ltac2 support `pattern:(...)`?  (I'm not in front of a computer right now and can't find any examples in the Ltac2 test-suite that test these.)

**Comment by SkySkimmer** [comment]
The open_constr hint works now.

With uconstr, the problem is that the meaning of pattern `t` is decided at runtime based on what `t` is bound to: if constr it's `pattern_of_constr` of the binding, otherwise it's a pattern variable.

Whatever way of dynamically producing patterns we end up with in ltac2 won't have this problem as we won't confuse the syntax between "use this ltac2 binding" and "pattern variable", see also https://github.com/coq/coq/pull/17667 & co

In ltac1 about the only thing we could do is decide at intern time that `t` may be bound to a constr so should always be bound to a constr, then `destruct_ uconstr:(invG _)` would error with "cannot coerce to constr" or some such thing (and the hint would still fail). Considering it wouldn't really help with this issue I don't think we want to spend the time coding this and dealing with the compatibility break.
