### ISSUE TITLE
custom entry conflict with Ltac parsing

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9633]
#### Description of the problem

```coq
Declare Custom Entry expr.
Notation "constr:( e )" := e (in custom expr, e constr).
Goal True.
  let x := open_constr:(1+1) in pose x.
  let x := constr:(1+1) in pose x.
(* Syntax error: [tactic:tactic_expr] expected after ':=' (in [let_clause]). *)
```

#### Coq Version

8.9.0

**Comment by andres-erbsen** [comment]
cc @herbelin as by https://github.com/coq/coq/pull/11530#issuecomment-583880767

**Comment by herbelin** [comment]
I would not call it a bug, it is standard factorization problem with grammars. You'd have to write the notation like this:

```
Notation "'constr' : ( e )" := e (in custom expr, e constr).
```
so that it factorizes with the `argname : ( e )` syntax of Ltac.

**Comment by andres-erbsen** [comment]
Oh, is the issue that `constr:(` was lexed as multiple tokens before, but is lexed as one token with this notation? What does `argname : ( e )` do in Ltac? Is there a way I can find out (both its existence and tokenization) from documentation?

**Comment by andres-erbsen** [comment]
The suggestion above works with the original example I gave, but is still dissatisfying because it makes `constr` a keyword.

```coq
Declare Custom Entry expr.

Check fun constr => constr.

Notation "'constr' : ( e )" := e (in custom expr, e constr).
(* Identifier 'constr' now a keyword *)

Goal True.
  let x := open_constr:(1+1) in pose x.
  let x := constr:(1+1) in pose x.
(* Syntax error: [tactic:tactic_expr] expected after ':=' (in [let_clause]). *)
Abort.

Check fun constr => constr.
(* Syntax error: [constr:open_binders] expected after 'fun' (in [constr:binder_constr]). *)
```

And putting `'cosntr:`` in the notation has the original issue.

**Comment by herbelin** [comment]
> What does `argname : ( e )` do in Ltac? 

There are a few `argname : ( e )` hard-wired in ltac (see file `extraargs.mlg` and `Tacentries.create_ltac_quotation` in `plugins/ltac`). Maybe would it be possible to change the grammar so that it uses keyword  of the form `argname:(`  without spaces, preventing in your case to have `constr` become a keyword. I don't know if @ppedrot sees an objection to that. It might be worth trying.

> Is there a way I can find out (both its existence and tokenization) from documentation?

I believe `Tacentries.create_ltac_quotation` was for internal Ltac purpose.

> The suggestion above works with the original example I gave, but is still dissatisfying because it makes constr a keyword.

The heuristics used by `Notation` is that an ident is put as a keyword if there is a risk that the ident is consumed by a rule of lower level. The typical example is: `f constr:(c)` where the rule parsing application would see an ident `constr` and start to parse `f constr` as an application (then seeing the ':`as the cast notation).

We could try to refine the heuristic. Or, maybe simpler, that a `Notation`modifier is provided to cancel the reservation of an ident as a keyword (at your own risk depending on the structure of your own grammar).

**Comment by andres-erbsen** [comment]
Okay, thanks to the explanations from @:herbelin and @:JasonGross I now understand what is going on here. I'll make `constr` a keyword in my code. That works for me, though would be neat to be able to do this without making `constr` a keyword, perhaps something along the lines of the following:

```coq
Notation "ltac : ( e )"         := e   (in custom bedrock_args, e constr, ltac terminal,
                                           format "ltac ':' '(' e ')'").
```
which would break
```coq
Check let ltac := 0 in ltac:(exact I).
```
but not
```coq
Check let ltac := 0 in ltac.
Check fun constr => constr.
Check fun ltac => ltac.
```

**Comment by JasonGross** [comment]
> ```coq
> Declare Custom Entry expr.
> 
> Check fun constr => constr.
> 
> Notation "'constr' : ( e )" := e (in custom expr, e constr).
> (* Identifier 'constr' now a keyword *)
> 
> Goal True.
>   let x := open_constr:(1+1) in pose x.
>   let x := constr:(1+1) in pose x.
> (* Syntax error: [tactic:tactic_expr] expected after ':=' (in [let_clause]). *)
> Abort.
> ```

I don't get a syntax error here, only on the later `fun constr => constr`.  Is this a copy-paste issue?

**Comment by JasonGross** [comment]
> ```coq
> Notation "ltac : ( e )"         := e   (in custom bedrock_args, e constr, ltac terminal,
>                                            format "ltac ':' '(' e ')'").
> ```
> 
> 
> which would break
> ```coq
> Check let ltac := 0 in ltac:(exact I).
> ```

No, the point is that it would not break `let ltac` if it's a terminal rather than a keyword
