### ISSUE TITLE
[meta] coq/build-maintainers team

### ISSUE THREAD

**Issue by ejgallego** [coq/coq#9747]
So far, @Zimmi48 and I have been maintaining the Dune build system for Coq, with great consulting help from Dune developers, in particular @rgrinberg ; this arrangement has however placed a lot of strain on @Zimmi48 , so I'd be great if we could do a group and add a bit more of manpower.

I suggest we create a build-maintainers team and expand Dune maintainers ship; maybe @SkySkimmer could be interested? How about @rgrinberg [tho if you don't use Coq from time to time it'd be IMHO pointless]

**Comment by rgrinberg** [comment]
I think I lack the qualifications to maintain the coq build system, but I'm quite happy to keep answering any questions regarding dune the coq might have.

I think the initial strain put the team is mostly due to the initial unfamiliarity with dune. Since dune isn't nearly as complicated as make (at least on the surface), this initial phase should hopefully pass. Most of the dune related PR's that I see are quite trivial, so I would suggest that other maintainers step up and review them.

On the other hand, I'm quite happy to help maintain the upcoming coq rules in dune itself.

**Comment by Zimmi48** [comment]
The upcoming support for Coq in Dune is indeed going to make maintenance of the Coq build system lighter, especially as we gradually get rid of the legacy Makefiles, move step by step toward more standard flags, etc.

Anyway, creating a @coq/build-maintainers team is probably a good idea (as we are moving more and more our `CODEOWNERS` file to use maintainer teams). However, in the current situation where we still have the legacy Makefiles and configure script, where the test-suite itself depends on a large Makefile, where another important brick to maintain is coq_makefile, it seems to me that this team should include at least @gares and @SkySkimmer in addition to @ejgallego and me.

**Comment by ejgallego** [comment]
IMO this can be closed after #10254
