### ISSUE TITLE
assertion failure on `specialize P with (1 := A)` if `P` contains a let

### ISSUE THREAD

**Issue by samuelgruetter** [coq/coq#9893]
```
Axiom foo: forall (m1 m2: nat), let n := 2 * m1 in m1 = m2 -> True.

Goal False.
  pose proof foo as P.
  assert (2 = 2) as A by reflexivity.
  specialize P with (1 := A).
```

leads to

```
Error: Anomaly "File "tactics/tactics.ml", line 3000, characters 18-24: Assertion failed."
Please report at http://coq.inria.fr/bugs/.
```

If I do `cbv zeta in P.` before the `specialize`, it works.

Expected behavior: Perform enough zeta reduction (but not more than strictly needed) to make `specialize` work.

Coq version: master commit 424c1973e96dfbf3b2e3245d735853ffa9600373 of Mon Apr 1 19:40:53 2019 +0000

**Comment by andres-erbsen** [comment]
What about `H : let m := 9^9^9^9 in True -> True` and `specialize (H I)`?

**Comment by andres-erbsen** [comment]
Oh, I meant the follwing:
`let x0 := True in let x1 := x0 /\ x0 in let x2 := x1 /\ x1 ... True -> True`.

**Comment by JasonGross** [comment]
I think the question of zeta-reducing lets is separate.  Note that `specialize (H _ _ A)` already works fine in the given example; this anomaly is almost certainly a result of a mismatch in how terms are traversed so that when you say `(1 := ...)` it tries to put the term in the wrong place (one term traversal considers the `m1 = m2` argument to be the fourth argument (c.f. `intros`), while another method (post-zeta) considers it to be the third).  (N.B. I haven't actually looked at the OCaml code here.)
