### ISSUE TITLE
cbv beta as a no-op is extremely slow in highly non-linear ways on large numbers of in the number of hypotheses

### ISSUE THREAD

**Issue by JasonGross** [coq/coq#9919]
#### Description of the problem

```coq
Goal True.                                                                                                                                                                                                  
  do 20 (do 100 pose proof I; time cbv beta in * ).                                                                                                                                                         
  (* Tactic call ran for 0.009 secs (0.011u,0.s) (success)                                                                                                                                                  
Tactic call ran for 0.036 secs (0.035u,0.s) (success)                                                                                                                                                       
Tactic call ran for 0.111 secs (0.112u,0.s) (success)                                                                                                                                                       
Tactic call ran for 0.211 secs (0.195u,0.012s) (success)                                                                                                                                                    
Tactic call ran for 0.331 secs (0.311u,0.02s) (success)                                                                                                                                                     
Tactic call ran for 0.314 secs (0.311u,0.s) (success)                                                                                                                                                       
Tactic call ran for 0.445 secs (0.423u,0.02s) (success)                                                                                                                                                     
Tactic call ran for 0.743 secs (0.72u,0.024s) (success)                                                                                                                                                     
Tactic call ran for 0.895 secs (0.863u,0.031s) (success)                                                                                                                                                    
Tactic call ran for 0.924 secs (0.855u,0.068s) (success)                                                                                                                                                    
Tactic call ran for 1.256 secs (1.224u,0.032s) (success)                                                                                                                                                    
Tactic call ran for 1.779 secs (1.715u,0.064s) (success)                                                                                                                                                    
Tactic call ran for 1.652 secs (1.592u,0.059s) (success)                                                                                                                                                    
Tactic call ran for 2.112 secs (2.06u,0.056s) (success)                                                                                                                                                     
Tactic call ran for 2.905 secs (2.836u,0.067s) (success)                                                                                                                                                    
Tactic call ran for 2.597 secs (2.495u,0.099s) (success)                                                                                                                                                    
Tactic call ran for 3.105 secs (3.024u,0.084s) (success)                                                                                                                                                    
Tactic call ran for 4.324 secs (4.268u,0.055s) (success)                                                                                                                                                    
Tactic call ran for 3.745 secs (3.635u,0.108s) (success)                                                                                                                                                    
Tactic call ran for 4.028 secs (3.92u,0.107s) (success)                                                                                                                                                     
*)
```

I believe this is behind some of the slowness of `lia` on large contexts, and `unfold Z_of_nat' in *` in `Lia.preprocess` seems to be one of the slower parts.

cc @ppedrot @samuelgruetter  @andres-erbsen 

#### Coq Version

8.9

**Comment by ppedrot** [comment]
That's an algorithmic issue. Changing a hypothesis is linear in the size of the context (see `Environ.apply_to_hyp`), so `cbv in *` is quadratic.

**Comment by JasonGross** [comment]
What about adding a fast-path to things like unfold, rewrite, cbv, etc, that don't try to actually modify a hypothesis if there is no change?  (But also, shouldn't updating a hypothesis to something that's convertible with it be constant in the size of the context?)

**Comment by ppedrot** [comment]
I tried to write a little patch to perform conversion tactics with `in *` occurrences in batch, but it turns out to be fairly subtle. For instance, it is unclear in which environment the partial tactics should be called. If I construct it piecewise, I get errors from instances of the form
```
Goal True.
Proof.
pose (P := True).
assert P by constructor.
unfold P in *.
```
because `P` does not exist yet when unfolding `P` in `P`. Dually, if I call it on the whole initial environment, unfolding will break because the shape of the resulting term depends on the order of application of the conversion tactic in general. So, essentially, to preserve the current behaviour we have to apply the conversion globally, but one term at a time to update the environment. In which case, we're back to square one because this is linear in the size of the context. Any thoughts?

**Comment by ppedrot** [comment]
> But also, shouldn't updating a hypothesis to something that's convertible with it be constant in the size of the context?

Forgot to comment on this: currently the representation of named contexts uses both a map (with O(log n) access) and a list. You need the list because most of the accesses to the context are performed in a LIFO way. We could try to generate it on the fly, but I am slightly concerned by the cost of it when most users require the linear form, not the map one.

**Comment by samuelgruetter** [comment]
Would it be possible to define a function `depends_on_environ` which, given a conversion, tells if the conversion depends on the environment? For instance, it would return `false` for `cbv beta`, and `true` for `unfold P` in the above example, and for `cbv [x]` it would return `true` if `x` is let-bound in the environment, but false if `x` is a global identifier.
Then if `depends_on_environ` returns true, run the existing one-term-at-a-time code, else run your new batch conversion code.

**Comment by samuelgruetter** [comment]
> Forgot to comment on this: currently the representation of named contexts uses both a map (with O(log n) access) and a list. You need the list because most of the accesses to the context are performed in a LIFO way. We could try to generate it on the fly, but I am slightly concerned by the cost of it when most users require the linear form, not the map one.

Not sure if I understand the problem here but there are [data structures](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html) which efficiently maintain both a map and a linked list at the same time. Does Coq use such a data structure for environments at the moment? Or what does it prevent from doing so?

**Comment by JasonGross** [comment]
> So, essentially, to preserve the current behaviour we have to apply the conversion globally, but one term at a time to update the environment. In which case, we're back to square one because this is linear in the size of the context. Any thoughts?

As long as the `in *` is not also modified by an `at 1`, it should be safe to find the first term in the context where the conversion is defined, and then do it separately on every term that comes after that.  In fact, even if it is modified by `at 1` I think we're fine, because I think you can't write `in (Value of *)` (can you?).

**Comment by ppedrot** [comment]
@samuelgruetter Currently, we literally have at the same time in the data structure a map (for fast non-linear access) and a list. The problem is not so much the need to design a efficient data structure than to keep backwards compatibility with existing code. There are *a hell of a lot* of places where we explicitly use the underlying list, and turning this into an abstract API is going to be a pain.

Also, the datastructure you mention seems to be imperative in nature. There is probably a way to make it immutable or at least persistent, but that's an additional requirement for Coq environments to take into account.

**Comment by ppedrot** [comment]
Crawling through the code history, I found bug #1898 which shows that the `in *` clause is tricky, and furthermore that the current handling is a bit ad-hoc, e.g. `fold` and `unfold` do not behave the same in case of failure.

**Comment by samuelgruetter** [comment]
It seems to me that all the tricky-ness is related to conversions which depend on the environment, while all the performance problems we encounter in practice are related to conversions which do not depend on the environment. 
So a patch which only focuses on environment-independent conversions would be very useful and also unlikely to trigger tricky cases.
