### ISSUE TITLE
`change tt with tt` is not identity

### ISSUE THREAD

**Issue by andres-erbsen** [coq/coq#9930]
#### Description of the problem

```coq
Set Primitive Projections.
Record params := { width : nat }.
Definition p : params := Build_params 64.

Goal width p = 0 -> width p = 0.
  intros.
  let e := lazymatch type of H with ?e = 0 => e end in
  change tt with tt in H;
  let E := lazymatch type of H with ?E = 0 => E end in
  idtac "before:" e; idtac "after :" E;
  (* before: (width p) *)
  (* after : (width p) *)
  tryif constr_eq e E then admit else idtac.
  all : fail "not equal".
  (* Error: Tactic failure: not equal. *)
Abort.
```

cc @samuelgruetter 

Note fixing this makes #9512 need a new test.

See also #9929

#### Coq Version

8.9.0

**Comment by Janno** [comment]
This bug still exists on master and it does breaks proofs. I don't have a minimal example but inserting `change tt with tt.` before line 34 of https://gitlab.mpi-sws.org/iris/iris/blob/master/theories/bi/lib/core.v#L34 ([link with fixed hash instead of master](https://gitlab.mpi-sws.org/iris/iris/blob/a2f75cd0b0c028cc282917ec00e364a23502a6b4/theories/bi/lib/core.v#L34)) will make the final call(s) to `auto` fail. I can give more details on what exactly happens, if necessary. (It might even be a combination of bugs.)

As far as I know there is no tactic besides `change .. with .. in H` that allows changing the *type* of a definition in the proof context so this bug is actually a blocker for me.

**Comment by SkySkimmer** [comment]
Fun one but not too hard in the end, see https://github.com/coq/coq/pull/11769

**Comment by Janno** [comment]
#11769 does not fix my example. I still haven't managed to get a minimal example but if you can manage to install iris master (or build the files up to theories/bi/lib/core.v) then the code below should be helpful in figuring out what's going on. It works just fine without the `change tt with tt.`
```coq
From iris.bi Require Export bi plainly.
From iris.bi.lib Require Import core.
From iris.proofmode Require Import tactics.
Set Default Proof Using "Type".

Section core.
  Context `{!BiPlainly PROP}.
  Implicit Types P Q : PROP.

  Axiom F : False.
  Global Instance coreP_persistent P : Persistent (coreP P).
  Proof.
    rewrite /coreP /Persistent. iIntros "HC" (Q).
    iApply persistently_wand_affinely_plainly. iIntros "#HQ".
    iApply persistently_wand_affinely_plainly. iIntros "#HPQ".
    iApply "HQ". iApply "HC".
    change tt with tt.
    lazymatch goal with
    | |- environments.envs_entails (environments.Envs (environments.Esnoc (environments.Esnoc _ _ ?P) _ _) ?Γs _) ?Q =>
      let p := constr:(true) in
      assert (@FromAssumption _ p P Q) as Hass
    end.
```

**Comment by Janno** [comment]
Sorry for any confusion I generated. The previous comment is indeed wrong and all it took was to make sure all my shell and emacs instances were using the correct opam switch. I can now happily report that #11769 fixes the problem! Thanks @SkySkimmer!
